/******************************************************************************/
/****              Generated by IBExpert 07/10/2023 17:42:16               ****/
/******************************************************************************/

/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE LAB_ESTINTORI_ERROR (
    STATINO                  VARCHAR(255) NOT NULL,    -- IdStatino
    ESTINTORE                VARCHAR(255) NOT NULL,    -- IdEstintore
    TECNICO                  VARCHAR(255),  -- Tecnico
    DESCRIZIONE_STATINO      VARCHAR(255),  -- DescrStatino
    STATO_STATINO            CHAR(1),      -- Stato (root)
    DESCRIZIONE_ALTERNATIVA  VARCHAR(255),
    RESET_DATA_COLLAUDO      CHAR(1),
    RESET_DATA_REVISIONE     CHAR(1),
    DATA_CONTROLLO           VARCHAR(255),
    DATA_SMALTIMENTO         VARCHAR(255),
    DATA_RESTITUZIONE        VARCHAR(255),
    DATA_CONSEGNA            VARCHAR(255),
    DATA_CONTROLLO_NEGATO    VARCHAR(255),
    DATA_STARTUP_REV         VARCHAR(255),
    TIPO_ESTINTORE           VARCHAR(255),
    PROGRESSIVO              VARCHAR(255),
    MATRICOLA                VARCHAR(255),
    ANNO_COSTRUZIONE         VARCHAR(255),
    DATA_STARTUP_COL         VARCHAR(255),
    STATO                    CHAR(1) NOT NULL,
    ANOMALIA_APPROVATA       CHAR(1),
    ANOMALIA                 VARCHAR(255),
    UBICAZIONE               VARCHAR(255),
    NOTE_TECNICO             VARCHAR(255),
    ID_NFC                   VARCHAR(100),
    MARCA                    VARCHAR(255),
    TIPO_INTERVENTO          CHAR(1),
    PERIODICITA_COLLAUDO     VARCHAR(255),
    PERIODICITA_REVISIONE    VARCHAR(255),
    ANOMALIA_DOWNLOAD        VARCHAR(255),
    RITIRATO                 CHAR(1),
    DATA_RITIRO              VARCHAR(255),
    ORARIO_RITIRO            VARCHAR(255),
    TECNIOO_RITIRO           VARCHAR(255),
    CONSEGNATO               CHAR(1),
    DATA_LAVORAZIONE         VARCHAR(255),
    ERROR_MESSAGE            VARCHAR(255)
);



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE LAB_ESTINTORI_ERROR
    ADD CONSTRAINT PK_LAB_ESTINTORI_ERROR PRIMARY KEY (STATINO, ESTINTORE);

