CREATE TABLE STATINI_STATO (
	STATO SMALLINT NOT NULL,
	DESCRIZIONE VARCHAR(30) NOT NULL);

ALTER TABLE STATINI_STATO
ADD CONSTRAINT PK_STATINI_STATO
PRIMARY KEY (STATO);


ALTER TABLE STATINI
ADD CONSTRAINT FK_STATINI_STATO
FOREIGN KEY (STATO)
REFERENCES STATINI_STATO(STATO)
USING INDEX FK_STATINI_STATO_NDX