/******************************************************************************/
/****              Generated by IBExpert 07/10/2023 17:42:16               ****/
/******************************************************************************/

/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE LABORATORIO_ESTINTORI (
    STATINO                  INTEGER NOT NULL,     -- IdStatino
    ESTINTORE                INTEGER NOT NULL,     -- IdEstintore
    TECNICO                  INTEGER,  -- Tecnico
    DESCRIZIONE_STATINO      VARCHAR(255),  -- DescrStatino
    STATO_STATINO            CHAR(1),      -- Stato (root)
    DESCRIZIONE_ALTERNATIVA  VARCHAR(255),
    RESET_DATA_COLLAUDO      CHAR(1),
    RESET_DATA_REVISIONE     CHAR(1),
    DATA_CONTROLLO           DATE,
    DATA_SMALTIMENTO         DATE,
    DATA_RESTITUZIONE        DATE,
    DATA_CONSEGNA            DATE,
    DATA_CONTROLLO_NEGATO    DATE,
    DATA_STARTUP_REV         DATE,
    TIPO_ESTINTORE           INTEGER,
    PROGRESSIVO              INTEGER NOT NULL,
    MATRICOLA                VARCHAR(255),
    ANNO_COSTRUZIONE         SMALLINT,
    DATA_STARTUP_COL         DATE,
    STATO                    CHAR(1) NOT NULL,
    ANOMALIA_APPROVATA       CHAR(1),
    ANOMALIA                 VARCHAR(255),
    UBICAZIONE               VARCHAR(255),
    NOTE_TECNICO             VARCHAR(255),
    ID_NFC                   VARCHAR(100),
    MARCA                    INTEGER,
    TIPO_INTERVENTO          CHAR(1),
    PERIODICITA_COLLAUDO     INTEGER,
    PERIODICITA_REVISIONE    INTEGER,
    ANOMALIA_DOWNLOAD        VARCHAR(255),
    RITIRATO                 CHAR(1),
    DATA_RITIRO              DATE,
    ORARIO_RITIRO            DATE,
    TECNIOO_RITIRO           INTEGER,
    CONSEGNATO               CHAR(1),
    DATA_LAVORAZIONE         DATE
);



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE LABORATORIO_ESTINTORI
    ADD CONSTRAINT PK_LABORATORIO_ESTINTORI PRIMARY KEY (STATINO, ESTINTORE);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE LABORATORIO_ESTINTORI ADD CONSTRAINT
    FK_INTERVENTI_ESTINTORI FOREIGN KEY (ESTINTORE) REFERENCES ESTINTORI_CLIENTI (CHIAVE);
ALTER TABLE LABORATORIO_ESTINTORI ADD CONSTRAINT
    FK_INTERVENTI_ESTINTORI_STATINO FOREIGN KEY (STATINO) REFERENCES STATINI (CHIAVE);


/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/
