DROP TABLE CALENDARIO;

COMMIT;

CREATE TABLE CALENDARIO (
    CHIAVE INTEGER NOT NULL,
    STATINO INTEGER,
    TECNICO INTEGER NOT NULL,
    DALLE_ORE TIMESTAMP NOT NULL,
    ALLE_ORE TIMESTAMP NOT NULL,
    NOTE BLOB SUB_TYPE 1 SEGMENT SIZE 2048);

COMMIT;

ALTER TABLE CALENDARIO
ADD CONSTRAINT PK_CALENDARIO
PRIMARY KEY (CHIAVE);

ALTER TABLE CALENDARIO
ADD CONSTRAINT FK_CALENDARIO_STATINO
FOREIGN KEY (STATINO)
REFERENCES STATINI(CHIAVE);

ALTER TABLE CALENDARIO
ADD CONSTRAINT FK_CALENDARIO_TECNICO
FOREIGN KEY (TECNICO)
REFERENCES TECNICI(CHIAVE);


insert into CALENDARIO (CHIAVE, STATINO, TECNICO, DALLE_ORE, ALLE_ORE, NOTE)
select
CHIAVE,
CHIAVE,
COALESCE(TECNICO_INTERVENTO, RESPONSABILE) AS TECNICO,
APPUNTAMENTO_DATA + APPUNTAMENTO_ORA AS APPUNTAMENTO_DATA_ORA,
dateadd (+1 hour to APPUNTAMENTO_DATA + APPUNTAMENTO_ORA),
NOTE_PER_IL_TECNICO
FROM STATINI S WHERE APPUNTAMENTO_DATA IS NOT NULL
AND NOT EXISTS (SELECT 1 FROM CALENDARIO WHERE CHIAVE = S.CHIAVE);

COMMIT;