const
  DropBoxAppkey = '';
  DropBoxAppSecret = '';

  WinLiveClientID = '';
  WinLiveClientSecret = '';

  //GoogleAppKey = '871182331783-1vv4igf0rc5jvnqtlgi7ebvbt0elpt8f.apps.googleusercontent.com';
  //GoogleAppSecret = 'ok60yC6BGpxCNvJoOCVZOaUU';

  GoogleAppKey = '421784218974-gki5a56bm4juco359d9s0v1o0hdn4jmm.apps.googleusercontent.com';
  GoogleAppSecret = '-U8ZqcIe1xjirBGDYi8rVWFi';


  BoxNetAppKey = '';
  BoxNetAppSecret = '';

  HubicAppKey = '';
  HubicAppSecret = '';
  HubicCallBack = '';

  HiDriveAppKey = '';
  HiDriveAppSecret = '';

  YandexDiskAppKey = '';
  YandexDiskAppSecret = '';
