program JanuaUniUnitTesting;

{$IFNDEF TESTINSIGHT}
{$APPTYPE CONSOLE}
{$ENDIF}{$STRONGLINKTYPES ON}

uses
  {$IFDEF TESTINSIGHT}
  TestInsight.DUnitX,
  {$ENDIF }
  DUnitX.Loggers.Console,
  DUnitX.Loggers.Xml.NUnit,
  DUnitX.TestFramework,
  System.SysUtils,
  System.Classes,
  Janua.Application.Framework,
  Janua.Postgres.Impl,
  Janua.Postgres.Cloud,
  Janua.Core.University in '..\..\src\januacore\Janua.Core.University.pas',
  Janua.Core.Users in '..\..\src\januacore\Janua.Core.Users.pas',
  Janua.Core.WebServices in '..\..\src\januacore\Janua.Core.WebServices.pas',
  Janua.Core.Ads in '..\..\src\januacore\Janua.Core.Ads.pas',
  Janua.Core.Backup in '..\..\src\januacore\Janua.Core.Backup.pas',
  Janua.Core.Books in '..\..\src\januacore\Janua.Core.Books.pas',
  Janua.Core.BooksForms in '..\..\src\januacore\Janua.Core.BooksForms.pas',
  Janua.Core.Classes in '..\..\src\januacore\Janua.Core.Classes.pas',
  Janua.Core.Cloud in '..\..\src\januacore\Janua.Core.Cloud.pas',
  Janua.Core.Cms in '..\..\src\januacore\Janua.Core.Cms.pas',
  Janua.Core.Collections in '..\..\src\januacore\Janua.Core.Collections.pas',
  Janua.Core.CRM in '..\..\src\januacore\Janua.Core.CRM.pas',
  Janua.Core.Crypt in '..\..\src\januacore\Janua.Core.Crypt.pas',
  Janua.Core.Customcontrols in '..\..\src\januacore\Janua.Core.Customcontrols.pas',
  Janua.Core.Customsession in '..\..\src\januacore\Janua.Core.Customsession.pas',
  Janua.Core.Customsystem in '..\..\src\januacore\Janua.Core.Customsystem.pas',
  Janua.Core.Docs in '..\..\src\januacore\Janua.Core.Docs.pas',
  Janua.Core.Exceptions in '..\..\src\januacore\Janua.Core.Exceptions.pas',
  Janua.Core.Feeds in '..\..\src\januacore\Janua.Core.Feeds.pas',
  Janua.Core.Football in '..\..\src\januacore\Janua.Core.Football.pas',
  Janua.Core.Forms in '..\..\src\januacore\Janua.Core.Forms.pas',
  Janua.Core.Functions in '..\..\src\januacore\Janua.Core.Functions.pas',
  Janua.Core.Http in '..\..\src\januacore\Janua.Core.Http.pas',
  Janua.Core.Items in '..\..\src\januacore\Janua.Core.Items.pas',
  Janua.Core.JPublic in '..\..\src\januacore\Janua.Core.JPublic.pas',
  Janua.Core.Mail in '..\..\src\januacore\Janua.Core.Mail.pas',
  Janua.Core.Ords in '..\..\src\januacore\Janua.Core.Ords.pas',
  Janua.Core.Params in '..\..\src\januacore\Janua.Core.Params.pas',
  Janua.Core.Pharmacies in '..\..\src\januacore\Janua.Core.Pharmacies.pas',
  Janua.Core.Pos in '..\..\src\januacore\Janua.Core.Pos.pas',
  Janua.Core.RealEstate in '..\..\src\januacore\Janua.Core.RealEstate.pas',
  Janua.Core.Social in '..\..\src\januacore\Janua.Core.Social.pas',
  Janua.Core.Sockets in '..\..\src\januacore\Janua.Core.Sockets.pas',
  Janua.Core.Hash in '..\..\src\januacore\Janua.Core.Hash.pas',
  Janua.Core.Swap in '..\..\src\januacore\Janua.Core.Swap.pas',
  Janua.Core.Roundings in '..\..\src\januacore\Janua.Core.Roundings.pas',
  Janua.Core.Printers in '..\..\src\januacore\Janua.Core.Printers.pas',
  Janua.Core.FTP in '..\..\src\januacore\Janua.Core.FTP.pas',
  Janua.Core.Mobyt in '..\..\src\januacore\Janua.Core.Mobyt.pas',
  Janua.Core.Excel in '..\..\src\januacore\Janua.Core.Excel.pas',
  Janua.Core.Servers in '..\..\src\januacore\Janua.Core.Servers.pas',
  Janua.Core.Health in '..\..\src\januacore\Janua.Core.Health.pas',
  Janua.Core.Cms.GraphicMenu in '..\..\src\januacore\Janua.Core.Cms.GraphicMenu.pas',
  Janua.Core.Cloud.Server in '..\..\src\januacore\Janua.Core.Cloud.Server.pas',
  Janua.Core.Locale in '..\..\src\januacore\Janua.Core.Locale.pas',
  Janua.Core.Metronics in '..\..\src\januacore\Janua.Core.Metronics.pas',
  Writers in '..\..\src\januacore\Writers.pas',
  udmJanuaCoreRSS in '..\..\src\januacore\udmJanuaCoreRSS.pas' {dmJanuaCoreRSS: TDataModule},
  Janua.Core.DB in '..\..\src\januacore\Janua.Core.DB.pas',
  Janua.Core.Json in '..\..\src\januacore\Janua.Core.Json.pas',
  Janua.Core.Statistics in '..\..\src\januacore\Janua.Core.Statistics.pas',
  udmJanuaCoreDBConnection in '..\..\src\januacore\udmJanuaCoreDBConnection.pas' {dmJanuaCoreDBConnections: TDataModule},
  Janua.Core.Types in '..\..\src\januacore\Janua.Core.Types.pas',
  Janua.Core.Conf in '..\..\src\januacore\Janua.Core.Conf.pas',
  Janua.Core.Math in '..\..\src\januacore\Janua.Core.Math.pas',
  Janua.Core.RESTCloudDatamodule in '..\..\src\januacore\Janua.Core.RESTCloudDatamodule.pas' {JanuaRestCloudDataModule: TDataModule},
  Janua.Core.Classes.Social in '..\..\src\januacore\Janua.Core.Classes.Social.pas',
  Janua.Html.Types in '..\..\src\januacore\Janua.Html.Types.pas',
  Janua.Football.Intf in '..\..\src\januacore\Janua.Football.Intf.pas',
  Janua.Football.Types in '..\..\src\januacore\Janua.Football.Types.pas',
  Janua.Maps.Intf in '..\..\src\januacore\Janua.Maps.Intf.pas',
  Janua.Maps.Types in '..\..\src\januacore\Janua.Maps.Types.pas',
  Janua.Core.Maps in '..\..\src\januacore\Janua.Core.Maps.pas',
  Janua.Cms.Types in '..\..\src\januacore\Janua.Cms.Types.pas',
  Janua.Cms.Server.Intf in '..\..\src\januacore\Janua.Cms.Server.Intf.pas',
  Janua.Cms.Core in '..\..\src\januacore\Janua.Cms.Core.pas',
  Janua.Anagraph.Types in '..\..\src\januacore\Janua.Anagraph.Types.pas',
  Janua.Html.Metro5.Types in '..\..\src\januacore\Janua.Html.Metro5.Types.pas',
  Janua.Html.Metro5.Impl in '..\..\src\januacore\Janua.Html.Metro5.Impl.pas',
  Janua.Orm.Impl in '..\..\src\januacore\Janua.Orm.Impl.pas',
  Janua.Orm.Intf in '..\..\src\januacore\Janua.Orm.Intf.pas',
  Janua.Orm.Types in '..\..\src\januacore\Janua.Orm.Types.pas',
  Janua.Test.Football in '..\..\src\januacore\Test\Janua.Test.Football.pas',
  Janua.Orm.Generator in '..\..\src\januacore\Janua.Orm.Generator.pas',
  Janua.Html.Bootstrap4 in '..\..\src\januacore\Janua.Html.Bootstrap4.pas',
  Janua.Html.Bootstrap4.Types in '..\..\src\januacore\Janua.Html.Bootstrap4.Types.pas',
  JOrm.System.UserProfile.Custom.Intf in '..\..\src\januacore\orm\JOrm.System.UserProfile.Custom.Intf.pas',
  JOrm.System.UserProfile.Custom.Impl in '..\..\src\januacore\orm\JOrm.System.UserProfile.Custom.Impl.pas',
  JOrm.Cms.MainArguments.Intf in '..\..\src\januacore\orm\JOrm.Cms.MainArguments.Intf.pas',
  JOrm.Cms.MainArguments.Impl in '..\..\src\januacore\orm\JOrm.Cms.MainArguments.Impl.pas',
  JOrm.Cms.Arguments.Intf in '..\..\src\januacore\orm\JOrm.Cms.Arguments.Intf.pas',
  JOrm.Cms.Arguments.Impl in '..\..\src\januacore\orm\JOrm.Cms.Arguments.Impl.pas',
  JOrm.Cms.SubArguments.Intf in '..\..\src\januacore\orm\JOrm.Cms.SubArguments.Intf.pas',
  JOrm.Cms.SubArguments.Impl in '..\..\src\januacore\orm\JOrm.Cms.SubArguments.Impl.pas',
  Janua.Html.Builder.Intf in '..\..\src\januacore\Janua.Html.Builder.Intf.pas',
  Janua.Metro5.Builder in '..\..\src\januacore\Janua.Metro5.Builder.pas',
  Janua.Metro5.Builder.Intf in '..\..\src\januacore\Janua.Metro5.Builder.Intf.pas',
  Janua.Html.Metro5.Pages in '..\..\src\januacore\Janua.Html.Metro5.Pages.pas',
  Janua.Html.Bootstrap4.Builder in '..\..\src\januacore\Janua.Html.Bootstrap4.Builder.pas',
  Janua.lnd.impl in '..\..\src\januacore\custom\Janua.lnd.impl.pas',
  Janua.lnd.Intf in '..\..\src\januacore\custom\Janua.lnd.Intf.pas',
  JOrm.Cms.Articles.Intf in '..\..\src\januacore\orm\JOrm.Cms.Articles.Intf.pas',
  JOrm.Cms.Articles.Impl in '..\..\src\januacore\orm\JOrm.Cms.Articles.Impl.pas',
  Janua.Html.Metro5.Intf in '..\..\src\januacore\Janua.Html.Metro5.Intf.pas',
  Janua.Html.Bootstrap4.Intf in '..\..\src\januacore\Janua.Html.Bootstrap4.Intf.pas',
  Janua.Cloud.Images.Intf in '..\..\src\januacore\Janua.Cloud.Images.Intf.pas',
  Janua.Cloud.Images.Impl in '..\..\src\januacore\Janua.Cloud.Images.Impl.pas',
  Janua.Server.Impl in '..\..\src\januacore\Janua.Server.Impl.pas',
  Janua.Server.Intf in '..\..\src\januacore\Janua.Server.Intf.pas',
  Janua.Cloud.Files.Impl in '..\..\src\januacore\Janua.Cloud.Files.Impl.pas',
  Janua.Cloud.Files.Intf in '..\..\src\januacore\Janua.Cloud.Files.Intf.pas',
  Janua.Orm.Dataset.Impl in '..\..\src\januacore\Janua.Orm.Dataset.Impl.pas',
  Janua.Orm.Dataset.Intf in '..\..\src\januacore\Janua.Orm.Dataset.Intf.pas',
  Janua.Orm.Functions in '..\..\src\januacore\Janua.Orm.Functions.pas',
  Janua.Core.ServerClasses in '..\..\src\januacore\Janua.Core.ServerClasses.pas',
  JOrm.System.Session.Intf in '..\..\src\januacore\orm\JOrm.System.Session.Intf.pas',
  JOrm.System.Session.Impl in '..\..\src\januacore\orm\JOrm.System.Session.Impl.pas',
  JORM.System.Intf in '..\..\src\januacore\orm\JORM.System.Intf.pas',
  JORM.System.Impl in '..\..\src\januacore\orm\JORM.System.Impl.pas',
  Janua.Cloud.Server.Intf in '..\..\src\januacore\Janua.Cloud.Server.Intf.pas',
  Janua.System.Server.Intf in '..\..\src\januacore\Janua.System.Server.Intf.pas',
  Janua.System.Server.Impl in '..\..\src\januacore\Janua.System.Server.Impl.pas',
  Janua.Cloud.Server.Impl in '..\..\src\januacore\Janua.Cloud.Server.Impl.pas',
  Janua.Cms.Server.Impl in '..\..\src\januacore\Janua.Cms.Server.Impl.pas',
  JOrm.Anagraph.Branches.Impl in '..\..\src\januacore\orm\JOrm.Anagraph.Branches.Impl.pas',
  JOrm.Anagraph.Branches.Intf in '..\..\src\januacore\orm\JOrm.Anagraph.Branches.Intf.pas',
  JOrm.System.Users.Impl in '..\..\src\januacore\orm\JOrm.System.Users.Impl.pas',
  JOrm.System.Users.Intf in '..\..\src\januacore\orm\JOrm.System.Users.Intf.pas',
  JOrm.Anagraph.anagraphs.Impl in '..\..\src\januacore\orm\JOrm.Anagraph.anagraphs.Impl.pas',
  JOrm.Anagraph.anagraphs.Intf in '..\..\src\januacore\orm\JOrm.Anagraph.anagraphs.Intf.pas',
  Janua.Html.Builder.Impl in '..\..\src\januacore\Janua.Html.Builder.Impl.pas',
  Janua.Football.Server.Intf in '..\..\src\januacore\Janua.Football.Server.Intf.pas',
  Janua.Football.Server.Impl in '..\..\src\januacore\Janua.Football.Server.Impl.pas',
  JOrm.Football.Matches.Impl in '..\..\src\januacore\orm\JOrm.Football.Matches.Impl.pas',
  JOrm.Football.Matches.Intf in '..\..\src\januacore\orm\JOrm.Football.Matches.Intf.pas',
  Janua.Dilettantissimo.Intf in '..\..\src\januacore\custom\Janua.Dilettantissimo.Intf.pas',
  Janua.Dilettantissimo.Impl in '..\..\src\januacore\custom\Janua.Dilettantissimo.Impl.pas',
  Janua.Football.Impl in '..\..\src\januacore\Janua.Football.Impl.pas',
  Janua.Http.Types in '..\..\src\januacore\Janua.Http.Types.pas',
  JOrm.Football.RankingTable.Impl in '..\..\src\januacore\orm\JOrm.Football.RankingTable.Impl.pas',
  JOrm.Football.RankingTable.Intf in '..\..\src\januacore\orm\JOrm.Football.RankingTable.Intf.pas',
  JOrm.Football.GoalRanking.Impl in '..\..\src\januacore\orm\JOrm.Football.GoalRanking.Impl.pas',
  JOrm.Football.GoalRanking.Intf in '..\..\src\januacore\orm\JOrm.Football.GoalRanking.Intf.pas',
  JOrm.Football.Championship.Impl in '..\..\src\januacore\orm\JOrm.Football.Championship.Impl.pas',
  JOrm.Football.Championship.Intf in '..\..\src\januacore\orm\JOrm.Football.Championship.Intf.pas',
  JOrm.Football.MatchDay.Impl in '..\..\src\januacore\orm\JOrm.Football.MatchDay.Impl.pas',
  JOrm.Football.MatchDay.Intf in '..\..\src\januacore\orm\JOrm.Football.MatchDay.Intf.pas',
  JOrm.Football.MatchPlayer.Impl in '..\..\src\januacore\orm\JOrm.Football.MatchPlayer.Impl.pas',
  JOrm.Football.MatchPlayer.Intf in '..\..\src\januacore\orm\JOrm.Football.MatchPlayer.Intf.pas',
  JOrm.Football.MatchEvent.Impl in '..\..\src\januacore\orm\JOrm.Football.MatchEvent.Impl.pas',
  JOrm.Football.MatchEvent.Intf in '..\..\src\januacore\orm\JOrm.Football.MatchEvent.Intf.pas',
  JOrm.Football.MatchEventDetail.Impl in '..\..\src\januacore\orm\JOrm.Football.MatchEventDetail.Impl.pas',
  JOrm.Football.MatchEventDetail.Intf in '..\..\src\januacore\orm\JOrm.Football.MatchEventDetail.Intf.pas',
  JOrm.Football.MatchDetails.Intf in '..\..\src\januacore\orm\JOrm.Football.MatchDetails.Intf.pas',
  JOrm.Football.MatchDetails.Impl in '..\..\src\januacore\orm\JOrm.Football.MatchDetails.Impl.pas',
  JOrm.Football.Season.Impl in '..\..\src\januacore\orm\JOrm.Football.Season.Impl.pas',
  JOrm.Football.Season.Intf in '..\..\src\januacore\orm\JOrm.Football.Season.Intf.pas',
  Janua.Cloud.Http.Impl in '..\..\src\januacore\Janua.Cloud.Http.Impl.pas',
  Janua.Cloud.Http.Intf in '..\..\src\januacore\Janua.Cloud.Http.Intf.pas',
  Janua.Football.Web.Intf in '..\..\src\januacore\Janua.Football.Web.Intf.pas',
  Janua.Football.Web.Impl in '..\..\src\januacore\Janua.Football.Web.Impl.pas',
  Janua.Cloud.Images.Cache in '..\..\src\januacore\Janua.Cloud.Images.Cache.pas',
  Janua.Cloud.Files.Cache in '..\..\src\januacore\Janua.Cloud.Files.Cache.pas',
  Janua.Cloud.Images.WebBroker in '..\..\src\januacore\Janua.Cloud.Images.WebBroker.pas',
  Janua.Cloud.Files.WebBroker in '..\..\src\januacore\Janua.Cloud.Files.WebBroker.pas',
  JOrm.Football.LeagueGroups.Impl in '..\..\src\januacore\orm\JOrm.Football.LeagueGroups.Impl.pas',
  JOrm.Football.LeagueGroups.Intf in '..\..\src\januacore\orm\JOrm.Football.LeagueGroups.Intf.pas',
  JOrm.Football.Leagues.Impl in '..\..\src\januacore\orm\JOrm.Football.Leagues.Impl.pas',
  JOrm.Football.Leagues.Intf in '..\..\src\januacore\orm\JOrm.Football.Leagues.Intf.pas',
  JOrm.Cms.ArticlesAttachment.Impl in '..\..\src\januacore\orm\JOrm.Cms.ArticlesAttachment.Impl.pas',
  JOrm.Cms.ArticlesAttachment.Intf in '..\..\src\januacore\orm\JOrm.Cms.ArticlesAttachment.Intf.pas',
  Janua.Html.Impl in '..\..\src\januacore\Janua.Html.Impl.pas',
  Janua.Html.Intf in '..\..\src\januacore\Janua.Html.Intf.pas',
  Janua.Http.Impl in '..\..\src\januacore\Janua.Http.Impl.pas',
  Janua.Http.Intf in '..\..\src\januacore\Janua.Http.Intf.pas',
  JOrm.Football.PlayerCareer.Impl in '..\..\src\januacore\orm\JOrm.Football.PlayerCareer.Impl.pas',
  JOrm.Football.PlayerCareer.Intf in '..\..\src\januacore\orm\JOrm.Football.PlayerCareer.Intf.pas',
  Janua.Cloud.Impl in '..\..\src\januacore\Janua.Cloud.Impl.pas',
  Janua.Cloud.Intf in '..\..\src\januacore\Janua.Cloud.Intf.pas',
  Janua.Cms.Impl in '..\..\src\januacore\Janua.Cms.Impl.pas',
  Janua.Cms.INtf in '..\..\src\januacore\Janua.Cms.INtf.pas',
  Janua.Postgres.System.Impl in '..\..\src\januaunidac\Janua.Postgres.System.Impl.pas',
  Janua.Postgres.System in '..\..\src\januaunidac\Janua.Postgres.System.pas',
  Janua.Postgres.Univeristy in '..\..\src\januaunidac\Janua.Postgres.Univeristy.pas',
  Janua.Postgres.Users in '..\..\src\januaunidac\Janua.Postgres.Users.pas',
  unitTestPgCloud in '..\src\unitTestPgCloud.pas',
  unitTestPgCms in '..\src\unitTestPgCms.pas',
  unitTestPgFootball in '..\src\unitTestPgFootball.pas',
  ServerMethodsCoreTest in '..\src\ServerMethodsCoreTest.pas',
  uWebModulePostgresTest in '..\src\uWebModulePostgresTest.pas' {WebModule1: TWebModule},
  uWebBrokerTest in '..\src\uWebBrokerTest.pas' {Critico},
  unitTestPgSystem in '..\src\unitTestPgSystem.pas',
  udmPgHealth in '..\..\src\januaunidac\datamodules\udmPgHealth.pas' {dmPgHealth},
  udmPgCms in '..\..\src\januaunidac\datamodules\udmPgCms.pas' {dmPgCms},
  udmPgSystemCommand in '..\..\src\januaunidac\datamodules\udmPgSystemCommand.pas' {dmPgSystemCommand},
  udmPgSwap in '..\..\src\januaunidac\datamodules\udmPgSwap.pas' {dmPgSwap},
  udmPgForms in '..\..\src\januaunidac\datamodules\udmPgForms.pas' {dmPgForms},
  udmPgAdsServer in '..\..\src\januaunidac\datamodules\udmPgAdsServer.pas' {dmPgAdsServer},
  udmPgFootballServer in '..\..\src\januaunidac\datamodules\udmPgFootballServer.pas' {dmPgFootballServer},
  udmSocial in '..\..\src\januaunidac\datamodules\udmSocial.pas' {dmSocial},
  udmPgAnagraph in '..\..\src\januaunidac\datamodules\udmPgAnagraph.pas' {dmPgAnagraph},
  udmPublic in '..\..\src\januaunidac\datamodules\udmPublic.pas' {dmPublic},
  udmPgCmsGraphicMenu in '..\..\src\januaunidac\datamodules\udmPgCmsGraphicMenu.pas' {dmPgCmsGraphicMenu},
  udmPgStorage in '..\..\src\januaunidac\datamodules\udmPgStorage.pas' {dmPgStorage: TDataModule},
  Janua.Anagraph.Postgres.Storage in '..\..\src\januaunidac\datamodules\Janua.Anagraph.Postgres.Storage.pas' {dmPgAnagraphStorage: TDataModule},
  udmPgCloud in '..\..\src\januaunidac\datamodules\udmPgCloud.pas' {dmPostgresCloud},
  udmPgFootballStorage in '..\..\src\januaunidac\datamodules\udmPgFootballStorage.pas' {dmPgFootballStorage: TDataModule},
  Janua.System.Postgres.Storage in '..\..\src\januaunidac\datamodules\Janua.System.Postgres.Storage.pas' {dmPgSystemStorage: TDataModule},
  udmPgCmsStorage in '..\..\src\januaunidac\datamodules\udmPgCmsStorage.pas' {dmPgCmsStorage: TDataModule},
  udmPgCloudStorage in '..\..\src\januaunidac\datamodules\udmPgCloudStorage.pas' {dmPgCloudStorage: TDataModule},
  udmPgAdsStorage in '..\..\src\januaunidac\datamodules\udmPgAdsStorage.pas' {dmPgAdsStorage: TDataModule},
  udmCloud in '..\..\src\januaunidac\datamodules\udmCloud.pas' {dmCloud: TDataModule},
  udmFootballModel in '..\..\src\januaunidac\datamodules\udmFootballModel.pas' {dmFootballModel: TDataModule},
  udmFootballPostgres in '..\..\src\januaunidac\datamodules\udmFootballPostgres.pas' {dmFootballPostgres: TDataModule},
  udmHealthBooking in '..\..\src\januaunidac\datamodules\udmHealthBooking.pas' {dmHealthBooking: TDataModule},
  udmJanuaOraModel in '..\..\src\januaunidac\datamodules\udmJanuaOraModel.pas' {dmJanuaOraModel: TDataModule},
  udmJanuaOraWebLog in '..\..\src\januaunidac\datamodules\udmJanuaOraWebLog.pas' {dmJanuaOraWebLog: TDataModule},
  udmJanuaPgConnections in '..\..\src\januaunidac\datamodules\udmJanuaPgConnections.pas' {dmJanuaPgConnections: TDataModule},
  udmJanuaPostgresDBConnections in '..\..\src\januaunidac\datamodules\udmJanuaPostgresDBConnections.pas' {dmJanuaPostgresDBConnections},
  udmJanuaPostgresExpo in '..\..\src\januaunidac\datamodules\udmJanuaPostgresExpo.pas' {dmJanuaPostgresExpo: TDataModule},
  udmJanuaPostgresExpoAnagraph in '..\..\src\januaunidac\datamodules\udmJanuaPostgresExpoAnagraph.pas' {dmJanuaPostgresExpoAnagraph: TDataModule},
  udmJanuaPostgresModel in '..\..\src\januaunidac\datamodules\udmJanuaPostgresModel.pas' {dmJanuaPostgresModel: TDataModule},
  udmLocalization in '..\..\src\januaunidac\datamodules\udmLocalization.pas' {dmLocalization: TDataModule},
  udmMailService in '..\..\src\januaunidac\datamodules\udmMailService.pas' {dmMailService: TDataModule},
  unitTestCloud in '..\src\unitTestCloud.pas',
  unitTestConf in '..\src\unitTestConf.pas',
  Janua.Cms.Test in '..\..\src\januacore\Test\Janua.Cms.Test.pas',
  Janua.Classes.Test in '..\..\src\januacore\Test\Janua.Classes.Test.pas',
  Janua.Core.Functions.Test in '..\..\src\januacore\Test\Janua.Core.Functions.Test.pas',
  unitTestCoreHtml in '..\src\unitTestCoreHtml.pas',
  unitTestCoreTypes in '..\src\unitTestCoreTypes.pas',
  Janua.Virtual.Anagraph in '..\..\src\januacore\datamodule\Janua.Virtual.Anagraph.pas',
  Janua.Virtual.Cloud in '..\..\src\januacore\datamodule\Janua.Virtual.Cloud.pas',
  Janua.Virtual.Cms in '..\..\src\januacore\datamodule\Janua.Virtual.Cms.pas',
  Janua.Virtual.Football in '..\..\src\januacore\datamodule\Janua.Virtual.Football.pas',
  Janua.Virtual.Functions in '..\..\src\januacore\datamodule\Janua.Virtual.Functions.pas',
  Janua.Virtual.System in '..\..\src\januacore\datamodule\Janua.Virtual.System.pas',
  udmVirtualAnagraph in '..\..\src\januacore\datamodule\udmVirtualAnagraph.pas' {dmVirtualAnagraph: TDataModule},
  udmVirtualCloudServer in '..\..\src\januacore\datamodule\udmVirtualCloudServer.pas' {dmVirtualCloudServer: TDataModule},
  udmVirtualCmsServer in '..\..\src\januacore\datamodule\udmVirtualCmsServer.pas' {dmVirtualCmsServer: TDataModule},
  udmVirtualFootballServer in '..\..\src\januacore\datamodule\udmVirtualFootballServer.pas' {dmVirtualFootballServer: TDataModule},
  udmVirtualFootballStorage in '..\..\src\januacore\datamodule\udmVirtualFootballStorage.pas' {dmVirtualFootballStorage: TDataModule},
  udmVirtualServerModel in '..\..\src\januacore\datamodule\udmVirtualServerModel.pas' {dmVirtualServerModel: TDataModule},
  udmVirtualSystemServer in '..\..\src\januacore\datamodule\udmVirtualSystemServer.pas' {dmVirtualSystemServer: TDataModule},
  udmWpJson in '..\..\src\januacore\datamodule\udmWpJson.pas' {dmWpJson: TDataModule},
  unitTestHtmlMetro5 in '..\src\unitTestHtmlMetro5.pas',
  unitTestLND in '..\src\unitTestLND.pas',
  unitTestFootball in '..\src\unitTestFootball.pas',
  unitTestDilettantissimo in '..\src\unitTestDilettantissimo.pas',
  unitTestMapsTypes in '..\src\unitTestMapsTypes.pas',
  ufrmTest in '..\src\ufrmTest.pas' {frmTest},
  uPgApplicationSetup in '..\src\uPgApplicationSetup.pas';

var
  runner: ITestRunner;
  results: IRunResults;
  logger: ITestLogger;
  nunitLogger: ITestLogger;

begin
  uPgApplicationSetup.PgApplicationSetup;

{$IFDEF TESTINSIGHT}
  TestInsight.DUnitX.RunRegisteredTests;
  exit;
{$ENDIF}
  try
    // Check command line options, will exit if invalid
    TDUnitX.CheckCommandLine;
    // Create the test runner
    runner := TDUnitX.CreateRunner;
    // Tell the runner to use RTTI to find Fixtures
    runner.UseRTTI := true;
    // tell the runner how we will log things
    // Log to the console window
    logger := TDUnitXConsoleLogger.Create(true);
    runner.AddLogger(logger);
    // Generate an NUnit compatible XML File
    nunitLogger := TDUnitXXMLNUnitFileLogger.Create(TDUnitX.Options.XMLOutputFile);
    runner.AddLogger(nunitLogger);
    runner.FailsOnNoAsserts := False; // When true, Assertions must be made during tests;

    // Run tests
    results := runner.Execute;
    if not results.AllPassed then
      System.ExitCode := EXIT_ERRORS;

{$IFNDEF CI}
    // We don't want this happening when running under CI.
    if TDUnitX.Options.ExitBehavior = TDUnitXExitBehavior.Pause then
    begin
      System.Write('Done.. press <Enter> key to quit.');
      System.Readln;
    end;
{$ENDIF}
  except
    on E: Exception do
      System.Writeln(E.ClassName, ': ', E.Message);
  end;

end.
