
INSERT INTO STATINI_STATO
VALUES (-1, 'Eliminato') ;

INSERT INTO STATINI_STATO
VALUES (0, 'Non programmato');

INSERT INTO STATINI_STATO
VALUES (1, 'Programmato');

INSERT INTO STATINI_STATO
VALUES (4, 'In Lavorazione');

INSERT INTO STATINI_STATO
VALUES (5, 'Pronto');

INSERT INTO STATINI_STATO
VALUES (6, 'Programmato');

INSERT INTO STATINI_STATO
VALUES (9, 'Chiuso') ;