-- FUNCTION: anagraph.anagraph_view_update_trg()

-- DROP FUNCTION anagraph.anagraph_view_update_trg();

CREATE OR REPLACE FUNCTION anagraph.anagraph_view_update_trg()
    RETURNS trigger
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE NOT LEAKPROOF
AS $BODY$
declare
  v_id integer; 
begin
  v_id := anagraph.sp_upd_anagraphs(
	new.db_schema_id ,
	new.anagraph_id ,
	new.an_title ,
	new.an_name ,
	new.an_second_name ,
	new.an_last_name ,
	new.an_notes ,
	new.an_address ,
	new.an_town ,
	new.an_postal_code ,
	new.an_iso_country_code ,
	new.an_state_province ,
	new.an_phone ,
	new.an_phone2 ,
	new.an_fax ,
	new.an_cellular ,
	new.an_code ,
	new.an_vat_numeric ,
	new.an_email ,
	new.an_web ,
	new.an_contact_id ,
	new.an_bank_account ,
	new.an_payment_des ,
	new.an_discount ,
	new.an_distance ,
	new.an_distance_mesunit ,
	new.an_sex ,
	new.an_cod_comune ,
	new.an_cod_provincia ,
	new.an_credit_line ,
	new.an_currency_id ,
	new.an_cat_id ,
	new.an_notes2 ,
	new.an_notes3 ,
	new.an_edi ,
	new.an_privacy ,
	new.an_office_id ,
	new.an_cod_prov_rif ,
	new.an_data_fido ,
	new.an_user_insert ,
	new.an_user_update ,
	new.an_area_id ,
	new.an_agent_id ,
	new.an_area_code ,
	new.an_zone_id ,
	new.an_ins_id ,
	new.an_upd_id ,
	new.an_documents ,
	new.an_last_date ,
	new.an_birthdate ,
	new.an_office_type_id ,
	new.an_searchname ,
	new.an_extra_ue_flag ,
	new.an_external_code ,
	new.an_vat_id ,
	new.an_personal_fiscal_code ,
	new.an_privacy_print ,
	new.an_sms ,
	new.an_encrypted_fiscal_code ,
	new.an_vat_purcentage ,
	new.an_status ,
	new.an_ownsite ,
	new.an_insurance_id ,
	new.an_anagraphs_anagraph_id ,
	new.an_main_language_code ,
	new.an_main_culture_code ,
	new.an_fiscal_code ,
	new.an_main_group_id ,
	new.an_image_id ,
	new.latitude ,
	new.longitude ,
	new.test ,
	new.search_index ,
	new.an_birthplace ,
	new.an_birthplace_code ,
	new.anagraph64 ,
	new.main_category_id ,
	new.osm_id ,
	new.an_description ,
	new.an_address_number ,
	new.anag_jguid ,
	new.anag_deleted ,
	new.insert_date ,
	new.update_date ,
	new.user_insert ,
	new.jguid ,
	new.custom_field_1 ,
	new.custom_field_2 ,
	new.custom_field_3 ,
	new.custom_float_1 ,
	new.custom_float_2 ,
	new.custom_int_1 ,
	new.custom_int_2 ,
	new.supplier_id ,
	new.vessel_id ,
	new.an_country_id ,
	new.an_iso_country_code2, 
    new.deleted); 
	
	return new; 
end; 
$BODY$;

ALTER FUNCTION anagraph.anagraph_view_update_trg()
    OWNER TO ergo;
