-- FUNCTION: documents.heads_view_insert_trg()

-- DROP FUNCTION IF EXISTS documents.heads_view_insert_trg();

CREATE OR REPLACE FUNCTION documents.heads_view_insert_trg()
    RETURNS trigger
    LANGUAGE 'plpgsql'
AS $BODY$
begin
    if New.id is null then
        New.id:=nextval('documents.documents_seq');
     end if; 
	 
	 if New.Inventory is null then 
	    New.Inventory := True; 
	 end if; 
	    
	  
  
	New.search_index = 
	  system.stripstringsearch(New.doc_number, New.doc_year::character varying) 
	  || system.stripstringsearch(New.holder_name, New.po_number)
	  || system.stripstringsearch(New.location_name, New.registry_code)
	  || system.stripstringsearch(New.dest_name, New.work_code);	  
	  
	INSERT INTO documents.heads (
		id,
		"type_id",
		in_out,
		doc_date,
		doc_number,
		reason,
		dest_address,
		dest_postal_code,
		dest_town,
		dest_state_province,
		dest_country_iso,
		departure_date,
		delivery_methos,
		goods_description,
		packages_number,
		total_weight,
		incoterms,
		delivery_charges,
		discount_rate,
		anagraph_id,
		carrier_id,
		dest_state_province_id,
		dest_region_id,
		dest_town_id,
		currency_id,
		payment_terms_id,
		payment_terms_des,
		package_description,
		payment_term_code,
		folder_id,
		doc_state,
		holder_name,
		holder_id,
		holder_vat_id,
		holder_address,
		holder_postal_code,
		holder_town,
		holder_state_province,
		holder_country_iso,
		delivery_rate_expense,
		holder_group_id,
		amount,
		net_amount,
		financial_year,
		doc_origin_id,
		delivery_vat_id,
		delivery_vat_rate,
		accounted,
		insert_date,
		update_date,
		delivery_due_date,
		sent,
		arrival_date,
		payment_due_date,
		duties,
		paid,
		doc_fine,
		user_insert,
		user_update,
		doc_year,
		po_number_id,
		po_number,
		printed,
		contact_name,
		contact_email,
		contact_phone,
		office_id,
		warehouse_location_id,
		jguid,
		notes1,
		notes2,
		notes3,
		db_schema_id,
		purchase_order_number,
		custom_field_1,
		custom_field_2,
		custom_field_3,
		custom_int_1,
		custom_int_2,
		custom_int_3,
		doc_ref_code,
		carrier_expenses,
		registry_code,
		carrier_tracking_number,
		carrier_expenses_currency_id,
		search_index,
		dest_name,
		carrier_name,
		location_name,
		goods_type_id,
		importexport,
		carrier_invoice_number,
		carrier_invoice_date,
		workflow_id,
		vessel_department_id,
		payment_term_id,
		an_code,
		ref_date,
		ref_code,
		stamp_duty,
		exchange_rate,
		conversion_date,
		work_code,
		work_date,
		deleted,
		dest_vat_number,
		holder_vat_number,
		currency_code,
		currency_description,
		taxable_amount,
		vat_taxes,
		assigned,
		location_code,
		vessel_id,
		vessel_name,
		vessel_code
	)
	VALUES (
		new.id,
		new.type_id,
		new.in_out,
		new.doc_date,
		new.doc_number,
		new.reason,
		new.dest_address,
		new.dest_postal_code,
		new.dest_town,
		new.dest_state_province,
		new.dest_country_iso,
		new.departure_date,
		new.delivery_methos,
		new.goods_description,
		new.packages_number,
		new.total_weight,
		new.incoterms,
		new.delivery_charges,
		new.discount_rate,
		new.anagraph_id,
		new.carrier_id,
		new.dest_state_province_id,
		new.dest_region_id,
		new.dest_town_id,
		new.currency_id,
		new.payment_terms_id,
		new.payment_terms_des,
		new.package_description,
		new.payment_term_code,
		new.folder_id,
		new.doc_state,
		new.holder_name,
		new.holder_id,
		new.holder_vat_id,
		new.holder_address,
		new.holder_postal_code,
		new.holder_town,
		new.holder_state_province,
		new.holder_country_iso,
		new.delivery_rate_expense,
		new.holder_group_id,
		new.amount,
		new.net_amount,
		new.financial_year,
		new.doc_origin_id,
		new.delivery_vat_id,
		new.delivery_vat_rate,
		new.accounted,
		new.insert_date,
		new.update_date,
		new.delivery_due_date,
		new.sent,
		new.arrival_date,
		new.payment_due_date,
		new.duties,
		new.paid,
		new.doc_fine,
		new.user_insert,
		new.user_update,
		new.doc_year,
		new.po_number_id,
		new.po_number,
		new.printed,
		new.contact_name,
		new.contact_email,
		new.contact_phone,
		new.office_id,
		new.warehouse_location_id,
		new.jguid,
		new.notes1,
		new.notes2,
		new.notes3,
		new.db_schema_id,
		new.purchase_order_number,
		new.custom_field_1,
		new.custom_field_2,
		new.custom_field_3,
		new.custom_int_1,
		new.custom_int_2,
		new.custom_int_3,
		new.doc_ref_code,
		new.carrier_expenses,
		new.registry_code,
		new.carrier_tracking_number,
		new.carrier_expenses_currency_id,
		new.search_index,
		new.dest_name,
		new.carrier_name,
		new.location_name,
		new.goods_type_id,
		new.importexport,
		new.carrier_invoice_number,
		new.carrier_invoice_date,
		new.workflow_id,
		new.vessel_department_id,
		new.payment_term_id,
		new.an_code,
		new.ref_date,
		new.ref_code,
		new.stamp_duty,
		new.exchange_rate,
		new.conversion_date,
		new.work_code,
		new.work_date,
		new.deleted,
		new.dest_vat_number,
		new.holder_vat_number,
		new.currency_code,
		new.currency_description,
		new.taxable_amount,
		new.vat_taxes,
		new.assigned,
		new.inventory,
		new.location_code,
		new.vessel_id,
		new.vessel_name,
		new.vessel_code
	);


  return new;   
end; 
$BODY$;

ALTER FUNCTION documents.heads_view_insert_trg()
    OWNER TO ergo;

COMMENT ON FUNCTION documents.heads_view_insert_trg()
    IS 'This is the trigger procedure to enable insert on DocView';
