CREATE OR REPLACE FUNCTION documents.heads_view_update_trg()
    RETURNS trigger
    LANGUAGE 'plpgsql'
     NOT LEAKPROOF
AS $BODY$
begin

    if New.id is null then
        New.id:=old.id; 
     end if; 
	 
  UPDATE documents.heads SET
    id = new.id, 
    "type_id" = new.type_id,
    in_out = new.in_out,
    doc_date = new.doc_date,
    doc_number = new.doc_number,
    reason = new.reason,
    dest_address = new.dest_address,
    dest_postal_code = new.dest_postal_code,
    dest_town = new.dest_town,
    dest_state_province = new.dest_state_province,
    dest_country_iso = new.dest_country_iso,
    departure_date = new.departure_date,
    delivery_methos = new.delivery_methos,
    goods_description = new.goods_description,
    packages_number = new.packages_number,
    total_weight = new.total_weight,
    incoterms = new.incoterms,
    delivery_charges = new.delivery_charges,
    discount_rate = new.discount_rate,
    anagraph_id = new.anagraph_id,
    carrier_id = new.carrier_id,
    dest_state_province_id = new.dest_state_province_id,
    dest_region_id = new.dest_region_id,
    dest_town_id = new.dest_town_id,
    currency_id = new.currency_id,
    payment_terms_id = new.payment_terms_id,
    payment_terms_des = new.payment_terms_des,
    package_description = new.package_description,
    payment_term_code = new.payment_term_code,
    folder_id = new.folder_id,
    doc_state = new.doc_state,
    holder_name = new.holder_name,
    holder_id = new.holder_id,
    holder_vat_id = new.holder_vat_id,
    holder_address = new.holder_address,
    holder_postal_code = new.holder_postal_code,
    holder_town = new.holder_town,
    holder_state_province = new.holder_state_province,
    holder_country_iso = new.holder_country_iso,
    delivery_rate_expense = new.delivery_rate_expense,
    holder_group_id = new.holder_group_id,
    amount = new.amount,
    net_amount = new.net_amount,
    financial_year = new.financial_year,
    doc_origin_id = new.doc_origin_id,
    delivery_vat_id = new.delivery_vat_id,
    delivery_vat_rate = new.delivery_vat_rate,
    accounted = new.accounted,
    insert_date = new.insert_date,
    update_date = new.update_date,
    delivery_due_date = new.delivery_due_date,
    sent = new.sent,
    arrival_date = new.arrival_date,
    payment_due_date = new.payment_due_date,
    duties = new.duties,
    paid = new.paid,
    doc_fine = new.doc_fine,
    user_insert = new.user_insert,
    user_update = new.user_update,
    doc_year = new.doc_year,
    po_number_id = new.po_number_id,
    po_number = new.po_number,
    printed = new.printed,
    contact_name = new.contact_name,
    contact_email = new.contact_email,
    contact_phone = new.contact_phone,
    office_id = new.office_id,
    warehouse_location_id = new.warehouse_location_id,
    jguid = new.jguid,
    notes1 = new.notes1,
    notes2 = new.notes2,
    notes3 = new.notes3,
    db_schema_id = new.db_schema_id,
    purchase_order_number = new.purchase_order_number,
    custom_field_1 = new.custom_field_1,
    custom_field_2 = new.custom_field_2,
    custom_field_3 = new.custom_field_3,
    custom_int_1 = new.custom_int_1,
    custom_int_2 = new.custom_int_2,
    custom_int_3 = new.custom_int_3,
    doc_ref_code = new.doc_ref_code,
    carrier_expenses = new.carrier_expenses,
    registry_code = new.registry_code,
    carrier_tracking_number = new.carrier_tracking_number,
    carrier_expenses_currency_id = new.carrier_expenses_currency_id,
    search_index = new.search_index,
    dest_name = new.dest_name,
    carrier_name = new.carrier_name,
    location_name = new.location_name,
    goods_type_id = new.goods_type_id,
    importexport = new.importexport,
    carrier_invoice_number = new.carrier_invoice_number,
    carrier_invoice_date = new.carrier_invoice_date,
    workflow_id = new.workflow_id,
    vessel_department_id = new.vessel_department_id,
    payment_term_id = new.payment_term_id,
    an_code = new.an_code,
    ref_date = new.ref_date,
    ref_code = new.ref_code,
    stamp_duty = new.stamp_duty,
    exchange_rate = new.exchange_rate,
    conversion_date = new.conversion_date,
    work_code = new.work_code,
    work_date = new.work_date,
    deleted = new.deleted,
    dest_vat_number = new.dest_vat_number,
    holder_vat_number = new.holder_vat_number,
    currency_code = new.currency_code,
    currency_description = new.currency_description,
    taxable_amount = new.taxable_amount,
    vat_taxes = new.vat_taxes,
    assigned = new.assigned,
    inventory = new.inventory,
	location_code = new.location_code,
	vessel_id = new.vessel_id,
	vessel_name = new.vessel_name,
	vessel_code = new.vessel_code
  WHERE 
    (id = old.id) ;

  return new; 
end; 
$BODY$;

ALTER FUNCTION documents.heads_view_update_trg()
    OWNER TO ergo;