CREATE OR REPLACE FUNCTION documents.rows_view_update_trg()
    RETURNS trigger
    LANGUAGE 'plpgsql'
     NOT LEAKPROOF
AS $BODY$
begin

  UPDATE documents.rows SET
    doc_id = new.doc_id,
    item_id = new.item_id,
    row_date = new.row_date,
    inout = new.inout,
    model = new.model,
    code = new.code,
    description = new.description,
    price = new.price,
    vat_id = new.vat_id,
    vat_rate = new.vat_rate,
    discount_rate = new.discount_rate,
    discount_comm_rate = new.discount_comm_rate,
    discount_ext_rate = new.discount_ext_rate,
    quantity = new.quantity,
    secondhand = new.secondhand,
    dimension_id1 = new.dimension_id1,
    dimension_id2 = new.dimension_id2,
    dimensions_id3 = new.dimensions_id3,
    currency_id = new.currency_id,
    exchange_rate = new.exchange_rate,
    position = new.position,
    delivery_date = new.delivery_date,
    barcode = new.barcode,
    delivered_qty = new.delivered_qty,
    sample_qty = new.sample_qty,
    is_sample = new.is_sample,
    ref_code = new.ref_code,
    doc_origin_id = new.doc_origin_id,
    row_origin_id = new.row_origin_id,
    anagrams_ref_id = new.anagrams_ref_id,
    collector_points = new.collector_points,
    collector_points_forfait = new.collector_points_forfait,
    package_type_id = new.package_type_id,
    jguid = new.jguid,
    ordered_qty = new.ordered_qty,
    pallets = new.pallets,
    weight_on_delivery = new.weight_on_delivery,
    weight_on_order = new.weight_on_order,
    weight_on_shipping = new.weight_on_shipping,
    volume = new.volume,
    doc_origin_number = new.doc_origin_number,
    doc_origin_date = new.doc_origin_date,
    customs_doc_ref = new.customs_doc_ref,
    customs_doc_type_id = new.customs_doc_type_id,
    purchase_order = new.purchase_order,
    insert_date = new.insert_date,
    update_date = new.update_date,
    user_insert = new.user_insert,
    user_update = new.user_update,
    size_weight = new.size_weight,
    size_length = new.size_length,
    size_height = new.size_height,
    inventory_qty = new.inventory_qty,
    inventory_weight = new.inventory_weight,
    customs_doc_cin = new.customs_doc_cin,
    customs_doc_date = new.customs_doc_date,
    supplier_id = new.supplier_id,
    doc_origin__number = new.doc_origin__number,
    db_schema_id = new.db_schema_id,
    doc_head_jguid = new.doc_head_jguid,
    item_jguid = new.item_jguid,
    container_status = new.container_status,
    rights = new.rights,
    invoice_number = new.invoice_number,
    custom_field_1 = new.custom_field_1,
    custom_field_2 = new.custom_field_2,
    invoice_amount = new.invoice_amount,
    custom_field_3 = new.custom_field_3,
    json_nested_table = new.json_nested_table,
    invoice_date = new.invoice_date,
    importexport = new.importexport,
    type_id = new.type_id,
    is_description = new.is_description,
    exchange_rage = new.exchange_rage,
    freight_qty = new.freight_qty,
    amount = new.amount,
    vat_code = new.vat_code,
    freight_rate = new.freight_rate,
    vat_description = new.vat_description,
    currency_code = new.currency_code,
    currency_description = new.currency_description,
    flg_description = new.flg_description,
	haz_class = new.haz_class
  WHERE 
    (jguid = old.jguid) ;

  return new; 
end; 
$BODY$;

ALTER FUNCTION documents.rows_view_update_trg()
    OWNER TO ergo;