object dmTestingComponents: TdmTestingComponents
  OldCreateOrder = False
  Height = 335
  Width = 627
  object JanuaCoreLogger1: TJanuaCoreLogger
    Component = Owner
    LogType = jltError
    AutoFileName = True
    IsCustomServer = False
    ErrorFileName = 'Error'
    LogFileName = 'Log'
    Left = 184
    Top = 120
  end
  object JanuaSystem1: TJanuaSystem
    Verbose = False
    LogToFile = False
    Language = jlaNone
    TestMode = False
    Left = 184
    Top = 248
  end
  object JanuaPostgresSystem1: TJanuaPostgresSystem
    Verbose = False
    LogToFile = False
    Language = jlaNone
    TestMode = False
    Connected = False
    JanuaMailSender = JanuaMailSender1
    KeepAlive = False
    SessionID = 0
    LoadedProfile = False
    Left = 296
    Top = 152
  end
  object JanuaMailSender1: TJanuaMailSender
    Verbose = False
    LogToFile = False
    Language = jlaNone
    TestMode = False
    sTo = ''
    sCC = ''
    sBcc = ''
    sAttach = ''
    sText = ''
    sSubject = ''
    sFrom = ''
    sFromAddr = ''
    Sent = False
    TestingFileName = ''
    MailPassword = ''
    MailUsername = ''
    MailServer = ''
    MailEncoding = jmeHTML
    VerifiedServer = False
    ServerIP = ''
    CustomMailTest = False
    MailEncryption = jmsNone
    Encryption = False
    Left = 296
    Top = 88
  end
  object JanuaServerHealthBooking1: TJanuaServerHealthBooking
    Verbose = False
    LogToFile = False
    Language = jlaNone
    TestMode = False
    Connected = False
    JanuaMailSender = JanuaMailSender1
    KeepAlive = False
    SessionID = 0
    select1 = 0
    select2 = 0
    select3 = 0
    JanuaServerSystem = JanuaPostgresSystem1
    bookingID = 0
    booking64 = 'MA=='
    SearchID = 0
    SearchItemID = 0
    Left = 296
    Top = 216
  end
  object JanuaServerPgFootball1: TJanuaServerPgFootball
    Verbose = False
    LogToFile = False
    Language = jlaNone
    TestMode = False
    Connected = False
    JanuaMailSender = JanuaMailSender1
    KeepAlive = False
    SessionID = 0
    JanuaSystem = JanuaPostgresSystem1
    JanuaCms = JanuaServerPgCms1
    GoalRankingLimit = 0
    Left = 296
    Top = 24
  end
  object JanuaServerPgCms1: TJanuaServerPgCms
    Verbose = False
    LogToFile = False
    Language = jlaNone
    TestMode = False
    Connected = False
    JanuaMailSender = JanuaMailSender1
    KeepAlive = False
    SessionID = 0
    ThemeID = 0
    ShowMessage = False
    NumArticles = 0
    JanuaServerSystem = JanuaPostgresSystem1
    JanuaGraphicMenu.Verbose = False
    JanuaGraphicMenu.KeepAlive = False
    JanuaGraphicMenu.id = 0
    Left = 296
    Top = 272
  end
  object JanuaCloudOAuth1: TJanuaCloudOAuth
    Verbose = False
    LogToFile = False
    Language = jlaNone
    TestMode = False
    ISOLanguage.Verbose = False
    ISOLanguage.ID = 1
    ISOLanguage.LanguageName = 'Italiano'
    ISOLanguage.Code = 'it'
    ISOLanguage.IsoCode3 = 'ita'
    ISOLanguage.Language = jlaItalian
    ISOCountry.Verbose = False
    ISOCountry.isoCountry = jicItalia
    SocialType = jstFacebook
    JanuaFacebookOuth.Verbose = False
    JanuaFacebookOuth.BaseURL = 'https://graph.facebook.com/'
    JanuaFacebookOuth.OAuthURL = 'https://www.facebook.com/dialog/oauth'
    JanuaFacebookOuth.AppID = '174153993173442'
    JanuaFacebookOuth.Scopes = [jfsEmail, jfsAboutMe, jfsBirthDay, jfsPublicProfile, jfsEducation, jfsHomeTown, jfsLocation]
    JanuaFacebookOuth.ResponseType = jfrCode
    Left = 416
    Top = 56
  end
end
