unit JOrm.Carservice.BookingHeadView.Custom.Intf;

interface

uses Janua.Orm.Intf;

type

  ICustomBookingHeadView = interface(IJanuaRecord)
    ['{A5D62E8B-9917-4239-A979-A4A1CFD30F44}']
    function GetId: IJanuaField;
    procedure SetId(const Value: IJanuaField);
    property Id: IJanuaField read GetId write SetId;
    function GetOfficeId: IJanuaField;
    procedure SetOfficeId(const Value: IJanuaField);
    property OfficeId: IJanuaField read GetOfficeId write SetOfficeId;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
    function GetDbSchemaId: IJanuaField;
    procedure SetDbSchemaId(const Value: IJanuaField);
    property DbSchemaId: IJanuaField read GetDbSchemaId write SetDbSchemaId;
    function GetUserInsert: IJanuaField;
    procedure SetUserInsert(const Value: IJanuaField);
    property UserInsert: IJanuaField read GetUserInsert write SetUserInsert;
    function GetInsertDate: IJanuaField;
    procedure SetInsertDate(const Value: IJanuaField);
    property InsertDate: IJanuaField read GetInsertDate write SetInsertDate;
    function GetCustomerId: IJanuaField;
    procedure SetCustomerId(const Value: IJanuaField);
    property CustomerId: IJanuaField read GetCustomerId write SetCustomerId;
    function GetStateId: IJanuaField;
    procedure SetStateId(const Value: IJanuaField);
    property StateId: IJanuaField read GetStateId write SetStateId;
    function GetBranchId: IJanuaField;
    procedure SetBranchId(const Value: IJanuaField);
    property BranchId: IJanuaField read GetBranchId write SetBranchId;
    function GetVehicleModel: IJanuaField;
    procedure SetVehicleModel(const Value: IJanuaField);
    property VehicleModel: IJanuaField read GetVehicleModel write SetVehicleModel;
    function GetVehicleColor: IJanuaField;
    procedure SetVehicleColor(const Value: IJanuaField);
    property VehicleColor: IJanuaField read GetVehicleColor write SetVehicleColor;
    function GetVehicleNumberplate: IJanuaField;
    procedure SetVehicleNumberplate(const Value: IJanuaField);
    property VehicleNumberplate: IJanuaField read GetVehicleNumberplate write SetVehicleNumberplate;
    function GetPickupDay: IJanuaField;
    procedure SetPickupDay(const Value: IJanuaField);
    property PickupDay: IJanuaField read GetPickupDay write SetPickupDay;
    function GetPickupSlotId: IJanuaField;
    procedure SetPickupSlotId(const Value: IJanuaField);
    property PickupSlotId: IJanuaField read GetPickupSlotId write SetPickupSlotId;
    function GetReturnDay: IJanuaField;
    procedure SetReturnDay(const Value: IJanuaField);
    property ReturnDay: IJanuaField read GetReturnDay write SetReturnDay;
    function GetReturnSlotId: IJanuaField;
    procedure SetReturnSlotId(const Value: IJanuaField);
    property ReturnSlotId: IJanuaField read GetReturnSlotId write SetReturnSlotId;
    function GetAnLastName: IJanuaField;
    procedure SetAnLastName(const Value: IJanuaField);
    property AnLastName: IJanuaField read GetAnLastName write SetAnLastName;
    function GetAnVatId: IJanuaField;
    procedure SetAnVatId(const Value: IJanuaField);
    property AnVatId: IJanuaField read GetAnVatId write SetAnVatId;
    function GetAnAddress: IJanuaField;
    procedure SetAnAddress(const Value: IJanuaField);
    property AnAddress: IJanuaField read GetAnAddress write SetAnAddress;
    function GetAnPostalCode: IJanuaField;
    procedure SetAnPostalCode(const Value: IJanuaField);
    property AnPostalCode: IJanuaField read GetAnPostalCode write SetAnPostalCode;
    function GetAnFiscalCode: IJanuaField;
    procedure SetAnFiscalCode(const Value: IJanuaField);
    property AnFiscalCode: IJanuaField read GetAnFiscalCode write SetAnFiscalCode;
    function GetAnTown: IJanuaField;
    procedure SetAnTown(const Value: IJanuaField);
    property AnTown: IJanuaField read GetAnTown write SetAnTown;
    function GetServiceName: IJanuaField;
    procedure SetServiceName(const Value: IJanuaField);
    property ServiceName: IJanuaField read GetServiceName write SetServiceName;
    function GetServiceAddress: IJanuaField;
    procedure SetServiceAddress(const Value: IJanuaField);
    property ServiceAddress: IJanuaField read GetServiceAddress write SetServiceAddress;
    function GetAnPhone: IJanuaField;
    procedure SetAnPhone(const Value: IJanuaField);
    property AnPhone: IJanuaField read GetAnPhone write SetAnPhone;
    function GetAnEmail: IJanuaField;
    procedure SetAnEmail(const Value: IJanuaField);
    property AnEmail: IJanuaField read GetAnEmail write SetAnEmail;
    function GetAnCellular: IJanuaField;
    procedure SetAnCellular(const Value: IJanuaField);
    property AnCellular: IJanuaField read GetAnCellular write SetAnCellular;
    function GetBranchAddress: IJanuaField;
    procedure SetBranchAddress(const Value: IJanuaField);
    property BranchAddress: IJanuaField read GetBranchAddress write SetBranchAddress;
    function GetBranchPostalCode: IJanuaField;
    procedure SetBranchPostalCode(const Value: IJanuaField);
    property BranchPostalCode: IJanuaField read GetBranchPostalCode write SetBranchPostalCode;
    function GetBranchTown: IJanuaField;
    procedure SetBranchTown(const Value: IJanuaField);
    property BranchTown: IJanuaField read GetBranchTown write SetBranchTown;
    function GetBranchPhone: IJanuaField;
    procedure SetBranchPhone(const Value: IJanuaField);
    property BranchPhone: IJanuaField read GetBranchPhone write SetBranchPhone;
    function GetCustFirstName: IJanuaField;
    procedure SetCustFirstName(const Value: IJanuaField);
    property CustFirstName: IJanuaField read GetCustFirstName write SetCustFirstName;
    function GetCustLastName: IJanuaField;
    procedure SetCustLastName(const Value: IJanuaField);
    property CustLastName: IJanuaField read GetCustLastName write SetCustLastName;
    function GetFullAddress: IJanuaField;
    procedure SetFullAddress(const Value: IJanuaField);
    property FullAddress: IJanuaField read GetFullAddress write SetFullAddress;
    function GetCustCellular: IJanuaField;
    procedure SetCustCellular(const Value: IJanuaField);
    property CustCellular: IJanuaField read GetCustCellular write SetCustCellular;
    function GetCustEmail: IJanuaField;
    procedure SetCustEmail(const Value: IJanuaField);
    property CustEmail: IJanuaField read GetCustEmail write SetCustEmail;
    function GetPickupAddress: IJanuaField;
    procedure SetPickupAddress(const Value: IJanuaField);
    property PickupAddress: IJanuaField read GetPickupAddress write SetPickupAddress;
    function GetReturnAddress: IJanuaField;
    procedure SetReturnAddress(const Value: IJanuaField);
    property ReturnAddress: IJanuaField read GetReturnAddress write SetReturnAddress;
    function GetPickupTime: IJanuaField;
    procedure SetPickupTime(const Value: IJanuaField);
    property PickupTime: IJanuaField read GetPickupTime write SetPickupTime;
    function GetReturnTime: IJanuaField;
    procedure SetReturnTime(const Value: IJanuaField);
    property ReturnTime: IJanuaField read GetReturnTime write SetReturnTime;
    function GetPickupDate: IJanuaField;
    procedure SetPickupDate(const Value: IJanuaField);
    property PickupDate: IJanuaField read GetPickupDate write SetPickupDate;
    function GetReturnDate: IJanuaField;
    procedure SetReturnDate(const Value: IJanuaField);
    property ReturnDate: IJanuaField read GetReturnDate write SetReturnDate;
    function GetDriver1Id: IJanuaField;
    procedure SetDriver1Id(const Value: IJanuaField);
    property Driver1Id: IJanuaField read GetDriver1Id write SetDriver1Id;
    function GetDriver2Id: IJanuaField;
    procedure SetDriver2Id(const Value: IJanuaField);
    property Driver2Id: IJanuaField read GetDriver2Id write SetDriver2Id;
    function GetDriver1Email: IJanuaField;
    procedure SetDriver1Email(const Value: IJanuaField);
    property Driver1Email: IJanuaField read GetDriver1Email write SetDriver1Email;
    function GetDriver2Email: IJanuaField;
    procedure SetDriver2Email(const Value: IJanuaField);
    property Driver2Email: IJanuaField read GetDriver2Email write SetDriver2Email;
    function GetDriver1Cellular: IJanuaField;
    procedure SetDriver1Cellular(const Value: IJanuaField);
    property Driver1Cellular: IJanuaField read GetDriver1Cellular write SetDriver1Cellular;
    function GetDriver2Cellular: IJanuaField;
    procedure SetDriver2Cellular(const Value: IJanuaField);
    property Driver2Cellular: IJanuaField read GetDriver2Cellular write SetDriver2Cellular;
    function GetPickupJguid: IJanuaField;
    procedure SetPickupJguid(const Value: IJanuaField);
    property PickupJguid: IJanuaField read GetPickupJguid write SetPickupJguid;
    function GetReturnJguid: IJanuaField;
    procedure SetReturnJguid(const Value: IJanuaField);
    property ReturnJguid: IJanuaField read GetReturnJguid write SetReturnJguid;

    function GetPickup2Address: IJanuaField;
    property Pickup2Address: IJanuaField read GetPickup2Address;
    function GetReturn2Address: IJanuaField;
    property Return2Address: IJanuaField read GetReturn2Address;
  end;

  ICustomBookingHeadViews = interface(IJanuaRecordSet)
    ['{CACC6BE1-EA56-4C4F-B58A-7579DF507392}']
    function GetId: IJanuaField;
    procedure SetId(const Value: IJanuaField);
    property Id: IJanuaField read GetId write SetId;
    function GetOfficeId: IJanuaField;
    procedure SetOfficeId(const Value: IJanuaField);
    property OfficeId: IJanuaField read GetOfficeId write SetOfficeId;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
    function GetDbSchemaId: IJanuaField;
    procedure SetDbSchemaId(const Value: IJanuaField);
    property DbSchemaId: IJanuaField read GetDbSchemaId write SetDbSchemaId;
    function GetUserInsert: IJanuaField;
    procedure SetUserInsert(const Value: IJanuaField);
    property UserInsert: IJanuaField read GetUserInsert write SetUserInsert;
    function GetInsertDate: IJanuaField;
    procedure SetInsertDate(const Value: IJanuaField);
    property InsertDate: IJanuaField read GetInsertDate write SetInsertDate;
    function GetCustomerId: IJanuaField;
    procedure SetCustomerId(const Value: IJanuaField);
    property CustomerId: IJanuaField read GetCustomerId write SetCustomerId;
    function GetStateId: IJanuaField;
    procedure SetStateId(const Value: IJanuaField);
    property StateId: IJanuaField read GetStateId write SetStateId;
    function GetBranchId: IJanuaField;
    procedure SetBranchId(const Value: IJanuaField);
    property BranchId: IJanuaField read GetBranchId write SetBranchId;
    function GetVehicleModel: IJanuaField;
    procedure SetVehicleModel(const Value: IJanuaField);
    property VehicleModel: IJanuaField read GetVehicleModel write SetVehicleModel;
    function GetVehicleColor: IJanuaField;
    procedure SetVehicleColor(const Value: IJanuaField);
    property VehicleColor: IJanuaField read GetVehicleColor write SetVehicleColor;
    function GetVehicleNumberplate: IJanuaField;
    procedure SetVehicleNumberplate(const Value: IJanuaField);
    property VehicleNumberplate: IJanuaField read GetVehicleNumberplate write SetVehicleNumberplate;
    function GetPickupDay: IJanuaField;
    procedure SetPickupDay(const Value: IJanuaField);
    property PickupDay: IJanuaField read GetPickupDay write SetPickupDay;
    function GetPickupSlotId: IJanuaField;
    procedure SetPickupSlotId(const Value: IJanuaField);
    property PickupSlotId: IJanuaField read GetPickupSlotId write SetPickupSlotId;
    function GetReturnDay: IJanuaField;
    procedure SetReturnDay(const Value: IJanuaField);
    property ReturnDay: IJanuaField read GetReturnDay write SetReturnDay;
    function GetReturnSlotId: IJanuaField;
    procedure SetReturnSlotId(const Value: IJanuaField);
    property ReturnSlotId: IJanuaField read GetReturnSlotId write SetReturnSlotId;
    function GetAnLastName: IJanuaField;
    procedure SetAnLastName(const Value: IJanuaField);
    property AnLastName: IJanuaField read GetAnLastName write SetAnLastName;
    function GetAnVatId: IJanuaField;
    procedure SetAnVatId(const Value: IJanuaField);
    property AnVatId: IJanuaField read GetAnVatId write SetAnVatId;
    function GetAnAddress: IJanuaField;
    procedure SetAnAddress(const Value: IJanuaField);
    property AnAddress: IJanuaField read GetAnAddress write SetAnAddress;
    function GetAnPostalCode: IJanuaField;
    procedure SetAnPostalCode(const Value: IJanuaField);
    property AnPostalCode: IJanuaField read GetAnPostalCode write SetAnPostalCode;
    function GetAnFiscalCode: IJanuaField;
    procedure SetAnFiscalCode(const Value: IJanuaField);
    property AnFiscalCode: IJanuaField read GetAnFiscalCode write SetAnFiscalCode;
    function GetAnTown: IJanuaField;
    procedure SetAnTown(const Value: IJanuaField);
    property AnTown: IJanuaField read GetAnTown write SetAnTown;
    function GetServiceName: IJanuaField;
    procedure SetServiceName(const Value: IJanuaField);
    property ServiceName: IJanuaField read GetServiceName write SetServiceName;
    function GetServiceAddress: IJanuaField;
    procedure SetServiceAddress(const Value: IJanuaField);
    property ServiceAddress: IJanuaField read GetServiceAddress write SetServiceAddress;
    function GetAnPhone: IJanuaField;
    procedure SetAnPhone(const Value: IJanuaField);
    property AnPhone: IJanuaField read GetAnPhone write SetAnPhone;
    function GetAnEmail: IJanuaField;
    procedure SetAnEmail(const Value: IJanuaField);
    property AnEmail: IJanuaField read GetAnEmail write SetAnEmail;
    function GetAnCellular: IJanuaField;
    procedure SetAnCellular(const Value: IJanuaField);
    property AnCellular: IJanuaField read GetAnCellular write SetAnCellular;
    function GetBranchAddress: IJanuaField;
    procedure SetBranchAddress(const Value: IJanuaField);
    property BranchAddress: IJanuaField read GetBranchAddress write SetBranchAddress;
    function GetBranchPostalCode: IJanuaField;
    procedure SetBranchPostalCode(const Value: IJanuaField);
    property BranchPostalCode: IJanuaField read GetBranchPostalCode write SetBranchPostalCode;
    function GetBranchTown: IJanuaField;
    procedure SetBranchTown(const Value: IJanuaField);
    property BranchTown: IJanuaField read GetBranchTown write SetBranchTown;
    function GetBranchPhone: IJanuaField;
    procedure SetBranchPhone(const Value: IJanuaField);
    property BranchPhone: IJanuaField read GetBranchPhone write SetBranchPhone;
    function GetCustFirstName: IJanuaField;
    procedure SetCustFirstName(const Value: IJanuaField);
    property CustFirstName: IJanuaField read GetCustFirstName write SetCustFirstName;
    function GetCustLastName: IJanuaField;
    procedure SetCustLastName(const Value: IJanuaField);
    property CustLastName: IJanuaField read GetCustLastName write SetCustLastName;
    function GetFullAddress: IJanuaField;
    procedure SetFullAddress(const Value: IJanuaField);
    property FullAddress: IJanuaField read GetFullAddress write SetFullAddress;
    function GetCustCellular: IJanuaField;
    procedure SetCustCellular(const Value: IJanuaField);
    property CustCellular: IJanuaField read GetCustCellular write SetCustCellular;
    function GetCustEmail: IJanuaField;
    procedure SetCustEmail(const Value: IJanuaField);
    property CustEmail: IJanuaField read GetCustEmail write SetCustEmail;
    function GetPickupAddress: IJanuaField;
    procedure SetPickupAddress(const Value: IJanuaField);
    property PickupAddress: IJanuaField read GetPickupAddress write SetPickupAddress;
    function GetReturnAddress: IJanuaField;
    procedure SetReturnAddress(const Value: IJanuaField);
    property ReturnAddress: IJanuaField read GetReturnAddress write SetReturnAddress;
    function GetPickupTime: IJanuaField;
    procedure SetPickupTime(const Value: IJanuaField);
    property PickupTime: IJanuaField read GetPickupTime write SetPickupTime;
    function GetReturnTime: IJanuaField;
    procedure SetReturnTime(const Value: IJanuaField);
    property ReturnTime: IJanuaField read GetReturnTime write SetReturnTime;
    function GetPickupDate: IJanuaField;
    procedure SetPickupDate(const Value: IJanuaField);
    property PickupDate: IJanuaField read GetPickupDate write SetPickupDate;
    function GetReturnDate: IJanuaField;
    procedure SetReturnDate(const Value: IJanuaField);
    property ReturnDate: IJanuaField read GetReturnDate write SetReturnDate;
    function GetDriver1Id: IJanuaField;
    procedure SetDriver1Id(const Value: IJanuaField);
    property Driver1Id: IJanuaField read GetDriver1Id write SetDriver1Id;
    function GetDriver2Id: IJanuaField;
    procedure SetDriver2Id(const Value: IJanuaField);
    property Driver2Id: IJanuaField read GetDriver2Id write SetDriver2Id;
    function GetDriver1Email: IJanuaField;
    procedure SetDriver1Email(const Value: IJanuaField);
    property Driver1Email: IJanuaField read GetDriver1Email write SetDriver1Email;
    function GetDriver2Email: IJanuaField;
    procedure SetDriver2Email(const Value: IJanuaField);
    property Driver2Email: IJanuaField read GetDriver2Email write SetDriver2Email;
    function GetDriver1Cellular: IJanuaField;
    procedure SetDriver1Cellular(const Value: IJanuaField);
    property Driver1Cellular: IJanuaField read GetDriver1Cellular write SetDriver1Cellular;
    function GetDriver2Cellular: IJanuaField;
    procedure SetDriver2Cellular(const Value: IJanuaField);
    property Driver2Cellular: IJanuaField read GetDriver2Cellular write SetDriver2Cellular;
    function GetPickupJguid: IJanuaField;
    procedure SetPickupJguid(const Value: IJanuaField);
    property PickupJguid: IJanuaField read GetPickupJguid write SetPickupJguid;
    function GetReturnJguid: IJanuaField;
    procedure SetReturnJguid(const Value: IJanuaField);
    property ReturnJguid: IJanuaField read GetReturnJguid write SetReturnJguid;
    function GetPickup2Address: IJanuaField;
    property Pickup2Address: IJanuaField read GetPickup2Address;
    function GetReturn2Address: IJanuaField;
    property Return2Address: IJanuaField read GetReturn2Address;
  end;

implementation

end.
