unit JOrm.Anagraph.Anagraphs.Custom.Intf;

interface

uses Janua.Orm.Intf;

type
  ICustomAnagraph = interface(IJanuaRecord)
    ['{0C7CECCF-0314-4F2E-8560-DC7856BD0145}']
    function GetDbSchemaId: IJanuaField;
    procedure SetDbSchemaId(const Value: IJanuaField);
    property DbSchemaId: IJanuaField read GetDbSchemaId write SetDbSchemaId;
    function GetAnagraphId: IJanuaField;
    procedure SetAnagraphId(const Value: IJanuaField);
    property AnagraphId: IJanuaField read GetAnagraphId write SetAnagraphId;
    function GetAnTitle: IJanuaField;
    procedure SetAnTitle(const Value: IJanuaField);
    property AnTitle: IJanuaField read GetAnTitle write SetAnTitle;
    function GetAnName: IJanuaField;
    procedure SetAnName(const Value: IJanuaField);
    property AnName: IJanuaField read GetAnName write SetAnName;
    function GetAnSecondName: IJanuaField;
    procedure SetAnSecondName(const Value: IJanuaField);
    property AnSecondName: IJanuaField read GetAnSecondName write SetAnSecondName;
    function GetAnLastName: IJanuaField;
    procedure SetAnLastName(const Value: IJanuaField);
    property AnLastName: IJanuaField read GetAnLastName write SetAnLastName;
    function GetAnNotes: IJanuaField;
    procedure SetAnNotes(const Value: IJanuaField);
    property AnNotes: IJanuaField read GetAnNotes write SetAnNotes;
    function GetAnAddress: IJanuaField;
    procedure SetAnAddress(const Value: IJanuaField);
    property AnAddress: IJanuaField read GetAnAddress write SetAnAddress;
    function GetAnTown: IJanuaField;
    procedure SetAnTown(const Value: IJanuaField);
    property AnTown: IJanuaField read GetAnTown write SetAnTown;
    function GetAnPostalCode: IJanuaField;
    procedure SetAnPostalCode(const Value: IJanuaField);
    property AnPostalCode: IJanuaField read GetAnPostalCode write SetAnPostalCode;
    function GetAnIsoCountryCode: IJanuaField;
    procedure SetAnIsoCountryCode(const Value: IJanuaField);
    property AnIsoCountryCode: IJanuaField read GetAnIsoCountryCode write SetAnIsoCountryCode;
    function GetAnStateProvince: IJanuaField;
    procedure SetAnStateProvince(const Value: IJanuaField);
    property AnStateProvince: IJanuaField read GetAnStateProvince write SetAnStateProvince;
    function GetAnPhone: IJanuaField;
    procedure SetAnPhone(const Value: IJanuaField);
    property AnPhone: IJanuaField read GetAnPhone write SetAnPhone;
    function GetAnPhone2: IJanuaField;
    procedure SetAnPhone2(const Value: IJanuaField);
    property AnPhone2: IJanuaField read GetAnPhone2 write SetAnPhone2;
    function GetAnFax: IJanuaField;
    procedure SetAnFax(const Value: IJanuaField);
    property AnFax: IJanuaField read GetAnFax write SetAnFax;
    function GetAnCellular: IJanuaField;
    procedure SetAnCellular(const Value: IJanuaField);
    property AnCellular: IJanuaField read GetAnCellular write SetAnCellular;
    function GetAnCode: IJanuaField;
    procedure SetAnCode(const Value: IJanuaField);
    property AnCode: IJanuaField read GetAnCode write SetAnCode;
    function GetAnVatNumeric: IJanuaField;
    procedure SetAnVatNumeric(const Value: IJanuaField);
    property AnVatNumeric: IJanuaField read GetAnVatNumeric write SetAnVatNumeric;
    function GetAnEmail: IJanuaField;
    procedure SetAnEmail(const Value: IJanuaField);
    property AnEmail: IJanuaField read GetAnEmail write SetAnEmail;
    function GetAnWeb: IJanuaField;
    procedure SetAnWeb(const Value: IJanuaField);
    property AnWeb: IJanuaField read GetAnWeb write SetAnWeb;
    function GetAnContactId: IJanuaField;
    procedure SetAnContactId(const Value: IJanuaField);
    property AnContactId: IJanuaField read GetAnContactId write SetAnContactId;
    function GetAnBankAccount: IJanuaField;
    procedure SetAnBankAccount(const Value: IJanuaField);
    property AnBankAccount: IJanuaField read GetAnBankAccount write SetAnBankAccount;
    function GetAnPaymentDes: IJanuaField;
    procedure SetAnPaymentDes(const Value: IJanuaField);
    property AnPaymentDes: IJanuaField read GetAnPaymentDes write SetAnPaymentDes;
    function GetAnDiscount: IJanuaField;
    procedure SetAnDiscount(const Value: IJanuaField);
    property AnDiscount: IJanuaField read GetAnDiscount write SetAnDiscount;
    function GetAnDistance: IJanuaField;
    procedure SetAnDistance(const Value: IJanuaField);
    property AnDistance: IJanuaField read GetAnDistance write SetAnDistance;
    function GetAnDistanceMesunit: IJanuaField;
    procedure SetAnDistanceMesunit(const Value: IJanuaField);
    property AnDistanceMesunit: IJanuaField read GetAnDistanceMesunit write SetAnDistanceMesunit;
    function GetAnSex: IJanuaField;
    procedure SetAnSex(const Value: IJanuaField);
    property AnSex: IJanuaField read GetAnSex write SetAnSex;
    function GetAnCodComune: IJanuaField;
    procedure SetAnCodComune(const Value: IJanuaField);
    property AnCodComune: IJanuaField read GetAnCodComune write SetAnCodComune;
    function GetAnCodProvincia: IJanuaField;
    procedure SetAnCodProvincia(const Value: IJanuaField);
    property AnCodProvincia: IJanuaField read GetAnCodProvincia write SetAnCodProvincia;
    function GetAnCreditLine: IJanuaField;
    procedure SetAnCreditLine(const Value: IJanuaField);
    property AnCreditLine: IJanuaField read GetAnCreditLine write SetAnCreditLine;
    function GetAnCurrencyId: IJanuaField;
    procedure SetAnCurrencyId(const Value: IJanuaField);
    property AnCurrencyId: IJanuaField read GetAnCurrencyId write SetAnCurrencyId;
    function GetAnCatId: IJanuaField;
    procedure SetAnCatId(const Value: IJanuaField);
    property AnCatId: IJanuaField read GetAnCatId write SetAnCatId;
    function GetAnNotes2: IJanuaField;
    procedure SetAnNotes2(const Value: IJanuaField);
    property AnNotes2: IJanuaField read GetAnNotes2 write SetAnNotes2;
    function GetAnNotes3: IJanuaField;
    procedure SetAnNotes3(const Value: IJanuaField);
    property AnNotes3: IJanuaField read GetAnNotes3 write SetAnNotes3;
    function GetAnEdi: IJanuaField;
    procedure SetAnEdi(const Value: IJanuaField);
    property AnEdi: IJanuaField read GetAnEdi write SetAnEdi;
    function GetAnPrivacy: IJanuaField;
    procedure SetAnPrivacy(const Value: IJanuaField);
    property AnPrivacy: IJanuaField read GetAnPrivacy write SetAnPrivacy;
    function GetAnOfficeId: IJanuaField;
    procedure SetAnOfficeId(const Value: IJanuaField);
    property AnOfficeId: IJanuaField read GetAnOfficeId write SetAnOfficeId;
    function GetAnCodProvRif: IJanuaField;
    procedure SetAnCodProvRif(const Value: IJanuaField);
    property AnCodProvRif: IJanuaField read GetAnCodProvRif write SetAnCodProvRif;
    function GetAnDataFido: IJanuaField;
    procedure SetAnDataFido(const Value: IJanuaField);
    property AnDataFido: IJanuaField read GetAnDataFido write SetAnDataFido;
    function GetAnUserInsert: IJanuaField;
    procedure SetAnUserInsert(const Value: IJanuaField);
    property AnUserInsert: IJanuaField read GetAnUserInsert write SetAnUserInsert;
    function GetAnUserUpdate: IJanuaField;
    procedure SetAnUserUpdate(const Value: IJanuaField);
    property AnUserUpdate: IJanuaField read GetAnUserUpdate write SetAnUserUpdate;
    function GetAnAreaId: IJanuaField;
    procedure SetAnAreaId(const Value: IJanuaField);
    property AnAreaId: IJanuaField read GetAnAreaId write SetAnAreaId;
    function GetAnAgentId: IJanuaField;
    procedure SetAnAgentId(const Value: IJanuaField);
    property AnAgentId: IJanuaField read GetAnAgentId write SetAnAgentId;
    function GetAnAreaCode: IJanuaField;
    procedure SetAnAreaCode(const Value: IJanuaField);
    property AnAreaCode: IJanuaField read GetAnAreaCode write SetAnAreaCode;
    function GetAnZoneId: IJanuaField;
    procedure SetAnZoneId(const Value: IJanuaField);
    property AnZoneId: IJanuaField read GetAnZoneId write SetAnZoneId;
    function GetAnInsId: IJanuaField;
    procedure SetAnInsId(const Value: IJanuaField);
    property AnInsId: IJanuaField read GetAnInsId write SetAnInsId;
    function GetAnUpdId: IJanuaField;
    procedure SetAnUpdId(const Value: IJanuaField);
    property AnUpdId: IJanuaField read GetAnUpdId write SetAnUpdId;
    function GetAnDocuments: IJanuaField;
    procedure SetAnDocuments(const Value: IJanuaField);
    property AnDocuments: IJanuaField read GetAnDocuments write SetAnDocuments;
    function GetAnLastDate: IJanuaField;
    procedure SetAnLastDate(const Value: IJanuaField);
    property AnLastDate: IJanuaField read GetAnLastDate write SetAnLastDate;
    function GetAnBirthdate: IJanuaField;
    procedure SetAnBirthdate(const Value: IJanuaField);
    property AnBirthdate: IJanuaField read GetAnBirthdate write SetAnBirthdate;
    function GetAnOfficeTypeId: IJanuaField;
    procedure SetAnOfficeTypeId(const Value: IJanuaField);
    property AnOfficeTypeId: IJanuaField read GetAnOfficeTypeId write SetAnOfficeTypeId;
    function GetAnSearchname: IJanuaField;
    procedure SetAnSearchname(const Value: IJanuaField);
    property AnSearchname: IJanuaField read GetAnSearchname write SetAnSearchname;
    function GetAnExtraUeFlag: IJanuaField;
    procedure SetAnExtraUeFlag(const Value: IJanuaField);
    property AnExtraUeFlag: IJanuaField read GetAnExtraUeFlag write SetAnExtraUeFlag;
    function GetAnExternalCode: IJanuaField;
    procedure SetAnExternalCode(const Value: IJanuaField);
    property AnExternalCode: IJanuaField read GetAnExternalCode write SetAnExternalCode;
    function GetAnVatId: IJanuaField;
    procedure SetAnVatId(const Value: IJanuaField);
    property AnVatId: IJanuaField read GetAnVatId write SetAnVatId;
    function GetAnPersonalFiscalCode: IJanuaField;
    procedure SetAnPersonalFiscalCode(const Value: IJanuaField);
    property AnPersonalFiscalCode: IJanuaField read GetAnPersonalFiscalCode write SetAnPersonalFiscalCode;
    function GetAnPrivacyPrint: IJanuaField;
    procedure SetAnPrivacyPrint(const Value: IJanuaField);
    property AnPrivacyPrint: IJanuaField read GetAnPrivacyPrint write SetAnPrivacyPrint;
    function GetAnSms: IJanuaField;
    procedure SetAnSms(const Value: IJanuaField);
    property AnSms: IJanuaField read GetAnSms write SetAnSms;
    function GetAnEncryptedFiscalCode: IJanuaField;
    procedure SetAnEncryptedFiscalCode(const Value: IJanuaField);
    property AnEncryptedFiscalCode: IJanuaField read GetAnEncryptedFiscalCode write SetAnEncryptedFiscalCode;
    function GetAnVatPurcentage: IJanuaField;
    procedure SetAnVatPurcentage(const Value: IJanuaField);
    property AnVatPurcentage: IJanuaField read GetAnVatPurcentage write SetAnVatPurcentage;
    function GetAnStatus: IJanuaField;
    procedure SetAnStatus(const Value: IJanuaField);
    property AnStatus: IJanuaField read GetAnStatus write SetAnStatus;
    function GetAnOwnsite: IJanuaField;
    procedure SetAnOwnsite(const Value: IJanuaField);
    property AnOwnsite: IJanuaField read GetAnOwnsite write SetAnOwnsite;
    function GetAnInsuranceId: IJanuaField;
    procedure SetAnInsuranceId(const Value: IJanuaField);
    property AnInsuranceId: IJanuaField read GetAnInsuranceId write SetAnInsuranceId;
    function GetAnAnagraphsAnagraphId: IJanuaField;
    procedure SetAnAnagraphsAnagraphId(const Value: IJanuaField);
    property AnAnagraphsAnagraphId: IJanuaField read GetAnAnagraphsAnagraphId write SetAnAnagraphsAnagraphId;
    function GetAnMainLanguageCode: IJanuaField;
    procedure SetAnMainLanguageCode(const Value: IJanuaField);
    property AnMainLanguageCode: IJanuaField read GetAnMainLanguageCode write SetAnMainLanguageCode;
    function GetAnMainCultureCode: IJanuaField;
    procedure SetAnMainCultureCode(const Value: IJanuaField);
    property AnMainCultureCode: IJanuaField read GetAnMainCultureCode write SetAnMainCultureCode;
    function GetAnFiscalCode: IJanuaField;
    procedure SetAnFiscalCode(const Value: IJanuaField);
    property AnFiscalCode: IJanuaField read GetAnFiscalCode write SetAnFiscalCode;
    function GetAnMainGroupId: IJanuaField;
    procedure SetAnMainGroupId(const Value: IJanuaField);
    property AnMainGroupId: IJanuaField read GetAnMainGroupId write SetAnMainGroupId;
    function GetAnImageId: IJanuaField;
    procedure SetAnImageId(const Value: IJanuaField);
    property AnImageId: IJanuaField read GetAnImageId write SetAnImageId;
    function GetLatitude: IJanuaField;
    procedure SetLatitude(const Value: IJanuaField);
    property Latitude: IJanuaField read GetLatitude write SetLatitude;
    function GetLongitude: IJanuaField;
    procedure SetLongitude(const Value: IJanuaField);
    property Longitude: IJanuaField read GetLongitude write SetLongitude;
    function GetTest: IJanuaField;
    procedure SetTest(const Value: IJanuaField);
    property Test: IJanuaField read GetTest write SetTest;
    function GetSearchIndex: IJanuaField;
    procedure SetSearchIndex(const Value: IJanuaField);
    property SearchIndex: IJanuaField read GetSearchIndex write SetSearchIndex;
    function GetAnBirthplace: IJanuaField;
    procedure SetAnBirthplace(const Value: IJanuaField);
    property AnBirthplace: IJanuaField read GetAnBirthplace write SetAnBirthplace;
    function GetAnBirthplaceCode: IJanuaField;
    procedure SetAnBirthplaceCode(const Value: IJanuaField);
    property AnBirthplaceCode: IJanuaField read GetAnBirthplaceCode write SetAnBirthplaceCode;
    function GetAnagraph64: IJanuaField;
    procedure SetAnagraph64(const Value: IJanuaField);
    property Anagraph64: IJanuaField read GetAnagraph64 write SetAnagraph64;
    function GetMainCategoryId: IJanuaField;
    procedure SetMainCategoryId(const Value: IJanuaField);
    property MainCategoryId: IJanuaField read GetMainCategoryId write SetMainCategoryId;
    function GetOsmId: IJanuaField;
    procedure SetOsmId(const Value: IJanuaField);
    property OsmId: IJanuaField read GetOsmId write SetOsmId;
    function GetAnDescription: IJanuaField;
    procedure SetAnDescription(const Value: IJanuaField);
    property AnDescription: IJanuaField read GetAnDescription write SetAnDescription;
    function GetAnAddressNumber: IJanuaField;
    procedure SetAnAddressNumber(const Value: IJanuaField);
    property AnAddressNumber: IJanuaField read GetAnAddressNumber write SetAnAddressNumber;
    function GetInsertDate: IJanuaField;
    procedure SetInsertDate(const Value: IJanuaField);
    property InsertDate: IJanuaField read GetInsertDate write SetInsertDate;
    function GetUpdateDate: IJanuaField;
    procedure SetUpdateDate(const Value: IJanuaField);
    property UpdateDate: IJanuaField read GetUpdateDate write SetUpdateDate;
    function GetUserInsert: IJanuaField;
    procedure SetUserInsert(const Value: IJanuaField);
    property UserInsert: IJanuaField read GetUserInsert write SetUserInsert;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
    function GetCustomField1: IJanuaField;
    procedure SetCustomField1(const Value: IJanuaField);
    property CustomField1: IJanuaField read GetCustomField1 write SetCustomField1;
    function GetCustomField2: IJanuaField;
    procedure SetCustomField2(const Value: IJanuaField);
    property CustomField2: IJanuaField read GetCustomField2 write SetCustomField2;
    function GetCustomField3: IJanuaField;
    procedure SetCustomField3(const Value: IJanuaField);
    property CustomField3: IJanuaField read GetCustomField3 write SetCustomField3;
    function GetCustomFloat1: IJanuaField;
    procedure SetCustomFloat1(const Value: IJanuaField);
    property CustomFloat1: IJanuaField read GetCustomFloat1 write SetCustomFloat1;
    function GetCustomFloat2: IJanuaField;
    procedure SetCustomFloat2(const Value: IJanuaField);
    property CustomFloat2: IJanuaField read GetCustomFloat2 write SetCustomFloat2;
    function GetCustomInt1: IJanuaField;
    procedure SetCustomInt1(const Value: IJanuaField);
    property CustomInt1: IJanuaField read GetCustomInt1 write SetCustomInt1;
    function GetCustomInt2: IJanuaField;
    procedure SetCustomInt2(const Value: IJanuaField);
    property CustomInt2: IJanuaField read GetCustomInt2 write SetCustomInt2;
    function GetSupplierId: IJanuaField;
    procedure SetSupplierId(const Value: IJanuaField);
    property SupplierId: IJanuaField read GetSupplierId write SetSupplierId;
    function GetVesselId: IJanuaField;
    procedure SetVesselId(const Value: IJanuaField);
    property VesselId: IJanuaField read GetVesselId write SetVesselId;
    function GetAnCountryId: IJanuaField;
    procedure SetAnCountryId(const Value: IJanuaField);
    property AnCountryId: IJanuaField read GetAnCountryId write SetAnCountryId;
    function GetAnIsoCountryCode2: IJanuaField;
    procedure SetAnIsoCountryCode2(const Value: IJanuaField);
    property AnIsoCountryCode2: IJanuaField read GetAnIsoCountryCode2 write SetAnIsoCountryCode2;
    // AnFullAddress
    function GetAnFullAddress: IJanuaField;
    procedure SetAnFullAddress(const Value: IJanuaField);
    property AnFullAddress: IJanuaField read GetAnFullAddress write SetAnFullAddress;
  end;

  ICustomAnagraphs = interface(IJanuaRecordSet)
    ['{64E33652-CBC3-4384-B40E-73C74C4482CA}']
    function GetDbSchemaId: IJanuaField;
    procedure SetDbSchemaId(const Value: IJanuaField);
    property DbSchemaId: IJanuaField read GetDbSchemaId write SetDbSchemaId;
    function GetAnagraphId: IJanuaField;
    procedure SetAnagraphId(const Value: IJanuaField);
    property AnagraphId: IJanuaField read GetAnagraphId write SetAnagraphId;
    function GetAnTitle: IJanuaField;
    procedure SetAnTitle(const Value: IJanuaField);
    property AnTitle: IJanuaField read GetAnTitle write SetAnTitle;
    function GetAnName: IJanuaField;
    procedure SetAnName(const Value: IJanuaField);
    property AnName: IJanuaField read GetAnName write SetAnName;
    function GetAnSecondName: IJanuaField;
    procedure SetAnSecondName(const Value: IJanuaField);
    property AnSecondName: IJanuaField read GetAnSecondName write SetAnSecondName;
    function GetAnLastName: IJanuaField;
    procedure SetAnLastName(const Value: IJanuaField);
    property AnLastName: IJanuaField read GetAnLastName write SetAnLastName;
    function GetAnNotes: IJanuaField;
    procedure SetAnNotes(const Value: IJanuaField);
    property AnNotes: IJanuaField read GetAnNotes write SetAnNotes;
    function GetAnAddress: IJanuaField;
    procedure SetAnAddress(const Value: IJanuaField);
    property AnAddress: IJanuaField read GetAnAddress write SetAnAddress;
    function GetAnTown: IJanuaField;
    procedure SetAnTown(const Value: IJanuaField);
    property AnTown: IJanuaField read GetAnTown write SetAnTown;
    function GetAnPostalCode: IJanuaField;
    procedure SetAnPostalCode(const Value: IJanuaField);
    property AnPostalCode: IJanuaField read GetAnPostalCode write SetAnPostalCode;
    function GetAnIsoCountryCode: IJanuaField;
    procedure SetAnIsoCountryCode(const Value: IJanuaField);
    property AnIsoCountryCode: IJanuaField read GetAnIsoCountryCode write SetAnIsoCountryCode;
    function GetAnStateProvince: IJanuaField;
    procedure SetAnStateProvince(const Value: IJanuaField);
    property AnStateProvince: IJanuaField read GetAnStateProvince write SetAnStateProvince;
    function GetAnPhone: IJanuaField;
    procedure SetAnPhone(const Value: IJanuaField);
    property AnPhone: IJanuaField read GetAnPhone write SetAnPhone;
    function GetAnPhone2: IJanuaField;
    procedure SetAnPhone2(const Value: IJanuaField);
    property AnPhone2: IJanuaField read GetAnPhone2 write SetAnPhone2;
    function GetAnFax: IJanuaField;
    procedure SetAnFax(const Value: IJanuaField);
    property AnFax: IJanuaField read GetAnFax write SetAnFax;
    function GetAnCellular: IJanuaField;
    procedure SetAnCellular(const Value: IJanuaField);
    property AnCellular: IJanuaField read GetAnCellular write SetAnCellular;
    function GetAnCode: IJanuaField;
    procedure SetAnCode(const Value: IJanuaField);
    property AnCode: IJanuaField read GetAnCode write SetAnCode;
    function GetAnVatNumeric: IJanuaField;
    procedure SetAnVatNumeric(const Value: IJanuaField);
    property AnVatNumeric: IJanuaField read GetAnVatNumeric write SetAnVatNumeric;
    function GetAnEmail: IJanuaField;
    procedure SetAnEmail(const Value: IJanuaField);
    property AnEmail: IJanuaField read GetAnEmail write SetAnEmail;
    function GetAnWeb: IJanuaField;
    procedure SetAnWeb(const Value: IJanuaField);
    property AnWeb: IJanuaField read GetAnWeb write SetAnWeb;
    function GetAnContactId: IJanuaField;
    procedure SetAnContactId(const Value: IJanuaField);
    property AnContactId: IJanuaField read GetAnContactId write SetAnContactId;
    function GetAnBankAccount: IJanuaField;
    procedure SetAnBankAccount(const Value: IJanuaField);
    property AnBankAccount: IJanuaField read GetAnBankAccount write SetAnBankAccount;
    function GetAnPaymentDes: IJanuaField;
    procedure SetAnPaymentDes(const Value: IJanuaField);
    property AnPaymentDes: IJanuaField read GetAnPaymentDes write SetAnPaymentDes;
    function GetAnDiscount: IJanuaField;
    procedure SetAnDiscount(const Value: IJanuaField);
    property AnDiscount: IJanuaField read GetAnDiscount write SetAnDiscount;
    function GetAnDistance: IJanuaField;
    procedure SetAnDistance(const Value: IJanuaField);
    property AnDistance: IJanuaField read GetAnDistance write SetAnDistance;
    function GetAnDistanceMesunit: IJanuaField;
    procedure SetAnDistanceMesunit(const Value: IJanuaField);
    property AnDistanceMesunit: IJanuaField read GetAnDistanceMesunit write SetAnDistanceMesunit;
    function GetAnSex: IJanuaField;
    procedure SetAnSex(const Value: IJanuaField);
    property AnSex: IJanuaField read GetAnSex write SetAnSex;
    function GetAnCodComune: IJanuaField;
    procedure SetAnCodComune(const Value: IJanuaField);
    property AnCodComune: IJanuaField read GetAnCodComune write SetAnCodComune;
    function GetAnCodProvincia: IJanuaField;
    procedure SetAnCodProvincia(const Value: IJanuaField);
    property AnCodProvincia: IJanuaField read GetAnCodProvincia write SetAnCodProvincia;
    function GetAnCreditLine: IJanuaField;
    procedure SetAnCreditLine(const Value: IJanuaField);
    property AnCreditLine: IJanuaField read GetAnCreditLine write SetAnCreditLine;
    function GetAnCurrencyId: IJanuaField;
    procedure SetAnCurrencyId(const Value: IJanuaField);
    property AnCurrencyId: IJanuaField read GetAnCurrencyId write SetAnCurrencyId;
    function GetAnCatId: IJanuaField;
    procedure SetAnCatId(const Value: IJanuaField);
    property AnCatId: IJanuaField read GetAnCatId write SetAnCatId;
    function GetAnNotes2: IJanuaField;
    procedure SetAnNotes2(const Value: IJanuaField);
    property AnNotes2: IJanuaField read GetAnNotes2 write SetAnNotes2;
    function GetAnNotes3: IJanuaField;
    procedure SetAnNotes3(const Value: IJanuaField);
    property AnNotes3: IJanuaField read GetAnNotes3 write SetAnNotes3;
    function GetAnEdi: IJanuaField;
    procedure SetAnEdi(const Value: IJanuaField);
    property AnEdi: IJanuaField read GetAnEdi write SetAnEdi;
    function GetAnPrivacy: IJanuaField;
    procedure SetAnPrivacy(const Value: IJanuaField);
    property AnPrivacy: IJanuaField read GetAnPrivacy write SetAnPrivacy;
    function GetAnOfficeId: IJanuaField;
    procedure SetAnOfficeId(const Value: IJanuaField);
    property AnOfficeId: IJanuaField read GetAnOfficeId write SetAnOfficeId;
    function GetAnCodProvRif: IJanuaField;
    procedure SetAnCodProvRif(const Value: IJanuaField);
    property AnCodProvRif: IJanuaField read GetAnCodProvRif write SetAnCodProvRif;
    function GetAnDataFido: IJanuaField;
    procedure SetAnDataFido(const Value: IJanuaField);
    property AnDataFido: IJanuaField read GetAnDataFido write SetAnDataFido;
    function GetAnUserInsert: IJanuaField;
    procedure SetAnUserInsert(const Value: IJanuaField);
    property AnUserInsert: IJanuaField read GetAnUserInsert write SetAnUserInsert;
    function GetAnUserUpdate: IJanuaField;
    procedure SetAnUserUpdate(const Value: IJanuaField);
    property AnUserUpdate: IJanuaField read GetAnUserUpdate write SetAnUserUpdate;
    function GetAnAreaId: IJanuaField;
    procedure SetAnAreaId(const Value: IJanuaField);
    property AnAreaId: IJanuaField read GetAnAreaId write SetAnAreaId;
    function GetAnAgentId: IJanuaField;
    procedure SetAnAgentId(const Value: IJanuaField);
    property AnAgentId: IJanuaField read GetAnAgentId write SetAnAgentId;
    function GetAnAreaCode: IJanuaField;
    procedure SetAnAreaCode(const Value: IJanuaField);
    property AnAreaCode: IJanuaField read GetAnAreaCode write SetAnAreaCode;
    function GetAnZoneId: IJanuaField;
    procedure SetAnZoneId(const Value: IJanuaField);
    property AnZoneId: IJanuaField read GetAnZoneId write SetAnZoneId;
    function GetAnInsId: IJanuaField;
    procedure SetAnInsId(const Value: IJanuaField);
    property AnInsId: IJanuaField read GetAnInsId write SetAnInsId;
    function GetAnUpdId: IJanuaField;
    procedure SetAnUpdId(const Value: IJanuaField);
    property AnUpdId: IJanuaField read GetAnUpdId write SetAnUpdId;
    function GetAnDocuments: IJanuaField;
    procedure SetAnDocuments(const Value: IJanuaField);
    property AnDocuments: IJanuaField read GetAnDocuments write SetAnDocuments;
    function GetAnLastDate: IJanuaField;
    procedure SetAnLastDate(const Value: IJanuaField);
    property AnLastDate: IJanuaField read GetAnLastDate write SetAnLastDate;
    function GetAnBirthdate: IJanuaField;
    procedure SetAnBirthdate(const Value: IJanuaField);
    property AnBirthdate: IJanuaField read GetAnBirthdate write SetAnBirthdate;
    function GetAnOfficeTypeId: IJanuaField;
    procedure SetAnOfficeTypeId(const Value: IJanuaField);
    property AnOfficeTypeId: IJanuaField read GetAnOfficeTypeId write SetAnOfficeTypeId;
    function GetAnSearchname: IJanuaField;
    procedure SetAnSearchname(const Value: IJanuaField);
    property AnSearchname: IJanuaField read GetAnSearchname write SetAnSearchname;
    function GetAnExtraUeFlag: IJanuaField;
    procedure SetAnExtraUeFlag(const Value: IJanuaField);
    property AnExtraUeFlag: IJanuaField read GetAnExtraUeFlag write SetAnExtraUeFlag;
    function GetAnExternalCode: IJanuaField;
    procedure SetAnExternalCode(const Value: IJanuaField);
    property AnExternalCode: IJanuaField read GetAnExternalCode write SetAnExternalCode;
    function GetAnVatId: IJanuaField;
    procedure SetAnVatId(const Value: IJanuaField);
    property AnVatId: IJanuaField read GetAnVatId write SetAnVatId;
    function GetAnPersonalFiscalCode: IJanuaField;
    procedure SetAnPersonalFiscalCode(const Value: IJanuaField);
    property AnPersonalFiscalCode: IJanuaField read GetAnPersonalFiscalCode write SetAnPersonalFiscalCode;
    function GetAnPrivacyPrint: IJanuaField;
    procedure SetAnPrivacyPrint(const Value: IJanuaField);
    property AnPrivacyPrint: IJanuaField read GetAnPrivacyPrint write SetAnPrivacyPrint;
    function GetAnSms: IJanuaField;
    procedure SetAnSms(const Value: IJanuaField);
    property AnSms: IJanuaField read GetAnSms write SetAnSms;
    function GetAnEncryptedFiscalCode: IJanuaField;
    procedure SetAnEncryptedFiscalCode(const Value: IJanuaField);
    property AnEncryptedFiscalCode: IJanuaField read GetAnEncryptedFiscalCode write SetAnEncryptedFiscalCode;
    function GetAnVatPurcentage: IJanuaField;
    procedure SetAnVatPurcentage(const Value: IJanuaField);
    property AnVatPurcentage: IJanuaField read GetAnVatPurcentage write SetAnVatPurcentage;
    function GetAnStatus: IJanuaField;
    procedure SetAnStatus(const Value: IJanuaField);
    property AnStatus: IJanuaField read GetAnStatus write SetAnStatus;
    function GetAnOwnsite: IJanuaField;
    procedure SetAnOwnsite(const Value: IJanuaField);
    property AnOwnsite: IJanuaField read GetAnOwnsite write SetAnOwnsite;
    function GetAnInsuranceId: IJanuaField;
    procedure SetAnInsuranceId(const Value: IJanuaField);
    property AnInsuranceId: IJanuaField read GetAnInsuranceId write SetAnInsuranceId;
    function GetAnAnagraphsAnagraphId: IJanuaField;
    procedure SetAnAnagraphsAnagraphId(const Value: IJanuaField);
    property AnAnagraphsAnagraphId: IJanuaField read GetAnAnagraphsAnagraphId write SetAnAnagraphsAnagraphId;
    function GetAnMainLanguageCode: IJanuaField;
    procedure SetAnMainLanguageCode(const Value: IJanuaField);
    property AnMainLanguageCode: IJanuaField read GetAnMainLanguageCode write SetAnMainLanguageCode;
    function GetAnMainCultureCode: IJanuaField;
    procedure SetAnMainCultureCode(const Value: IJanuaField);
    property AnMainCultureCode: IJanuaField read GetAnMainCultureCode write SetAnMainCultureCode;
    function GetAnFiscalCode: IJanuaField;
    procedure SetAnFiscalCode(const Value: IJanuaField);
    property AnFiscalCode: IJanuaField read GetAnFiscalCode write SetAnFiscalCode;
    function GetAnMainGroupId: IJanuaField;
    procedure SetAnMainGroupId(const Value: IJanuaField);
    property AnMainGroupId: IJanuaField read GetAnMainGroupId write SetAnMainGroupId;
    function GetAnImageId: IJanuaField;
    procedure SetAnImageId(const Value: IJanuaField);
    property AnImageId: IJanuaField read GetAnImageId write SetAnImageId;
    function GetLatitude: IJanuaField;
    procedure SetLatitude(const Value: IJanuaField);
    property Latitude: IJanuaField read GetLatitude write SetLatitude;
    function GetLongitude: IJanuaField;
    procedure SetLongitude(const Value: IJanuaField);
    property Longitude: IJanuaField read GetLongitude write SetLongitude;
    function GetTest: IJanuaField;
    procedure SetTest(const Value: IJanuaField);
    property Test: IJanuaField read GetTest write SetTest;
    function GetSearchIndex: IJanuaField;
    procedure SetSearchIndex(const Value: IJanuaField);
    property SearchIndex: IJanuaField read GetSearchIndex write SetSearchIndex;
    function GetAnBirthplace: IJanuaField;
    procedure SetAnBirthplace(const Value: IJanuaField);
    property AnBirthplace: IJanuaField read GetAnBirthplace write SetAnBirthplace;
    function GetAnBirthplaceCode: IJanuaField;
    procedure SetAnBirthplaceCode(const Value: IJanuaField);
    property AnBirthplaceCode: IJanuaField read GetAnBirthplaceCode write SetAnBirthplaceCode;
    function GetAnagraph64: IJanuaField;
    procedure SetAnagraph64(const Value: IJanuaField);
    property Anagraph64: IJanuaField read GetAnagraph64 write SetAnagraph64;
    function GetMainCategoryId: IJanuaField;
    procedure SetMainCategoryId(const Value: IJanuaField);
    property MainCategoryId: IJanuaField read GetMainCategoryId write SetMainCategoryId;
    function GetOsmId: IJanuaField;
    procedure SetOsmId(const Value: IJanuaField);
    property OsmId: IJanuaField read GetOsmId write SetOsmId;
    function GetAnDescription: IJanuaField;
    procedure SetAnDescription(const Value: IJanuaField);
    property AnDescription: IJanuaField read GetAnDescription write SetAnDescription;
    function GetAnAddressNumber: IJanuaField;
    procedure SetAnAddressNumber(const Value: IJanuaField);
    property AnAddressNumber: IJanuaField read GetAnAddressNumber write SetAnAddressNumber;
    function GetInsertDate: IJanuaField;
    procedure SetInsertDate(const Value: IJanuaField);
    property InsertDate: IJanuaField read GetInsertDate write SetInsertDate;
    function GetUpdateDate: IJanuaField;
    procedure SetUpdateDate(const Value: IJanuaField);
    property UpdateDate: IJanuaField read GetUpdateDate write SetUpdateDate;
    function GetUserInsert: IJanuaField;
    procedure SetUserInsert(const Value: IJanuaField);
    property UserInsert: IJanuaField read GetUserInsert write SetUserInsert;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
    function GetCustomField1: IJanuaField;
    procedure SetCustomField1(const Value: IJanuaField);
    property CustomField1: IJanuaField read GetCustomField1 write SetCustomField1;
    function GetCustomField2: IJanuaField;
    procedure SetCustomField2(const Value: IJanuaField);
    property CustomField2: IJanuaField read GetCustomField2 write SetCustomField2;
    function GetCustomField3: IJanuaField;
    procedure SetCustomField3(const Value: IJanuaField);
    property CustomField3: IJanuaField read GetCustomField3 write SetCustomField3;
    function GetCustomFloat1: IJanuaField;
    procedure SetCustomFloat1(const Value: IJanuaField);
    property CustomFloat1: IJanuaField read GetCustomFloat1 write SetCustomFloat1;
    function GetCustomFloat2: IJanuaField;
    procedure SetCustomFloat2(const Value: IJanuaField);
    property CustomFloat2: IJanuaField read GetCustomFloat2 write SetCustomFloat2;
    function GetCustomInt1: IJanuaField;
    procedure SetCustomInt1(const Value: IJanuaField);
    property CustomInt1: IJanuaField read GetCustomInt1 write SetCustomInt1;
    function GetCustomInt2: IJanuaField;
    procedure SetCustomInt2(const Value: IJanuaField);
    property CustomInt2: IJanuaField read GetCustomInt2 write SetCustomInt2;
    function GetSupplierId: IJanuaField;
    procedure SetSupplierId(const Value: IJanuaField);
    property SupplierId: IJanuaField read GetSupplierId write SetSupplierId;
    function GetVesselId: IJanuaField;
    procedure SetVesselId(const Value: IJanuaField);
    property VesselId: IJanuaField read GetVesselId write SetVesselId;
    function GetAnCountryId: IJanuaField;
    procedure SetAnCountryId(const Value: IJanuaField);
    property AnCountryId: IJanuaField read GetAnCountryId write SetAnCountryId;
    function GetAnIsoCountryCode2: IJanuaField;
    procedure SetAnIsoCountryCode2(const Value: IJanuaField);
    property AnIsoCountryCode2: IJanuaField read GetAnIsoCountryCode2 write SetAnIsoCountryCode2;
    // AnFullAddress
    function GetAnFullAddress: IJanuaField;
    procedure SetAnFullAddress(const Value: IJanuaField);
    property AnFullAddress: IJanuaField read GetAnFullAddress write SetAnFullAddress;
    // ICustomAnagraph
    function GetCustomAnagraph: ICustomAnagraph;
    procedure SetCustomAnagraph(const Value: ICustomAnagraph);
    property CustomAnagraph: ICustomAnagraph read GetCustomAnagraph write SetCustomAnagraph;
  end;

implementation

end.
