unit JOrm.System.UserProfile.Custom.Intf;

interface

uses Janua.Orm.Intf, JOrm.Anagraph.Intf;

type

  ICustomUserProfile = interface(IJanuaRecord)
    ['{98A01052-F5BC-461E-87B5-E140CAF1E3EF}']
    function GetDb_user_id: IJanuaField;
    procedure SetDb_user_id(const Value: IJanuaField);
    property Db_user_id: IJanuaField read GetDb_user_id write SetDb_user_id;
    function GetCountry_id: IJanuaField;
    procedure SetCountry_id(const Value: IJanuaField);
    property Country_id: IJanuaField read GetCountry_id write SetCountry_id;
    function GetRegion_id: IJanuaField;
    procedure SetRegion_id(const Value: IJanuaField);
    property Region_id: IJanuaField read GetRegion_id write SetRegion_id;
    function GetDistrict_id: IJanuaField;
    procedure SetDistrict_id(const Value: IJanuaField);
    property District_id: IJanuaField read GetDistrict_id write SetDistrict_id;
    function GetTown_id: IJanuaField;
    procedure SetTown_id(const Value: IJanuaField);
    property Town_id: IJanuaField read GetTown_id write SetTown_id;
    function GetFirst_name: IJanuaField;
    procedure SetFirst_name(const Value: IJanuaField);
    property First_name: IJanuaField read GetFirst_name write SetFirst_name;
    function GetLast_name: IJanuaField;
    procedure SetLast_name(const Value: IJanuaField);
    property Last_name: IJanuaField read GetLast_name write SetLast_name;
    function GetAddress_street: IJanuaField;
    procedure SetAddress_street(const Value: IJanuaField);
    property Address_street: IJanuaField read GetAddress_street write SetAddress_street;
    function GetAddress_number: IJanuaField;
    procedure SetAddress_number(const Value: IJanuaField);
    property Address_number: IJanuaField read GetAddress_number write SetAddress_number;
    function GetAddress_postal_code: IJanuaField;
    procedure SetAddress_postal_code(const Value: IJanuaField);
    property Address_postal_code: IJanuaField read GetAddress_postal_code write SetAddress_postal_code;
    function GetPhone: IJanuaField;
    procedure SetPhone(const Value: IJanuaField);
    property Phone: IJanuaField read GetPhone write SetPhone;
    function GetCellular_phone: IJanuaField;
    procedure SetCellular_phone(const Value: IJanuaField);
    property Cellular_phone: IJanuaField read GetCellular_phone write SetCellular_phone;
    function GetWork_phone: IJanuaField;
    procedure SetWork_phone(const Value: IJanuaField);
    property Work_phone: IJanuaField read GetWork_phone write SetWork_phone;
    function GetFax_number: IJanuaField;
    procedure SetFax_number(const Value: IJanuaField);
    property Fax_number: IJanuaField read GetFax_number write SetFax_number;
    function GetGender_code: IJanuaField;
    procedure SetGender_code(const Value: IJanuaField);
    property Gender_code: IJanuaField read GetGender_code write SetGender_code;
    function GetBirth_date: IJanuaField;
    procedure SetBirth_date(const Value: IJanuaField);
    property Birth_date: IJanuaField read GetBirth_date write SetBirth_date;
    function GetBirth_country_id: IJanuaField;
    procedure SetBirth_country_id(const Value: IJanuaField);
    property Birth_country_id: IJanuaField read GetBirth_country_id write SetBirth_country_id;
    function GetBirth_region_id: IJanuaField;
    procedure SetBirth_region_id(const Value: IJanuaField);
    property Birth_region_id: IJanuaField read GetBirth_region_id write SetBirth_region_id;
    function GetBirth_district_id: IJanuaField;
    procedure SetBirth_district_id(const Value: IJanuaField);
    property Birth_district_id: IJanuaField read GetBirth_district_id write SetBirth_district_id;
    function GetBirth_town_id: IJanuaField;
    procedure SetBirth_town_id(const Value: IJanuaField);
    property Birth_town_id: IJanuaField read GetBirth_town_id write SetBirth_town_id;
    function GetPublic_email: IJanuaField;
    procedure SetPublic_email(const Value: IJanuaField);
    property Public_email: IJanuaField read GetPublic_email write SetPublic_email;
    function GetTitle: IJanuaField;
    procedure SetTitle(const Value: IJanuaField);
    property Title: IJanuaField read GetTitle write SetTitle;
    function GetSearch_name: IJanuaField;
    procedure SetSearch_name(const Value: IJanuaField);
    property Search_name: IJanuaField read GetSearch_name write SetSearch_name;
    function GetReverse_search: IJanuaField;
    procedure SetReverse_search(const Value: IJanuaField);
    property Reverse_search: IJanuaField read GetReverse_search write SetReverse_search;
    function GetAddress_full: IJanuaField;
    procedure SetAddress_full(const Value: IJanuaField);
    property Address_full: IJanuaField read GetAddress_full write SetAddress_full;
    function GetLatitude: IJanuaField;
    procedure SetLatitude(const Value: IJanuaField);
    property Latitude: IJanuaField read GetLatitude write SetLatitude;
    function GetLongitude: IJanuaField;
    procedure SetLongitude(const Value: IJanuaField);
    property Longitude: IJanuaField read GetLongitude write SetLongitude;
    function GetFiscal_code: IJanuaField;
    procedure SetFiscal_code(const Value: IJanuaField);
    property Fiscal_code: IJanuaField read GetFiscal_code write SetFiscal_code;
    function GetSmssent: IJanuaField;
    procedure SetSmssent(const Value: IJanuaField);
    property Smssent: IJanuaField read GetSmssent write SetSmssent;
    function GetSmsconfirmed: IJanuaField;
    procedure SetSmsconfirmed(const Value: IJanuaField);
    property Smsconfirmed: IJanuaField read GetSmsconfirmed write SetSmsconfirmed;
    function GetSmsdate: IJanuaField;
    procedure SetSmsdate(const Value: IJanuaField);
    property Smsdate: IJanuaField read GetSmsdate write SetSmsdate;
    function GetSmschecknumber: IJanuaField;
    procedure SetSmschecknumber(const Value: IJanuaField);
    property Smschecknumber: IJanuaField read GetSmschecknumber write SetSmschecknumber;
    function GetAddress_town: IJanuaField;
    procedure SetAddress_town(const Value: IJanuaField);
    property Address_town: IJanuaField read GetAddress_town write SetAddress_town;
    function GetFacebook_json: IJanuaField;
    procedure SetFacebook_json(const Value: IJanuaField);
    property Facebook_json: IJanuaField read GetFacebook_json write SetFacebook_json;
    function GetAddress_state_province: IJanuaField;
    procedure SetAddress_state_province(const Value: IJanuaField);
    property Address_state_province: IJanuaField read GetAddress_state_province write SetAddress_state_province;
    // Anagraph
    function GetAnagraphID: IJanuaField;
    procedure SetAnagraphID(const Value: IJanuaField);
    property AnagraphID: IJanuaField read GetAnagraphID write SetAnagraphID;
  end;

  ICustomUserProfiles = interface(IJanuaRecordSet)
    ['{CE0BA5EE-D250-4AEC-95E5-755D8052B6C3}']
    function GetDb_user_id: IJanuaField;
    procedure SetDb_user_id(const Value: IJanuaField);
    property Db_user_id: IJanuaField read GetDb_user_id write SetDb_user_id;
    function GetCountry_id: IJanuaField;
    procedure SetCountry_id(const Value: IJanuaField);
    property Country_id: IJanuaField read GetCountry_id write SetCountry_id;
    function GetRegion_id: IJanuaField;
    procedure SetRegion_id(const Value: IJanuaField);
    property Region_id: IJanuaField read GetRegion_id write SetRegion_id;
    function GetDistrict_id: IJanuaField;
    procedure SetDistrict_id(const Value: IJanuaField);
    property District_id: IJanuaField read GetDistrict_id write SetDistrict_id;
    function GetTown_id: IJanuaField;
    procedure SetTown_id(const Value: IJanuaField);
    property Town_id: IJanuaField read GetTown_id write SetTown_id;
    function GetFirst_name: IJanuaField;
    procedure SetFirst_name(const Value: IJanuaField);
    property First_name: IJanuaField read GetFirst_name write SetFirst_name;
    function GetLast_name: IJanuaField;
    procedure SetLast_name(const Value: IJanuaField);
    property Last_name: IJanuaField read GetLast_name write SetLast_name;
    function GetAddress_street: IJanuaField;
    procedure SetAddress_street(const Value: IJanuaField);
    property Address_street: IJanuaField read GetAddress_street write SetAddress_street;
    function GetAddress_number: IJanuaField;
    procedure SetAddress_number(const Value: IJanuaField);
    property Address_number: IJanuaField read GetAddress_number write SetAddress_number;
    function GetAddress_postal_code: IJanuaField;
    procedure SetAddress_postal_code(const Value: IJanuaField);
    property Address_postal_code: IJanuaField read GetAddress_postal_code write SetAddress_postal_code;
    function GetPhone: IJanuaField;
    procedure SetPhone(const Value: IJanuaField);
    property Phone: IJanuaField read GetPhone write SetPhone;
    function GetCellular_phone: IJanuaField;
    procedure SetCellular_phone(const Value: IJanuaField);
    property Cellular_phone: IJanuaField read GetCellular_phone write SetCellular_phone;
    function GetWork_phone: IJanuaField;
    procedure SetWork_phone(const Value: IJanuaField);
    property Work_phone: IJanuaField read GetWork_phone write SetWork_phone;
    function GetFax_number: IJanuaField;
    procedure SetFax_number(const Value: IJanuaField);
    property Fax_number: IJanuaField read GetFax_number write SetFax_number;
    function GetGender_code: IJanuaField;
    procedure SetGender_code(const Value: IJanuaField);
    property Gender_code: IJanuaField read GetGender_code write SetGender_code;
    function GetBirth_date: IJanuaField;
    procedure SetBirth_date(const Value: IJanuaField);
    property Birth_date: IJanuaField read GetBirth_date write SetBirth_date;
    function GetBirth_country_id: IJanuaField;
    procedure SetBirth_country_id(const Value: IJanuaField);
    property Birth_country_id: IJanuaField read GetBirth_country_id write SetBirth_country_id;
    function GetBirth_region_id: IJanuaField;
    procedure SetBirth_region_id(const Value: IJanuaField);
    property Birth_region_id: IJanuaField read GetBirth_region_id write SetBirth_region_id;
    function GetBirth_district_id: IJanuaField;
    procedure SetBirth_district_id(const Value: IJanuaField);
    property Birth_district_id: IJanuaField read GetBirth_district_id write SetBirth_district_id;
    function GetBirth_town_id: IJanuaField;
    procedure SetBirth_town_id(const Value: IJanuaField);
    property Birth_town_id: IJanuaField read GetBirth_town_id write SetBirth_town_id;
    function GetPublic_email: IJanuaField;
    procedure SetPublic_email(const Value: IJanuaField);
    property Public_email: IJanuaField read GetPublic_email write SetPublic_email;
    function GetTitle: IJanuaField;
    procedure SetTitle(const Value: IJanuaField);
    property Title: IJanuaField read GetTitle write SetTitle;
    function GetSearch_name: IJanuaField;
    procedure SetSearch_name(const Value: IJanuaField);
    property Search_name: IJanuaField read GetSearch_name write SetSearch_name;
    function GetReverse_search: IJanuaField;
    procedure SetReverse_search(const Value: IJanuaField);
    property Reverse_search: IJanuaField read GetReverse_search write SetReverse_search;
    function GetAddress_full: IJanuaField;
    procedure SetAddress_full(const Value: IJanuaField);
    property Address_full: IJanuaField read GetAddress_full write SetAddress_full;
    function GetLatitude: IJanuaField;
    procedure SetLatitude(const Value: IJanuaField);
    property Latitude: IJanuaField read GetLatitude write SetLatitude;
    function GetLongitude: IJanuaField;
    procedure SetLongitude(const Value: IJanuaField);
    property Longitude: IJanuaField read GetLongitude write SetLongitude;
    function GetFiscal_code: IJanuaField;
    procedure SetFiscal_code(const Value: IJanuaField);
    property Fiscal_code: IJanuaField read GetFiscal_code write SetFiscal_code;
    function GetSmssent: IJanuaField;
    procedure SetSmssent(const Value: IJanuaField);
    property Smssent: IJanuaField read GetSmssent write SetSmssent;
    function GetSmsconfirmed: IJanuaField;
    procedure SetSmsconfirmed(const Value: IJanuaField);
    property Smsconfirmed: IJanuaField read GetSmsconfirmed write SetSmsconfirmed;
    function GetSmsdate: IJanuaField;
    procedure SetSmsdate(const Value: IJanuaField);
    property Smsdate: IJanuaField read GetSmsdate write SetSmsdate;
    function GetSmschecknumber: IJanuaField;
    procedure SetSmschecknumber(const Value: IJanuaField);
    property Smschecknumber: IJanuaField read GetSmschecknumber write SetSmschecknumber;
    function GetAddress_town: IJanuaField;
    procedure SetAddress_town(const Value: IJanuaField);
    property Address_town: IJanuaField read GetAddress_town write SetAddress_town;
    function GetFacebook_json: IJanuaField;
    procedure SetFacebook_json(const Value: IJanuaField);
    property Facebook_json: IJanuaField read GetFacebook_json write SetFacebook_json;
    function GetAddress_state_province: IJanuaField;
    procedure SetAddress_state_province(const Value: IJanuaField);
    property Address_state_province: IJanuaField read GetAddress_state_province write SetAddress_state_province;
  end;

implementation

end.
