unit JOrm.Football.Matches.Intf;

interface

uses Janua.Orm.Intf, Janua.Html.Intf;

type

  IMatch = interface(IJanuaRecord)
    ['{68FB3429-7410-443F-914C-41F1C8B3022A}']
    function GetMatchId: IJanuaField;
    procedure SetMatchId(const Value: IJanuaField);
    property MatchId: IJanuaField read GetMatchId write SetMatchId;
    function GetLeagueId: IJanuaField;
    procedure SetLeagueId(const Value: IJanuaField);
    property LeagueId: IJanuaField read GetLeagueId write SetLeagueId;
    function GetSeasonId: IJanuaField;
    procedure SetSeasonId(const Value: IJanuaField);
    property SeasonId: IJanuaField read GetSeasonId write SetSeasonId;
    function GetMatchDayNumber: IJanuaField;
    procedure SetMatchDayNumber(const Value: IJanuaField);
    property MatchDayNumber: IJanuaField read GetMatchDayNumber write SetMatchDayNumber;
    function GetMatchDate: IJanuaField;
    procedure SetMatchDate(const Value: IJanuaField);
    property MatchDate: IJanuaField read GetMatchDate write SetMatchDate;
    function GetHomeTeamId: IJanuaField;
    procedure SetHomeTeamId(const Value: IJanuaField);
    property HomeTeamId: IJanuaField read GetHomeTeamId write SetHomeTeamId;
    function GetVisitorsTeamId: IJanuaField;
    procedure SetVisitorsTeamId(const Value: IJanuaField);
    property VisitorsTeamId: IJanuaField read GetVisitorsTeamId write SetVisitorsTeamId;
    function GetGoalHome: IJanuaField;
    procedure SetGoalHome(const Value: IJanuaField);
    property GoalHome: IJanuaField read GetGoalHome write SetGoalHome;
    function GetGoalVisitor: IJanuaField;
    procedure SetGoalVisitor(const Value: IJanuaField);
    property GoalVisitor: IJanuaField read GetGoalVisitor write SetGoalVisitor;
    function GetPointsHome: IJanuaField;
    procedure SetPointsHome(const Value: IJanuaField);
    property PointsHome: IJanuaField read GetPointsHome write SetPointsHome;
    function GetPointsVisitors: IJanuaField;
    procedure SetPointsVisitors(const Value: IJanuaField);
    property PointsVisitors: IJanuaField read GetPointsVisitors write SetPointsVisitors;
    function GetNotes: IJanuaField;
    procedure SetNotes(const Value: IJanuaField);
    property Notes: IJanuaField read GetNotes write SetNotes;
    function GetConfirmed: IJanuaField;
    procedure SetConfirmed(const Value: IJanuaField);
    property Confirmed: IJanuaField read GetConfirmed write SetConfirmed;
    function GetDbSchemaId: IJanuaField;
    procedure SetDbSchemaId(const Value: IJanuaField);
    property DbSchemaId: IJanuaField read GetDbSchemaId write SetDbSchemaId;
    function GetInsertDate: IJanuaField;
    procedure SetInsertDate(const Value: IJanuaField);
    property InsertDate: IJanuaField read GetInsertDate write SetInsertDate;
    function GetUpdateDate: IJanuaField;
    procedure SetUpdateDate(const Value: IJanuaField);
    property UpdateDate: IJanuaField read GetUpdateDate write SetUpdateDate;
    function GetHomeNotes: IJanuaField;
    procedure SetHomeNotes(const Value: IJanuaField);
    property HomeNotes: IJanuaField read GetHomeNotes write SetHomeNotes;
    function GetVisitorsNotes: IJanuaField;
    procedure SetVisitorsNotes(const Value: IJanuaField);
    property VisitorsNotes: IJanuaField read GetVisitorsNotes write SetVisitorsNotes;
    function GetMatchTime: IJanuaField;
    procedure SetMatchTime(const Value: IJanuaField);
    property MatchTime: IJanuaField read GetMatchTime write SetMatchTime;
    function GetRefereeId: IJanuaField;
    procedure SetRefereeId(const Value: IJanuaField);
    property RefereeId: IJanuaField read GetRefereeId write SetRefereeId;
    function GetRefereeSecondId: IJanuaField;
    procedure SetRefereeSecondId(const Value: IJanuaField);
    property RefereeSecondId: IJanuaField read GetRefereeSecondId write SetRefereeSecondId;
    function GetRefereeThirdId: IJanuaField;
    procedure SetRefereeThirdId(const Value: IJanuaField);
    property RefereeThirdId: IJanuaField read GetRefereeThirdId write SetRefereeThirdId;
    function GetSuspended: IJanuaField;
    procedure SetSuspended(const Value: IJanuaField);
    property Suspended: IJanuaField read GetSuspended write SetSuspended;
    function GetPostponed: IJanuaField;
    procedure SetPostponed(const Value: IJanuaField);
    property Postponed: IJanuaField read GetPostponed write SetPostponed;
    function GetForfeit: IJanuaField;
    procedure SetForfeit(const Value: IJanuaField);
    property Forfeit: IJanuaField read GetForfeit write SetForfeit;
    function GetRemoteId: IJanuaField;
    procedure SetRemoteId(const Value: IJanuaField);
    property RemoteId: IJanuaField read GetRemoteId write SetRemoteId;
    function GetFiledId: IJanuaField;
    procedure SetFiledId(const Value: IJanuaField);
    property FiledId: IJanuaField read GetFiledId write SetFiledId;
    procedure SetHomeTeamLogo(const Value: IJanuaField);
    procedure SetHomeTeamName(const Value: IJanuaField);
    procedure SetVisitorsTeamLogo(const Value: IJanuaField);
    procedure SetVisitorsTeamName(const Value: IJanuaField);
    function GetHomeTeamLogo: IJanuaField;
    function GetHomeTeamName: IJanuaField;
    function GetVisitorsTeamLogo: IJanuaField;
    function GetVisitorsTeamName: IJanuaField;
    property HomeTeamName: IJanuaField read GetHomeTeamName write SetHomeTeamName;
    property VisitorsTeamName: IJanuaField read GetVisitorsTeamName write SetVisitorsTeamName;
    property HomeTeamLogo: IJanuaField read GetHomeTeamLogo write SetHomeTeamLogo;
    property VisitorsTeamLogo: IJanuaField read GetVisitorsTeamLogo write SetVisitorsTeamLogo;
    procedure SetScore(const Value: IJanuaField);
    function GetScore: IJanuaField;
    property Score: IJanuaField read GetScore write SetScore;
    procedure SetButtons(const Value: IJanuaField);
    function GetButtons: IJanuaField;
    property Buttons: IJanuaField read GetButtons write SetButtons;
    procedure SetHtmlNote(const Value: IJanuaField);
    function GetHtmlNote: IJanuaField;
    property HtmlNote: IJanuaField read GetHtmlNote write SetHtmlNote;
    procedure SetMatchLevel(const Value: IJanuaField);
    function GetMatchLevel: IJanuaField;
    property MatchLevel: IJanuaField read GetMatchLevel write SetMatchLevel;
    function MatchStatus(IsSmallScreen: boolean = False): string;
    function MatchStatusHtml(IsSmallScreen: boolean): IJanuaHtmlObject;
  end;

  IMatches = interface(IJanuaRecordSet)
    ['{39F05AAA-7C8E-400D-8899-384FCEE95D69}']
    function GetMatchId: IJanuaField;
    procedure SetMatchId(const Value: IJanuaField);
    property MatchId: IJanuaField read GetMatchId write SetMatchId;
    function GetLeagueId: IJanuaField;
    procedure SetLeagueId(const Value: IJanuaField);
    property LeagueId: IJanuaField read GetLeagueId write SetLeagueId;
    function GetSeasonId: IJanuaField;
    procedure SetSeasonId(const Value: IJanuaField);
    property SeasonId: IJanuaField read GetSeasonId write SetSeasonId;
    function GetMatchDayNumber: IJanuaField;
    procedure SetMatchDayNumber(const Value: IJanuaField);
    property MatchDayNumber: IJanuaField read GetMatchDayNumber write SetMatchDayNumber;
    function GetMatchDate: IJanuaField;
    procedure SetMatchDate(const Value: IJanuaField);
    property MatchDate: IJanuaField read GetMatchDate write SetMatchDate;
    function GetHomeTeamId: IJanuaField;
    procedure SetHomeTeamId(const Value: IJanuaField);
    property HomeTeamId: IJanuaField read GetHomeTeamId write SetHomeTeamId;
    function GetVisitorsTeamId: IJanuaField;
    procedure SetVisitorsTeamId(const Value: IJanuaField);
    property VisitorsTeamId: IJanuaField read GetVisitorsTeamId write SetVisitorsTeamId;
    function GetGoalHome: IJanuaField;
    procedure SetGoalHome(const Value: IJanuaField);
    property GoalHome: IJanuaField read GetGoalHome write SetGoalHome;
    function GetGoalVisitor: IJanuaField;
    procedure SetGoalVisitor(const Value: IJanuaField);
    property GoalVisitor: IJanuaField read GetGoalVisitor write SetGoalVisitor;
    function GetPointsHome: IJanuaField;
    procedure SetPointsHome(const Value: IJanuaField);
    property PointsHome: IJanuaField read GetPointsHome write SetPointsHome;
    function GetPointsVisitors: IJanuaField;
    procedure SetPointsVisitors(const Value: IJanuaField);
    property PointsVisitors: IJanuaField read GetPointsVisitors write SetPointsVisitors;
    function GetNotes: IJanuaField;
    procedure SetNotes(const Value: IJanuaField);
    property Notes: IJanuaField read GetNotes write SetNotes;
    function GetConfirmed: IJanuaField;
    procedure SetConfirmed(const Value: IJanuaField);
    property Confirmed: IJanuaField read GetConfirmed write SetConfirmed;
    function GetDbSchemaId: IJanuaField;
    procedure SetDbSchemaId(const Value: IJanuaField);
    property DbSchemaId: IJanuaField read GetDbSchemaId write SetDbSchemaId;
    function GetInsertDate: IJanuaField;
    procedure SetInsertDate(const Value: IJanuaField);
    property InsertDate: IJanuaField read GetInsertDate write SetInsertDate;
    function GetUpdateDate: IJanuaField;
    procedure SetUpdateDate(const Value: IJanuaField);
    property UpdateDate: IJanuaField read GetUpdateDate write SetUpdateDate;
    function GetHomeNotes: IJanuaField;
    procedure SetHomeNotes(const Value: IJanuaField);
    property HomeNotes: IJanuaField read GetHomeNotes write SetHomeNotes;
    function GetVisitorsNotes: IJanuaField;
    procedure SetVisitorsNotes(const Value: IJanuaField);
    property VisitorsNotes: IJanuaField read GetVisitorsNotes write SetVisitorsNotes;
    function GetMatchTime: IJanuaField;
    procedure SetMatchTime(const Value: IJanuaField);
    property MatchTime: IJanuaField read GetMatchTime write SetMatchTime;
    function GetRefereeId: IJanuaField;
    procedure SetRefereeId(const Value: IJanuaField);
    property RefereeId: IJanuaField read GetRefereeId write SetRefereeId;
    function GetRefereeSecondId: IJanuaField;
    procedure SetRefereeSecondId(const Value: IJanuaField);
    property RefereeSecondId: IJanuaField read GetRefereeSecondId write SetRefereeSecondId;
    function GetRefereeThirdId: IJanuaField;
    procedure SetRefereeThirdId(const Value: IJanuaField);
    property RefereeThirdId: IJanuaField read GetRefereeThirdId write SetRefereeThirdId;
    function GetSuspended: IJanuaField;
    procedure SetSuspended(const Value: IJanuaField);
    property Suspended: IJanuaField read GetSuspended write SetSuspended;
    function GetPostponed: IJanuaField;
    procedure SetPostponed(const Value: IJanuaField);
    property Postponed: IJanuaField read GetPostponed write SetPostponed;
    function GetForfeit: IJanuaField;
    procedure SetForfeit(const Value: IJanuaField);
    property Forfeit: IJanuaField read GetForfeit write SetForfeit;
    function GetRemoteId: IJanuaField;
    procedure SetRemoteId(const Value: IJanuaField);
    property RemoteId: IJanuaField read GetRemoteId write SetRemoteId;
    function GetFiledId: IJanuaField;
    procedure SetFiledId(const Value: IJanuaField);
    property FiledId: IJanuaField read GetFiledId write SetFiledId;
    function GetMatch: IMatch;
    procedure SetMatch(const Value: IMatch);
    procedure SetHomeTeamLogo(const Value: IJanuaField);
    procedure SetHomeTeamName(const Value: IJanuaField);
    procedure SetVisitorsTeamLogo(const Value: IJanuaField);
    procedure SetVisitorsTeamName(const Value: IJanuaField);
    function GetHomeTeamLogo: IJanuaField;
    function GetHomeTeamName: IJanuaField;
    function GetVisitorsTeamLogo: IJanuaField;
    function GetVisitorsTeamName: IJanuaField;
    property HomeTeamName: IJanuaField read GetHomeTeamName write SetHomeTeamName;
    property VisitorsTeamName: IJanuaField read GetVisitorsTeamName write SetVisitorsTeamName;
    property HomeTeamLogo: IJanuaField read GetHomeTeamLogo write SetHomeTeamLogo;
    property VisitorsTeamLogo: IJanuaField read GetVisitorsTeamLogo write SetVisitorsTeamLogo;
    property Match: IMatch read GetMatch write SetMatch;
    procedure SetScore(const Value: IJanuaField);
    function GetScore: IJanuaField;
    property Score: IJanuaField read GetScore write SetScore;
  end;

implementation

end.
