unit JOrm.Logistic.ShipmentRows.Custom.Intf;

interface

uses Janua.Orm.Intf;

type

  ICustomShipmentRow = interface(IJanuaRecord)
    ['{D544A104-4129-490B-8A8A-1256FD8A51E9}']
    function GetYear: IJanuaField;
    procedure SetYear(const Value: IJanuaField);
    property Year: IJanuaField read GetYear write SetYear;
    function GetShipmentId: IJanuaField;
    procedure SetShipmentId(const Value: IJanuaField);
    property ShipmentId: IJanuaField read GetShipmentId write SetShipmentId;
    function GetOfficeId: IJanuaField;
    procedure SetOfficeId(const Value: IJanuaField);
    property OfficeId: IJanuaField read GetOfficeId write SetOfficeId;
    function GetWarehouseId: IJanuaField;
    procedure SetWarehouseId(const Value: IJanuaField);
    property WarehouseId: IJanuaField read GetWarehouseId write SetWarehouseId;
    function GetPos: IJanuaField;
    procedure SetPos(const Value: IJanuaField);
    property Pos: IJanuaField read GetPos write SetPos;
    function GetQuantity: IJanuaField;
    procedure SetQuantity(const Value: IJanuaField);
    property Quantity: IJanuaField read GetQuantity write SetQuantity;
    function GetWeight: IJanuaField;
    procedure SetWeight(const Value: IJanuaField);
    property Weight: IJanuaField read GetWeight write SetWeight;
    function GetVolume: IJanuaField;
    procedure SetVolume(const Value: IJanuaField);
    property Volume: IJanuaField read GetVolume write SetVolume;
    function GetBooking: IJanuaField;
    procedure SetBooking(const Value: IJanuaField);
    property Booking: IJanuaField read GetBooking write SetBooking;
    function GetCntrType: IJanuaField;
    procedure SetCntrType(const Value: IJanuaField);
    property CntrType: IJanuaField read GetCntrType write SetCntrType;
    function GetCntrCode: IJanuaField;
    procedure SetCntrCode(const Value: IJanuaField);
    property CntrCode: IJanuaField read GetCntrCode write SetCntrCode;
    function GetCntrSeal: IJanuaField;
    procedure SetCntrSeal(const Value: IJanuaField);
    property CntrSeal: IJanuaField read GetCntrSeal write SetCntrSeal;
    function GetPkgTypeCode: IJanuaField;
    procedure SetPkgTypeCode(const Value: IJanuaField);
    property PkgTypeCode: IJanuaField read GetPkgTypeCode write SetPkgTypeCode;
    function GetPo1: IJanuaField;
    procedure SetPo1(const Value: IJanuaField);
    property Po1: IJanuaField read GetPo1 write SetPo1;
    function GetPo2: IJanuaField;
    procedure SetPo2(const Value: IJanuaField);
    property Po2: IJanuaField read GetPo2 write SetPo2;
    function GetPo3: IJanuaField;
    procedure SetPo3(const Value: IJanuaField);
    property Po3: IJanuaField read GetPo3 write SetPo3;
    function GetPo4: IJanuaField;
    procedure SetPo4(const Value: IJanuaField);
    property Po4: IJanuaField read GetPo4 write SetPo4;
    function GetPo5: IJanuaField;
    procedure SetPo5(const Value: IJanuaField);
    property Po5: IJanuaField read GetPo5 write SetPo5;
    function GetPo6: IJanuaField;
    procedure SetPo6(const Value: IJanuaField);
    property Po6: IJanuaField read GetPo6 write SetPo6;
    function GetPo7: IJanuaField;
    procedure SetPo7(const Value: IJanuaField);
    property Po7: IJanuaField read GetPo7 write SetPo7;
    function GetPo8: IJanuaField;
    procedure SetPo8(const Value: IJanuaField);
    property Po8: IJanuaField read GetPo8 write SetPo8;
    function GetFreightAmount: IJanuaField;
    procedure SetFreightAmount(const Value: IJanuaField);
    property FreightAmount: IJanuaField read GetFreightAmount write SetFreightAmount;
    function GetMarks: IJanuaField;
    procedure SetMarks(const Value: IJanuaField);
    property Marks: IJanuaField read GetMarks write SetMarks;
    function GetDescription1: IJanuaField;
    procedure SetDescription1(const Value: IJanuaField);
    property Description1: IJanuaField read GetDescription1 write SetDescription1;
    function GetDescription2: IJanuaField;
    procedure SetDescription2(const Value: IJanuaField);
    property Description2: IJanuaField read GetDescription2 write SetDescription2;
    function GetBol: IJanuaField;
    procedure SetBol(const Value: IJanuaField);
    property Bol: IJanuaField read GetBol write SetBol;
    function GetBolhouse: IJanuaField;
    procedure SetBolhouse(const Value: IJanuaField);
    property Bolhouse: IJanuaField read GetBolhouse write SetBolhouse;
    function GetNote: IJanuaField;
    procedure SetNote(const Value: IJanuaField);
    property Note: IJanuaField read GetNote write SetNote;
    function GetTemperature: IJanuaField;
    procedure SetTemperature(const Value: IJanuaField);
    property Temperature: IJanuaField read GetTemperature write SetTemperature;
    function GetSupplier: IJanuaField;
    procedure SetSupplier(const Value: IJanuaField);
    property Supplier: IJanuaField read GetSupplier write SetSupplier;
    function GetSupplierCode: IJanuaField;
    procedure SetSupplierCode(const Value: IJanuaField);
    property SupplierCode: IJanuaField read GetSupplierCode write SetSupplierCode;
    function GetWarehouseReceiptDate: IJanuaField;
    procedure SetWarehouseReceiptDate(const Value: IJanuaField);
    property WarehouseReceiptDate: IJanuaField read GetWarehouseReceiptDate write SetWarehouseReceiptDate;
    function GetInvoiceNumber: IJanuaField;
    procedure SetInvoiceNumber(const Value: IJanuaField);
    property InvoiceNumber: IJanuaField read GetInvoiceNumber write SetInvoiceNumber;
    function GetInvoiceDate: IJanuaField;
    procedure SetInvoiceDate(const Value: IJanuaField);
    property InvoiceDate: IJanuaField read GetInvoiceDate write SetInvoiceDate;
    function GetTaxableWeight: IJanuaField;
    procedure SetTaxableWeight(const Value: IJanuaField);
    property TaxableWeight: IJanuaField read GetTaxableWeight write SetTaxableWeight;
    function GetMunitId: IJanuaField;
    procedure SetMunitId(const Value: IJanuaField);
    property MunitId: IJanuaField read GetMunitId write SetMunitId;
    function GetValue: IJanuaField;
    procedure SetValue(const Value: IJanuaField);
    property Value: IJanuaField read GetValue write SetValue;
    function GetCurrencyId: IJanuaField;
    procedure SetCurrencyId(const Value: IJanuaField);
    property CurrencyId: IJanuaField read GetCurrencyId write SetCurrencyId;
    function GetInvoiceAmount: IJanuaField;
    procedure SetInvoiceAmount(const Value: IJanuaField);
    property InvoiceAmount: IJanuaField read GetInvoiceAmount write SetInvoiceAmount;
    function GetExchangeRate: IJanuaField;
    procedure SetExchangeRate(const Value: IJanuaField);
    property ExchangeRate: IJanuaField read GetExchangeRate write SetExchangeRate;
    function GetDimentions: IJanuaField;
    procedure SetDimentions(const Value: IJanuaField);
    property Dimentions: IJanuaField read GetDimentions write SetDimentions;
    function GetRemarks: IJanuaField;
    procedure SetRemarks(const Value: IJanuaField);
    property Remarks: IJanuaField read GetRemarks write SetRemarks;
    function GetWeghtVolumeRatio: IJanuaField;
    procedure SetWeghtVolumeRatio(const Value: IJanuaField);
    property WeghtVolumeRatio: IJanuaField read GetWeghtVolumeRatio write SetWeghtVolumeRatio;
    function GetFlgnotaxw: IJanuaField;
    procedure SetFlgnotaxw(const Value: IJanuaField);
    property Flgnotaxw: IJanuaField read GetFlgnotaxw write SetFlgnotaxw;
    function GetActualWeight: IJanuaField;
    procedure SetActualWeight(const Value: IJanuaField);
    property ActualWeight: IJanuaField read GetActualWeight write SetActualWeight;
    function GetActualVolume: IJanuaField;
    procedure SetActualVolume(const Value: IJanuaField);
    property ActualVolume: IJanuaField read GetActualVolume write SetActualVolume;
    function GetBookingNumber: IJanuaField;
    procedure SetBookingNumber(const Value: IJanuaField);
    property BookingNumber: IJanuaField read GetBookingNumber write SetBookingNumber;
    function GetCustomsTariff: IJanuaField;
    procedure SetCustomsTariff(const Value: IJanuaField);
    property CustomsTariff: IJanuaField read GetCustomsTariff write SetCustomsTariff;
    function GetSizeWeight: IJanuaField;
    procedure SetSizeWeight(const Value: IJanuaField);
    property SizeWeight: IJanuaField read GetSizeWeight write SetSizeWeight;
    function GetSizeLength: IJanuaField;
    procedure SetSizeLength(const Value: IJanuaField);
    property SizeLength: IJanuaField read GetSizeLength write SetSizeLength;
    function GetSizeHeight: IJanuaField;
    procedure SetSizeHeight(const Value: IJanuaField);
    property SizeHeight: IJanuaField read GetSizeHeight write SetSizeHeight;
    function GetSupplierWarehouseCode: IJanuaField;
    procedure SetSupplierWarehouseCode(const Value: IJanuaField);
    property SupplierWarehouseCode: IJanuaField read GetSupplierWarehouseCode write SetSupplierWarehouseCode;
    function GetSupplierWarehouseId: IJanuaField;
    procedure SetSupplierWarehouseId(const Value: IJanuaField);
    property SupplierWarehouseId: IJanuaField read GetSupplierWarehouseId write SetSupplierWarehouseId;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
    function GetId: IJanuaField;
    procedure SetId(const Value: IJanuaField);
    property Id: IJanuaField read GetId write SetId;
    function GetItemId: IJanuaField;
    procedure SetItemId(const Value: IJanuaField);
    property ItemId: IJanuaField read GetItemId write SetItemId;
  end;

  ICustomShipmentRows = interface(IJanuaRecordSet)
    ['{25AC5B56-91B4-4FBA-925B-49E2D061CC81}']
    function GetYear: IJanuaField;
    procedure SetYear(const Value: IJanuaField);
    property Year: IJanuaField read GetYear write SetYear;
    function GetShipmentId: IJanuaField;
    procedure SetShipmentId(const Value: IJanuaField);
    property ShipmentId: IJanuaField read GetShipmentId write SetShipmentId;
    function GetOfficeId: IJanuaField;
    procedure SetOfficeId(const Value: IJanuaField);
    property OfficeId: IJanuaField read GetOfficeId write SetOfficeId;
    function GetWarehouseId: IJanuaField;
    procedure SetWarehouseId(const Value: IJanuaField);
    property WarehouseId: IJanuaField read GetWarehouseId write SetWarehouseId;
    function GetPos: IJanuaField;
    procedure SetPos(const Value: IJanuaField);
    property Pos: IJanuaField read GetPos write SetPos;
    function GetQuantity: IJanuaField;
    procedure SetQuantity(const Value: IJanuaField);
    property Quantity: IJanuaField read GetQuantity write SetQuantity;
    function GetWeight: IJanuaField;
    procedure SetWeight(const Value: IJanuaField);
    property Weight: IJanuaField read GetWeight write SetWeight;
    function GetVolume: IJanuaField;
    procedure SetVolume(const Value: IJanuaField);
    property Volume: IJanuaField read GetVolume write SetVolume;
    function GetBooking: IJanuaField;
    procedure SetBooking(const Value: IJanuaField);
    property Booking: IJanuaField read GetBooking write SetBooking;
    function GetCntrType: IJanuaField;
    procedure SetCntrType(const Value: IJanuaField);
    property CntrType: IJanuaField read GetCntrType write SetCntrType;
    function GetCntrCode: IJanuaField;
    procedure SetCntrCode(const Value: IJanuaField);
    property CntrCode: IJanuaField read GetCntrCode write SetCntrCode;
    function GetCntrSeal: IJanuaField;
    procedure SetCntrSeal(const Value: IJanuaField);
    property CntrSeal: IJanuaField read GetCntrSeal write SetCntrSeal;
    function GetPkgTypeCode: IJanuaField;
    procedure SetPkgTypeCode(const Value: IJanuaField);
    property PkgTypeCode: IJanuaField read GetPkgTypeCode write SetPkgTypeCode;
    function GetPo1: IJanuaField;
    procedure SetPo1(const Value: IJanuaField);
    property Po1: IJanuaField read GetPo1 write SetPo1;
    function GetPo2: IJanuaField;
    procedure SetPo2(const Value: IJanuaField);
    property Po2: IJanuaField read GetPo2 write SetPo2;
    function GetPo3: IJanuaField;
    procedure SetPo3(const Value: IJanuaField);
    property Po3: IJanuaField read GetPo3 write SetPo3;
    function GetPo4: IJanuaField;
    procedure SetPo4(const Value: IJanuaField);
    property Po4: IJanuaField read GetPo4 write SetPo4;
    function GetPo5: IJanuaField;
    procedure SetPo5(const Value: IJanuaField);
    property Po5: IJanuaField read GetPo5 write SetPo5;
    function GetPo6: IJanuaField;
    procedure SetPo6(const Value: IJanuaField);
    property Po6: IJanuaField read GetPo6 write SetPo6;
    function GetPo7: IJanuaField;
    procedure SetPo7(const Value: IJanuaField);
    property Po7: IJanuaField read GetPo7 write SetPo7;
    function GetPo8: IJanuaField;
    procedure SetPo8(const Value: IJanuaField);
    property Po8: IJanuaField read GetPo8 write SetPo8;
    function GetFreightAmount: IJanuaField;
    procedure SetFreightAmount(const Value: IJanuaField);
    property FreightAmount: IJanuaField read GetFreightAmount write SetFreightAmount;
    function GetMarks: IJanuaField;
    procedure SetMarks(const Value: IJanuaField);
    property Marks: IJanuaField read GetMarks write SetMarks;
    function GetDescription1: IJanuaField;
    procedure SetDescription1(const Value: IJanuaField);
    property Description1: IJanuaField read GetDescription1 write SetDescription1;
    function GetDescription2: IJanuaField;
    procedure SetDescription2(const Value: IJanuaField);
    property Description2: IJanuaField read GetDescription2 write SetDescription2;
    function GetBol: IJanuaField;
    procedure SetBol(const Value: IJanuaField);
    property Bol: IJanuaField read GetBol write SetBol;
    function GetBolhouse: IJanuaField;
    procedure SetBolhouse(const Value: IJanuaField);
    property Bolhouse: IJanuaField read GetBolhouse write SetBolhouse;
    function GetNote: IJanuaField;
    procedure SetNote(const Value: IJanuaField);
    property Note: IJanuaField read GetNote write SetNote;
    function GetTemperature: IJanuaField;
    procedure SetTemperature(const Value: IJanuaField);
    property Temperature: IJanuaField read GetTemperature write SetTemperature;
    function GetSupplier: IJanuaField;
    procedure SetSupplier(const Value: IJanuaField);
    property Supplier: IJanuaField read GetSupplier write SetSupplier;
    function GetSupplierCode: IJanuaField;
    procedure SetSupplierCode(const Value: IJanuaField);
    property SupplierCode: IJanuaField read GetSupplierCode write SetSupplierCode;
    function GetWarehouseReceiptDate: IJanuaField;
    procedure SetWarehouseReceiptDate(const Value: IJanuaField);
    property WarehouseReceiptDate: IJanuaField read GetWarehouseReceiptDate write SetWarehouseReceiptDate;
    function GetInvoiceNumber: IJanuaField;
    procedure SetInvoiceNumber(const Value: IJanuaField);
    property InvoiceNumber: IJanuaField read GetInvoiceNumber write SetInvoiceNumber;
    function GetInvoiceDate: IJanuaField;
    procedure SetInvoiceDate(const Value: IJanuaField);
    property InvoiceDate: IJanuaField read GetInvoiceDate write SetInvoiceDate;
    function GetTaxableWeight: IJanuaField;
    procedure SetTaxableWeight(const Value: IJanuaField);
    property TaxableWeight: IJanuaField read GetTaxableWeight write SetTaxableWeight;
    function GetMunitId: IJanuaField;
    procedure SetMunitId(const Value: IJanuaField);
    property MunitId: IJanuaField read GetMunitId write SetMunitId;
    function GetValue: IJanuaField;
    procedure SetValue(const Value: IJanuaField);
    property Value: IJanuaField read GetValue write SetValue;
    function GetCurrencyId: IJanuaField;
    procedure SetCurrencyId(const Value: IJanuaField);
    property CurrencyId: IJanuaField read GetCurrencyId write SetCurrencyId;
    function GetInvoiceAmount: IJanuaField;
    procedure SetInvoiceAmount(const Value: IJanuaField);
    property InvoiceAmount: IJanuaField read GetInvoiceAmount write SetInvoiceAmount;
    function GetExchangeRate: IJanuaField;
    procedure SetExchangeRate(const Value: IJanuaField);
    property ExchangeRate: IJanuaField read GetExchangeRate write SetExchangeRate;
    function GetDimentions: IJanuaField;
    procedure SetDimentions(const Value: IJanuaField);
    property Dimentions: IJanuaField read GetDimentions write SetDimentions;
    function GetRemarks: IJanuaField;
    procedure SetRemarks(const Value: IJanuaField);
    property Remarks: IJanuaField read GetRemarks write SetRemarks;
    function GetWeghtVolumeRatio: IJanuaField;
    procedure SetWeghtVolumeRatio(const Value: IJanuaField);
    property WeghtVolumeRatio: IJanuaField read GetWeghtVolumeRatio write SetWeghtVolumeRatio;
    function GetFlgnotaxw: IJanuaField;
    procedure SetFlgnotaxw(const Value: IJanuaField);
    property Flgnotaxw: IJanuaField read GetFlgnotaxw write SetFlgnotaxw;
    function GetActualWeight: IJanuaField;
    procedure SetActualWeight(const Value: IJanuaField);
    property ActualWeight: IJanuaField read GetActualWeight write SetActualWeight;
    function GetActualVolume: IJanuaField;
    procedure SetActualVolume(const Value: IJanuaField);
    property ActualVolume: IJanuaField read GetActualVolume write SetActualVolume;
    function GetBookingNumber: IJanuaField;
    procedure SetBookingNumber(const Value: IJanuaField);
    property BookingNumber: IJanuaField read GetBookingNumber write SetBookingNumber;
    function GetCustomsTariff: IJanuaField;
    procedure SetCustomsTariff(const Value: IJanuaField);
    property CustomsTariff: IJanuaField read GetCustomsTariff write SetCustomsTariff;
    function GetSizeWeight: IJanuaField;
    procedure SetSizeWeight(const Value: IJanuaField);
    property SizeWeight: IJanuaField read GetSizeWeight write SetSizeWeight;
    function GetSizeLength: IJanuaField;
    procedure SetSizeLength(const Value: IJanuaField);
    property SizeLength: IJanuaField read GetSizeLength write SetSizeLength;
    function GetSizeHeight: IJanuaField;
    procedure SetSizeHeight(const Value: IJanuaField);
    property SizeHeight: IJanuaField read GetSizeHeight write SetSizeHeight;
    function GetSupplierWarehouseCode: IJanuaField;
    procedure SetSupplierWarehouseCode(const Value: IJanuaField);
    property SupplierWarehouseCode: IJanuaField read GetSupplierWarehouseCode write SetSupplierWarehouseCode;
    function GetSupplierWarehouseId: IJanuaField;
    procedure SetSupplierWarehouseId(const Value: IJanuaField);
    property SupplierWarehouseId: IJanuaField read GetSupplierWarehouseId write SetSupplierWarehouseId;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
    function GetId: IJanuaField;
    procedure SetId(const Value: IJanuaField);
    property Id: IJanuaField read GetId write SetId;
    function GetItemId: IJanuaField;
    procedure SetItemId(const Value: IJanuaField);
    property ItemId: IJanuaField read GetItemId write SetItemId;
  end;

implementation

end.
