unit JOrm.Documents.Types.Intf;

interface

uses Janua.Orm.Intf;

type

  IDocType = interface(IJanuaRecord)
    ['{874CB47C-430C-4228-85A9-11E5D1967BE4}']
    function GetId: IJanuaField;
    procedure SetId(const Value: IJanuaField);
    property Id: IJanuaField read GetId write SetId;
    function GetDbSchemaId: IJanuaField;
    procedure SetDbSchemaId(const Value: IJanuaField);
    property DbSchemaId: IJanuaField read GetDbSchemaId write SetDbSchemaId;
    function GetCode: IJanuaField;
    procedure SetCode(const Value: IJanuaField);
    property Code: IJanuaField read GetCode write SetCode;
    function GetInOut: IJanuaField;
    procedure SetInOut(const Value: IJanuaField);
    property InOut: IJanuaField read GetInOut write SetInOut;
    function GetCash: IJanuaField;
    procedure SetCash(const Value: IJanuaField);
    property Cash: IJanuaField read GetCash write SetCash;
    function GetCredit: IJanuaField;
    procedure SetCredit(const Value: IJanuaField);
    property Credit: IJanuaField read GetCredit write SetCredit;
    function GetDescription: IJanuaField;
    procedure SetDescription(const Value: IJanuaField);
    property Description: IJanuaField read GetDescription write SetDescription;
    function GetFlgOrder: IJanuaField;
    procedure SetFlgOrder(const Value: IJanuaField);
    property FlgOrder: IJanuaField read GetFlgOrder write SetFlgOrder;
    function GetFlgQuotation: IJanuaField;
    procedure SetFlgQuotation(const Value: IJanuaField);
    property FlgQuotation: IJanuaField read GetFlgQuotation write SetFlgQuotation;
    function GetFlgCustomers: IJanuaField;
    procedure SetFlgCustomers(const Value: IJanuaField);
    property FlgCustomers: IJanuaField read GetFlgCustomers write SetFlgCustomers;
    function GetFlgSuppliers: IJanuaField;
    procedure SetFlgSuppliers(const Value: IJanuaField);
    property FlgSuppliers: IJanuaField read GetFlgSuppliers write SetFlgSuppliers;
    function GetCurrencyId: IJanuaField;
    procedure SetCurrencyId(const Value: IJanuaField);
    property CurrencyId: IJanuaField read GetCurrencyId write SetCurrencyId;
    function GetIsAccouting: IJanuaField;
    procedure SetIsAccouting(const Value: IJanuaField);
    property IsAccouting: IJanuaField read GetIsAccouting write SetIsAccouting;
    function GetAcGroupCode: IJanuaField;
    procedure SetAcGroupCode(const Value: IJanuaField);
    property AcGroupCode: IJanuaField read GetAcGroupCode write SetAcGroupCode;
    function GetAcLedgerCode: IJanuaField;
    procedure SetAcLedgerCode(const Value: IJanuaField);
    property AcLedgerCode: IJanuaField read GetAcLedgerCode write SetAcLedgerCode;
    function GetAcSubledgerCode: IJanuaField;
    procedure SetAcSubledgerCode(const Value: IJanuaField);
    property AcSubledgerCode: IJanuaField read GetAcSubledgerCode write SetAcSubledgerCode;
    function GetAcGroupVatCode: IJanuaField;
    procedure SetAcGroupVatCode(const Value: IJanuaField);
    property AcGroupVatCode: IJanuaField read GetAcGroupVatCode write SetAcGroupVatCode;
    function GetAcLedgerVatCode: IJanuaField;
    procedure SetAcLedgerVatCode(const Value: IJanuaField);
    property AcLedgerVatCode: IJanuaField read GetAcLedgerVatCode write SetAcLedgerVatCode;
    function GetAcSubledgerVatCode: IJanuaField;
    procedure SetAcSubledgerVatCode(const Value: IJanuaField);
    property AcSubledgerVatCode: IJanuaField read GetAcSubledgerVatCode write SetAcSubledgerVatCode;
    function GetAcGroupTaxableAmntCode: IJanuaField;
    procedure SetAcGroupTaxableAmntCode(const Value: IJanuaField);
    property AcGroupTaxableAmntCode: IJanuaField read GetAcGroupTaxableAmntCode write SetAcGroupTaxableAmntCode;
    function GetAcLedgerTaxableAmntCode: IJanuaField;
    procedure SetAcLedgerTaxableAmntCode(const Value: IJanuaField);
    property AcLedgerTaxableAmntCode: IJanuaField read GetAcLedgerTaxableAmntCode write SetAcLedgerTaxableAmntCode;
    function GetAcSubledgerTaxableAmntCode: IJanuaField;
    procedure SetAcSubledgerTaxableAmntCode(const Value: IJanuaField);
    property AcSubledgerTaxableAmntCode: IJanuaField read GetAcSubledgerTaxableAmntCode
      write SetAcSubledgerTaxableAmntCode;
    function GetAcText: IJanuaField;
    procedure SetAcText(const Value: IJanuaField);
    property AcText: IJanuaField read GetAcText write SetAcText;
    function GetAcEntry: IJanuaField;
    procedure SetAcEntry(const Value: IJanuaField);
    property AcEntry: IJanuaField read GetAcEntry write SetAcEntry;
    function GetAcEntryPos: IJanuaField;
    procedure SetAcEntryPos(const Value: IJanuaField);
    property AcEntryPos: IJanuaField read GetAcEntryPos write SetAcEntryPos;
    function GetAcVatEntryPos: IJanuaField;
    procedure SetAcVatEntryPos(const Value: IJanuaField);
    property AcVatEntryPos: IJanuaField read GetAcVatEntryPos write SetAcVatEntryPos;
    function GetAcTaxableAmntEntryPos: IJanuaField;
    procedure SetAcTaxableAmntEntryPos(const Value: IJanuaField);
    property AcTaxableAmntEntryPos: IJanuaField read GetAcTaxableAmntEntryPos write SetAcTaxableAmntEntryPos;
    function GetGroupTransFeesCod: IJanuaField;
    procedure SetGroupTransFeesCod(const Value: IJanuaField);
    property GroupTransFeesCod: IJanuaField read GetGroupTransFeesCod write SetGroupTransFeesCod;
    function GetLedgerTransFeesCod: IJanuaField;
    procedure SetLedgerTransFeesCod(const Value: IJanuaField);
    property LedgerTransFeesCod: IJanuaField read GetLedgerTransFeesCod write SetLedgerTransFeesCod;
    function GetSubledgerTransFeesCod: IJanuaField;
    procedure SetSubledgerTransFeesCod(const Value: IJanuaField);
    property SubledgerTransFeesCod: IJanuaField read GetSubledgerTransFeesCod write SetSubledgerTransFeesCod;
    function GetAcTransFeesEntry: IJanuaField;
    procedure SetAcTransFeesEntry(const Value: IJanuaField);
    property AcTransFeesEntry: IJanuaField read GetAcTransFeesEntry write SetAcTransFeesEntry;
    function GetIsoDescription: IJanuaField;
    procedure SetIsoDescription(const Value: IJanuaField);
    property IsoDescription: IJanuaField read GetIsoDescription write SetIsoDescription;
    function GetAnGroupId: IJanuaField;
    procedure SetAnGroupId(const Value: IJanuaField);
    property AnGroupId: IJanuaField read GetAnGroupId write SetAnGroupId;
    function GetInsertDate: IJanuaField;
    procedure SetInsertDate(const Value: IJanuaField);
    property InsertDate: IJanuaField read GetInsertDate write SetInsertDate;
    function GetUpdateDate: IJanuaField;
    procedure SetUpdateDate(const Value: IJanuaField);
    property UpdateDate: IJanuaField read GetUpdateDate write SetUpdateDate;
    function GetUserInsert: IJanuaField;
    procedure SetUserInsert(const Value: IJanuaField);
    property UserInsert: IJanuaField read GetUserInsert write SetUserInsert;
    function GetUserUpdate: IJanuaField;
    procedure SetUserUpdate(const Value: IJanuaField);
    property UserUpdate: IJanuaField read GetUserUpdate write SetUserUpdate;
    function GetLocal: IJanuaField;
    procedure SetLocal(const Value: IJanuaField);
    property Local: IJanuaField read GetLocal write SetLocal;
    function GetDtVatRegistry: IJanuaField;
    procedure SetDtVatRegistry(const Value: IJanuaField);
    property DtVatRegistry: IJanuaField read GetDtVatRegistry write SetDtVatRegistry;
    function GetBillBook: IJanuaField;
    procedure SetBillBook(const Value: IJanuaField);
    property BillBook: IJanuaField read GetBillBook write SetBillBook;
    function GetTypeGroup: IJanuaField;
    procedure SetTypeGroup(const Value: IJanuaField);
    property TypeGroup: IJanuaField read GetTypeGroup write SetTypeGroup;
    function GetTypeAnagraphId: IJanuaField;
    procedure SetTypeAnagraphId(const Value: IJanuaField);
    property TypeAnagraphId: IJanuaField read GetTypeAnagraphId write SetTypeAnagraphId;
    function GetShortDescription: IJanuaField;
    procedure SetShortDescription(const Value: IJanuaField);
    property ShortDescription: IJanuaField read GetShortDescription write SetShortDescription;
    function GetNOSTRODOC: IJanuaField;
    procedure SetNOSTRODOC(const Value: IJanuaField);
    property NOSTRODOC: IJanuaField read GetNOSTRODOC write SetNOSTRODOC;
    function GetCASSA: IJanuaField;
    procedure SetCASSA(const Value: IJanuaField);
    property CASSA: IJanuaField read GetCASSA write SetCASSA;
    function GetWarehouseRegister: IJanuaField;
    procedure SetWarehouseRegister(const Value: IJanuaField);
    property WarehouseRegister: IJanuaField read GetWarehouseRegister write SetWarehouseRegister;
    function GetReverseDocType: IJanuaField;
    procedure SetReverseDocType(const Value: IJanuaField);
    property ReverseDocType: IJanuaField read GetReverseDocType write SetReverseDocType;
    function GetTypeGroupId: IJanuaField;
    procedure SetTypeGroupId(const Value: IJanuaField);
    property TypeGroupId: IJanuaField read GetTypeGroupId write SetTypeGroupId;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
    function GetCustomsDocDate: IJanuaField;
    procedure SetCustomsDocDate(const Value: IJanuaField);
    property CustomsDocDate: IJanuaField read GetCustomsDocDate write SetCustomsDocDate;
    function GetCustomsDocCin: IJanuaField;
    procedure SetCustomsDocCin(const Value: IJanuaField);
    property CustomsDocCin: IJanuaField read GetCustomsDocCin write SetCustomsDocCin;
  end;

  IDocTypes = interface(IJanuaRecordSet)
    ['{058F76A0-387F-4112-8980-4A5958D4B810}']
    function GetId: IJanuaField;
    procedure SetId(const Value: IJanuaField);
    property Id: IJanuaField read GetId write SetId;
    function GetDbSchemaId: IJanuaField;
    procedure SetDbSchemaId(const Value: IJanuaField);
    property DbSchemaId: IJanuaField read GetDbSchemaId write SetDbSchemaId;
    function GetCode: IJanuaField;
    procedure SetCode(const Value: IJanuaField);
    property Code: IJanuaField read GetCode write SetCode;
    function GetInOut: IJanuaField;
    procedure SetInOut(const Value: IJanuaField);
    property InOut: IJanuaField read GetInOut write SetInOut;
    function GetCash: IJanuaField;
    procedure SetCash(const Value: IJanuaField);
    property Cash: IJanuaField read GetCash write SetCash;
    function GetCredit: IJanuaField;
    procedure SetCredit(const Value: IJanuaField);
    property Credit: IJanuaField read GetCredit write SetCredit;
    function GetDescription: IJanuaField;
    procedure SetDescription(const Value: IJanuaField);
    property Description: IJanuaField read GetDescription write SetDescription;
    function GetFlgOrder: IJanuaField;
    procedure SetFlgOrder(const Value: IJanuaField);
    property FlgOrder: IJanuaField read GetFlgOrder write SetFlgOrder;
    function GetFlgQuotation: IJanuaField;
    procedure SetFlgQuotation(const Value: IJanuaField);
    property FlgQuotation: IJanuaField read GetFlgQuotation write SetFlgQuotation;
    function GetFlgCustomers: IJanuaField;
    procedure SetFlgCustomers(const Value: IJanuaField);
    property FlgCustomers: IJanuaField read GetFlgCustomers write SetFlgCustomers;
    function GetFlgSuppliers: IJanuaField;
    procedure SetFlgSuppliers(const Value: IJanuaField);
    property FlgSuppliers: IJanuaField read GetFlgSuppliers write SetFlgSuppliers;
    function GetCurrencyId: IJanuaField;
    procedure SetCurrencyId(const Value: IJanuaField);
    property CurrencyId: IJanuaField read GetCurrencyId write SetCurrencyId;
    function GetIsAccouting: IJanuaField;
    procedure SetIsAccouting(const Value: IJanuaField);
    property IsAccouting: IJanuaField read GetIsAccouting write SetIsAccouting;
    function GetAcGroupCode: IJanuaField;
    procedure SetAcGroupCode(const Value: IJanuaField);
    property AcGroupCode: IJanuaField read GetAcGroupCode write SetAcGroupCode;
    function GetAcLedgerCode: IJanuaField;
    procedure SetAcLedgerCode(const Value: IJanuaField);
    property AcLedgerCode: IJanuaField read GetAcLedgerCode write SetAcLedgerCode;
    function GetAcSubledgerCode: IJanuaField;
    procedure SetAcSubledgerCode(const Value: IJanuaField);
    property AcSubledgerCode: IJanuaField read GetAcSubledgerCode write SetAcSubledgerCode;
    function GetAcGroupVatCode: IJanuaField;
    procedure SetAcGroupVatCode(const Value: IJanuaField);
    property AcGroupVatCode: IJanuaField read GetAcGroupVatCode write SetAcGroupVatCode;
    function GetAcLedgerVatCode: IJanuaField;
    procedure SetAcLedgerVatCode(const Value: IJanuaField);
    property AcLedgerVatCode: IJanuaField read GetAcLedgerVatCode write SetAcLedgerVatCode;
    function GetAcSubledgerVatCode: IJanuaField;
    procedure SetAcSubledgerVatCode(const Value: IJanuaField);
    property AcSubledgerVatCode: IJanuaField read GetAcSubledgerVatCode write SetAcSubledgerVatCode;
    function GetAcGroupTaxableAmntCode: IJanuaField;
    procedure SetAcGroupTaxableAmntCode(const Value: IJanuaField);
    property AcGroupTaxableAmntCode: IJanuaField read GetAcGroupTaxableAmntCode write SetAcGroupTaxableAmntCode;
    function GetAcLedgerTaxableAmntCode: IJanuaField;
    procedure SetAcLedgerTaxableAmntCode(const Value: IJanuaField);
    property AcLedgerTaxableAmntCode: IJanuaField read GetAcLedgerTaxableAmntCode write SetAcLedgerTaxableAmntCode;
    function GetAcSubledgerTaxableAmntCode: IJanuaField;
    procedure SetAcSubledgerTaxableAmntCode(const Value: IJanuaField);
    property AcSubledgerTaxableAmntCode: IJanuaField read GetAcSubledgerTaxableAmntCode
      write SetAcSubledgerTaxableAmntCode;
    function GetAcText: IJanuaField;
    procedure SetAcText(const Value: IJanuaField);
    property AcText: IJanuaField read GetAcText write SetAcText;
    function GetAcEntry: IJanuaField;
    procedure SetAcEntry(const Value: IJanuaField);
    property AcEntry: IJanuaField read GetAcEntry write SetAcEntry;
    function GetAcEntryPos: IJanuaField;
    procedure SetAcEntryPos(const Value: IJanuaField);
    property AcEntryPos: IJanuaField read GetAcEntryPos write SetAcEntryPos;
    function GetAcVatEntryPos: IJanuaField;
    procedure SetAcVatEntryPos(const Value: IJanuaField);
    property AcVatEntryPos: IJanuaField read GetAcVatEntryPos write SetAcVatEntryPos;
    function GetAcTaxableAmntEntryPos: IJanuaField;
    procedure SetAcTaxableAmntEntryPos(const Value: IJanuaField);
    property AcTaxableAmntEntryPos: IJanuaField read GetAcTaxableAmntEntryPos write SetAcTaxableAmntEntryPos;
    function GetGroupTransFeesCod: IJanuaField;
    procedure SetGroupTransFeesCod(const Value: IJanuaField);
    property GroupTransFeesCod: IJanuaField read GetGroupTransFeesCod write SetGroupTransFeesCod;
    function GetLedgerTransFeesCod: IJanuaField;
    procedure SetLedgerTransFeesCod(const Value: IJanuaField);
    property LedgerTransFeesCod: IJanuaField read GetLedgerTransFeesCod write SetLedgerTransFeesCod;
    function GetSubledgerTransFeesCod: IJanuaField;
    procedure SetSubledgerTransFeesCod(const Value: IJanuaField);
    property SubledgerTransFeesCod: IJanuaField read GetSubledgerTransFeesCod write SetSubledgerTransFeesCod;
    function GetAcTransFeesEntry: IJanuaField;
    procedure SetAcTransFeesEntry(const Value: IJanuaField);
    property AcTransFeesEntry: IJanuaField read GetAcTransFeesEntry write SetAcTransFeesEntry;
    function GetIsoDescription: IJanuaField;
    procedure SetIsoDescription(const Value: IJanuaField);
    property IsoDescription: IJanuaField read GetIsoDescription write SetIsoDescription;
    function GetAnGroupId: IJanuaField;
    procedure SetAnGroupId(const Value: IJanuaField);
    property AnGroupId: IJanuaField read GetAnGroupId write SetAnGroupId;
    function GetInsertDate: IJanuaField;
    procedure SetInsertDate(const Value: IJanuaField);
    property InsertDate: IJanuaField read GetInsertDate write SetInsertDate;
    function GetUpdateDate: IJanuaField;
    procedure SetUpdateDate(const Value: IJanuaField);
    property UpdateDate: IJanuaField read GetUpdateDate write SetUpdateDate;
    function GetUserInsert: IJanuaField;
    procedure SetUserInsert(const Value: IJanuaField);
    property UserInsert: IJanuaField read GetUserInsert write SetUserInsert;
    function GetUserUpdate: IJanuaField;
    procedure SetUserUpdate(const Value: IJanuaField);
    property UserUpdate: IJanuaField read GetUserUpdate write SetUserUpdate;
    function GetLocal: IJanuaField;
    procedure SetLocal(const Value: IJanuaField);
    property Local: IJanuaField read GetLocal write SetLocal;
    function GetDtVatRegistry: IJanuaField;
    procedure SetDtVatRegistry(const Value: IJanuaField);
    property DtVatRegistry: IJanuaField read GetDtVatRegistry write SetDtVatRegistry;
    function GetBillBook: IJanuaField;
    procedure SetBillBook(const Value: IJanuaField);
    property BillBook: IJanuaField read GetBillBook write SetBillBook;
    function GetTypeGroup: IJanuaField;
    procedure SetTypeGroup(const Value: IJanuaField);
    property TypeGroup: IJanuaField read GetTypeGroup write SetTypeGroup;
    function GetTypeAnagraphId: IJanuaField;
    procedure SetTypeAnagraphId(const Value: IJanuaField);
    property TypeAnagraphId: IJanuaField read GetTypeAnagraphId write SetTypeAnagraphId;
    function GetShortDescription: IJanuaField;
    procedure SetShortDescription(const Value: IJanuaField);
    property ShortDescription: IJanuaField read GetShortDescription write SetShortDescription;
    function GetNOSTRODOC: IJanuaField;
    procedure SetNOSTRODOC(const Value: IJanuaField);
    property NOSTRODOC: IJanuaField read GetNOSTRODOC write SetNOSTRODOC;
    function GetCASSA: IJanuaField;
    procedure SetCASSA(const Value: IJanuaField);
    property CASSA: IJanuaField read GetCASSA write SetCASSA;
    function GetWarehouseRegister: IJanuaField;
    procedure SetWarehouseRegister(const Value: IJanuaField);
    property WarehouseRegister: IJanuaField read GetWarehouseRegister write SetWarehouseRegister;
    function GetReverseDocType: IJanuaField;
    procedure SetReverseDocType(const Value: IJanuaField);
    property ReverseDocType: IJanuaField read GetReverseDocType write SetReverseDocType;
    function GetTypeGroupId: IJanuaField;
    procedure SetTypeGroupId(const Value: IJanuaField);
    property TypeGroupId: IJanuaField read GetTypeGroupId write SetTypeGroupId;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
    function GetCustomsDocDate: IJanuaField;
    procedure SetCustomsDocDate(const Value: IJanuaField);
    property CustomsDocDate: IJanuaField read GetCustomsDocDate write SetCustomsDocDate;
    function GetCustomsDocCin: IJanuaField;
    procedure SetCustomsDocCin(const Value: IJanuaField);
    property CustomsDocCin: IJanuaField read GetCustomsDocCin write SetCustomsDocCin;
    function GetDocType: IDocType;
    procedure SetDocType(const Value: IDocType);
    property DocType: IDocType read GetDocType write SetDocType;

  end;

implementation

end.
