unit JOrm.Documents.RowViews.Custom.Intf;

interface

uses Janua.Orm.Intf;

type

  IDocRowCustomView = interface(IJanuaRecord)
    ['{6F290B4C-8522-41CB-AB38-FEC5612E8547}']
    function GetId: IJanuaField;
    procedure SetId(const Value: IJanuaField);
    property Id: IJanuaField read GetId write SetId;
    function GetDocId: IJanuaField;
    procedure SetDocId(const Value: IJanuaField);
    property DocId: IJanuaField read GetDocId write SetDocId;
    function GetItemId: IJanuaField;
    procedure SetItemId(const Value: IJanuaField);
    property ItemId: IJanuaField read GetItemId write SetItemId;
    function GetRowDate: IJanuaField;
    procedure SetRowDate(const Value: IJanuaField);
    property RowDate: IJanuaField read GetRowDate write SetRowDate;
    function GetInout: IJanuaField;
    procedure SetInout(const Value: IJanuaField);
    property Inout: IJanuaField read GetInout write SetInout;
    function GetModel: IJanuaField;
    procedure SetModel(const Value: IJanuaField);
    property Model: IJanuaField read GetModel write SetModel;
    function GetCode: IJanuaField;
    procedure SetCode(const Value: IJanuaField);
    property Code: IJanuaField read GetCode write SetCode;
    function GetDescription: IJanuaField;
    procedure SetDescription(const Value: IJanuaField);
    property Description: IJanuaField read GetDescription write SetDescription;
    function GetPrice: IJanuaField;
    procedure SetPrice(const Value: IJanuaField);
    property Price: IJanuaField read GetPrice write SetPrice;
    function GetVatId: IJanuaField;
    procedure SetVatId(const Value: IJanuaField);
    property VatId: IJanuaField read GetVatId write SetVatId;
    function GetVatRate: IJanuaField;
    procedure SetVatRate(const Value: IJanuaField);
    property VatRate: IJanuaField read GetVatRate write SetVatRate;
    function GetDiscountRate: IJanuaField;
    procedure SetDiscountRate(const Value: IJanuaField);
    property DiscountRate: IJanuaField read GetDiscountRate write SetDiscountRate;
    function GetDiscountCommRate: IJanuaField;
    procedure SetDiscountCommRate(const Value: IJanuaField);
    property DiscountCommRate: IJanuaField read GetDiscountCommRate write SetDiscountCommRate;
    function GetDiscountExtRate: IJanuaField;
    procedure SetDiscountExtRate(const Value: IJanuaField);
    property DiscountExtRate: IJanuaField read GetDiscountExtRate write SetDiscountExtRate;
    function GetQuantity: IJanuaField;
    procedure SetQuantity(const Value: IJanuaField);
    property Quantity: IJanuaField read GetQuantity write SetQuantity;
    function GetSecondhand: IJanuaField;
    procedure SetSecondhand(const Value: IJanuaField);
    property Secondhand: IJanuaField read GetSecondhand write SetSecondhand;
    function GetDimensionId1: IJanuaField;
    procedure SetDimensionId1(const Value: IJanuaField);
    property DimensionId1: IJanuaField read GetDimensionId1 write SetDimensionId1;
    function GetDimensionId2: IJanuaField;
    procedure SetDimensionId2(const Value: IJanuaField);
    property DimensionId2: IJanuaField read GetDimensionId2 write SetDimensionId2;
    function GetDimensionsId3: IJanuaField;
    procedure SetDimensionsId3(const Value: IJanuaField);
    property DimensionsId3: IJanuaField read GetDimensionsId3 write SetDimensionsId3;
    function GetCurrencyId: IJanuaField;
    procedure SetCurrencyId(const Value: IJanuaField);
    property CurrencyId: IJanuaField read GetCurrencyId write SetCurrencyId;
    function GetExchangeRate: IJanuaField;
    procedure SetExchangeRate(const Value: IJanuaField);
    property ExchangeRate: IJanuaField read GetExchangeRate write SetExchangeRate;
    function GetPosition: IJanuaField;
    procedure SetPosition(const Value: IJanuaField);
    property Position: IJanuaField read GetPosition write SetPosition;
    function GetDeliveryDate: IJanuaField;
    procedure SetDeliveryDate(const Value: IJanuaField);
    property DeliveryDate: IJanuaField read GetDeliveryDate write SetDeliveryDate;
    function GetBarcode: IJanuaField;
    procedure SetBarcode(const Value: IJanuaField);
    property Barcode: IJanuaField read GetBarcode write SetBarcode;
    function GetDeliveredQty: IJanuaField;
    procedure SetDeliveredQty(const Value: IJanuaField);
    property DeliveredQty: IJanuaField read GetDeliveredQty write SetDeliveredQty;
    function GetSampleQty: IJanuaField;
    procedure SetSampleQty(const Value: IJanuaField);
    property SampleQty: IJanuaField read GetSampleQty write SetSampleQty;
    function GetIsSample: IJanuaField;
    procedure SetIsSample(const Value: IJanuaField);
    property IsSample: IJanuaField read GetIsSample write SetIsSample;
    function GetRefCode: IJanuaField;
    procedure SetRefCode(const Value: IJanuaField);
    property RefCode: IJanuaField read GetRefCode write SetRefCode;
    function GetDocOriginId: IJanuaField;
    procedure SetDocOriginId(const Value: IJanuaField);
    property DocOriginId: IJanuaField read GetDocOriginId write SetDocOriginId;
    function GetRowOriginId: IJanuaField;
    procedure SetRowOriginId(const Value: IJanuaField);
    property RowOriginId: IJanuaField read GetRowOriginId write SetRowOriginId;
    function GetAnagramsRefId: IJanuaField;
    procedure SetAnagramsRefId(const Value: IJanuaField);
    property AnagramsRefId: IJanuaField read GetAnagramsRefId write SetAnagramsRefId;
    function GetCollectorPoints: IJanuaField;
    procedure SetCollectorPoints(const Value: IJanuaField);
    property CollectorPoints: IJanuaField read GetCollectorPoints write SetCollectorPoints;
    function GetCollectorPointsForfait: IJanuaField;
    procedure SetCollectorPointsForfait(const Value: IJanuaField);
    property CollectorPointsForfait: IJanuaField read GetCollectorPointsForfait
      write SetCollectorPointsForfait;
    function GetPackageTypeId: IJanuaField;
    procedure SetPackageTypeId(const Value: IJanuaField);
    property PackageTypeId: IJanuaField read GetPackageTypeId write SetPackageTypeId;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
    function GetOrderedQty: IJanuaField;
    procedure SetOrderedQty(const Value: IJanuaField);
    property OrderedQty: IJanuaField read GetOrderedQty write SetOrderedQty;
    function GetPallets: IJanuaField;
    procedure SetPallets(const Value: IJanuaField);
    property Pallets: IJanuaField read GetPallets write SetPallets;
    function GetWeightOnDelivery: IJanuaField;
    procedure SetWeightOnDelivery(const Value: IJanuaField);
    property WeightOnDelivery: IJanuaField read GetWeightOnDelivery write SetWeightOnDelivery;
    function GetWeightOnOrder: IJanuaField;
    procedure SetWeightOnOrder(const Value: IJanuaField);
    property WeightOnOrder: IJanuaField read GetWeightOnOrder write SetWeightOnOrder;
    function GetWeightOnShipping: IJanuaField;
    procedure SetWeightOnShipping(const Value: IJanuaField);
    property WeightOnShipping: IJanuaField read GetWeightOnShipping write SetWeightOnShipping;
    function GetVolume: IJanuaField;
    procedure SetVolume(const Value: IJanuaField);
    property Volume: IJanuaField read GetVolume write SetVolume;
    function GetDocOriginNumber: IJanuaField;
    procedure SetDocOriginNumber(const Value: IJanuaField);
    property DocOriginNumber: IJanuaField read GetDocOriginNumber write SetDocOriginNumber;
    function GetDocOriginDate: IJanuaField;
    procedure SetDocOriginDate(const Value: IJanuaField);
    property DocOriginDate: IJanuaField read GetDocOriginDate write SetDocOriginDate;
    function GetCustomsDocRef: IJanuaField;
    procedure SetCustomsDocRef(const Value: IJanuaField);
    property CustomsDocRef: IJanuaField read GetCustomsDocRef write SetCustomsDocRef;
    function GetCustomsDocTypeId: IJanuaField;
    procedure SetCustomsDocTypeId(const Value: IJanuaField);
    property CustomsDocTypeId: IJanuaField read GetCustomsDocTypeId write SetCustomsDocTypeId;
    function GetPurchaseOrder: IJanuaField;
    procedure SetPurchaseOrder(const Value: IJanuaField);
    property PurchaseOrder: IJanuaField read GetPurchaseOrder write SetPurchaseOrder;
    function GetInsertDate: IJanuaField;
    procedure SetInsertDate(const Value: IJanuaField);
    property InsertDate: IJanuaField read GetInsertDate write SetInsertDate;
    function GetUpdateDate: IJanuaField;
    procedure SetUpdateDate(const Value: IJanuaField);
    property UpdateDate: IJanuaField read GetUpdateDate write SetUpdateDate;
    function GetUserInsert: IJanuaField;
    procedure SetUserInsert(const Value: IJanuaField);
    property UserInsert: IJanuaField read GetUserInsert write SetUserInsert;
    function GetUserUpdate: IJanuaField;
    procedure SetUserUpdate(const Value: IJanuaField);
    property UserUpdate: IJanuaField read GetUserUpdate write SetUserUpdate;
    function GetSizeWeight: IJanuaField;
    procedure SetSizeWeight(const Value: IJanuaField);
    property SizeWeight: IJanuaField read GetSizeWeight write SetSizeWeight;
    function GetSizeLength: IJanuaField;
    procedure SetSizeLength(const Value: IJanuaField);
    property SizeLength: IJanuaField read GetSizeLength write SetSizeLength;
    function GetSizeHeight: IJanuaField;
    procedure SetSizeHeight(const Value: IJanuaField);
    property SizeHeight: IJanuaField read GetSizeHeight write SetSizeHeight;
    function GetInventoryQty: IJanuaField;
    procedure SetInventoryQty(const Value: IJanuaField);
    property InventoryQty: IJanuaField read GetInventoryQty write SetInventoryQty;
    function GetInventoryWeight: IJanuaField;
    procedure SetInventoryWeight(const Value: IJanuaField);
    property InventoryWeight: IJanuaField read GetInventoryWeight write SetInventoryWeight;
    function GetCustomsDocCin: IJanuaField;
    procedure SetCustomsDocCin(const Value: IJanuaField);
    property CustomsDocCin: IJanuaField read GetCustomsDocCin write SetCustomsDocCin;
    function GetCustomsDocDate: IJanuaField;
    procedure SetCustomsDocDate(const Value: IJanuaField);
    property CustomsDocDate: IJanuaField read GetCustomsDocDate write SetCustomsDocDate;
    function GetSupplierId: IJanuaField;
    procedure SetSupplierId(const Value: IJanuaField);
    property SupplierId: IJanuaField read GetSupplierId write SetSupplierId;
    function GetDbSchemaId: IJanuaField;
    procedure SetDbSchemaId(const Value: IJanuaField);
    property DbSchemaId: IJanuaField read GetDbSchemaId write SetDbSchemaId;
    function GetDocHeadJguid: IJanuaField;
    procedure SetDocHeadJguid(const Value: IJanuaField);
    property DocHeadJguid: IJanuaField read GetDocHeadJguid write SetDocHeadJguid;
    function GetItemJguid: IJanuaField;
    procedure SetItemJguid(const Value: IJanuaField);
    property ItemJguid: IJanuaField read GetItemJguid write SetItemJguid;
    function GetContainerStatus: IJanuaField;
    procedure SetContainerStatus(const Value: IJanuaField);
    property ContainerStatus: IJanuaField read GetContainerStatus write SetContainerStatus;
    function GetRights: IJanuaField;
    procedure SetRights(const Value: IJanuaField);
    property Rights: IJanuaField read GetRights write SetRights;
    function GetInvoiceNumber: IJanuaField;
    procedure SetInvoiceNumber(const Value: IJanuaField);
    property InvoiceNumber: IJanuaField read GetInvoiceNumber write SetInvoiceNumber;
    function GetCustomField1: IJanuaField;
    procedure SetCustomField1(const Value: IJanuaField);
    property CustomField1: IJanuaField read GetCustomField1 write SetCustomField1;
    function GetCustomField2: IJanuaField;
    procedure SetCustomField2(const Value: IJanuaField);
    property CustomField2: IJanuaField read GetCustomField2 write SetCustomField2;
    function GetInvoiceAmount: IJanuaField;
    procedure SetInvoiceAmount(const Value: IJanuaField);
    property InvoiceAmount: IJanuaField read GetInvoiceAmount write SetInvoiceAmount;
    function GetCustomField3: IJanuaField;
    procedure SetCustomField3(const Value: IJanuaField);
    property CustomField3: IJanuaField read GetCustomField3 write SetCustomField3;
    function GetJsonNestedTable: IJanuaField;
    procedure SetJsonNestedTable(const Value: IJanuaField);
    property JsonNestedTable: IJanuaField read GetJsonNestedTable write SetJsonNestedTable;
    function GetInvoiceDate: IJanuaField;
    procedure SetInvoiceDate(const Value: IJanuaField);
    property InvoiceDate: IJanuaField read GetInvoiceDate write SetInvoiceDate;
    function GetImportexport: IJanuaField;
    procedure SetImportexport(const Value: IJanuaField);
    property Importexport: IJanuaField read GetImportexport write SetImportexport;
    function GetTypeId: IJanuaField;
    procedure SetTypeId(const Value: IJanuaField);
    property TypeId: IJanuaField read GetTypeId write SetTypeId;
    function GetIsDescription: IJanuaField;
    procedure SetIsDescription(const Value: IJanuaField);
    property IsDescription: IJanuaField read GetIsDescription write SetIsDescription;
    function GetExchangeRage: IJanuaField;
    procedure SetExchangeRage(const Value: IJanuaField);
    property ExchangeRage: IJanuaField read GetExchangeRage write SetExchangeRage;
    function GetFreightQty: IJanuaField;
    procedure SetFreightQty(const Value: IJanuaField);
    property FreightQty: IJanuaField read GetFreightQty write SetFreightQty;
    function GetAmount: IJanuaField;
    procedure SetAmount(const Value: IJanuaField);
    property Amount: IJanuaField read GetAmount write SetAmount;
    function GetVatCode: IJanuaField;
    procedure SetVatCode(const Value: IJanuaField);
    property VatCode: IJanuaField read GetVatCode write SetVatCode;
    function GetFreightRate: IJanuaField;
    procedure SetFreightRate(const Value: IJanuaField);
    property FreightRate: IJanuaField read GetFreightRate write SetFreightRate;
    function GetVatDescription: IJanuaField;
    procedure SetVatDescription(const Value: IJanuaField);
    property VatDescription: IJanuaField read GetVatDescription write SetVatDescription;
    function GetCurrencyCode: IJanuaField;
    procedure SetCurrencyCode(const Value: IJanuaField);
    property CurrencyCode: IJanuaField read GetCurrencyCode write SetCurrencyCode;
    function GetCurrencyDescription: IJanuaField;
    procedure SetCurrencyDescription(const Value: IJanuaField);
    property CurrencyDescription: IJanuaField read GetCurrencyDescription write SetCurrencyDescription;
    function GetFlgDescription: IJanuaField;
    procedure SetFlgDescription(const Value: IJanuaField);
    property FlgDescription: IJanuaField read GetFlgDescription write SetFlgDescription;
    function GetSupplierName: IJanuaField;
    procedure SetSupplierName(const Value: IJanuaField);
    property SupplierName: IJanuaField read GetSupplierName write SetSupplierName;
    function GetHazClass: IJanuaField;
    procedure SetHazClass(const Value: IJanuaField);
    property HazClass: IJanuaField read GetHazClass write SetHazClass;
  end;

  IDocRowCustomViews = interface(IJanuaRecordSet)
    ['{3464D959-9244-4AA2-91D9-154920F7B6FD}']
    function GetId: IJanuaField;
    procedure SetId(const Value: IJanuaField);
    property Id: IJanuaField read GetId write SetId;
    function GetDocId: IJanuaField;
    procedure SetDocId(const Value: IJanuaField);
    property DocId: IJanuaField read GetDocId write SetDocId;
    function GetItemId: IJanuaField;
    procedure SetItemId(const Value: IJanuaField);
    property ItemId: IJanuaField read GetItemId write SetItemId;
    function GetRowDate: IJanuaField;
    procedure SetRowDate(const Value: IJanuaField);
    property RowDate: IJanuaField read GetRowDate write SetRowDate;
    function GetInout: IJanuaField;
    procedure SetInout(const Value: IJanuaField);
    property Inout: IJanuaField read GetInout write SetInout;
    function GetModel: IJanuaField;
    procedure SetModel(const Value: IJanuaField);
    property Model: IJanuaField read GetModel write SetModel;
    function GetCode: IJanuaField;
    procedure SetCode(const Value: IJanuaField);
    property Code: IJanuaField read GetCode write SetCode;
    function GetDescription: IJanuaField;
    procedure SetDescription(const Value: IJanuaField);
    property Description: IJanuaField read GetDescription write SetDescription;
    function GetPrice: IJanuaField;
    procedure SetPrice(const Value: IJanuaField);
    property Price: IJanuaField read GetPrice write SetPrice;
    function GetVatId: IJanuaField;
    procedure SetVatId(const Value: IJanuaField);
    property VatId: IJanuaField read GetVatId write SetVatId;
    function GetVatRate: IJanuaField;
    procedure SetVatRate(const Value: IJanuaField);
    property VatRate: IJanuaField read GetVatRate write SetVatRate;
    function GetDiscountRate: IJanuaField;
    procedure SetDiscountRate(const Value: IJanuaField);
    property DiscountRate: IJanuaField read GetDiscountRate write SetDiscountRate;
    function GetDiscountCommRate: IJanuaField;
    procedure SetDiscountCommRate(const Value: IJanuaField);
    property DiscountCommRate: IJanuaField read GetDiscountCommRate write SetDiscountCommRate;
    function GetDiscountExtRate: IJanuaField;
    procedure SetDiscountExtRate(const Value: IJanuaField);
    property DiscountExtRate: IJanuaField read GetDiscountExtRate write SetDiscountExtRate;
    function GetQuantity: IJanuaField;
    procedure SetQuantity(const Value: IJanuaField);
    property Quantity: IJanuaField read GetQuantity write SetQuantity;
    function GetSecondhand: IJanuaField;
    procedure SetSecondhand(const Value: IJanuaField);
    property Secondhand: IJanuaField read GetSecondhand write SetSecondhand;
    function GetDimensionId1: IJanuaField;
    procedure SetDimensionId1(const Value: IJanuaField);
    property DimensionId1: IJanuaField read GetDimensionId1 write SetDimensionId1;
    function GetDimensionId2: IJanuaField;
    procedure SetDimensionId2(const Value: IJanuaField);
    property DimensionId2: IJanuaField read GetDimensionId2 write SetDimensionId2;
    function GetDimensionsId3: IJanuaField;
    procedure SetDimensionsId3(const Value: IJanuaField);
    property DimensionsId3: IJanuaField read GetDimensionsId3 write SetDimensionsId3;
    function GetCurrencyId: IJanuaField;
    procedure SetCurrencyId(const Value: IJanuaField);
    property CurrencyId: IJanuaField read GetCurrencyId write SetCurrencyId;
    function GetExchangeRate: IJanuaField;
    procedure SetExchangeRate(const Value: IJanuaField);
    property ExchangeRate: IJanuaField read GetExchangeRate write SetExchangeRate;
    function GetPosition: IJanuaField;
    procedure SetPosition(const Value: IJanuaField);
    property Position: IJanuaField read GetPosition write SetPosition;
    function GetDeliveryDate: IJanuaField;
    procedure SetDeliveryDate(const Value: IJanuaField);
    property DeliveryDate: IJanuaField read GetDeliveryDate write SetDeliveryDate;
    function GetBarcode: IJanuaField;
    procedure SetBarcode(const Value: IJanuaField);
    property Barcode: IJanuaField read GetBarcode write SetBarcode;
    function GetDeliveredQty: IJanuaField;
    procedure SetDeliveredQty(const Value: IJanuaField);
    property DeliveredQty: IJanuaField read GetDeliveredQty write SetDeliveredQty;
    function GetSampleQty: IJanuaField;
    procedure SetSampleQty(const Value: IJanuaField);
    property SampleQty: IJanuaField read GetSampleQty write SetSampleQty;
    function GetIsSample: IJanuaField;
    procedure SetIsSample(const Value: IJanuaField);
    property IsSample: IJanuaField read GetIsSample write SetIsSample;
    function GetRefCode: IJanuaField;
    procedure SetRefCode(const Value: IJanuaField);
    property RefCode: IJanuaField read GetRefCode write SetRefCode;
    function GetDocOriginId: IJanuaField;
    procedure SetDocOriginId(const Value: IJanuaField);
    property DocOriginId: IJanuaField read GetDocOriginId write SetDocOriginId;
    function GetRowOriginId: IJanuaField;
    procedure SetRowOriginId(const Value: IJanuaField);
    property RowOriginId: IJanuaField read GetRowOriginId write SetRowOriginId;
    function GetAnagramsRefId: IJanuaField;
    procedure SetAnagramsRefId(const Value: IJanuaField);
    property AnagramsRefId: IJanuaField read GetAnagramsRefId write SetAnagramsRefId;
    function GetCollectorPoints: IJanuaField;
    procedure SetCollectorPoints(const Value: IJanuaField);
    property CollectorPoints: IJanuaField read GetCollectorPoints write SetCollectorPoints;
    function GetCollectorPointsForfait: IJanuaField;
    procedure SetCollectorPointsForfait(const Value: IJanuaField);
    property CollectorPointsForfait: IJanuaField read GetCollectorPointsForfait
      write SetCollectorPointsForfait;
    function GetPackageTypeId: IJanuaField;
    procedure SetPackageTypeId(const Value: IJanuaField);
    property PackageTypeId: IJanuaField read GetPackageTypeId write SetPackageTypeId;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
    function GetOrderedQty: IJanuaField;
    procedure SetOrderedQty(const Value: IJanuaField);
    property OrderedQty: IJanuaField read GetOrderedQty write SetOrderedQty;
    function GetPallets: IJanuaField;
    procedure SetPallets(const Value: IJanuaField);
    property Pallets: IJanuaField read GetPallets write SetPallets;
    function GetWeightOnDelivery: IJanuaField;
    procedure SetWeightOnDelivery(const Value: IJanuaField);
    property WeightOnDelivery: IJanuaField read GetWeightOnDelivery write SetWeightOnDelivery;
    function GetWeightOnOrder: IJanuaField;
    procedure SetWeightOnOrder(const Value: IJanuaField);
    property WeightOnOrder: IJanuaField read GetWeightOnOrder write SetWeightOnOrder;
    function GetWeightOnShipping: IJanuaField;
    procedure SetWeightOnShipping(const Value: IJanuaField);
    property WeightOnShipping: IJanuaField read GetWeightOnShipping write SetWeightOnShipping;
    function GetVolume: IJanuaField;
    procedure SetVolume(const Value: IJanuaField);
    property Volume: IJanuaField read GetVolume write SetVolume;
    function GetDocOriginNumber: IJanuaField;
    procedure SetDocOriginNumber(const Value: IJanuaField);
    property DocOriginNumber: IJanuaField read GetDocOriginNumber write SetDocOriginNumber;
    function GetDocOriginDate: IJanuaField;
    procedure SetDocOriginDate(const Value: IJanuaField);
    property DocOriginDate: IJanuaField read GetDocOriginDate write SetDocOriginDate;
    function GetCustomsDocRef: IJanuaField;
    procedure SetCustomsDocRef(const Value: IJanuaField);
    property CustomsDocRef: IJanuaField read GetCustomsDocRef write SetCustomsDocRef;
    function GetCustomsDocTypeId: IJanuaField;
    procedure SetCustomsDocTypeId(const Value: IJanuaField);
    property CustomsDocTypeId: IJanuaField read GetCustomsDocTypeId write SetCustomsDocTypeId;
    function GetPurchaseOrder: IJanuaField;
    procedure SetPurchaseOrder(const Value: IJanuaField);
    property PurchaseOrder: IJanuaField read GetPurchaseOrder write SetPurchaseOrder;
    function GetInsertDate: IJanuaField;
    procedure SetInsertDate(const Value: IJanuaField);
    property InsertDate: IJanuaField read GetInsertDate write SetInsertDate;
    function GetUpdateDate: IJanuaField;
    procedure SetUpdateDate(const Value: IJanuaField);
    property UpdateDate: IJanuaField read GetUpdateDate write SetUpdateDate;
    function GetUserInsert: IJanuaField;
    procedure SetUserInsert(const Value: IJanuaField);
    property UserInsert: IJanuaField read GetUserInsert write SetUserInsert;
    function GetUserUpdate: IJanuaField;
    procedure SetUserUpdate(const Value: IJanuaField);
    property UserUpdate: IJanuaField read GetUserUpdate write SetUserUpdate;
    function GetSizeWeight: IJanuaField;
    procedure SetSizeWeight(const Value: IJanuaField);
    property SizeWeight: IJanuaField read GetSizeWeight write SetSizeWeight;
    function GetSizeLength: IJanuaField;
    procedure SetSizeLength(const Value: IJanuaField);
    property SizeLength: IJanuaField read GetSizeLength write SetSizeLength;
    function GetSizeHeight: IJanuaField;
    procedure SetSizeHeight(const Value: IJanuaField);
    property SizeHeight: IJanuaField read GetSizeHeight write SetSizeHeight;
    function GetInventoryQty: IJanuaField;
    procedure SetInventoryQty(const Value: IJanuaField);
    property InventoryQty: IJanuaField read GetInventoryQty write SetInventoryQty;
    function GetInventoryWeight: IJanuaField;
    procedure SetInventoryWeight(const Value: IJanuaField);
    property InventoryWeight: IJanuaField read GetInventoryWeight write SetInventoryWeight;
    function GetCustomsDocCin: IJanuaField;
    procedure SetCustomsDocCin(const Value: IJanuaField);
    property CustomsDocCin: IJanuaField read GetCustomsDocCin write SetCustomsDocCin;
    function GetCustomsDocDate: IJanuaField;
    procedure SetCustomsDocDate(const Value: IJanuaField);
    property CustomsDocDate: IJanuaField read GetCustomsDocDate write SetCustomsDocDate;
    function GetSupplierId: IJanuaField;
    procedure SetSupplierId(const Value: IJanuaField);
    property SupplierId: IJanuaField read GetSupplierId write SetSupplierId;
    function GetDbSchemaId: IJanuaField;
    procedure SetDbSchemaId(const Value: IJanuaField);
    property DbSchemaId: IJanuaField read GetDbSchemaId write SetDbSchemaId;
    function GetDocHeadJguid: IJanuaField;
    procedure SetDocHeadJguid(const Value: IJanuaField);
    property DocHeadJguid: IJanuaField read GetDocHeadJguid write SetDocHeadJguid;
    function GetItemJguid: IJanuaField;
    procedure SetItemJguid(const Value: IJanuaField);
    property ItemJguid: IJanuaField read GetItemJguid write SetItemJguid;
    function GetContainerStatus: IJanuaField;
    procedure SetContainerStatus(const Value: IJanuaField);
    property ContainerStatus: IJanuaField read GetContainerStatus write SetContainerStatus;
    function GetRights: IJanuaField;
    procedure SetRights(const Value: IJanuaField);
    property Rights: IJanuaField read GetRights write SetRights;
    function GetInvoiceNumber: IJanuaField;
    procedure SetInvoiceNumber(const Value: IJanuaField);
    property InvoiceNumber: IJanuaField read GetInvoiceNumber write SetInvoiceNumber;
    function GetCustomField1: IJanuaField;
    procedure SetCustomField1(const Value: IJanuaField);
    property CustomField1: IJanuaField read GetCustomField1 write SetCustomField1;
    function GetCustomField2: IJanuaField;
    procedure SetCustomField2(const Value: IJanuaField);
    property CustomField2: IJanuaField read GetCustomField2 write SetCustomField2;
    function GetInvoiceAmount: IJanuaField;
    procedure SetInvoiceAmount(const Value: IJanuaField);
    property InvoiceAmount: IJanuaField read GetInvoiceAmount write SetInvoiceAmount;
    function GetCustomField3: IJanuaField;
    procedure SetCustomField3(const Value: IJanuaField);
    property CustomField3: IJanuaField read GetCustomField3 write SetCustomField3;
    function GetJsonNestedTable: IJanuaField;
    procedure SetJsonNestedTable(const Value: IJanuaField);
    property JsonNestedTable: IJanuaField read GetJsonNestedTable write SetJsonNestedTable;
    function GetInvoiceDate: IJanuaField;
    procedure SetInvoiceDate(const Value: IJanuaField);
    property InvoiceDate: IJanuaField read GetInvoiceDate write SetInvoiceDate;
    function GetImportexport: IJanuaField;
    procedure SetImportexport(const Value: IJanuaField);
    property Importexport: IJanuaField read GetImportexport write SetImportexport;
    function GetTypeId: IJanuaField;
    procedure SetTypeId(const Value: IJanuaField);
    property TypeId: IJanuaField read GetTypeId write SetTypeId;
    function GetIsDescription: IJanuaField;
    procedure SetIsDescription(const Value: IJanuaField);
    property IsDescription: IJanuaField read GetIsDescription write SetIsDescription;
    function GetExchangeRage: IJanuaField;
    procedure SetExchangeRage(const Value: IJanuaField);
    property ExchangeRage: IJanuaField read GetExchangeRage write SetExchangeRage;
    function GetFreightQty: IJanuaField;
    procedure SetFreightQty(const Value: IJanuaField);
    property FreightQty: IJanuaField read GetFreightQty write SetFreightQty;
    function GetAmount: IJanuaField;
    procedure SetAmount(const Value: IJanuaField);
    property Amount: IJanuaField read GetAmount write SetAmount;
    function GetVatCode: IJanuaField;
    procedure SetVatCode(const Value: IJanuaField);
    property VatCode: IJanuaField read GetVatCode write SetVatCode;
    function GetFreightRate: IJanuaField;
    procedure SetFreightRate(const Value: IJanuaField);
    property FreightRate: IJanuaField read GetFreightRate write SetFreightRate;
    function GetVatDescription: IJanuaField;
    procedure SetVatDescription(const Value: IJanuaField);
    property VatDescription: IJanuaField read GetVatDescription write SetVatDescription;
    function GetCurrencyCode: IJanuaField;
    procedure SetCurrencyCode(const Value: IJanuaField);
    property CurrencyCode: IJanuaField read GetCurrencyCode write SetCurrencyCode;
    function GetCurrencyDescription: IJanuaField;
    procedure SetCurrencyDescription(const Value: IJanuaField);
    property CurrencyDescription: IJanuaField read GetCurrencyDescription write SetCurrencyDescription;
    function GetFlgDescription: IJanuaField;
    procedure SetFlgDescription(const Value: IJanuaField);
    property FlgDescription: IJanuaField read GetFlgDescription write SetFlgDescription;
    function GetSupplierName: IJanuaField;
    procedure SetSupplierName(const Value: IJanuaField);
    property SupplierName: IJanuaField read GetSupplierName write SetSupplierName;
    function GetRowView: IDocRowCustomView;
    procedure SetRowView(const Value: IDocRowCustomView);
    property RowView: IDocRowCustomView read GetRowView write SetRowView;

  end;

implementation

end.
