unit JOrm.Phoenix.Statini.Custom.Intf;

interface

uses Janua.Orm.Intf;

type

  ICustomStatino = interface(IJanuaRecord)
    ['{8F638B73-0CDE-4409-917B-FA1EF5B4F2B4}']
    function GetChiave: IJanuaField;
    property Chiave: IJanuaField read GetChiave;
    function GetCliente: IJanuaField;
    property Cliente: IJanuaField read GetCliente;
    function GetFiliale: IJanuaField;
    property Filiale: IJanuaField read GetFiliale;
    function GetTitolo: IJanuaField;
    property Titolo: IJanuaField read GetTitolo;
    function GetRagioneSociale: IJanuaField;
    property RagioneSociale: IJanuaField read GetRagioneSociale;
    function GetIndirizzo: IJanuaField;
    property Indirizzo: IJanuaField read GetIndirizzo;
    function GetComune: IJanuaField;
    property Comune: IJanuaField read GetComune;
    function GetProvincia: IJanuaField;
    property Provincia: IJanuaField read GetProvincia;
    function GetCap: IJanuaField;
    property Cap: IJanuaField read GetCap;
    function GetTelefono: IJanuaField;
    property Telefono: IJanuaField read GetTelefono;
    function GetCellulare: IJanuaField;
    property Cellulare: IJanuaField read GetCellulare;
    function GetNote: IJanuaField;
    property Note: IJanuaField read GetNote;
    function GetOrarioAperturaDal1: IJanuaField;
    property OrarioAperturaDal1: IJanuaField read GetOrarioAperturaDal1;
    function GetOrarioAperturaDal2: IJanuaField;
    property OrarioAperturaDal2: IJanuaField read GetOrarioAperturaDal2;
    function GetOrarioAperturaAl1: IJanuaField;
    property OrarioAperturaAl1: IJanuaField read GetOrarioAperturaAl1;
    function GetOrarioAperturaAl2: IJanuaField;
    property OrarioAperturaAl2: IJanuaField read GetOrarioAperturaAl2;
    function GetChiusura: IJanuaField;
    property Chiusura: IJanuaField read GetChiusura;
    function GetFattura: IJanuaField;
    property Fattura: IJanuaField read GetFattura;
    function GetDataIntervento: IJanuaField;
    property DataIntervento: IJanuaField read GetDataIntervento;
    function GetGenerazioneAutomatica: IJanuaField;
    property GenerazioneAutomatica: IJanuaField read GetGenerazioneAutomatica;
    function GetTecnicoIntervento: IJanuaField;
    property TecnicoIntervento: IJanuaField read GetTecnicoIntervento;
    function GetScansione: IJanuaField;
    property Scansione: IJanuaField read GetScansione;
    function GetRegistro: IJanuaField;
    property Registro: IJanuaField read GetRegistro;
    function GetNotePerIlTecnico: IJanuaField;
    property NotePerIlTecnico: IJanuaField read GetNotePerIlTecnico;
    function GetSospeso: IJanuaField;
    property Sospeso: IJanuaField read GetSospeso;
    function GetDaEsportareSulWeb: IJanuaField;
    property DaEsportareSulWeb: IJanuaField read GetDaEsportareSulWeb;
    function GetResponsabile: IJanuaField;
    property Responsabile: IJanuaField read GetResponsabile;
    function GetEsportatoSuMobile: IJanuaField;
    property EsportatoSuMobile: IJanuaField read GetEsportatoSuMobile;
    function GetNoteDalTecnico: IJanuaField;
    property NoteDalTecnico: IJanuaField read GetNoteDalTecnico;
    function GetJsonDaMobile: IJanuaField;
    property JsonDaMobile: IJanuaField read GetJsonDaMobile;
    function GetPdfStatino: IJanuaField;
    property PdfStatino: IJanuaField read GetPdfStatino;
    function GetRegistroIsPdf: IJanuaField;
    property RegistroIsPdf: IJanuaField read GetRegistroIsPdf;
    function GetVerbaleProvaDinamica: IJanuaField;
    property VerbaleProvaDinamica: IJanuaField read GetVerbaleProvaDinamica;
    function GetVerbaleManichette: IJanuaField;
    property VerbaleManichette: IJanuaField read GetVerbaleManichette;
    function GetPreventivo: IJanuaField;
    property Preventivo: IJanuaField read GetPreventivo;
    function GetIgnoraEvidenziazione: IJanuaField;
    property IgnoraEvidenziazione: IJanuaField read GetIgnoraEvidenziazione;
    function GetAnnullatoDaTablet: IJanuaField;
    property AnnullatoDaTablet: IJanuaField read GetAnnullatoDaTablet;
    function GetMobilewarnNuovaAttrezzatura: IJanuaField;
    property MobilewarnNuovaAttrezzatura: IJanuaField read GetMobilewarnNuovaAttrezzatura;
    function GetMobilewarnOrdinariaRitirata: IJanuaField;
    property MobilewarnOrdinariaRitirata: IJanuaField read GetMobilewarnOrdinariaRitirata;
    function GetMobilewarnNOrdinControllata: IJanuaField;
    property MobilewarnNOrdinControllata: IJanuaField read GetMobilewarnNOrdinControllata;
    function GetMobilewarnSmaltimento: IJanuaField;
    property MobilewarnSmaltimento: IJanuaField read GetMobilewarnSmaltimento;
    function GetStatoLavorazione: IJanuaField;
    property StatoLavorazione: IJanuaField read GetStatoLavorazione;
    function GetDataChiusuraDaServer: IJanuaField;
    property DataChiusuraDaServer: IJanuaField read GetDataChiusuraDaServer;
    function GetChiusuraExt: IJanuaField;
    property ChiusuraExt: IJanuaField read GetChiusuraExt;
    function GetChiusuraStatino: IJanuaField;
    property ChiusuraStatino: IJanuaField read GetChiusuraStatino;
    function GetMobilewarnNonEseguiti: IJanuaField;
    property MobilewarnNonEseguiti: IJanuaField read GetMobilewarnNonEseguiti;
    function GetPresaInCarico: IJanuaField;
    property PresaInCarico: IJanuaField read GetPresaInCarico;
    function GetFornitura: IJanuaField;
    property Fornitura: IJanuaField read GetFornitura;
    function GetAppuntamentoData: IJanuaField;
    property AppuntamentoData: IJanuaField read GetAppuntamentoData;
    function GetAppuntamentoOra: IJanuaField;
    property AppuntamentoOra: IJanuaField read GetAppuntamentoOra;
    function GetStato: IJanuaField;
    property Stato: IJanuaField read GetStato;
  end;

  ICustomStatini = interface(IJanuaRecordSet)
    ['{AB2910A6-D0FF-4C7B-A45F-46346AFDAC83}']
    function GetChiave: IJanuaField;
    property Chiave: IJanuaField read GetChiave;
    function GetCliente: IJanuaField;
    property Cliente: IJanuaField read GetCliente;
    function GetFiliale: IJanuaField;
    property Filiale: IJanuaField read GetFiliale;
    function GetTitolo: IJanuaField;
    property Titolo: IJanuaField read GetTitolo;
    function GetRagioneSociale: IJanuaField;
    property RagioneSociale: IJanuaField read GetRagioneSociale;
    function GetIndirizzo: IJanuaField;
    property Indirizzo: IJanuaField read GetIndirizzo;
    function GetComune: IJanuaField;
    property Comune: IJanuaField read GetComune;
    function GetProvincia: IJanuaField;
    property Provincia: IJanuaField read GetProvincia;
    function GetCap: IJanuaField;
    property Cap: IJanuaField read GetCap;
    function GetTelefono: IJanuaField;
    property Telefono: IJanuaField read GetTelefono;
    function GetCellulare: IJanuaField;
    property Cellulare: IJanuaField read GetCellulare;
    function GetNote: IJanuaField;
    property Note: IJanuaField read GetNote;
    function GetOrarioAperturaDal1: IJanuaField;
    property OrarioAperturaDal1: IJanuaField read GetOrarioAperturaDal1;
    function GetOrarioAperturaDal2: IJanuaField;
    property OrarioAperturaDal2: IJanuaField read GetOrarioAperturaDal2;
    function GetOrarioAperturaAl1: IJanuaField;
    property OrarioAperturaAl1: IJanuaField read GetOrarioAperturaAl1;
    function GetOrarioAperturaAl2: IJanuaField;
    property OrarioAperturaAl2: IJanuaField read GetOrarioAperturaAl2;
    function GetChiusura: IJanuaField;
    property Chiusura: IJanuaField read GetChiusura;
    function GetFattura: IJanuaField;
    property Fattura: IJanuaField read GetFattura;
    function GetDataIntervento: IJanuaField;
    property DataIntervento: IJanuaField read GetDataIntervento;
    function GetGenerazioneAutomatica: IJanuaField;
    property GenerazioneAutomatica: IJanuaField read GetGenerazioneAutomatica;
    function GetTecnicoIntervento: IJanuaField;
    property TecnicoIntervento: IJanuaField read GetTecnicoIntervento;
    function GetScansione: IJanuaField;
    property Scansione: IJanuaField read GetScansione;
    function GetRegistro: IJanuaField;
    property Registro: IJanuaField read GetRegistro;
    function GetNotePerIlTecnico: IJanuaField;
    property NotePerIlTecnico: IJanuaField read GetNotePerIlTecnico;
    function GetSospeso: IJanuaField;
    property Sospeso: IJanuaField read GetSospeso;
    function GetDaEsportareSulWeb: IJanuaField;
    property DaEsportareSulWeb: IJanuaField read GetDaEsportareSulWeb;
    function GetResponsabile: IJanuaField;
    property Responsabile: IJanuaField read GetResponsabile;
    function GetEsportatoSuMobile: IJanuaField;
    property EsportatoSuMobile: IJanuaField read GetEsportatoSuMobile;
    function GetNoteDalTecnico: IJanuaField;
    property NoteDalTecnico: IJanuaField read GetNoteDalTecnico;
    function GetJsonDaMobile: IJanuaField;
    property JsonDaMobile: IJanuaField read GetJsonDaMobile;
    function GetPdfStatino: IJanuaField;
    property PdfStatino: IJanuaField read GetPdfStatino;
    function GetRegistroIsPdf: IJanuaField;
    property RegistroIsPdf: IJanuaField read GetRegistroIsPdf;
    function GetVerbaleProvaDinamica: IJanuaField;
    property VerbaleProvaDinamica: IJanuaField read GetVerbaleProvaDinamica;
    function GetVerbaleManichette: IJanuaField;
    property VerbaleManichette: IJanuaField read GetVerbaleManichette;
    function GetPreventivo: IJanuaField;
    property Preventivo: IJanuaField read GetPreventivo;
    function GetIgnoraEvidenziazione: IJanuaField;
    property IgnoraEvidenziazione: IJanuaField read GetIgnoraEvidenziazione;
    function GetAnnullatoDaTablet: IJanuaField;
    property AnnullatoDaTablet: IJanuaField read GetAnnullatoDaTablet;
    function GetMobilewarnNuovaAttrezzatura: IJanuaField;
    property MobilewarnNuovaAttrezzatura: IJanuaField read GetMobilewarnNuovaAttrezzatura;
    function GetMobilewarnOrdinariaRitirata: IJanuaField;
    property MobilewarnOrdinariaRitirata: IJanuaField read GetMobilewarnOrdinariaRitirata;
    function GetMobilewarnNOrdinControllata: IJanuaField;
    property MobilewarnNOrdinControllata: IJanuaField read GetMobilewarnNOrdinControllata;
    function GetMobilewarnSmaltimento: IJanuaField;
    property MobilewarnSmaltimento: IJanuaField read GetMobilewarnSmaltimento;
    function GetStatoLavorazione: IJanuaField;
    property StatoLavorazione: IJanuaField read GetStatoLavorazione;
    function GetDataChiusuraDaServer: IJanuaField;
    property DataChiusuraDaServer: IJanuaField read GetDataChiusuraDaServer;
    function GetChiusuraExt: IJanuaField;
    property ChiusuraExt: IJanuaField read GetChiusuraExt;
    function GetChiusuraStatino: IJanuaField;
    property ChiusuraStatino: IJanuaField read GetChiusuraStatino;
    function GetMobilewarnNonEseguiti: IJanuaField;
    property MobilewarnNonEseguiti: IJanuaField read GetMobilewarnNonEseguiti;
    function GetPresaInCarico: IJanuaField;
    property PresaInCarico: IJanuaField read GetPresaInCarico;
    function GetFornitura: IJanuaField;
    property Fornitura: IJanuaField read GetFornitura;
    function GetAppuntamentoData: IJanuaField;
    property AppuntamentoData: IJanuaField read GetAppuntamentoData;
    function GetAppuntamentoOra: IJanuaField;
    property AppuntamentoOra: IJanuaField read GetAppuntamentoOra;
    function GetStato: IJanuaField;
    property Stato: IJanuaField read GetStato;

  end;

implementation

end.
