unit JOrm.Documents.Heads.Custom.Intf;

interface

uses Janua.Orm.Intf;

type

  ICustomDocHead = interface(IJanuaRecord)
  ['{86B0D1B5-0AD5-448C-9AAC-C17219430CB9}']
    function GetId: IJanuaField;
    procedure SetId(const Value: IJanuaField);
    property Id: IJanuaField read GetId write SetId;
    function GetTypeId: IJanuaField;
    procedure SetTypeId(const Value: IJanuaField);
    property TypeId: IJanuaField read GetTypeId write SetTypeId;
    function GetInOut: IJanuaField;
    procedure SetInOut(const Value: IJanuaField);
    property InOut: IJanuaField read GetInOut write SetInOut;
    function GetDocDate: IJanuaField;
    procedure SetDocDate(const Value: IJanuaField);
    property DocDate: IJanuaField read GetDocDate write SetDocDate;
    function GetDocNumber: IJanuaField;
    procedure SetDocNumber(const Value: IJanuaField);
    property DocNumber: IJanuaField read GetDocNumber write SetDocNumber;
    function GetReason: IJanuaField;
    procedure SetReason(const Value: IJanuaField);
    property Reason: IJanuaField read GetReason write SetReason;
    function GetDestAddress: IJanuaField;
    procedure SetDestAddress(const Value: IJanuaField);
    property DestAddress: IJanuaField read GetDestAddress write SetDestAddress;
    function GetDestPostalCode: IJanuaField;
    procedure SetDestPostalCode(const Value: IJanuaField);
    property DestPostalCode: IJanuaField read GetDestPostalCode write SetDestPostalCode;
    function GetDestTown: IJanuaField;
    procedure SetDestTown(const Value: IJanuaField);
    property DestTown: IJanuaField read GetDestTown write SetDestTown;
    function GetDestStateProvince: IJanuaField;
    procedure SetDestStateProvince(const Value: IJanuaField);
    property DestStateProvince: IJanuaField read GetDestStateProvince write SetDestStateProvince;
    function GetDestCountryIso: IJanuaField;
    procedure SetDestCountryIso(const Value: IJanuaField);
    property DestCountryIso: IJanuaField read GetDestCountryIso write SetDestCountryIso;
    function GetDepartureDate: IJanuaField;
    procedure SetDepartureDate(const Value: IJanuaField);
    property DepartureDate: IJanuaField read GetDepartureDate write SetDepartureDate;
    function GetDeliveryMethos: IJanuaField;
    procedure SetDeliveryMethos(const Value: IJanuaField);
    property DeliveryMethos: IJanuaField read GetDeliveryMethos write SetDeliveryMethos;
    function GetGoodsDescription: IJanuaField;
    procedure SetGoodsDescription(const Value: IJanuaField);
    property GoodsDescription: IJanuaField read GetGoodsDescription write SetGoodsDescription;
    function GetPackagesNumber: IJanuaField;
    procedure SetPackagesNumber(const Value: IJanuaField);
    property PackagesNumber: IJanuaField read GetPackagesNumber write SetPackagesNumber;
    function GetTotalWeight: IJanuaField;
    procedure SetTotalWeight(const Value: IJanuaField);
    property TotalWeight: IJanuaField read GetTotalWeight write SetTotalWeight;
    function GetIncoterms: IJanuaField;
    procedure SetIncoterms(const Value: IJanuaField);
    property Incoterms: IJanuaField read GetIncoterms write SetIncoterms;
    function GetDeliveryCharges: IJanuaField;
    procedure SetDeliveryCharges(const Value: IJanuaField);
    property DeliveryCharges: IJanuaField read GetDeliveryCharges write SetDeliveryCharges;
    function GetDiscountRate: IJanuaField;
    procedure SetDiscountRate(const Value: IJanuaField);
    property DiscountRate: IJanuaField read GetDiscountRate write SetDiscountRate;
    function GetAnagraphId: IJanuaField;
    procedure SetAnagraphId(const Value: IJanuaField);
    property AnagraphId: IJanuaField read GetAnagraphId write SetAnagraphId;
    function GetCarrierId: IJanuaField;
    procedure SetCarrierId(const Value: IJanuaField);
    property CarrierId: IJanuaField read GetCarrierId write SetCarrierId;
    function GetDestStateProvinceId: IJanuaField;
    procedure SetDestStateProvinceId(const Value: IJanuaField);
    property DestStateProvinceId: IJanuaField read GetDestStateProvinceId write SetDestStateProvinceId;
    function GetDestRegionId: IJanuaField;
    procedure SetDestRegionId(const Value: IJanuaField);
    property DestRegionId: IJanuaField read GetDestRegionId write SetDestRegionId;
    function GetDestTownId: IJanuaField;
    procedure SetDestTownId(const Value: IJanuaField);
    property DestTownId: IJanuaField read GetDestTownId write SetDestTownId;
    function GetCurrencyId: IJanuaField;
    procedure SetCurrencyId(const Value: IJanuaField);
    property CurrencyId: IJanuaField read GetCurrencyId write SetCurrencyId;
    function GetPaymentTermsId: IJanuaField;
    procedure SetPaymentTermsId(const Value: IJanuaField);
    property PaymentTermsId: IJanuaField read GetPaymentTermsId write SetPaymentTermsId;
    function GetPaymentTermsDes: IJanuaField;
    procedure SetPaymentTermsDes(const Value: IJanuaField);
    property PaymentTermsDes: IJanuaField read GetPaymentTermsDes write SetPaymentTermsDes;
    function GetPackageDescription: IJanuaField;
    procedure SetPackageDescription(const Value: IJanuaField);
    property PackageDescription: IJanuaField read GetPackageDescription write SetPackageDescription;
    function GetPaymentTermCode: IJanuaField;
    procedure SetPaymentTermCode(const Value: IJanuaField);
    property PaymentTermCode: IJanuaField read GetPaymentTermCode write SetPaymentTermCode;
    function GetFolderId: IJanuaField;
    procedure SetFolderId(const Value: IJanuaField);
    property FolderId: IJanuaField read GetFolderId write SetFolderId;
    function GetDocState: IJanuaField;
    procedure SetDocState(const Value: IJanuaField);
    property DocState: IJanuaField read GetDocState write SetDocState;
    function GetHolderName: IJanuaField;
    procedure SetHolderName(const Value: IJanuaField);
    property HolderName: IJanuaField read GetHolderName write SetHolderName;
    function GetHolderId: IJanuaField;
    procedure SetHolderId(const Value: IJanuaField);
    property HolderId: IJanuaField read GetHolderId write SetHolderId;
    function GetHolderVatId: IJanuaField;
    procedure SetHolderVatId(const Value: IJanuaField);
    property HolderVatId: IJanuaField read GetHolderVatId write SetHolderVatId;
    function GetHolderAddress: IJanuaField;
    procedure SetHolderAddress(const Value: IJanuaField);
    property HolderAddress: IJanuaField read GetHolderAddress write SetHolderAddress;
    function GetHolderPostalCode: IJanuaField;
    procedure SetHolderPostalCode(const Value: IJanuaField);
    property HolderPostalCode: IJanuaField read GetHolderPostalCode write SetHolderPostalCode;
    function GetHolderTown: IJanuaField;
    procedure SetHolderTown(const Value: IJanuaField);
    property HolderTown: IJanuaField read GetHolderTown write SetHolderTown;
    function GetHolderStateProvince: IJanuaField;
    procedure SetHolderStateProvince(const Value: IJanuaField);
    property HolderStateProvince: IJanuaField read GetHolderStateProvince write SetHolderStateProvince;
    function GetHolderCountryIso: IJanuaField;
    procedure SetHolderCountryIso(const Value: IJanuaField);
    property HolderCountryIso: IJanuaField read GetHolderCountryIso write SetHolderCountryIso;
    function GetDeliveryRateExpense: IJanuaField;
    procedure SetDeliveryRateExpense(const Value: IJanuaField);
    property DeliveryRateExpense: IJanuaField read GetDeliveryRateExpense write SetDeliveryRateExpense;
    function GetHolderGroupId: IJanuaField;
    procedure SetHolderGroupId(const Value: IJanuaField);
    property HolderGroupId: IJanuaField read GetHolderGroupId write SetHolderGroupId;
    function GetAmount: IJanuaField;
    procedure SetAmount(const Value: IJanuaField);
    property Amount: IJanuaField read GetAmount write SetAmount;
    function GetNetAmount: IJanuaField;
    procedure SetNetAmount(const Value: IJanuaField);
    property NetAmount: IJanuaField read GetNetAmount write SetNetAmount;
    function GetFinancialYear: IJanuaField;
    procedure SetFinancialYear(const Value: IJanuaField);
    property FinancialYear: IJanuaField read GetFinancialYear write SetFinancialYear;
    function GetDocOriginId: IJanuaField;
    procedure SetDocOriginId(const Value: IJanuaField);
    property DocOriginId: IJanuaField read GetDocOriginId write SetDocOriginId;
    function GetDeliveryVatId: IJanuaField;
    procedure SetDeliveryVatId(const Value: IJanuaField);
    property DeliveryVatId: IJanuaField read GetDeliveryVatId write SetDeliveryVatId;
    function GetDeliveryVatRate: IJanuaField;
    procedure SetDeliveryVatRate(const Value: IJanuaField);
    property DeliveryVatRate: IJanuaField read GetDeliveryVatRate write SetDeliveryVatRate;
    function GetAccounted: IJanuaField;
    procedure SetAccounted(const Value: IJanuaField);
    property Accounted: IJanuaField read GetAccounted write SetAccounted;
    function GetInsertDate: IJanuaField;
    procedure SetInsertDate(const Value: IJanuaField);
    property InsertDate: IJanuaField read GetInsertDate write SetInsertDate;
    function GetUpdateDate: IJanuaField;
    procedure SetUpdateDate(const Value: IJanuaField);
    property UpdateDate: IJanuaField read GetUpdateDate write SetUpdateDate;
    function GetDeliveryDueDate: IJanuaField;
    procedure SetDeliveryDueDate(const Value: IJanuaField);
    property DeliveryDueDate: IJanuaField read GetDeliveryDueDate write SetDeliveryDueDate;
    function GetSent: IJanuaField;
    procedure SetSent(const Value: IJanuaField);
    property Sent: IJanuaField read GetSent write SetSent;
    function GetArrivalDate: IJanuaField;
    procedure SetArrivalDate(const Value: IJanuaField);
    property ArrivalDate: IJanuaField read GetArrivalDate write SetArrivalDate;
    function GetPaymentDueDate: IJanuaField;
    procedure SetPaymentDueDate(const Value: IJanuaField);
    property PaymentDueDate: IJanuaField read GetPaymentDueDate write SetPaymentDueDate;
    function GetDuties: IJanuaField;
    procedure SetDuties(const Value: IJanuaField);
    property Duties: IJanuaField read GetDuties write SetDuties;
    function GetPaid: IJanuaField;
    procedure SetPaid(const Value: IJanuaField);
    property Paid: IJanuaField read GetPaid write SetPaid;
    function GetDocFine: IJanuaField;
    procedure SetDocFine(const Value: IJanuaField);
    property DocFine: IJanuaField read GetDocFine write SetDocFine;
    function GetUserInsert: IJanuaField;
    procedure SetUserInsert(const Value: IJanuaField);
    property UserInsert: IJanuaField read GetUserInsert write SetUserInsert;
    function GetUserUpdate: IJanuaField;
    procedure SetUserUpdate(const Value: IJanuaField);
    property UserUpdate: IJanuaField read GetUserUpdate write SetUserUpdate;
    function GetDocYear: IJanuaField;
    procedure SetDocYear(const Value: IJanuaField);
    property DocYear: IJanuaField read GetDocYear write SetDocYear;
    function GetPoNumberId: IJanuaField;
    procedure SetPoNumberId(const Value: IJanuaField);
    property PoNumberId: IJanuaField read GetPoNumberId write SetPoNumberId;
    function GetPoNumber: IJanuaField;
    procedure SetPoNumber(const Value: IJanuaField);
    property PoNumber: IJanuaField read GetPoNumber write SetPoNumber;
    function GetPrinted: IJanuaField;
    procedure SetPrinted(const Value: IJanuaField);
    property Printed: IJanuaField read GetPrinted write SetPrinted;
    function GetContactName: IJanuaField;
    procedure SetContactName(const Value: IJanuaField);
    property ContactName: IJanuaField read GetContactName write SetContactName;
    function GetContactEmail: IJanuaField;
    procedure SetContactEmail(const Value: IJanuaField);
    property ContactEmail: IJanuaField read GetContactEmail write SetContactEmail;
    function GetContactPhone: IJanuaField;
    procedure SetContactPhone(const Value: IJanuaField);
    property ContactPhone: IJanuaField read GetContactPhone write SetContactPhone;
    function GetOfficeId: IJanuaField;
    procedure SetOfficeId(const Value: IJanuaField);
    property OfficeId: IJanuaField read GetOfficeId write SetOfficeId;
    function GetWarehouseLocationId: IJanuaField;
    procedure SetWarehouseLocationId(const Value: IJanuaField);
    property WarehouseLocationId: IJanuaField read GetWarehouseLocationId write SetWarehouseLocationId;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
    function GetNotes1: IJanuaField;
    procedure SetNotes1(const Value: IJanuaField);
    property Notes1: IJanuaField read GetNotes1 write SetNotes1;
    function GetNotes2: IJanuaField;
    procedure SetNotes2(const Value: IJanuaField);
    property Notes2: IJanuaField read GetNotes2 write SetNotes2;
    function GetNotes3: IJanuaField;
    procedure SetNotes3(const Value: IJanuaField);
    property Notes3: IJanuaField read GetNotes3 write SetNotes3;
    function GetDbSchemaId: IJanuaField;
    procedure SetDbSchemaId(const Value: IJanuaField);
    property DbSchemaId: IJanuaField read GetDbSchemaId write SetDbSchemaId;
    function GetPurchaseOrderNumber: IJanuaField;
    procedure SetPurchaseOrderNumber(const Value: IJanuaField);
    property PurchaseOrderNumber: IJanuaField read GetPurchaseOrderNumber write SetPurchaseOrderNumber;
    function GetCustomField1: IJanuaField;
    procedure SetCustomField1(const Value: IJanuaField);
    property CustomField1: IJanuaField read GetCustomField1 write SetCustomField1;
    function GetCustomField2: IJanuaField;
    procedure SetCustomField2(const Value: IJanuaField);
    property CustomField2: IJanuaField read GetCustomField2 write SetCustomField2;
    function GetCustomField3: IJanuaField;
    procedure SetCustomField3(const Value: IJanuaField);
    property CustomField3: IJanuaField read GetCustomField3 write SetCustomField3;
    function GetCustomInt1: IJanuaField;
    procedure SetCustomInt1(const Value: IJanuaField);
    property CustomInt1: IJanuaField read GetCustomInt1 write SetCustomInt1;
    function GetCustomInt2: IJanuaField;
    procedure SetCustomInt2(const Value: IJanuaField);
    property CustomInt2: IJanuaField read GetCustomInt2 write SetCustomInt2;
    function GetCustomInt3: IJanuaField;
    procedure SetCustomInt3(const Value: IJanuaField);
    property CustomInt3: IJanuaField read GetCustomInt3 write SetCustomInt3;
    function GetDocRefCode: IJanuaField;
    procedure SetDocRefCode(const Value: IJanuaField);
    property DocRefCode: IJanuaField read GetDocRefCode write SetDocRefCode;
    function GetCarrierExpenses: IJanuaField;
    procedure SetCarrierExpenses(const Value: IJanuaField);
    property CarrierExpenses: IJanuaField read GetCarrierExpenses write SetCarrierExpenses;
    function GetRegistryCode: IJanuaField;
    procedure SetRegistryCode(const Value: IJanuaField);
    property RegistryCode: IJanuaField read GetRegistryCode write SetRegistryCode;
    function GetCarrierTrackingNumber: IJanuaField;
    procedure SetCarrierTrackingNumber(const Value: IJanuaField);
    property CarrierTrackingNumber: IJanuaField read GetCarrierTrackingNumber write SetCarrierTrackingNumber;
    function GetCarrierExpensesCurrencyId: IJanuaField;
    procedure SetCarrierExpensesCurrencyId(const Value: IJanuaField);
    property CarrierExpensesCurrencyId: IJanuaField read GetCarrierExpensesCurrencyId
      write SetCarrierExpensesCurrencyId;
    function GetSearchIndex: IJanuaField;
    procedure SetSearchIndex(const Value: IJanuaField);
    property SearchIndex: IJanuaField read GetSearchIndex write SetSearchIndex;
    function GetDestName: IJanuaField;
    procedure SetDestName(const Value: IJanuaField);
    property DestName: IJanuaField read GetDestName write SetDestName;
    function GetCarrierName: IJanuaField;
    procedure SetCarrierName(const Value: IJanuaField);
    property CarrierName: IJanuaField read GetCarrierName write SetCarrierName;
    function GetLocationName: IJanuaField;
    procedure SetLocationName(const Value: IJanuaField);
    property LocationName: IJanuaField read GetLocationName write SetLocationName;
    function GetGoodsTypeId: IJanuaField;
    procedure SetGoodsTypeId(const Value: IJanuaField);
    property GoodsTypeId: IJanuaField read GetGoodsTypeId write SetGoodsTypeId;
    function GetImportexport: IJanuaField;
    procedure SetImportexport(const Value: IJanuaField);
    property Importexport: IJanuaField read GetImportexport write SetImportexport;
    function GetCarrierInvoiceNumber: IJanuaField;
    procedure SetCarrierInvoiceNumber(const Value: IJanuaField);
    property CarrierInvoiceNumber: IJanuaField read GetCarrierInvoiceNumber write SetCarrierInvoiceNumber;
    function GetCarrierInvoiceDate: IJanuaField;
    procedure SetCarrierInvoiceDate(const Value: IJanuaField);
    property CarrierInvoiceDate: IJanuaField read GetCarrierInvoiceDate write SetCarrierInvoiceDate;

    function GetVesselDepartmentId: IJanuaField;
    procedure SetVesselDepartmentId(const Value: IJanuaField);
    property VesselDepartmentId: IJanuaField read GetVesselDepartmentId write SetVesselDepartmentId;

    // vessel_id
    function GetVesselID: IJanuaField;
    procedure SetVesselID(const Value: IJanuaField);
    property VesselID: IJanuaField read GetVesselID write SetVesselID;

    // vessel_name
    function GetVesselName: IJanuaField;
    procedure SetVesselName(const Value: IJanuaField);
    property VesselName: IJanuaField read GetVesselName write SetVesselName;

    // vessel_code
    function GetVesselCode: IJanuaField;
    procedure SetVesselCode(const Value: IJanuaField);
    property VesselCode: IJanuaField read GetVesselCode write SetVesselCode;

    // location_code
    function GetLocationCode: IJanuaField;
    procedure SetLocationCode(const Value: IJanuaField);
    property LocationCode: IJanuaField read GetLocationCode write SetLocationCode;

    // shipment_des
    function GetShipmentDes: IJanuaField;
    procedure SetShipmentDes(const Value: IJanuaField);
    property ShipmentDes: IJanuaField read GetShipmentDes write SetShipmentDes;

  end;

  ICustomDocHeads = interface(IJanuaRecordSet)
    ['{73353147-9EA3-4608-BAC4-B0EE3882E254}']
    function GetId: IJanuaField;
    procedure SetId(const Value: IJanuaField);
    property Id: IJanuaField read GetId write SetId;
    function GetTypeId: IJanuaField;
    procedure SetTypeId(const Value: IJanuaField);
    property TypeId: IJanuaField read GetTypeId write SetTypeId;
    function GetInOut: IJanuaField;
    procedure SetInOut(const Value: IJanuaField);
    property InOut: IJanuaField read GetInOut write SetInOut;
    function GetDocDate: IJanuaField;
    procedure SetDocDate(const Value: IJanuaField);
    property DocDate: IJanuaField read GetDocDate write SetDocDate;
    function GetDocNumber: IJanuaField;
    procedure SetDocNumber(const Value: IJanuaField);
    property DocNumber: IJanuaField read GetDocNumber write SetDocNumber;
    function GetReason: IJanuaField;
    procedure SetReason(const Value: IJanuaField);
    property Reason: IJanuaField read GetReason write SetReason;
    function GetDestAddress: IJanuaField;
    procedure SetDestAddress(const Value: IJanuaField);
    property DestAddress: IJanuaField read GetDestAddress write SetDestAddress;
    function GetDestPostalCode: IJanuaField;
    procedure SetDestPostalCode(const Value: IJanuaField);
    property DestPostalCode: IJanuaField read GetDestPostalCode write SetDestPostalCode;
    function GetDestTown: IJanuaField;
    procedure SetDestTown(const Value: IJanuaField);
    property DestTown: IJanuaField read GetDestTown write SetDestTown;
    function GetDestStateProvince: IJanuaField;
    procedure SetDestStateProvince(const Value: IJanuaField);
    property DestStateProvince: IJanuaField read GetDestStateProvince write SetDestStateProvince;
    function GetDestCountryIso: IJanuaField;
    procedure SetDestCountryIso(const Value: IJanuaField);
    property DestCountryIso: IJanuaField read GetDestCountryIso write SetDestCountryIso;
    function GetDepartureDate: IJanuaField;
    procedure SetDepartureDate(const Value: IJanuaField);
    property DepartureDate: IJanuaField read GetDepartureDate write SetDepartureDate;
    function GetDeliveryMethos: IJanuaField;
    procedure SetDeliveryMethos(const Value: IJanuaField);
    property DeliveryMethos: IJanuaField read GetDeliveryMethos write SetDeliveryMethos;
    function GetGoodsDescription: IJanuaField;
    procedure SetGoodsDescription(const Value: IJanuaField);
    property GoodsDescription: IJanuaField read GetGoodsDescription write SetGoodsDescription;
    function GetPackagesNumber: IJanuaField;
    procedure SetPackagesNumber(const Value: IJanuaField);
    property PackagesNumber: IJanuaField read GetPackagesNumber write SetPackagesNumber;
    function GetTotalWeight: IJanuaField;
    procedure SetTotalWeight(const Value: IJanuaField);
    property TotalWeight: IJanuaField read GetTotalWeight write SetTotalWeight;
    function GetIncoterms: IJanuaField;
    procedure SetIncoterms(const Value: IJanuaField);
    property Incoterms: IJanuaField read GetIncoterms write SetIncoterms;
    function GetDeliveryCharges: IJanuaField;
    procedure SetDeliveryCharges(const Value: IJanuaField);
    property DeliveryCharges: IJanuaField read GetDeliveryCharges write SetDeliveryCharges;
    function GetDiscountRate: IJanuaField;
    procedure SetDiscountRate(const Value: IJanuaField);
    property DiscountRate: IJanuaField read GetDiscountRate write SetDiscountRate;
    function GetAnagraphId: IJanuaField;
    procedure SetAnagraphId(const Value: IJanuaField);
    property AnagraphId: IJanuaField read GetAnagraphId write SetAnagraphId;
    function GetCarrierId: IJanuaField;
    procedure SetCarrierId(const Value: IJanuaField);
    property CarrierId: IJanuaField read GetCarrierId write SetCarrierId;
    function GetDestStateProvinceId: IJanuaField;
    procedure SetDestStateProvinceId(const Value: IJanuaField);
    property DestStateProvinceId: IJanuaField read GetDestStateProvinceId write SetDestStateProvinceId;
    function GetDestRegionId: IJanuaField;
    procedure SetDestRegionId(const Value: IJanuaField);
    property DestRegionId: IJanuaField read GetDestRegionId write SetDestRegionId;
    function GetDestTownId: IJanuaField;
    procedure SetDestTownId(const Value: IJanuaField);
    property DestTownId: IJanuaField read GetDestTownId write SetDestTownId;
    function GetCurrencyId: IJanuaField;
    procedure SetCurrencyId(const Value: IJanuaField);
    property CurrencyId: IJanuaField read GetCurrencyId write SetCurrencyId;
    function GetPaymentTermsId: IJanuaField;
    procedure SetPaymentTermsId(const Value: IJanuaField);
    property PaymentTermsId: IJanuaField read GetPaymentTermsId write SetPaymentTermsId;
    function GetPaymentTermsDes: IJanuaField;
    procedure SetPaymentTermsDes(const Value: IJanuaField);
    property PaymentTermsDes: IJanuaField read GetPaymentTermsDes write SetPaymentTermsDes;
    function GetPackageDescription: IJanuaField;
    procedure SetPackageDescription(const Value: IJanuaField);
    property PackageDescription: IJanuaField read GetPackageDescription write SetPackageDescription;
    function GetPaymentTermCode: IJanuaField;
    procedure SetPaymentTermCode(const Value: IJanuaField);
    property PaymentTermCode: IJanuaField read GetPaymentTermCode write SetPaymentTermCode;
    function GetFolderId: IJanuaField;
    procedure SetFolderId(const Value: IJanuaField);
    property FolderId: IJanuaField read GetFolderId write SetFolderId;
    function GetDocState: IJanuaField;
    procedure SetDocState(const Value: IJanuaField);
    property DocState: IJanuaField read GetDocState write SetDocState;
    function GetHolderName: IJanuaField;
    procedure SetHolderName(const Value: IJanuaField);
    property HolderName: IJanuaField read GetHolderName write SetHolderName;
    function GetHolderId: IJanuaField;
    procedure SetHolderId(const Value: IJanuaField);
    property HolderId: IJanuaField read GetHolderId write SetHolderId;
    function GetHolderVatId: IJanuaField;
    procedure SetHolderVatId(const Value: IJanuaField);
    property HolderVatId: IJanuaField read GetHolderVatId write SetHolderVatId;
    function GetHolderAddress: IJanuaField;
    procedure SetHolderAddress(const Value: IJanuaField);
    property HolderAddress: IJanuaField read GetHolderAddress write SetHolderAddress;
    function GetHolderPostalCode: IJanuaField;
    procedure SetHolderPostalCode(const Value: IJanuaField);
    property HolderPostalCode: IJanuaField read GetHolderPostalCode write SetHolderPostalCode;
    function GetHolderTown: IJanuaField;
    procedure SetHolderTown(const Value: IJanuaField);
    property HolderTown: IJanuaField read GetHolderTown write SetHolderTown;
    function GetHolderStateProvince: IJanuaField;
    procedure SetHolderStateProvince(const Value: IJanuaField);
    property HolderStateProvince: IJanuaField read GetHolderStateProvince write SetHolderStateProvince;
    function GetHolderCountryIso: IJanuaField;
    procedure SetHolderCountryIso(const Value: IJanuaField);
    property HolderCountryIso: IJanuaField read GetHolderCountryIso write SetHolderCountryIso;
    function GetDeliveryRateExpense: IJanuaField;
    procedure SetDeliveryRateExpense(const Value: IJanuaField);
    property DeliveryRateExpense: IJanuaField read GetDeliveryRateExpense write SetDeliveryRateExpense;
    function GetHolderGroupId: IJanuaField;
    procedure SetHolderGroupId(const Value: IJanuaField);
    property HolderGroupId: IJanuaField read GetHolderGroupId write SetHolderGroupId;
    function GetAmount: IJanuaField;
    procedure SetAmount(const Value: IJanuaField);
    property Amount: IJanuaField read GetAmount write SetAmount;
    function GetNetAmount: IJanuaField;
    procedure SetNetAmount(const Value: IJanuaField);
    property NetAmount: IJanuaField read GetNetAmount write SetNetAmount;
    function GetFinancialYear: IJanuaField;
    procedure SetFinancialYear(const Value: IJanuaField);
    property FinancialYear: IJanuaField read GetFinancialYear write SetFinancialYear;
    function GetDocOriginId: IJanuaField;
    procedure SetDocOriginId(const Value: IJanuaField);
    property DocOriginId: IJanuaField read GetDocOriginId write SetDocOriginId;
    function GetDeliveryVatId: IJanuaField;
    procedure SetDeliveryVatId(const Value: IJanuaField);
    property DeliveryVatId: IJanuaField read GetDeliveryVatId write SetDeliveryVatId;
    function GetDeliveryVatRate: IJanuaField;
    procedure SetDeliveryVatRate(const Value: IJanuaField);
    property DeliveryVatRate: IJanuaField read GetDeliveryVatRate write SetDeliveryVatRate;
    function GetAccounted: IJanuaField;
    procedure SetAccounted(const Value: IJanuaField);
    property Accounted: IJanuaField read GetAccounted write SetAccounted;
    function GetInsertDate: IJanuaField;
    procedure SetInsertDate(const Value: IJanuaField);
    property InsertDate: IJanuaField read GetInsertDate write SetInsertDate;
    function GetUpdateDate: IJanuaField;
    procedure SetUpdateDate(const Value: IJanuaField);
    property UpdateDate: IJanuaField read GetUpdateDate write SetUpdateDate;
    function GetDeliveryDueDate: IJanuaField;
    procedure SetDeliveryDueDate(const Value: IJanuaField);
    property DeliveryDueDate: IJanuaField read GetDeliveryDueDate write SetDeliveryDueDate;
    function GetSent: IJanuaField;
    procedure SetSent(const Value: IJanuaField);
    property Sent: IJanuaField read GetSent write SetSent;
    function GetArrivalDate: IJanuaField;
    procedure SetArrivalDate(const Value: IJanuaField);
    property ArrivalDate: IJanuaField read GetArrivalDate write SetArrivalDate;
    function GetPaymentDueDate: IJanuaField;
    procedure SetPaymentDueDate(const Value: IJanuaField);
    property PaymentDueDate: IJanuaField read GetPaymentDueDate write SetPaymentDueDate;
    function GetDuties: IJanuaField;
    procedure SetDuties(const Value: IJanuaField);
    property Duties: IJanuaField read GetDuties write SetDuties;
    function GetPaid: IJanuaField;
    procedure SetPaid(const Value: IJanuaField);
    property Paid: IJanuaField read GetPaid write SetPaid;
    function GetDocFine: IJanuaField;
    procedure SetDocFine(const Value: IJanuaField);
    property DocFine: IJanuaField read GetDocFine write SetDocFine;
    function GetUserInsert: IJanuaField;
    procedure SetUserInsert(const Value: IJanuaField);
    property UserInsert: IJanuaField read GetUserInsert write SetUserInsert;
    function GetUserUpdate: IJanuaField;
    procedure SetUserUpdate(const Value: IJanuaField);
    property UserUpdate: IJanuaField read GetUserUpdate write SetUserUpdate;
    function GetDocYear: IJanuaField;
    procedure SetDocYear(const Value: IJanuaField);
    property DocYear: IJanuaField read GetDocYear write SetDocYear;
    function GetPoNumberId: IJanuaField;
    procedure SetPoNumberId(const Value: IJanuaField);
    property PoNumberId: IJanuaField read GetPoNumberId write SetPoNumberId;
    function GetPoNumber: IJanuaField;
    procedure SetPoNumber(const Value: IJanuaField);
    property PoNumber: IJanuaField read GetPoNumber write SetPoNumber;
    function GetPrinted: IJanuaField;
    procedure SetPrinted(const Value: IJanuaField);
    property Printed: IJanuaField read GetPrinted write SetPrinted;
    function GetContactName: IJanuaField;
    procedure SetContactName(const Value: IJanuaField);
    property ContactName: IJanuaField read GetContactName write SetContactName;
    function GetContactEmail: IJanuaField;
    procedure SetContactEmail(const Value: IJanuaField);
    property ContactEmail: IJanuaField read GetContactEmail write SetContactEmail;
    function GetContactPhone: IJanuaField;
    procedure SetContactPhone(const Value: IJanuaField);
    property ContactPhone: IJanuaField read GetContactPhone write SetContactPhone;
    function GetOfficeId: IJanuaField;
    procedure SetOfficeId(const Value: IJanuaField);
    property OfficeId: IJanuaField read GetOfficeId write SetOfficeId;
    function GetWarehouseLocationId: IJanuaField;
    procedure SetWarehouseLocationId(const Value: IJanuaField);
    property WarehouseLocationId: IJanuaField read GetWarehouseLocationId write SetWarehouseLocationId;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
    function GetNotes1: IJanuaField;
    procedure SetNotes1(const Value: IJanuaField);
    property Notes1: IJanuaField read GetNotes1 write SetNotes1;
    function GetNotes2: IJanuaField;
    procedure SetNotes2(const Value: IJanuaField);
    property Notes2: IJanuaField read GetNotes2 write SetNotes2;
    function GetNotes3: IJanuaField;
    procedure SetNotes3(const Value: IJanuaField);
    property Notes3: IJanuaField read GetNotes3 write SetNotes3;
    function GetDbSchemaId: IJanuaField;
    procedure SetDbSchemaId(const Value: IJanuaField);
    property DbSchemaId: IJanuaField read GetDbSchemaId write SetDbSchemaId;
    function GetPurchaseOrderNumber: IJanuaField;
    procedure SetPurchaseOrderNumber(const Value: IJanuaField);
    property PurchaseOrderNumber: IJanuaField read GetPurchaseOrderNumber write SetPurchaseOrderNumber;
    function GetCustomField1: IJanuaField;
    procedure SetCustomField1(const Value: IJanuaField);
    property CustomField1: IJanuaField read GetCustomField1 write SetCustomField1;
    function GetCustomField2: IJanuaField;
    procedure SetCustomField2(const Value: IJanuaField);
    property CustomField2: IJanuaField read GetCustomField2 write SetCustomField2;
    function GetCustomField3: IJanuaField;
    procedure SetCustomField3(const Value: IJanuaField);
    property CustomField3: IJanuaField read GetCustomField3 write SetCustomField3;
    function GetCustomInt1: IJanuaField;
    procedure SetCustomInt1(const Value: IJanuaField);
    property CustomInt1: IJanuaField read GetCustomInt1 write SetCustomInt1;
    function GetCustomInt2: IJanuaField;
    procedure SetCustomInt2(const Value: IJanuaField);
    property CustomInt2: IJanuaField read GetCustomInt2 write SetCustomInt2;
    function GetCustomInt3: IJanuaField;
    procedure SetCustomInt3(const Value: IJanuaField);
    property CustomInt3: IJanuaField read GetCustomInt3 write SetCustomInt3;
    function GetDocRefCode: IJanuaField;
    procedure SetDocRefCode(const Value: IJanuaField);
    property DocRefCode: IJanuaField read GetDocRefCode write SetDocRefCode;
    function GetCarrierExpenses: IJanuaField;
    procedure SetCarrierExpenses(const Value: IJanuaField);
    property CarrierExpenses: IJanuaField read GetCarrierExpenses write SetCarrierExpenses;
    function GetRegistryCode: IJanuaField;
    procedure SetRegistryCode(const Value: IJanuaField);
    property RegistryCode: IJanuaField read GetRegistryCode write SetRegistryCode;
    function GetCarrierTrackingNumber: IJanuaField;
    procedure SetCarrierTrackingNumber(const Value: IJanuaField);
    property CarrierTrackingNumber: IJanuaField read GetCarrierTrackingNumber write SetCarrierTrackingNumber;
    function GetCarrierExpensesCurrencyId: IJanuaField;
    procedure SetCarrierExpensesCurrencyId(const Value: IJanuaField);
    property CarrierExpensesCurrencyId: IJanuaField read GetCarrierExpensesCurrencyId
      write SetCarrierExpensesCurrencyId;
    function GetSearchIndex: IJanuaField;
    procedure SetSearchIndex(const Value: IJanuaField);
    property SearchIndex: IJanuaField read GetSearchIndex write SetSearchIndex;
    function GetDestName: IJanuaField;
    procedure SetDestName(const Value: IJanuaField);
    property DestName: IJanuaField read GetDestName write SetDestName;
    function GetCarrierName: IJanuaField;
    procedure SetCarrierName(const Value: IJanuaField);
    property CarrierName: IJanuaField read GetCarrierName write SetCarrierName;
    function GetLocationName: IJanuaField;
    procedure SetLocationName(const Value: IJanuaField);
    property LocationName: IJanuaField read GetLocationName write SetLocationName;
    function GetGoodsTypeId: IJanuaField;
    procedure SetGoodsTypeId(const Value: IJanuaField);
    property GoodsTypeId: IJanuaField read GetGoodsTypeId write SetGoodsTypeId;
    function GetImportexport: IJanuaField;
    procedure SetImportexport(const Value: IJanuaField);
    property Importexport: IJanuaField read GetImportexport write SetImportexport;
    function GetCarrierInvoiceNumber: IJanuaField;
    procedure SetCarrierInvoiceNumber(const Value: IJanuaField);
    property CarrierInvoiceNumber: IJanuaField read GetCarrierInvoiceNumber write SetCarrierInvoiceNumber;
    function GetCarrierInvoiceDate: IJanuaField;
    procedure SetCarrierInvoiceDate(const Value: IJanuaField);
    property CarrierInvoiceDate: IJanuaField read GetCarrierInvoiceDate write SetCarrierInvoiceDate;


    function GetVesselDepartmentId: IJanuaField;
    procedure SetVesselDepartmentId(const Value: IJanuaField);
    property VesselDepartmentId: IJanuaField read GetVesselDepartmentId write SetVesselDepartmentId;

    // shipment_des
    function GetShipmentDes: IJanuaField;
    procedure SetShipmentDes(const Value: IJanuaField);
    property ShipmentDes: IJanuaField read GetShipmentDes write SetShipmentDes;
  end;

implementation

end.
