unit JOrm.Logistic.AWBs.Custom.Intf;

interface

uses Janua.Orm.Intf, JOrm.Logistic.AWBRows.Intf, JOrm.Anagraph.Intf;

type

  ILogisticCustomAWB = interface(IJanuaRecord)
    ['{6E3EBD39-A009-4965-81F7-66A4F8B46CCA}']
    function GetYear: IJanuaField;
    procedure SetYear(const Value: IJanuaField);
    property Year: IJanuaField read GetYear write SetYear;
    function GetOfficeId: IJanuaField;
    procedure SetOfficeId(const Value: IJanuaField);
    property OfficeId: IJanuaField read GetOfficeId write SetOfficeId;
    function GetId: IJanuaField;
    procedure SetId(const Value: IJanuaField);
    property Id: IJanuaField read GetId write SetId;
    function GetCode: IJanuaField;
    procedure SetCode(const Value: IJanuaField);
    property Code: IJanuaField read GetCode write SetCode;
    function GetDbSchemaId: IJanuaField;
    procedure SetDbSchemaId(const Value: IJanuaField);
    property DbSchemaId: IJanuaField read GetDbSchemaId write SetDbSchemaId;
    function GetField1a: IJanuaField;
    procedure SetField1a(const Value: IJanuaField);
    property Field1a: IJanuaField read GetField1a write SetField1a;
    function GetField1b: IJanuaField;
    procedure SetField1b(const Value: IJanuaField);
    property Field1b: IJanuaField read GetField1b write SetField1b;
    function GetField1c: IJanuaField;
    procedure SetField1c(const Value: IJanuaField);
    property Field1c: IJanuaField read GetField1c write SetField1c;
    function GetCin: IJanuaField;
    procedure SetCin(const Value: IJanuaField);
    property Cin: IJanuaField read GetCin write SetCin;
    function GetField2: IJanuaField;
    procedure SetField2(const Value: IJanuaField);
    property Field2: IJanuaField read GetField2 write SetField2;
    function GetField21: IJanuaField;
    procedure SetField21(const Value: IJanuaField);
    property Field21: IJanuaField read GetField21 write SetField21;
    function GetField22: IJanuaField;
    procedure SetField22(const Value: IJanuaField);
    property Field22: IJanuaField read GetField22 write SetField22;
    function GetField23: IJanuaField;
    procedure SetField23(const Value: IJanuaField);
    property Field23: IJanuaField read GetField23 write SetField23;
    function GetField3: IJanuaField;
    procedure SetField3(const Value: IJanuaField);
    property Field3: IJanuaField read GetField3 write SetField3;
    function GetField31: IJanuaField;
    procedure SetField31(const Value: IJanuaField);
    property Field31: IJanuaField read GetField31 write SetField31;
    function GetField32: IJanuaField;
    procedure SetField32(const Value: IJanuaField);
    property Field32: IJanuaField read GetField32 write SetField32;
    function GetField33: IJanuaField;
    procedure SetField33(const Value: IJanuaField);
    property Field33: IJanuaField read GetField33 write SetField33;
    function GetField4a: IJanuaField;
    procedure SetField4a(const Value: IJanuaField);
    property Field4a: IJanuaField read GetField4a write SetField4a;
    function GetField4b: IJanuaField;
    procedure SetField4b(const Value: IJanuaField);
    property Field4b: IJanuaField read GetField4b write SetField4b;
    function GetField4c: IJanuaField;
    procedure SetField4c(const Value: IJanuaField);
    property Field4c: IJanuaField read GetField4c write SetField4c;
    function GetField4c2: IJanuaField;
    procedure SetField4c2(const Value: IJanuaField);
    property Field4c2: IJanuaField read GetField4c2 write SetField4c2;
    function GetField4c3: IJanuaField;
    procedure SetField4c3(const Value: IJanuaField);
    property Field4c3: IJanuaField read GetField4c3 write SetField4c3;
    function GetField5: IJanuaField;
    procedure SetField5(const Value: IJanuaField);
    property Field5: IJanuaField read GetField5 write SetField5;
    function GetField6: IJanuaField;
    procedure SetField6(const Value: IJanuaField);
    property Field6: IJanuaField read GetField6 write SetField6;
    function GetField7: IJanuaField;
    procedure SetField7(const Value: IJanuaField);
    property Field7: IJanuaField read GetField7 write SetField7;
    function GetField8: IJanuaField;
    procedure SetField8(const Value: IJanuaField);
    property Field8: IJanuaField read GetField8 write SetField8;
    function GetField8a: IJanuaField;
    procedure SetField8a(const Value: IJanuaField);
    property Field8a: IJanuaField read GetField8a write SetField8a;
    function GetField8b: IJanuaField;
    procedure SetField8b(const Value: IJanuaField);
    property Field8b: IJanuaField read GetField8b write SetField8b;
    function GetField8c: IJanuaField;
    procedure SetField8c(const Value: IJanuaField);
    property Field8c: IJanuaField read GetField8c write SetField8c;
    function GetField8d: IJanuaField;
    procedure SetField8d(const Value: IJanuaField);
    property Field8d: IJanuaField read GetField8d write SetField8d;
    function GetField8c1: IJanuaField;
    procedure SetField8c1(const Value: IJanuaField);
    property Field8c1: IJanuaField read GetField8c1 write SetField8c1;
    function GetField8d1: IJanuaField;
    procedure SetField8d1(const Value: IJanuaField);
    property Field8d1: IJanuaField read GetField8d1 write SetField8d1;
    function GetField8e: IJanuaField;
    procedure SetField8e(const Value: IJanuaField);
    property Field8e: IJanuaField read GetField8e write SetField8e;
    function GetField8f: IJanuaField;
    procedure SetField8f(const Value: IJanuaField);
    property Field8f: IJanuaField read GetField8f write SetField8f;
    function GetField8f1: IJanuaField;
    procedure SetField8f1(const Value: IJanuaField);
    property Field8f1: IJanuaField read GetField8f1 write SetField8f1;
    function GetField9: IJanuaField;
    procedure SetField9(const Value: IJanuaField);
    property Field9: IJanuaField read GetField9 write SetField9;
    function GetField10: IJanuaField;
    procedure SetField10(const Value: IJanuaField);
    property Field10: IJanuaField read GetField10 write SetField10;
    function GetField11: IJanuaField;
    procedure SetField11(const Value: IJanuaField);
    property Field11: IJanuaField read GetField11 write SetField11;
    function GetField12: IJanuaField;
    procedure SetField12(const Value: IJanuaField);
    property Field12: IJanuaField read GetField12 write SetField12;
    function GetField13: IJanuaField;
    procedure SetField13(const Value: IJanuaField);
    property Field13: IJanuaField read GetField13 write SetField13;
    function GetField14: IJanuaField;
    procedure SetField14(const Value: IJanuaField);
    property Field14: IJanuaField read GetField14 write SetField14;
    function GetField15: IJanuaField;
    procedure SetField15(const Value: IJanuaField);
    property Field15: IJanuaField read GetField15 write SetField15;
    function GetField16: IJanuaField;
    procedure SetField16(const Value: IJanuaField);
    property Field16: IJanuaField read GetField16 write SetField16;
    function GetField17: IJanuaField;
    procedure SetField17(const Value: IJanuaField);
    property Field17: IJanuaField read GetField17 write SetField17;
    function GetField28a: IJanuaField;
    procedure SetField28a(const Value: IJanuaField);
    property Field28a: IJanuaField read GetField28a write SetField28a;
    function GetField28b: IJanuaField;
    procedure SetField28b(const Value: IJanuaField);
    property Field28b: IJanuaField read GetField28b write SetField28b;
    function GetField29a: IJanuaField;
    procedure SetField29a(const Value: IJanuaField);
    property Field29a: IJanuaField read GetField29a write SetField29a;
    function GetField29b: IJanuaField;
    procedure SetField29b(const Value: IJanuaField);
    property Field29b: IJanuaField read GetField29b write SetField29b;
    function GetField30a: IJanuaField;
    procedure SetField30a(const Value: IJanuaField);
    property Field30a: IJanuaField read GetField30a write SetField30a;
    function GetField30b: IJanuaField;
    procedure SetField30b(const Value: IJanuaField);
    property Field30b: IJanuaField read GetField30b write SetField30b;
    function GetField31a: IJanuaField;
    procedure SetField31a(const Value: IJanuaField);
    property Field31a: IJanuaField read GetField31a write SetField31a;
    function GetField31b: IJanuaField;
    procedure SetField31b(const Value: IJanuaField);
    property Field31b: IJanuaField read GetField31b write SetField31b;
    function GetField32a: IJanuaField;
    procedure SetField32a(const Value: IJanuaField);
    property Field32a: IJanuaField read GetField32a write SetField32a;
    function GetField32b: IJanuaField;
    procedure SetField32b(const Value: IJanuaField);
    property Field32b: IJanuaField read GetField32b write SetField32b;
    function GetField33a: IJanuaField;
    procedure SetField33a(const Value: IJanuaField);
    property Field33a: IJanuaField read GetField33a write SetField33a;
    function GetField33b: IJanuaField;
    procedure SetField33b(const Value: IJanuaField);
    property Field33b: IJanuaField read GetField33b write SetField33b;
    function GetField34: IJanuaField;
    procedure SetField34(const Value: IJanuaField);
    property Field34: IJanuaField read GetField34 write SetField34;
    function GetField35: IJanuaField;
    procedure SetField35(const Value: IJanuaField);
    property Field35: IJanuaField read GetField35 write SetField35;
    function GetField36: IJanuaField;
    procedure SetField36(const Value: IJanuaField);
    property Field36: IJanuaField read GetField36 write SetField36;
    function GetField37: IJanuaField;
    procedure SetField37(const Value: IJanuaField);
    property Field37: IJanuaField read GetField37 write SetField37;
    function GetField38: IJanuaField;
    procedure SetField38(const Value: IJanuaField);
    property Field38: IJanuaField read GetField38 write SetField38;
    function GetHi1: IJanuaField;
    procedure SetHi1(const Value: IJanuaField);
    property Hi1: IJanuaField read GetHi1 write SetHi1;
    function GetHi2: IJanuaField;
    procedure SetHi2(const Value: IJanuaField);
    property Hi2: IJanuaField read GetHi2 write SetHi2;
    function GetHi3: IJanuaField;
    procedure SetHi3(const Value: IJanuaField);
    property Hi3: IJanuaField read GetHi3 write SetHi3;
    function GetCodother1: IJanuaField;
    procedure SetCodother1(const Value: IJanuaField);
    property Codother1: IJanuaField read GetCodother1 write SetCodother1;
    function GetCodother2: IJanuaField;
    procedure SetCodother2(const Value: IJanuaField);
    property Codother2: IJanuaField read GetCodother2 write SetCodother2;
    function GetCodother3: IJanuaField;
    procedure SetCodother3(const Value: IJanuaField);
    property Codother3: IJanuaField read GetCodother3 write SetCodother3;
    function GetCodother4: IJanuaField;
    procedure SetCodother4(const Value: IJanuaField);
    property Codother4: IJanuaField read GetCodother4 write SetCodother4;
    function GetCodother5: IJanuaField;
    procedure SetCodother5(const Value: IJanuaField);
    property Codother5: IJanuaField read GetCodother5 write SetCodother5;
    function GetCodother6: IJanuaField;
    procedure SetCodother6(const Value: IJanuaField);
    property Codother6: IJanuaField read GetCodother6 write SetCodother6;
    function GetCodother7: IJanuaField;
    procedure SetCodother7(const Value: IJanuaField);
    property Codother7: IJanuaField read GetCodother7 write SetCodother7;
    function GetCodother8: IJanuaField;
    procedure SetCodother8(const Value: IJanuaField);
    property Codother8: IJanuaField read GetCodother8 write SetCodother8;
    function GetCodother9: IJanuaField;
    procedure SetCodother9(const Value: IJanuaField);
    property Codother9: IJanuaField read GetCodother9 write SetCodother9;
    function GetAmountother9: IJanuaField;
    procedure SetAmountother9(const Value: IJanuaField);
    property Amountother9: IJanuaField read GetAmountother9 write SetAmountother9;
    function GetAmountother8: IJanuaField;
    procedure SetAmountother8(const Value: IJanuaField);
    property Amountother8: IJanuaField read GetAmountother8 write SetAmountother8;
    function GetAmountother7: IJanuaField;
    procedure SetAmountother7(const Value: IJanuaField);
    property Amountother7: IJanuaField read GetAmountother7 write SetAmountother7;
    function GetAmountother6: IJanuaField;
    procedure SetAmountother6(const Value: IJanuaField);
    property Amountother6: IJanuaField read GetAmountother6 write SetAmountother6;
    function GetAmountother5: IJanuaField;
    procedure SetAmountother5(const Value: IJanuaField);
    property Amountother5: IJanuaField read GetAmountother5 write SetAmountother5;
    function GetAmountother4: IJanuaField;
    procedure SetAmountother4(const Value: IJanuaField);
    property Amountother4: IJanuaField read GetAmountother4 write SetAmountother4;
    function GetAmountother3: IJanuaField;
    procedure SetAmountother3(const Value: IJanuaField);
    property Amountother3: IJanuaField read GetAmountother3 write SetAmountother3;
    function GetAmountother2: IJanuaField;
    procedure SetAmountother2(const Value: IJanuaField);
    property Amountother2: IJanuaField read GetAmountother2 write SetAmountother2;
    function GetAmountother1: IJanuaField;
    procedure SetAmountother1(const Value: IJanuaField);
    property Amountother1: IJanuaField read GetAmountother1 write SetAmountother1;
    function GetFieldhead: IJanuaField;
    procedure SetFieldhead(const Value: IJanuaField);
    property Fieldhead: IJanuaField read GetFieldhead write SetFieldhead;
    function GetPartialmaster: IJanuaField;
    procedure SetPartialmaster(const Value: IJanuaField);
    property Partialmaster: IJanuaField read GetPartialmaster write SetPartialmaster;
    function GetPartialmasteryear: IJanuaField;
    procedure SetPartialmasteryear(const Value: IJanuaField);
    property Partialmasteryear: IJanuaField read GetPartialmasteryear write SetPartialmasteryear;
    function GetCurrencyId: IJanuaField;
    procedure SetCurrencyId(const Value: IJanuaField);
    property CurrencyId: IJanuaField read GetCurrencyId write SetCurrencyId;
    function GetAwbTypeId: IJanuaField;
    procedure SetAwbTypeId(const Value: IJanuaField);
    property AwbTypeId: IJanuaField read GetAwbTypeId write SetAwbTypeId;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
    function GetNetamount: IJanuaField;
    procedure SetNetamount(const Value: IJanuaField);
    property Netamount: IJanuaField read GetNetamount write SetNetamount;
    function GetProgressive: IJanuaField;
    procedure SetProgressive(const Value: IJanuaField);
    property Progressive: IJanuaField read GetProgressive write SetProgressive;
    function GetMawbcosts: IJanuaField;
    procedure SetMawbcosts(const Value: IJanuaField);
    property Mawbcosts: IJanuaField read GetMawbcosts write SetMawbcosts;
    function GetMawbothcosts: IJanuaField;
    procedure SetMawbothcosts(const Value: IJanuaField);
    property Mawbothcosts: IJanuaField read GetMawbothcosts write SetMawbothcosts;
    function GetTaxableweight: IJanuaField;
    procedure SetTaxableweight(const Value: IJanuaField);
    property Taxableweight: IJanuaField read GetTaxableweight write SetTaxableweight;
    function GetMasterdate: IJanuaField;
    procedure SetMasterdate(const Value: IJanuaField);
    property Masterdate: IJanuaField read GetMasterdate write SetMasterdate;
    function GetEstimateflight: IJanuaField;
    procedure SetEstimateflight(const Value: IJanuaField);
    property Estimateflight: IJanuaField read GetEstimateflight write SetEstimateflight;
    function GetEffectiveflight: IJanuaField;
    procedure SetEffectiveflight(const Value: IJanuaField);
    property Effectiveflight: IJanuaField read GetEffectiveflight write SetEffectiveflight;
    function GetEtdestimate: IJanuaField;
    procedure SetEtdestimate(const Value: IJanuaField);
    property Etdestimate: IJanuaField read GetEtdestimate write SetEtdestimate;
    function GetEtdeffective: IJanuaField;
    procedure SetEtdeffective(const Value: IJanuaField);
    property Etdeffective: IJanuaField read GetEtdeffective write SetEtdeffective;
    function GetEtaestimate: IJanuaField;
    procedure SetEtaestimate(const Value: IJanuaField);
    property Etaestimate: IJanuaField read GetEtaestimate write SetEtaestimate;
    function GetEtaeffective: IJanuaField;
    procedure SetEtaeffective(const Value: IJanuaField);
    property Etaeffective: IJanuaField read GetEtaeffective write SetEtaeffective;
    function GetTransportcost: IJanuaField;
    procedure SetTransportcost(const Value: IJanuaField);
    property Transportcost: IJanuaField read GetTransportcost write SetTransportcost;
    function GetContainerseals: IJanuaField;
    procedure SetContainerseals(const Value: IJanuaField);
    property Containerseals: IJanuaField read GetContainerseals write SetContainerseals;
    function GetMasternotes: IJanuaField;
    procedure SetMasternotes(const Value: IJanuaField);
    property Masternotes: IJanuaField read GetMasternotes write SetMasternotes;
    function GetAwbType: IJanuaField;
    procedure SetAwbType(const Value: IJanuaField);
    property AwbType: IJanuaField read GetAwbType write SetAwbType;
    function GetOrderId: IJanuaField;
    procedure SetOrderId(const Value: IJanuaField);
    property OrderId: IJanuaField read GetOrderId write SetOrderId;
    function GetCustomsDocType: IJanuaField;
    procedure SetCustomsDocType(const Value: IJanuaField);
    property CustomsDocType: IJanuaField read GetCustomsDocType write SetCustomsDocType;
    function GetPalletcost: IJanuaField;
    procedure SetPalletcost(const Value: IJanuaField);
    property Palletcost: IJanuaField read GetPalletcost write SetPalletcost;
    function GetYearNumber: IJanuaField;
    procedure SetYearNumber(const Value: IJanuaField);
    property YearNumber: IJanuaField read GetYearNumber write SetYearNumber;
    function GetField19a: IJanuaField;
    procedure SetField19a(const Value: IJanuaField);
    property Field19a: IJanuaField read GetField19a write SetField19a;
    function GetBranchlog: IJanuaField;
    procedure SetBranchlog(const Value: IJanuaField);
    property Branchlog: IJanuaField read GetBranchlog write SetBranchlog;
    function GetDeleted: IJanuaField;
    procedure SetDeleted(const Value: IJanuaField);
    property Deleted: IJanuaField read GetDeleted write SetDeleted;
    function GetCarrierId: IJanuaField;
    procedure SetCarrierId(const Value: IJanuaField);
    property CarrierId: IJanuaField read GetCarrierId write SetCarrierId;
    function GetCarrierName: IJanuaField;
    procedure SetCarrierName(const Value: IJanuaField);
    property CarrierName: IJanuaField read GetCarrierName write SetCarrierName;
    function GetCarrierCode: IJanuaField;
    procedure SetCarrierCode(const Value: IJanuaField);
    property CarrierCode: IJanuaField read GetCarrierCode write SetCarrierCode;
    function GetShipperId: IJanuaField;
    procedure SetShipperId(const Value: IJanuaField);
    property ShipperId: IJanuaField read GetShipperId write SetShipperId;
    function GetShipperCode: IJanuaField;
    procedure SetShipperCode(const Value: IJanuaField);
    property ShipperCode: IJanuaField read GetShipperCode write SetShipperCode;
    function GetShipperName: IJanuaField;
    procedure SetShipperName(const Value: IJanuaField);
    property ShipperName: IJanuaField read GetShipperName write SetShipperName;
    function GetConsigneeId: IJanuaField;
    procedure SetConsigneeId(const Value: IJanuaField);
    property ConsigneeId: IJanuaField read GetConsigneeId write SetConsigneeId;
    function GetConsigneeName: IJanuaField;
    procedure SetConsigneeName(const Value: IJanuaField);
    property ConsigneeName: IJanuaField read GetConsigneeName write SetConsigneeName;
    function GetConsigneeCode: IJanuaField;
    procedure SetConsigneeCode(const Value: IJanuaField);
    property ConsigneeCode: IJanuaField read GetConsigneeCode write SetConsigneeCode;
    function GetIataAgentId: IJanuaField;
    procedure SetIataAgentId(const Value: IJanuaField);
    property IataAgentId: IJanuaField read GetIataAgentId write SetIataAgentId;
    function GetIataAgentCode: IJanuaField;
    procedure SetIataAgentCode(const Value: IJanuaField);
    property IataAgentCode: IJanuaField read GetIataAgentCode write SetIataAgentCode;
    function GetIataAgentName: IJanuaField;
    procedure SetIataAgentName(const Value: IJanuaField);
    property IataAgentName: IJanuaField read GetIataAgentName write SetIataAgentName;
  end;

  ILogisticCustomAWBs = interface(IJanuaRecordSet)
    ['{E9E5E5D3-A87B-4A1C-AEBD-56B105E78F80}']
    function GetYear: IJanuaField;
    procedure SetYear(const Value: IJanuaField);
    property Year: IJanuaField read GetYear write SetYear;
    function GetOfficeId: IJanuaField;
    procedure SetOfficeId(const Value: IJanuaField);
    property OfficeId: IJanuaField read GetOfficeId write SetOfficeId;
    function GetId: IJanuaField;
    procedure SetId(const Value: IJanuaField);
    property Id: IJanuaField read GetId write SetId;
    function GetCode: IJanuaField;
    procedure SetCode(const Value: IJanuaField);
    property Code: IJanuaField read GetCode write SetCode;
    function GetDbSchemaId: IJanuaField;
    procedure SetDbSchemaId(const Value: IJanuaField);
    property DbSchemaId: IJanuaField read GetDbSchemaId write SetDbSchemaId;
    function GetField1a: IJanuaField;
    procedure SetField1a(const Value: IJanuaField);
    property Field1a: IJanuaField read GetField1a write SetField1a;
    function GetField1b: IJanuaField;
    procedure SetField1b(const Value: IJanuaField);
    property Field1b: IJanuaField read GetField1b write SetField1b;
    function GetField1c: IJanuaField;
    procedure SetField1c(const Value: IJanuaField);
    property Field1c: IJanuaField read GetField1c write SetField1c;
    function GetCin: IJanuaField;
    procedure SetCin(const Value: IJanuaField);
    property Cin: IJanuaField read GetCin write SetCin;
    function GetField2: IJanuaField;
    procedure SetField2(const Value: IJanuaField);
    property Field2: IJanuaField read GetField2 write SetField2;
    function GetField21: IJanuaField;
    procedure SetField21(const Value: IJanuaField);
    property Field21: IJanuaField read GetField21 write SetField21;
    function GetField22: IJanuaField;
    procedure SetField22(const Value: IJanuaField);
    property Field22: IJanuaField read GetField22 write SetField22;
    function GetField23: IJanuaField;
    procedure SetField23(const Value: IJanuaField);
    property Field23: IJanuaField read GetField23 write SetField23;
    function GetField3: IJanuaField;
    procedure SetField3(const Value: IJanuaField);
    property Field3: IJanuaField read GetField3 write SetField3;
    function GetField31: IJanuaField;
    procedure SetField31(const Value: IJanuaField);
    property Field31: IJanuaField read GetField31 write SetField31;
    function GetField32: IJanuaField;
    procedure SetField32(const Value: IJanuaField);
    property Field32: IJanuaField read GetField32 write SetField32;
    function GetField33: IJanuaField;
    procedure SetField33(const Value: IJanuaField);
    property Field33: IJanuaField read GetField33 write SetField33;
    function GetField4a: IJanuaField;
    procedure SetField4a(const Value: IJanuaField);
    property Field4a: IJanuaField read GetField4a write SetField4a;
    function GetField4b: IJanuaField;
    procedure SetField4b(const Value: IJanuaField);
    property Field4b: IJanuaField read GetField4b write SetField4b;
    function GetField4c: IJanuaField;
    procedure SetField4c(const Value: IJanuaField);
    property Field4c: IJanuaField read GetField4c write SetField4c;
    function GetField4c2: IJanuaField;
    procedure SetField4c2(const Value: IJanuaField);
    property Field4c2: IJanuaField read GetField4c2 write SetField4c2;
    function GetField4c3: IJanuaField;
    procedure SetField4c3(const Value: IJanuaField);
    property Field4c3: IJanuaField read GetField4c3 write SetField4c3;
    function GetField5: IJanuaField;
    procedure SetField5(const Value: IJanuaField);
    property Field5: IJanuaField read GetField5 write SetField5;
    function GetField6: IJanuaField;
    procedure SetField6(const Value: IJanuaField);
    property Field6: IJanuaField read GetField6 write SetField6;
    function GetField7: IJanuaField;
    procedure SetField7(const Value: IJanuaField);
    property Field7: IJanuaField read GetField7 write SetField7;
    function GetField8: IJanuaField;
    procedure SetField8(const Value: IJanuaField);
    property Field8: IJanuaField read GetField8 write SetField8;
    function GetField8a: IJanuaField;
    procedure SetField8a(const Value: IJanuaField);
    property Field8a: IJanuaField read GetField8a write SetField8a;
    function GetField8b: IJanuaField;
    procedure SetField8b(const Value: IJanuaField);
    property Field8b: IJanuaField read GetField8b write SetField8b;
    function GetField8c: IJanuaField;
    procedure SetField8c(const Value: IJanuaField);
    property Field8c: IJanuaField read GetField8c write SetField8c;
    function GetField8d: IJanuaField;
    procedure SetField8d(const Value: IJanuaField);
    property Field8d: IJanuaField read GetField8d write SetField8d;
    function GetField8c1: IJanuaField;
    procedure SetField8c1(const Value: IJanuaField);
    property Field8c1: IJanuaField read GetField8c1 write SetField8c1;
    function GetField8d1: IJanuaField;
    procedure SetField8d1(const Value: IJanuaField);
    property Field8d1: IJanuaField read GetField8d1 write SetField8d1;
    function GetField8e: IJanuaField;
    procedure SetField8e(const Value: IJanuaField);
    property Field8e: IJanuaField read GetField8e write SetField8e;
    function GetField8f: IJanuaField;
    procedure SetField8f(const Value: IJanuaField);
    property Field8f: IJanuaField read GetField8f write SetField8f;
    function GetField8f1: IJanuaField;
    procedure SetField8f1(const Value: IJanuaField);
    property Field8f1: IJanuaField read GetField8f1 write SetField8f1;
    function GetField9: IJanuaField;
    procedure SetField9(const Value: IJanuaField);
    property Field9: IJanuaField read GetField9 write SetField9;
    function GetField10: IJanuaField;
    procedure SetField10(const Value: IJanuaField);
    property Field10: IJanuaField read GetField10 write SetField10;
    function GetField11: IJanuaField;
    procedure SetField11(const Value: IJanuaField);
    property Field11: IJanuaField read GetField11 write SetField11;
    function GetField12: IJanuaField;
    procedure SetField12(const Value: IJanuaField);
    property Field12: IJanuaField read GetField12 write SetField12;
    function GetField13: IJanuaField;
    procedure SetField13(const Value: IJanuaField);
    property Field13: IJanuaField read GetField13 write SetField13;
    function GetField14: IJanuaField;
    procedure SetField14(const Value: IJanuaField);
    property Field14: IJanuaField read GetField14 write SetField14;
    function GetField15: IJanuaField;
    procedure SetField15(const Value: IJanuaField);
    property Field15: IJanuaField read GetField15 write SetField15;
    function GetField16: IJanuaField;
    procedure SetField16(const Value: IJanuaField);
    property Field16: IJanuaField read GetField16 write SetField16;
    function GetField17: IJanuaField;
    procedure SetField17(const Value: IJanuaField);
    property Field17: IJanuaField read GetField17 write SetField17;
    function GetField28a: IJanuaField;
    procedure SetField28a(const Value: IJanuaField);
    property Field28a: IJanuaField read GetField28a write SetField28a;
    function GetField28b: IJanuaField;
    procedure SetField28b(const Value: IJanuaField);
    property Field28b: IJanuaField read GetField28b write SetField28b;
    function GetField29a: IJanuaField;
    procedure SetField29a(const Value: IJanuaField);
    property Field29a: IJanuaField read GetField29a write SetField29a;
    function GetField29b: IJanuaField;
    procedure SetField29b(const Value: IJanuaField);
    property Field29b: IJanuaField read GetField29b write SetField29b;
    function GetField30a: IJanuaField;
    procedure SetField30a(const Value: IJanuaField);
    property Field30a: IJanuaField read GetField30a write SetField30a;
    function GetField30b: IJanuaField;
    procedure SetField30b(const Value: IJanuaField);
    property Field30b: IJanuaField read GetField30b write SetField30b;
    function GetField31a: IJanuaField;
    procedure SetField31a(const Value: IJanuaField);
    property Field31a: IJanuaField read GetField31a write SetField31a;
    function GetField31b: IJanuaField;
    procedure SetField31b(const Value: IJanuaField);
    property Field31b: IJanuaField read GetField31b write SetField31b;
    function GetField32a: IJanuaField;
    procedure SetField32a(const Value: IJanuaField);
    property Field32a: IJanuaField read GetField32a write SetField32a;
    function GetField32b: IJanuaField;
    procedure SetField32b(const Value: IJanuaField);
    property Field32b: IJanuaField read GetField32b write SetField32b;
    function GetField33a: IJanuaField;
    procedure SetField33a(const Value: IJanuaField);
    property Field33a: IJanuaField read GetField33a write SetField33a;
    function GetField33b: IJanuaField;
    procedure SetField33b(const Value: IJanuaField);
    property Field33b: IJanuaField read GetField33b write SetField33b;
    function GetField34: IJanuaField;
    procedure SetField34(const Value: IJanuaField);
    property Field34: IJanuaField read GetField34 write SetField34;
    function GetField35: IJanuaField;
    procedure SetField35(const Value: IJanuaField);
    property Field35: IJanuaField read GetField35 write SetField35;
    function GetField36: IJanuaField;
    procedure SetField36(const Value: IJanuaField);
    property Field36: IJanuaField read GetField36 write SetField36;
    function GetField37: IJanuaField;
    procedure SetField37(const Value: IJanuaField);
    property Field37: IJanuaField read GetField37 write SetField37;
    function GetField38: IJanuaField;
    procedure SetField38(const Value: IJanuaField);
    property Field38: IJanuaField read GetField38 write SetField38;
    function GetHi1: IJanuaField;
    procedure SetHi1(const Value: IJanuaField);
    property Hi1: IJanuaField read GetHi1 write SetHi1;
    function GetHi2: IJanuaField;
    procedure SetHi2(const Value: IJanuaField);
    property Hi2: IJanuaField read GetHi2 write SetHi2;
    function GetHi3: IJanuaField;
    procedure SetHi3(const Value: IJanuaField);
    property Hi3: IJanuaField read GetHi3 write SetHi3;
    function GetCodother1: IJanuaField;
    procedure SetCodother1(const Value: IJanuaField);
    property Codother1: IJanuaField read GetCodother1 write SetCodother1;
    function GetCodother2: IJanuaField;
    procedure SetCodother2(const Value: IJanuaField);
    property Codother2: IJanuaField read GetCodother2 write SetCodother2;
    function GetCodother3: IJanuaField;
    procedure SetCodother3(const Value: IJanuaField);
    property Codother3: IJanuaField read GetCodother3 write SetCodother3;
    function GetCodother4: IJanuaField;
    procedure SetCodother4(const Value: IJanuaField);
    property Codother4: IJanuaField read GetCodother4 write SetCodother4;
    function GetCodother5: IJanuaField;
    procedure SetCodother5(const Value: IJanuaField);
    property Codother5: IJanuaField read GetCodother5 write SetCodother5;
    function GetCodother6: IJanuaField;
    procedure SetCodother6(const Value: IJanuaField);
    property Codother6: IJanuaField read GetCodother6 write SetCodother6;
    function GetCodother7: IJanuaField;
    procedure SetCodother7(const Value: IJanuaField);
    property Codother7: IJanuaField read GetCodother7 write SetCodother7;
    function GetCodother8: IJanuaField;
    procedure SetCodother8(const Value: IJanuaField);
    property Codother8: IJanuaField read GetCodother8 write SetCodother8;
    function GetCodother9: IJanuaField;
    procedure SetCodother9(const Value: IJanuaField);
    property Codother9: IJanuaField read GetCodother9 write SetCodother9;
    function GetAmountother9: IJanuaField;
    procedure SetAmountother9(const Value: IJanuaField);
    property Amountother9: IJanuaField read GetAmountother9 write SetAmountother9;
    function GetAmountother8: IJanuaField;
    procedure SetAmountother8(const Value: IJanuaField);
    property Amountother8: IJanuaField read GetAmountother8 write SetAmountother8;
    function GetAmountother7: IJanuaField;
    procedure SetAmountother7(const Value: IJanuaField);
    property Amountother7: IJanuaField read GetAmountother7 write SetAmountother7;
    function GetAmountother6: IJanuaField;
    procedure SetAmountother6(const Value: IJanuaField);
    property Amountother6: IJanuaField read GetAmountother6 write SetAmountother6;
    function GetAmountother5: IJanuaField;
    procedure SetAmountother5(const Value: IJanuaField);
    property Amountother5: IJanuaField read GetAmountother5 write SetAmountother5;
    function GetAmountother4: IJanuaField;
    procedure SetAmountother4(const Value: IJanuaField);
    property Amountother4: IJanuaField read GetAmountother4 write SetAmountother4;
    function GetAmountother3: IJanuaField;
    procedure SetAmountother3(const Value: IJanuaField);
    property Amountother3: IJanuaField read GetAmountother3 write SetAmountother3;
    function GetAmountother2: IJanuaField;
    procedure SetAmountother2(const Value: IJanuaField);
    property Amountother2: IJanuaField read GetAmountother2 write SetAmountother2;
    function GetAmountother1: IJanuaField;
    procedure SetAmountother1(const Value: IJanuaField);
    property Amountother1: IJanuaField read GetAmountother1 write SetAmountother1;
    function GetFieldhead: IJanuaField;
    procedure SetFieldhead(const Value: IJanuaField);
    property Fieldhead: IJanuaField read GetFieldhead write SetFieldhead;
    function GetPartialmaster: IJanuaField;
    procedure SetPartialmaster(const Value: IJanuaField);
    property Partialmaster: IJanuaField read GetPartialmaster write SetPartialmaster;
    function GetPartialmasteryear: IJanuaField;
    procedure SetPartialmasteryear(const Value: IJanuaField);
    property Partialmasteryear: IJanuaField read GetPartialmasteryear write SetPartialmasteryear;
    function GetCurrencyId: IJanuaField;
    procedure SetCurrencyId(const Value: IJanuaField);
    property CurrencyId: IJanuaField read GetCurrencyId write SetCurrencyId;
    function GetAwbTypeId: IJanuaField;
    procedure SetAwbTypeId(const Value: IJanuaField);
    property AwbTypeId: IJanuaField read GetAwbTypeId write SetAwbTypeId;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
    function GetNetamount: IJanuaField;
    procedure SetNetamount(const Value: IJanuaField);
    property Netamount: IJanuaField read GetNetamount write SetNetamount;
    function GetProgressive: IJanuaField;
    procedure SetProgressive(const Value: IJanuaField);
    property Progressive: IJanuaField read GetProgressive write SetProgressive;
    function GetMawbcosts: IJanuaField;
    procedure SetMawbcosts(const Value: IJanuaField);
    property Mawbcosts: IJanuaField read GetMawbcosts write SetMawbcosts;
    function GetMawbothcosts: IJanuaField;
    procedure SetMawbothcosts(const Value: IJanuaField);
    property Mawbothcosts: IJanuaField read GetMawbothcosts write SetMawbothcosts;
    function GetTaxableweight: IJanuaField;
    procedure SetTaxableweight(const Value: IJanuaField);
    property Taxableweight: IJanuaField read GetTaxableweight write SetTaxableweight;
    function GetMasterdate: IJanuaField;
    procedure SetMasterdate(const Value: IJanuaField);
    property Masterdate: IJanuaField read GetMasterdate write SetMasterdate;
    function GetEstimateflight: IJanuaField;
    procedure SetEstimateflight(const Value: IJanuaField);
    property Estimateflight: IJanuaField read GetEstimateflight write SetEstimateflight;
    function GetEffectiveflight: IJanuaField;
    procedure SetEffectiveflight(const Value: IJanuaField);
    property Effectiveflight: IJanuaField read GetEffectiveflight write SetEffectiveflight;
    function GetEtdestimate: IJanuaField;
    procedure SetEtdestimate(const Value: IJanuaField);
    property Etdestimate: IJanuaField read GetEtdestimate write SetEtdestimate;
    function GetEtdeffective: IJanuaField;
    procedure SetEtdeffective(const Value: IJanuaField);
    property Etdeffective: IJanuaField read GetEtdeffective write SetEtdeffective;
    function GetEtaestimate: IJanuaField;
    procedure SetEtaestimate(const Value: IJanuaField);
    property Etaestimate: IJanuaField read GetEtaestimate write SetEtaestimate;
    function GetEtaeffective: IJanuaField;
    procedure SetEtaeffective(const Value: IJanuaField);
    property Etaeffective: IJanuaField read GetEtaeffective write SetEtaeffective;
    function GetTransportcost: IJanuaField;
    procedure SetTransportcost(const Value: IJanuaField);
    property Transportcost: IJanuaField read GetTransportcost write SetTransportcost;
    function GetContainerseals: IJanuaField;
    procedure SetContainerseals(const Value: IJanuaField);
    property Containerseals: IJanuaField read GetContainerseals write SetContainerseals;
    function GetMasternotes: IJanuaField;
    procedure SetMasternotes(const Value: IJanuaField);
    property Masternotes: IJanuaField read GetMasternotes write SetMasternotes;
    function GetAwbType: IJanuaField;
    procedure SetAwbType(const Value: IJanuaField);
    property AwbType: IJanuaField read GetAwbType write SetAwbType;
    function GetOrderId: IJanuaField;
    procedure SetOrderId(const Value: IJanuaField);
    property OrderId: IJanuaField read GetOrderId write SetOrderId;
    function GetCustomsDocType: IJanuaField;
    procedure SetCustomsDocType(const Value: IJanuaField);
    property CustomsDocType: IJanuaField read GetCustomsDocType write SetCustomsDocType;
    function GetPalletcost: IJanuaField;
    procedure SetPalletcost(const Value: IJanuaField);
    property Palletcost: IJanuaField read GetPalletcost write SetPalletcost;
    function GetYearNumber: IJanuaField;
    procedure SetYearNumber(const Value: IJanuaField);
    property YearNumber: IJanuaField read GetYearNumber write SetYearNumber;
    function GetField19a: IJanuaField;
    procedure SetField19a(const Value: IJanuaField);
    property Field19a: IJanuaField read GetField19a write SetField19a;
    function GetBranchlog: IJanuaField;
    procedure SetBranchlog(const Value: IJanuaField);
    property Branchlog: IJanuaField read GetBranchlog write SetBranchlog;
    function GetDeleted: IJanuaField;
    procedure SetDeleted(const Value: IJanuaField);
    property Deleted: IJanuaField read GetDeleted write SetDeleted;
    function GetCarrierId: IJanuaField;
    procedure SetCarrierId(const Value: IJanuaField);
    property CarrierId: IJanuaField read GetCarrierId write SetCarrierId;
    function GetCarrierName: IJanuaField;
    procedure SetCarrierName(const Value: IJanuaField);
    property CarrierName: IJanuaField read GetCarrierName write SetCarrierName;
    function GetCarrierCode: IJanuaField;
    procedure SetCarrierCode(const Value: IJanuaField);
    property CarrierCode: IJanuaField read GetCarrierCode write SetCarrierCode;
    function GetShipperId: IJanuaField;
    procedure SetShipperId(const Value: IJanuaField);
    property ShipperId: IJanuaField read GetShipperId write SetShipperId;
    function GetShipperCode: IJanuaField;
    procedure SetShipperCode(const Value: IJanuaField);
    property ShipperCode: IJanuaField read GetShipperCode write SetShipperCode;
    function GetShipperName: IJanuaField;
    procedure SetShipperName(const Value: IJanuaField);
    property ShipperName: IJanuaField read GetShipperName write SetShipperName;
    function GetConsigneeId: IJanuaField;
    procedure SetConsigneeId(const Value: IJanuaField);
    property ConsigneeId: IJanuaField read GetConsigneeId write SetConsigneeId;
    function GetConsigneeName: IJanuaField;
    procedure SetConsigneeName(const Value: IJanuaField);
    property ConsigneeName: IJanuaField read GetConsigneeName write SetConsigneeName;
    function GetConsigneeCode: IJanuaField;
    procedure SetConsigneeCode(const Value: IJanuaField);
    property ConsigneeCode: IJanuaField read GetConsigneeCode write SetConsigneeCode;
    function GetIataAgentId: IJanuaField;
    procedure SetIataAgentId(const Value: IJanuaField);
    property IataAgentId: IJanuaField read GetIataAgentId write SetIataAgentId;
    function GetIataAgentCode: IJanuaField;
    procedure SetIataAgentCode(const Value: IJanuaField);
    property IataAgentCode: IJanuaField read GetIataAgentCode write SetIataAgentCode;
    function GetIataAgentName: IJanuaField;
    procedure SetIataAgentName(const Value: IJanuaField);
    property IataAgentName: IJanuaField read GetIataAgentName write SetIataAgentName;
  end;

implementation

end.
