unit JOrm.Logistic.ShipmentsView.Custom.Intf;

interface

uses Janua.Orm.Intf;

type

  ICustomShipmentView = interface(IJanuaRecord)
    ['{9B30A74A-17A5-4051-9D8B-020E366A5597}']
    function GetId: IJanuaField;
    procedure SetId(const Value: IJanuaField);
    property Id: IJanuaField read GetId write SetId;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
    function GetCreationDate: IJanuaField;
    procedure SetCreationDate(const Value: IJanuaField);
    property CreationDate: IJanuaField read GetCreationDate write SetCreationDate;
    function GetPickupDate: IJanuaField;
    procedure SetPickupDate(const Value: IJanuaField);
    property PickupDate: IJanuaField read GetPickupDate write SetPickupDate;
    function GetDeliveryDate: IJanuaField;
    procedure SetDeliveryDate(const Value: IJanuaField);
    property DeliveryDate: IJanuaField read GetDeliveryDate write SetDeliveryDate;
    function GetOfficeId: IJanuaField;
    procedure SetOfficeId(const Value: IJanuaField);
    property OfficeId: IJanuaField read GetOfficeId write SetOfficeId;
    function GetWorkflowUid: IJanuaField;
    procedure SetWorkflowUid(const Value: IJanuaField);
    property WorkflowUid: IJanuaField read GetWorkflowUid write SetWorkflowUid;
    function GetAgentId: IJanuaField;
    procedure SetAgentId(const Value: IJanuaField);
    property AgentId: IJanuaField read GetAgentId write SetAgentId;
    function GetShipperId: IJanuaField;
    procedure SetShipperId(const Value: IJanuaField);
    property ShipperId: IJanuaField read GetShipperId write SetShipperId;
    function GetShipperAddress: IJanuaField;
    procedure SetShipperAddress(const Value: IJanuaField);
    property ShipperAddress: IJanuaField read GetShipperAddress write SetShipperAddress;
    function GetPickupAddress: IJanuaField;
    procedure SetPickupAddress(const Value: IJanuaField);
    property PickupAddress: IJanuaField read GetPickupAddress write SetPickupAddress;
    function GetYear: IJanuaField;
    procedure SetYear(const Value: IJanuaField);
    property Year: IJanuaField read GetYear write SetYear;
    function GetGroupageNumber: IJanuaField;
    procedure SetGroupageNumber(const Value: IJanuaField);
    property GroupageNumber: IJanuaField read GetGroupageNumber write SetGroupageNumber;
    function GetExportTypeId: IJanuaField;
    procedure SetExportTypeId(const Value: IJanuaField);
    property ExportTypeId: IJanuaField read GetExportTypeId write SetExportTypeId;
    function GetFullcontainer: IJanuaField;
    procedure SetFullcontainer(const Value: IJanuaField);
    property Fullcontainer: IJanuaField read GetFullcontainer write SetFullcontainer;
    function GetVesselId: IJanuaField;
    procedure SetVesselId(const Value: IJanuaField);
    property VesselId: IJanuaField read GetVesselId write SetVesselId;
    function GetWorkCode: IJanuaField;
    procedure SetWorkCode(const Value: IJanuaField);
    property WorkCode: IJanuaField read GetWorkCode write SetWorkCode;
    function GetTravelIdentificationCode: IJanuaField;
    procedure SetTravelIdentificationCode(const Value: IJanuaField);
    property TravelIdentificationCode: IJanuaField read GetTravelIdentificationCode
      write SetTravelIdentificationCode;
    function GetCarrierId: IJanuaField;
    procedure SetCarrierId(const Value: IJanuaField);
    property CarrierId: IJanuaField read GetCarrierId write SetCarrierId;
    function GetCarrierCode: IJanuaField;
    procedure SetCarrierCode(const Value: IJanuaField);
    property CarrierCode: IJanuaField read GetCarrierCode write SetCarrierCode;
    function GetWorkflowId: IJanuaField;
    procedure SetWorkflowId(const Value: IJanuaField);
    property WorkflowId: IJanuaField read GetWorkflowId write SetWorkflowId;
    function GetPolId: IJanuaField;
    procedure SetPolId(const Value: IJanuaField);
    property PolId: IJanuaField read GetPolId write SetPolId;
    function GetPolCode: IJanuaField;
    procedure SetPolCode(const Value: IJanuaField);
    property PolCode: IJanuaField read GetPolCode write SetPolCode;
    function GetPolName: IJanuaField;
    procedure SetPolName(const Value: IJanuaField);
    property PolName: IJanuaField read GetPolName write SetPolName;
    function GetPodId: IJanuaField;
    procedure SetPodId(const Value: IJanuaField);
    property PodId: IJanuaField read GetPodId write SetPodId;
    function GetPodName: IJanuaField;
    procedure SetPodName(const Value: IJanuaField);
    property PodName: IJanuaField read GetPodName write SetPodName;
    function GetPodCode: IJanuaField;
    procedure SetPodCode(const Value: IJanuaField);
    property PodCode: IJanuaField read GetPodCode write SetPodCode;
    function GetCustomerId: IJanuaField;
    procedure SetCustomerId(const Value: IJanuaField);
    property CustomerId: IJanuaField read GetCustomerId write SetCustomerId;
    function GetNotes: IJanuaField;
    procedure SetNotes(const Value: IJanuaField);
    property Notes: IJanuaField read GetNotes write SetNotes;
    function GetWarehouseId: IJanuaField;
    procedure SetWarehouseId(const Value: IJanuaField);
    property WarehouseId: IJanuaField read GetWarehouseId write SetWarehouseId;
    function GetWorkDate: IJanuaField;
    procedure SetWorkDate(const Value: IJanuaField);
    property WorkDate: IJanuaField read GetWorkDate write SetWorkDate;
    function GetOrderState: IJanuaField;
    procedure SetOrderState(const Value: IJanuaField);
    property OrderState: IJanuaField read GetOrderState write SetOrderState;
    function GetAirportId: IJanuaField;
    procedure SetAirportId(const Value: IJanuaField);
    property AirportId: IJanuaField read GetAirportId write SetAirportId;
    function GetAirportCode: IJanuaField;
    procedure SetAirportCode(const Value: IJanuaField);
    property AirportCode: IJanuaField read GetAirportCode write SetAirportCode;
    function GetAwbNumber: IJanuaField;
    procedure SetAwbNumber(const Value: IJanuaField);
    property AwbNumber: IJanuaField read GetAwbNumber write SetAwbNumber;
    function GetInternalNotes: IJanuaField;
    procedure SetInternalNotes(const Value: IJanuaField);
    property InternalNotes: IJanuaField read GetInternalNotes write SetInternalNotes;
    function GetInternalNotes2: IJanuaField;
    procedure SetInternalNotes2(const Value: IJanuaField);
    property InternalNotes2: IJanuaField read GetInternalNotes2 write SetInternalNotes2;
    function GetWarehouseNotes: IJanuaField;
    procedure SetWarehouseNotes(const Value: IJanuaField);
    property WarehouseNotes: IJanuaField read GetWarehouseNotes write SetWarehouseNotes;
    function GetRouteType: IJanuaField;
    procedure SetRouteType(const Value: IJanuaField);
    property RouteType: IJanuaField read GetRouteType write SetRouteType;
    function GetInternetVisible: IJanuaField;
    procedure SetInternetVisible(const Value: IJanuaField);
    property InternetVisible: IJanuaField read GetInternetVisible write SetInternetVisible;
    function GetFlagAir: IJanuaField;
    procedure SetFlagAir(const Value: IJanuaField);
    property FlagAir: IJanuaField read GetFlagAir write SetFlagAir;
    function GetFlagGround: IJanuaField;
    procedure SetFlagGround(const Value: IJanuaField);
    property FlagGround: IJanuaField read GetFlagGround write SetFlagGround;
    function GetDepartureDate: IJanuaField;
    procedure SetDepartureDate(const Value: IJanuaField);
    property DepartureDate: IJanuaField read GetDepartureDate write SetDepartureDate;
    function GetArrivalDate: IJanuaField;
    procedure SetArrivalDate(const Value: IJanuaField);
    property ArrivalDate: IJanuaField read GetArrivalDate write SetArrivalDate;
    function GetPoState: IJanuaField;
    procedure SetPoState(const Value: IJanuaField);
    property PoState: IJanuaField read GetPoState write SetPoState;
    function GetPoLevel: IJanuaField;
    procedure SetPoLevel(const Value: IJanuaField);
    property PoLevel: IJanuaField read GetPoLevel write SetPoLevel;
    function GetFinalDate: IJanuaField;
    procedure SetFinalDate(const Value: IJanuaField);
    property FinalDate: IJanuaField read GetFinalDate write SetFinalDate;
    function GetFlgHouse: IJanuaField;
    procedure SetFlgHouse(const Value: IJanuaField);
    property FlgHouse: IJanuaField read GetFlgHouse write SetFlgHouse;
    function GetFlgMaster: IJanuaField;
    procedure SetFlgMaster(const Value: IJanuaField);
    property FlgMaster: IJanuaField read GetFlgMaster write SetFlgMaster;
    function GetDelivered: IJanuaField;
    procedure SetDelivered(const Value: IJanuaField);
    property Delivered: IJanuaField read GetDelivered write SetDelivered;
    function GetFlgBillable: IJanuaField;
    procedure SetFlgBillable(const Value: IJanuaField);
    property FlgBillable: IJanuaField read GetFlgBillable write SetFlgBillable;
    function GetCustomsDeclearer: IJanuaField;
    procedure SetCustomsDeclearer(const Value: IJanuaField);
    property CustomsDeclearer: IJanuaField read GetCustomsDeclearer write SetCustomsDeclearer;
    function GetCustomsDate: IJanuaField;
    procedure SetCustomsDate(const Value: IJanuaField);
    property CustomsDate: IJanuaField read GetCustomsDate write SetCustomsDate;
    function GetUpdateDate: IJanuaField;
    procedure SetUpdateDate(const Value: IJanuaField);
    property UpdateDate: IJanuaField read GetUpdateDate write SetUpdateDate;
    function GetInsertDate: IJanuaField;
    procedure SetInsertDate(const Value: IJanuaField);
    property InsertDate: IJanuaField read GetInsertDate write SetInsertDate;
    function GetDeleted: IJanuaField;
    procedure SetDeleted(const Value: IJanuaField);
    property Deleted: IJanuaField read GetDeleted write SetDeleted;
    function GetDbSchemaId: IJanuaField;
    procedure SetDbSchemaId(const Value: IJanuaField);
    property DbSchemaId: IJanuaField read GetDbSchemaId write SetDbSchemaId;
    function GetCarrierName: IJanuaField;
    procedure SetCarrierName(const Value: IJanuaField);
    property CarrierName: IJanuaField read GetCarrierName write SetCarrierName;
    function GetCode: IJanuaField;
    procedure SetCode(const Value: IJanuaField);
    property Code: IJanuaField read GetCode write SetCode;
    function GetTypeId: IJanuaField;
    procedure SetTypeId(const Value: IJanuaField);
    property TypeId: IJanuaField read GetTypeId write SetTypeId;
    function GetLevelId: IJanuaField;
    procedure SetLevelId(const Value: IJanuaField);
    property LevelId: IJanuaField read GetLevelId write SetLevelId;
    function GetAgentName: IJanuaField;
    procedure SetAgentName(const Value: IJanuaField);
    property AgentName: IJanuaField read GetAgentName write SetAgentName;
    function GetAgentCode: IJanuaField;
    procedure SetAgentCode(const Value: IJanuaField);
    property AgentCode: IJanuaField read GetAgentCode write SetAgentCode;
    function GetAgentTown: IJanuaField;
    procedure SetAgentTown(const Value: IJanuaField);
    property AgentTown: IJanuaField read GetAgentTown write SetAgentTown;
    function GetShipperName: IJanuaField;
    procedure SetShipperName(const Value: IJanuaField);
    property ShipperName: IJanuaField read GetShipperName write SetShipperName;
    function GetShipperCode: IJanuaField;
    procedure SetShipperCode(const Value: IJanuaField);
    property ShipperCode: IJanuaField read GetShipperCode write SetShipperCode;
    function GetShipperTown: IJanuaField;
    procedure SetShipperTown(const Value: IJanuaField);
    property ShipperTown: IJanuaField read GetShipperTown write SetShipperTown;
    function GetVesselName: IJanuaField;
    procedure SetVesselName(const Value: IJanuaField);
    property VesselName: IJanuaField read GetVesselName write SetVesselName;
    function GetAirportName: IJanuaField;
    procedure SetAirportName(const Value: IJanuaField);
    property AirportName: IJanuaField read GetAirportName write SetAirportName;
    function GetCarrierTown: IJanuaField;
    procedure SetCarrierTown(const Value: IJanuaField);
    property CarrierTown: IJanuaField read GetCarrierTown write SetCarrierTown;
    function GetCustomerName: IJanuaField;
    procedure SetCustomerName(const Value: IJanuaField);
    property CustomerName: IJanuaField read GetCustomerName write SetCustomerName;
    function GetCustomerCode: IJanuaField;
    procedure SetCustomerCode(const Value: IJanuaField);
    property CustomerCode: IJanuaField read GetCustomerCode write SetCustomerCode;
    function GetCustomerTown: IJanuaField;
    procedure SetCustomerTown(const Value: IJanuaField);
    property CustomerTown: IJanuaField read GetCustomerTown write SetCustomerTown;
    function GetCustomerAddress: IJanuaField;
    procedure SetCustomerAddress(const Value: IJanuaField);
    property CustomerAddress: IJanuaField read GetCustomerAddress write SetCustomerAddress;
    function GetCustomerPostalCode: IJanuaField;
    procedure SetCustomerPostalCode(const Value: IJanuaField);
    property CustomerPostalCode: IJanuaField read GetCustomerPostalCode write SetCustomerPostalCode;
    function GetCustomerPhone: IJanuaField;
    procedure SetCustomerPhone(const Value: IJanuaField);
    property CustomerPhone: IJanuaField read GetCustomerPhone write SetCustomerPhone;
    // work_number
    function GetWorkNumber: IJanuaField;
    procedure SetWorkNumber(const Value: IJanuaField);
    property WorkNumber: IJanuaField read GetWorkNumber write SetWorkNumber;
    // po_number
    function GetPoNumber: IJanuaField;
    procedure SetPoNumber(const Value: IJanuaField);
    property PoNumber: IJanuaField read GetPoNumber write SetPoNumber;
  end;

  ICustomShipmentsView = interface(IJanuaRecordSet)
    ['{C6990107-BEED-482D-B481-E968C3046320}']
    function GetId: IJanuaField;
    procedure SetId(const Value: IJanuaField);
    property Id: IJanuaField read GetId write SetId;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
    function GetCreationDate: IJanuaField;
    procedure SetCreationDate(const Value: IJanuaField);
    property CreationDate: IJanuaField read GetCreationDate write SetCreationDate;
    function GetPickupDate: IJanuaField;
    procedure SetPickupDate(const Value: IJanuaField);
    property PickupDate: IJanuaField read GetPickupDate write SetPickupDate;
    function GetDeliveryDate: IJanuaField;
    procedure SetDeliveryDate(const Value: IJanuaField);
    property DeliveryDate: IJanuaField read GetDeliveryDate write SetDeliveryDate;
    function GetOfficeId: IJanuaField;
    procedure SetOfficeId(const Value: IJanuaField);
    property OfficeId: IJanuaField read GetOfficeId write SetOfficeId;
    function GetWorkflowUid: IJanuaField;
    procedure SetWorkflowUid(const Value: IJanuaField);
    property WorkflowUid: IJanuaField read GetWorkflowUid write SetWorkflowUid;
    function GetAgentId: IJanuaField;
    procedure SetAgentId(const Value: IJanuaField);
    property AgentId: IJanuaField read GetAgentId write SetAgentId;
    function GetShipperId: IJanuaField;
    procedure SetShipperId(const Value: IJanuaField);
    property ShipperId: IJanuaField read GetShipperId write SetShipperId;
    function GetShipperAddress: IJanuaField;
    procedure SetShipperAddress(const Value: IJanuaField);
    property ShipperAddress: IJanuaField read GetShipperAddress write SetShipperAddress;
    function GetPickupAddress: IJanuaField;
    procedure SetPickupAddress(const Value: IJanuaField);
    property PickupAddress: IJanuaField read GetPickupAddress write SetPickupAddress;
    function GetYear: IJanuaField;
    procedure SetYear(const Value: IJanuaField);
    property Year: IJanuaField read GetYear write SetYear;
    function GetGroupageNumber: IJanuaField;
    procedure SetGroupageNumber(const Value: IJanuaField);
    property GroupageNumber: IJanuaField read GetGroupageNumber write SetGroupageNumber;
    function GetExportTypeId: IJanuaField;
    procedure SetExportTypeId(const Value: IJanuaField);
    property ExportTypeId: IJanuaField read GetExportTypeId write SetExportTypeId;
    function GetFullcontainer: IJanuaField;
    procedure SetFullcontainer(const Value: IJanuaField);
    property Fullcontainer: IJanuaField read GetFullcontainer write SetFullcontainer;
    function GetVesselId: IJanuaField;
    procedure SetVesselId(const Value: IJanuaField);
    property VesselId: IJanuaField read GetVesselId write SetVesselId;
    function GetWorkCode: IJanuaField;
    procedure SetWorkCode(const Value: IJanuaField);
    property WorkCode: IJanuaField read GetWorkCode write SetWorkCode;
    function GetTravelIdentificationCode: IJanuaField;
    procedure SetTravelIdentificationCode(const Value: IJanuaField);
    property TravelIdentificationCode: IJanuaField read GetTravelIdentificationCode
      write SetTravelIdentificationCode;
    function GetCarrierId: IJanuaField;
    procedure SetCarrierId(const Value: IJanuaField);
    property CarrierId: IJanuaField read GetCarrierId write SetCarrierId;
    function GetCarrierCode: IJanuaField;
    procedure SetCarrierCode(const Value: IJanuaField);
    property CarrierCode: IJanuaField read GetCarrierCode write SetCarrierCode;
    function GetWorkflowId: IJanuaField;
    procedure SetWorkflowId(const Value: IJanuaField);
    property WorkflowId: IJanuaField read GetWorkflowId write SetWorkflowId;
    function GetPolId: IJanuaField;
    procedure SetPolId(const Value: IJanuaField);
    property PolId: IJanuaField read GetPolId write SetPolId;
    function GetPolCode: IJanuaField;
    procedure SetPolCode(const Value: IJanuaField);
    property PolCode: IJanuaField read GetPolCode write SetPolCode;
    function GetPolName: IJanuaField;
    procedure SetPolName(const Value: IJanuaField);
    property PolName: IJanuaField read GetPolName write SetPolName;
    function GetPodId: IJanuaField;
    procedure SetPodId(const Value: IJanuaField);
    property PodId: IJanuaField read GetPodId write SetPodId;
    function GetPodName: IJanuaField;
    procedure SetPodName(const Value: IJanuaField);
    property PodName: IJanuaField read GetPodName write SetPodName;
    function GetPodCode: IJanuaField;
    procedure SetPodCode(const Value: IJanuaField);
    property PodCode: IJanuaField read GetPodCode write SetPodCode;
    function GetCustomerId: IJanuaField;
    procedure SetCustomerId(const Value: IJanuaField);
    property CustomerId: IJanuaField read GetCustomerId write SetCustomerId;
    function GetNotes: IJanuaField;
    procedure SetNotes(const Value: IJanuaField);
    property Notes: IJanuaField read GetNotes write SetNotes;
    function GetWarehouseId: IJanuaField;
    procedure SetWarehouseId(const Value: IJanuaField);
    property WarehouseId: IJanuaField read GetWarehouseId write SetWarehouseId;
    function GetWorkDate: IJanuaField;
    procedure SetWorkDate(const Value: IJanuaField);
    property WorkDate: IJanuaField read GetWorkDate write SetWorkDate;
    function GetOrderState: IJanuaField;
    procedure SetOrderState(const Value: IJanuaField);
    property OrderState: IJanuaField read GetOrderState write SetOrderState;
    function GetAirportId: IJanuaField;
    procedure SetAirportId(const Value: IJanuaField);
    property AirportId: IJanuaField read GetAirportId write SetAirportId;
    function GetAirportCode: IJanuaField;
    procedure SetAirportCode(const Value: IJanuaField);
    property AirportCode: IJanuaField read GetAirportCode write SetAirportCode;
    function GetAwbNumber: IJanuaField;
    procedure SetAwbNumber(const Value: IJanuaField);
    property AwbNumber: IJanuaField read GetAwbNumber write SetAwbNumber;
    function GetInternalNotes: IJanuaField;
    procedure SetInternalNotes(const Value: IJanuaField);
    property InternalNotes: IJanuaField read GetInternalNotes write SetInternalNotes;
    function GetInternalNotes2: IJanuaField;
    procedure SetInternalNotes2(const Value: IJanuaField);
    property InternalNotes2: IJanuaField read GetInternalNotes2 write SetInternalNotes2;
    function GetWarehouseNotes: IJanuaField;
    procedure SetWarehouseNotes(const Value: IJanuaField);
    property WarehouseNotes: IJanuaField read GetWarehouseNotes write SetWarehouseNotes;
    function GetRouteType: IJanuaField;
    procedure SetRouteType(const Value: IJanuaField);
    property RouteType: IJanuaField read GetRouteType write SetRouteType;
    function GetInternetVisible: IJanuaField;
    procedure SetInternetVisible(const Value: IJanuaField);
    property InternetVisible: IJanuaField read GetInternetVisible write SetInternetVisible;
    function GetFlagAir: IJanuaField;
    procedure SetFlagAir(const Value: IJanuaField);
    property FlagAir: IJanuaField read GetFlagAir write SetFlagAir;
    function GetFlagGround: IJanuaField;
    procedure SetFlagGround(const Value: IJanuaField);
    property FlagGround: IJanuaField read GetFlagGround write SetFlagGround;
    function GetDepartureDate: IJanuaField;
    procedure SetDepartureDate(const Value: IJanuaField);
    property DepartureDate: IJanuaField read GetDepartureDate write SetDepartureDate;
    function GetArrivalDate: IJanuaField;
    procedure SetArrivalDate(const Value: IJanuaField);
    property ArrivalDate: IJanuaField read GetArrivalDate write SetArrivalDate;
    function GetPoState: IJanuaField;
    procedure SetPoState(const Value: IJanuaField);
    property PoState: IJanuaField read GetPoState write SetPoState;
    function GetPoLevel: IJanuaField;
    procedure SetPoLevel(const Value: IJanuaField);
    property PoLevel: IJanuaField read GetPoLevel write SetPoLevel;
    function GetFinalDate: IJanuaField;
    procedure SetFinalDate(const Value: IJanuaField);
    property FinalDate: IJanuaField read GetFinalDate write SetFinalDate;
    function GetFlgHouse: IJanuaField;
    procedure SetFlgHouse(const Value: IJanuaField);
    property FlgHouse: IJanuaField read GetFlgHouse write SetFlgHouse;
    function GetFlgMaster: IJanuaField;
    procedure SetFlgMaster(const Value: IJanuaField);
    property FlgMaster: IJanuaField read GetFlgMaster write SetFlgMaster;
    function GetDelivered: IJanuaField;
    procedure SetDelivered(const Value: IJanuaField);
    property Delivered: IJanuaField read GetDelivered write SetDelivered;
    function GetFlgBillable: IJanuaField;
    procedure SetFlgBillable(const Value: IJanuaField);
    property FlgBillable: IJanuaField read GetFlgBillable write SetFlgBillable;
    function GetCustomsDeclearer: IJanuaField;
    procedure SetCustomsDeclearer(const Value: IJanuaField);
    property CustomsDeclearer: IJanuaField read GetCustomsDeclearer write SetCustomsDeclearer;
    function GetCustomsDate: IJanuaField;
    procedure SetCustomsDate(const Value: IJanuaField);
    property CustomsDate: IJanuaField read GetCustomsDate write SetCustomsDate;
    function GetUpdateDate: IJanuaField;
    procedure SetUpdateDate(const Value: IJanuaField);
    property UpdateDate: IJanuaField read GetUpdateDate write SetUpdateDate;
    function GetInsertDate: IJanuaField;
    procedure SetInsertDate(const Value: IJanuaField);
    property InsertDate: IJanuaField read GetInsertDate write SetInsertDate;
    function GetDeleted: IJanuaField;
    procedure SetDeleted(const Value: IJanuaField);
    property Deleted: IJanuaField read GetDeleted write SetDeleted;
    function GetDbSchemaId: IJanuaField;
    procedure SetDbSchemaId(const Value: IJanuaField);
    property DbSchemaId: IJanuaField read GetDbSchemaId write SetDbSchemaId;
    function GetCarrierName: IJanuaField;
    procedure SetCarrierName(const Value: IJanuaField);
    property CarrierName: IJanuaField read GetCarrierName write SetCarrierName;
    function GetCode: IJanuaField;
    procedure SetCode(const Value: IJanuaField);
    property Code: IJanuaField read GetCode write SetCode;
    function GetTypeId: IJanuaField;
    procedure SetTypeId(const Value: IJanuaField);
    property TypeId: IJanuaField read GetTypeId write SetTypeId;
    function GetLevelId: IJanuaField;
    procedure SetLevelId(const Value: IJanuaField);
    property LevelId: IJanuaField read GetLevelId write SetLevelId;
    function GetAgentName: IJanuaField;
    procedure SetAgentName(const Value: IJanuaField);
    property AgentName: IJanuaField read GetAgentName write SetAgentName;
    function GetAgentCode: IJanuaField;
    procedure SetAgentCode(const Value: IJanuaField);
    property AgentCode: IJanuaField read GetAgentCode write SetAgentCode;
    function GetAgentTown: IJanuaField;
    procedure SetAgentTown(const Value: IJanuaField);
    property AgentTown: IJanuaField read GetAgentTown write SetAgentTown;
    function GetShipperName: IJanuaField;
    procedure SetShipperName(const Value: IJanuaField);
    property ShipperName: IJanuaField read GetShipperName write SetShipperName;
    function GetShipperCode: IJanuaField;
    procedure SetShipperCode(const Value: IJanuaField);
    property ShipperCode: IJanuaField read GetShipperCode write SetShipperCode;
    function GetShipperTown: IJanuaField;
    procedure SetShipperTown(const Value: IJanuaField);
    property ShipperTown: IJanuaField read GetShipperTown write SetShipperTown;
    function GetVesselName: IJanuaField;
    procedure SetVesselName(const Value: IJanuaField);
    property VesselName: IJanuaField read GetVesselName write SetVesselName;
    function GetAirportName: IJanuaField;
    procedure SetAirportName(const Value: IJanuaField);
    property AirportName: IJanuaField read GetAirportName write SetAirportName;
    function GetCarrierTown: IJanuaField;
    procedure SetCarrierTown(const Value: IJanuaField);
    property CarrierTown: IJanuaField read GetCarrierTown write SetCarrierTown;
    function GetCustomerName: IJanuaField;
    procedure SetCustomerName(const Value: IJanuaField);
    property CustomerName: IJanuaField read GetCustomerName write SetCustomerName;
    function GetCustomerCode: IJanuaField;
    procedure SetCustomerCode(const Value: IJanuaField);
    property CustomerCode: IJanuaField read GetCustomerCode write SetCustomerCode;
    function GetCustomerTown: IJanuaField;
    procedure SetCustomerTown(const Value: IJanuaField);
    property CustomerTown: IJanuaField read GetCustomerTown write SetCustomerTown;
    function GetCustomerAddress: IJanuaField;
    procedure SetCustomerAddress(const Value: IJanuaField);
    property CustomerAddress: IJanuaField read GetCustomerAddress write SetCustomerAddress;
    function GetCustomerPostalCode: IJanuaField;
    procedure SetCustomerPostalCode(const Value: IJanuaField);
    property CustomerPostalCode: IJanuaField read GetCustomerPostalCode write SetCustomerPostalCode;
    function GetCustomerPhone: IJanuaField;
    procedure SetCustomerPhone(const Value: IJanuaField);
    property CustomerPhone: IJanuaField read GetCustomerPhone write SetCustomerPhone;
    // work_number
    function GetWorkNumber: IJanuaField;
    procedure SetWorkNumber(const Value: IJanuaField);
    property WorkNumber: IJanuaField read GetWorkNumber write SetWorkNumber;
    // po_number
    function GetPoNumber: IJanuaField;
    procedure SetPoNumber(const Value: IJanuaField);
    property PoNumber: IJanuaField read GetPoNumber write SetPoNumber;
  end;

implementation

end.
