unit JOrm.System.User.Intf;

interface

uses janua.Orm.Intf;

type

  IUser = interface(IJanuaRecord)
    ['{D6E02B08-61B5-446A-B313-C2B1C437F49D}']
    function GetActive: IJanuaField;
    procedure SetActive(const Value: IJanuaField);
    property Active: IJanuaField read GetActive write SetActive;
    function GetEmail: IJanuaField;
    procedure SetEmail(const Value: IJanuaField);
    property Email: IJanuaField read GetEmail write SetEmail;
    function GetDb_user_id: IJanuaField;
    procedure SetDb_user_id(const Value: IJanuaField);
    property Db_user_id: IJanuaField read GetDb_user_id write SetDb_user_id;
    function GetPassword: IJanuaField;
    procedure SetPassword(const Value: IJanuaField);
    property Password: IJanuaField read GetPassword write SetPassword;
    function GetUsername: IJanuaField;
    procedure SetUsername(const Value: IJanuaField);
    property Username: IJanuaField read GetUsername write SetUsername;
    function GetIsactive: IJanuaField;
    procedure SetIsactive(const Value: IJanuaField);
    property Isactive: IJanuaField read GetIsactive write SetIsactive;
    function GetVerify_token: IJanuaField;
    procedure SetVerify_token(const Value: IJanuaField);
    property Verify_token: IJanuaField read GetVerify_token write SetVerify_token;
    function GetVerified: IJanuaField;
    procedure SetVerified(const Value: IJanuaField);
    property Verified: IJanuaField read GetVerified write SetVerified;
    function GetDefault_schema_id: IJanuaField;
    procedure SetDefault_schema_id(const Value: IJanuaField);
    property Default_schema_id: IJanuaField read GetDefault_schema_id write SetDefault_schema_id;
    function GetIspublic: IJanuaField;
    procedure SetIspublic(const Value: IJanuaField);
    property Ispublic: IJanuaField read GetIspublic write SetIspublic;
    function GetInternal_key: IJanuaField;
    procedure SetInternal_key(const Value: IJanuaField);
    property Internal_key: IJanuaField read GetInternal_key write SetInternal_key;
    function GetDefault_role_id: IJanuaField;
    procedure SetDefault_role_id(const Value: IJanuaField);
    property Default_role_id: IJanuaField read GetDefault_role_id write SetDefault_role_id;
    function GetSearch_name: IJanuaField;
    procedure SetSearch_name(const Value: IJanuaField);
    property Search_name: IJanuaField read GetSearch_name write SetSearch_name;
    function GetReverse_search: IJanuaField;
    procedure SetReverse_search(const Value: IJanuaField);
    property Reverse_search: IJanuaField read GetReverse_search write SetReverse_search;
    function GetInsert_date: IJanuaField;
    procedure SetInsert_date(const Value: IJanuaField);
    property Insert_date: IJanuaField read GetInsert_date write SetInsert_date;
    function GetCountry_id: IJanuaField;
    procedure SetCountry_id(const Value: IJanuaField);
    property Country_id: IJanuaField read GetCountry_id write SetCountry_id;
    function GetMain_profile_type_id: IJanuaField;
    procedure SetMain_profile_type_id(const Value: IJanuaField);
    property Main_profile_type_id: IJanuaField read GetMain_profile_type_id write SetMain_profile_type_id;
    function GetMain_profile_id: IJanuaField;
    procedure SetMain_profile_id(const Value: IJanuaField);
    property Main_profile_id: IJanuaField read GetMain_profile_id write SetMain_profile_id;
    function GetImage_id: IJanuaField;
    procedure SetImage_id(const Value: IJanuaField);
    property Image_id: IJanuaField read GetImage_id write SetImage_id;
    function GetImage_url: IJanuaField;
    procedure SetImage_url(const Value: IJanuaField);
    property Image_url: IJanuaField read GetImage_url write SetImage_url;
    function GetIso_language_code: IJanuaField;
    procedure SetIso_language_code(const Value: IJanuaField);
    property Iso_language_code: IJanuaField read GetIso_language_code write SetIso_language_code;
    function GetIso_culture_code: IJanuaField;
    procedure SetIso_culture_code(const Value: IJanuaField);
    property Iso_culture_code: IJanuaField read GetIso_culture_code write SetIso_culture_code;
    function GetUser_first_name: IJanuaField;
    procedure SetUser_first_name(const Value: IJanuaField);
    property User_first_name: IJanuaField read GetUser_first_name write SetUser_first_name;
    function GetUser_family_name: IJanuaField;
    procedure SetUser_family_name(const Value: IJanuaField);
    property User_family_name: IJanuaField read GetUser_family_name write SetUser_family_name;
    function GetEmailsent: IJanuaField;
    procedure SetEmailsent(const Value: IJanuaField);
    property Emailsent: IJanuaField read GetEmailsent write SetEmailsent;
    function GetEmailconfirmed: IJanuaField;
    procedure SetEmailconfirmed(const Value: IJanuaField);
    property Emailconfirmed: IJanuaField read GetEmailconfirmed write SetEmailconfirmed;
    function GetEmaildate: IJanuaField;
    procedure SetEmaildate(const Value: IJanuaField);
    property Emaildate: IJanuaField read GetEmaildate write SetEmaildate;
    function GetPayment: IJanuaField;
    procedure SetPayment(const Value: IJanuaField);
    property Payment: IJanuaField read GetPayment write SetPayment;
    function GetPayment_expiration_date: IJanuaField;
    procedure SetPayment_expiration_date(const Value: IJanuaField);
    property Payment_expiration_date: IJanuaField read GetPayment_expiration_date write SetPayment_expiration_date;
  end;

  IUsers = interface(IJanuaRecordSet)
  ['{6F11C6C1-CF90-4E05-A02D-5E7A7BE99D0A}']
    function GetActive: IJanuaField;
    procedure SetActive(const Value: IJanuaField);
    property Active: IJanuaField read GetActive write SetActive;
    function GetEmail: IJanuaField;
    procedure SetEmail(const Value: IJanuaField);
    property Email: IJanuaField read GetEmail write SetEmail;
    function GetDb_user_id: IJanuaField;
    procedure SetDb_user_id(const Value: IJanuaField);
    property Db_user_id: IJanuaField read GetDb_user_id write SetDb_user_id;
    function GetPassword: IJanuaField;
    procedure SetPassword(const Value: IJanuaField);
    property Password: IJanuaField read GetPassword write SetPassword;
    function GetUsername: IJanuaField;
    procedure SetUsername(const Value: IJanuaField);
    property Username: IJanuaField read GetUsername write SetUsername;
    function GetIsactive: IJanuaField;
    procedure SetIsactive(const Value: IJanuaField);
    property Isactive: IJanuaField read GetIsactive write SetIsactive;
    function GetVerify_token: IJanuaField;
    procedure SetVerify_token(const Value: IJanuaField);
    property Verify_token: IJanuaField read GetVerify_token write SetVerify_token;
    function GetVerified: IJanuaField;
    procedure SetVerified(const Value: IJanuaField);
    property Verified: IJanuaField read GetVerified write SetVerified;
    function GetDefault_schema_id: IJanuaField;
    procedure SetDefault_schema_id(const Value: IJanuaField);
    property Default_schema_id: IJanuaField read GetDefault_schema_id write SetDefault_schema_id;
    function GetIspublic: IJanuaField;
    procedure SetIspublic(const Value: IJanuaField);
    property Ispublic: IJanuaField read GetIspublic write SetIspublic;
    function GetInternal_key: IJanuaField;
    procedure SetInternal_key(const Value: IJanuaField);
    property Internal_key: IJanuaField read GetInternal_key write SetInternal_key;
    function GetDefault_role_id: IJanuaField;
    procedure SetDefault_role_id(const Value: IJanuaField);
    property Default_role_id: IJanuaField read GetDefault_role_id write SetDefault_role_id;
    function GetSearch_name: IJanuaField;
    procedure SetSearch_name(const Value: IJanuaField);
    property Search_name: IJanuaField read GetSearch_name write SetSearch_name;
    function GetReverse_search: IJanuaField;
    procedure SetReverse_search(const Value: IJanuaField);
    property Reverse_search: IJanuaField read GetReverse_search write SetReverse_search;
    function GetInsert_date: IJanuaField;
    procedure SetInsert_date(const Value: IJanuaField);
    property Insert_date: IJanuaField read GetInsert_date write SetInsert_date;
    function GetCountry_id: IJanuaField;
    procedure SetCountry_id(const Value: IJanuaField);
    property Country_id: IJanuaField read GetCountry_id write SetCountry_id;
    function GetMain_profile_type_id: IJanuaField;
    procedure SetMain_profile_type_id(const Value: IJanuaField);
    property Main_profile_type_id: IJanuaField read GetMain_profile_type_id write SetMain_profile_type_id;
    function GetMain_profile_id: IJanuaField;
    procedure SetMain_profile_id(const Value: IJanuaField);
    property Main_profile_id: IJanuaField read GetMain_profile_id write SetMain_profile_id;
    function GetImage_id: IJanuaField;
    procedure SetImage_id(const Value: IJanuaField);
    property Image_id: IJanuaField read GetImage_id write SetImage_id;
    function GetImage_url: IJanuaField;
    procedure SetImage_url(const Value: IJanuaField);
    property Image_url: IJanuaField read GetImage_url write SetImage_url;
    function GetIso_language_code: IJanuaField;
    procedure SetIso_language_code(const Value: IJanuaField);
    property Iso_language_code: IJanuaField read GetIso_language_code write SetIso_language_code;
    function GetIso_culture_code: IJanuaField;
    procedure SetIso_culture_code(const Value: IJanuaField);
    property Iso_culture_code: IJanuaField read GetIso_culture_code write SetIso_culture_code;
    function GetUser_first_name: IJanuaField;
    procedure SetUser_first_name(const Value: IJanuaField);
    property User_first_name: IJanuaField read GetUser_first_name write SetUser_first_name;
    function GetUser_family_name: IJanuaField;
    procedure SetUser_family_name(const Value: IJanuaField);
    property User_family_name: IJanuaField read GetUser_family_name write SetUser_family_name;
    function GetEmailsent: IJanuaField;
    procedure SetEmailsent(const Value: IJanuaField);
    property Emailsent: IJanuaField read GetEmailsent write SetEmailsent;
    function GetEmailconfirmed: IJanuaField;
    procedure SetEmailconfirmed(const Value: IJanuaField);
    property Emailconfirmed: IJanuaField read GetEmailconfirmed write SetEmailconfirmed;
    function GetEmaildate: IJanuaField;
    procedure SetEmaildate(const Value: IJanuaField);
    property Emaildate: IJanuaField read GetEmaildate write SetEmaildate;
    function GetPayment: IJanuaField;
    procedure SetPayment(const Value: IJanuaField);
    property Payment: IJanuaField read GetPayment write SetPayment;
    function GetPayment_expiration_date: IJanuaField;
    procedure SetPayment_expiration_date(const Value: IJanuaField);
    property Payment_expiration_date: IJanuaField read GetPayment_expiration_date write SetPayment_expiration_date;
    function GetUser: IUser;
    procedure SetUser(const Value: IUser);
    property User:IUser read GetUser write SetUser;

  end;

implementation

end.
