unit JOrm.System.Users.Custom.Intf;

interface

uses Janua.Orm.Intf;

type

  ICustomUser = interface(IJanuaRecord)
    ['{852D924C-923C-4D82-B765-5DF4B21852AC}']
    function GetActive: IJanuaField;
    procedure SetActive(const Value: IJanuaField);
    property Active: IJanuaField read GetActive write SetActive;
    function GetEmail: IJanuaField;
    procedure SetEmail(const Value: IJanuaField);
    property Email: IJanuaField read GetEmail write SetEmail;
    function GetDbUserId: IJanuaField;
    procedure SetDbUserId(const Value: IJanuaField);
    property DbUserId: IJanuaField read GetDbUserId write SetDbUserId;
    function GetPassword: IJanuaField;
    procedure SetPassword(const Value: IJanuaField);
    property Password: IJanuaField read GetPassword write SetPassword;
    function GetUsername: IJanuaField;
    procedure SetUsername(const Value: IJanuaField);
    property Username: IJanuaField read GetUsername write SetUsername;
    function GetIsactive: IJanuaField;
    procedure SetIsactive(const Value: IJanuaField);
    property Isactive: IJanuaField read GetIsactive write SetIsactive;
    function GetVerifyToken: IJanuaField;
    procedure SetVerifyToken(const Value: IJanuaField);
    property VerifyToken: IJanuaField read GetVerifyToken write SetVerifyToken;
    function GetVerified: IJanuaField;
    procedure SetVerified(const Value: IJanuaField);
    property Verified: IJanuaField read GetVerified write SetVerified;
    function GetDefaultSchemaId: IJanuaField;
    procedure SetDefaultSchemaId(const Value: IJanuaField);
    property DefaultSchemaId: IJanuaField read GetDefaultSchemaId write SetDefaultSchemaId;
    function GetIspublic: IJanuaField;
    procedure SetIspublic(const Value: IJanuaField);
    property Ispublic: IJanuaField read GetIspublic write SetIspublic;
    function GetInternalKey: IJanuaField;
    procedure SetInternalKey(const Value: IJanuaField);
    property InternalKey: IJanuaField read GetInternalKey write SetInternalKey;
    function GetDefaultRoleId: IJanuaField;
    procedure SetDefaultRoleId(const Value: IJanuaField);
    property DefaultRoleId: IJanuaField read GetDefaultRoleId write SetDefaultRoleId;
    function GetSearchName: IJanuaField;
    procedure SetSearchName(const Value: IJanuaField);
    property SearchName: IJanuaField read GetSearchName write SetSearchName;
    function GetReverseSearch: IJanuaField;
    procedure SetReverseSearch(const Value: IJanuaField);
    property ReverseSearch: IJanuaField read GetReverseSearch write SetReverseSearch;
    function GetInsertDate: IJanuaField;
    procedure SetInsertDate(const Value: IJanuaField);
    property InsertDate: IJanuaField read GetInsertDate write SetInsertDate;
    function GetCountryId: IJanuaField;
    procedure SetCountryId(const Value: IJanuaField);
    property CountryId: IJanuaField read GetCountryId write SetCountryId;
    function GetMainProfileTypeId: IJanuaField;
    procedure SetMainProfileTypeId(const Value: IJanuaField);
    property MainProfileTypeId: IJanuaField read GetMainProfileTypeId write SetMainProfileTypeId;
    function GetMainProfileId: IJanuaField;
    procedure SetMainProfileId(const Value: IJanuaField);
    property MainProfileId: IJanuaField read GetMainProfileId write SetMainProfileId;
    function GetImageId: IJanuaField;
    procedure SetImageId(const Value: IJanuaField);
    property ImageId: IJanuaField read GetImageId write SetImageId;
    function GetImageUrl: IJanuaField;
    procedure SetImageUrl(const Value: IJanuaField);
    property ImageUrl: IJanuaField read GetImageUrl write SetImageUrl;
    function GetIsoLanguageCode: IJanuaField;
    procedure SetIsoLanguageCode(const Value: IJanuaField);
    property IsoLanguageCode: IJanuaField read GetIsoLanguageCode write SetIsoLanguageCode;
    function GetIsoCultureCode: IJanuaField;
    procedure SetIsoCultureCode(const Value: IJanuaField);
    property IsoCultureCode: IJanuaField read GetIsoCultureCode write SetIsoCultureCode;
    function GetUserFirstName: IJanuaField;
    procedure SetUserFirstName(const Value: IJanuaField);
    property UserFirstName: IJanuaField read GetUserFirstName write SetUserFirstName;
    function GetUserFamilyName: IJanuaField;
    procedure SetUserFamilyName(const Value: IJanuaField);
    property UserFamilyName: IJanuaField read GetUserFamilyName write SetUserFamilyName;
    function GetEmailsent: IJanuaField;
    procedure SetEmailsent(const Value: IJanuaField);
    property Emailsent: IJanuaField read GetEmailsent write SetEmailsent;
    function GetEmailconfirmed: IJanuaField;
    procedure SetEmailconfirmed(const Value: IJanuaField);
    property Emailconfirmed: IJanuaField read GetEmailconfirmed write SetEmailconfirmed;
    function GetEmaildate: IJanuaField;
    procedure SetEmaildate(const Value: IJanuaField);
    property Emaildate: IJanuaField read GetEmaildate write SetEmaildate;
    function GetPayment: IJanuaField;
    procedure SetPayment(const Value: IJanuaField);
    property Payment: IJanuaField read GetPayment write SetPayment;
    function GetSocialID: IJanuaField;
    procedure SetSocialID(const Value: IJanuaField);
    property SocialID: IJanuaField read GetSocialID write SetSocialID;
    function GetSocialType: IJanuaField;
    procedure SetSocialType(const Value: IJanuaField);
    property SocialType: IJanuaField read GetSocialType write SetSocialType;
    function GetPaymentExpirationDate: IJanuaField;
    procedure SetPaymentExpirationDate(const Value: IJanuaField);
    property PaymentExpirationDate: IJanuaField read GetPaymentExpirationDate write SetPaymentExpirationDate;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
    function GetDeleted: IJanuaField;
    procedure SetDeleted(const Value: IJanuaField);
    property Deleted: IJanuaField read GetDeleted write SetDeleted;
  end;

  ICustomUsers = interface(IJanuaRecordSet)
    ['{60AAF026-3D8F-406C-B48B-6F8911C2277A}']
    function GetActive: IJanuaField;
    procedure SetActive(const Value: IJanuaField);
    property Active: IJanuaField read GetActive write SetActive;
    function GetEmail: IJanuaField;
    procedure SetEmail(const Value: IJanuaField);
    property Email: IJanuaField read GetEmail write SetEmail;
    function GetDbUserId: IJanuaField;
    procedure SetDbUserId(const Value: IJanuaField);
    property DbUserId: IJanuaField read GetDbUserId write SetDbUserId;
    function GetPassword: IJanuaField;
    procedure SetPassword(const Value: IJanuaField);
    property Password: IJanuaField read GetPassword write SetPassword;
    function GetUsername: IJanuaField;
    procedure SetUsername(const Value: IJanuaField);
    property Username: IJanuaField read GetUsername write SetUsername;
    function GetIsactive: IJanuaField;
    procedure SetIsactive(const Value: IJanuaField);
    property Isactive: IJanuaField read GetIsactive write SetIsactive;
    function GetVerifyToken: IJanuaField;
    procedure SetVerifyToken(const Value: IJanuaField);
    property VerifyToken: IJanuaField read GetVerifyToken write SetVerifyToken;
    function GetVerified: IJanuaField;
    procedure SetVerified(const Value: IJanuaField);
    property Verified: IJanuaField read GetVerified write SetVerified;
    function GetDefaultSchemaId: IJanuaField;
    procedure SetDefaultSchemaId(const Value: IJanuaField);
    property DefaultSchemaId: IJanuaField read GetDefaultSchemaId write SetDefaultSchemaId;
    function GetIspublic: IJanuaField;
    procedure SetIspublic(const Value: IJanuaField);
    property Ispublic: IJanuaField read GetIspublic write SetIspublic;
    function GetInternalKey: IJanuaField;
    procedure SetInternalKey(const Value: IJanuaField);
    property InternalKey: IJanuaField read GetInternalKey write SetInternalKey;
    function GetDefaultRoleId: IJanuaField;
    procedure SetDefaultRoleId(const Value: IJanuaField);
    property DefaultRoleId: IJanuaField read GetDefaultRoleId write SetDefaultRoleId;
    function GetSearchName: IJanuaField;
    procedure SetSearchName(const Value: IJanuaField);
    property SearchName: IJanuaField read GetSearchName write SetSearchName;
    function GetReverseSearch: IJanuaField;
    procedure SetReverseSearch(const Value: IJanuaField);
    property ReverseSearch: IJanuaField read GetReverseSearch write SetReverseSearch;
    function GetInsertDate: IJanuaField;
    procedure SetInsertDate(const Value: IJanuaField);
    property InsertDate: IJanuaField read GetInsertDate write SetInsertDate;
    function GetCountryId: IJanuaField;
    procedure SetCountryId(const Value: IJanuaField);
    property CountryId: IJanuaField read GetCountryId write SetCountryId;
    function GetMainProfileTypeId: IJanuaField;
    procedure SetMainProfileTypeId(const Value: IJanuaField);
    property MainProfileTypeId: IJanuaField read GetMainProfileTypeId write SetMainProfileTypeId;
    function GetMainProfileId: IJanuaField;
    procedure SetMainProfileId(const Value: IJanuaField);
    property MainProfileId: IJanuaField read GetMainProfileId write SetMainProfileId;
    function GetImageId: IJanuaField;
    procedure SetImageId(const Value: IJanuaField);
    property ImageId: IJanuaField read GetImageId write SetImageId;
    function GetImageUrl: IJanuaField;
    procedure SetImageUrl(const Value: IJanuaField);
    property ImageUrl: IJanuaField read GetImageUrl write SetImageUrl;
    function GetIsoLanguageCode: IJanuaField;
    procedure SetIsoLanguageCode(const Value: IJanuaField);
    property IsoLanguageCode: IJanuaField read GetIsoLanguageCode write SetIsoLanguageCode;
    function GetIsoCultureCode: IJanuaField;
    procedure SetIsoCultureCode(const Value: IJanuaField);
    property IsoCultureCode: IJanuaField read GetIsoCultureCode write SetIsoCultureCode;
    function GetUserFirstName: IJanuaField;
    procedure SetUserFirstName(const Value: IJanuaField);
    property UserFirstName: IJanuaField read GetUserFirstName write SetUserFirstName;
    function GetUserFamilyName: IJanuaField;
    procedure SetUserFamilyName(const Value: IJanuaField);
    property UserFamilyName: IJanuaField read GetUserFamilyName write SetUserFamilyName;
    function GetEmailsent: IJanuaField;
    procedure SetEmailsent(const Value: IJanuaField);
    property Emailsent: IJanuaField read GetEmailsent write SetEmailsent;
    function GetEmailconfirmed: IJanuaField;
    procedure SetEmailconfirmed(const Value: IJanuaField);
    property Emailconfirmed: IJanuaField read GetEmailconfirmed write SetEmailconfirmed;
    function GetEmaildate: IJanuaField;
    procedure SetEmaildate(const Value: IJanuaField);
    property Emaildate: IJanuaField read GetEmaildate write SetEmaildate;
    function GetPayment: IJanuaField;
    procedure SetPayment(const Value: IJanuaField);
    property Payment: IJanuaField read GetPayment write SetPayment;
    function GetPaymentExpirationDate: IJanuaField;
    procedure SetPaymentExpirationDate(const Value: IJanuaField);
    property PaymentExpirationDate: IJanuaField read GetPaymentExpirationDate write SetPaymentExpirationDate;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
    function GetDeleted: IJanuaField;
    procedure SetDeleted(const Value: IJanuaField);
    property Deleted: IJanuaField read GetDeleted write SetDeleted;
  end;

implementation

end.
