unit JOrm.Items.ItemDef.Intf;

interface

uses Janua.Orm.Intf;

type

  IItemDef = interface(IJanuaRecord)
    ['{14773691-2A8F-4FA0-84CC-7F16419D7D43}']
    function GetDbSchemaId: IJanuaField;
    procedure SetDbSchemaId(const Value: IJanuaField);
    property DbSchemaId: IJanuaField read GetDbSchemaId write SetDbSchemaId;
    function GetId: IJanuaField;
    procedure SetId(const Value: IJanuaField);
    property Id: IJanuaField read GetId write SetId;
    function GetCode: IJanuaField;
    procedure SetCode(const Value: IJanuaField);
    property Code: IJanuaField read GetCode write SetCode;
    function GetModel: IJanuaField;
    procedure SetModel(const Value: IJanuaField);
    property Model: IJanuaField read GetModel write SetModel;
    function GetDescription: IJanuaField;
    procedure SetDescription(const Value: IJanuaField);
    property Description: IJanuaField read GetDescription write SetDescription;
    function GetMainSupplierId: IJanuaField;
    procedure SetMainSupplierId(const Value: IJanuaField);
    property MainSupplierId: IJanuaField read GetMainSupplierId write SetMainSupplierId;
    function GetConventions: IJanuaField;
    procedure SetConventions(const Value: IJanuaField);
    property Conventions: IJanuaField read GetConventions write SetConventions;
    function GetSupplierCode: IJanuaField;
    procedure SetSupplierCode(const Value: IJanuaField);
    property SupplierCode: IJanuaField read GetSupplierCode write SetSupplierCode;
    function GetInsertDate: IJanuaField;
    procedure SetInsertDate(const Value: IJanuaField);
    property InsertDate: IJanuaField read GetInsertDate write SetInsertDate;
    function GetUpdateDate: IJanuaField;
    procedure SetUpdateDate(const Value: IJanuaField);
    property UpdateDate: IJanuaField read GetUpdateDate write SetUpdateDate;
    function GetInsId: IJanuaField;
    procedure SetInsId(const Value: IJanuaField);
    property InsId: IJanuaField read GetInsId write SetInsId;
    function GetUpdId: IJanuaField;
    procedure SetUpdId(const Value: IJanuaField);
    property UpdId: IJanuaField read GetUpdId write SetUpdId;
    function GetUserInsert: IJanuaField;
    procedure SetUserInsert(const Value: IJanuaField);
    property UserInsert: IJanuaField read GetUserInsert write SetUserInsert;
    function GetUserUpdate: IJanuaField;
    procedure SetUserUpdate(const Value: IJanuaField);
    property UserUpdate: IJanuaField read GetUserUpdate write SetUserUpdate;
    function GetLocal: IJanuaField;
    procedure SetLocal(const Value: IJanuaField);
    property Local: IJanuaField read GetLocal write SetLocal;
    function GetWildcard: IJanuaField;
    procedure SetWildcard(const Value: IJanuaField);
    property Wildcard: IJanuaField read GetWildcard write SetWildcard;
    function GetRefTypeId: IJanuaField;
    procedure SetRefTypeId(const Value: IJanuaField);
    property RefTypeId: IJanuaField read GetRefTypeId write SetRefTypeId;
    function GetPkgUnits: IJanuaField;
    procedure SetPkgUnits(const Value: IJanuaField);
    property PkgUnits: IJanuaField read GetPkgUnits write SetPkgUnits;
    function GetStatus: IJanuaField;
    procedure SetStatus(const Value: IJanuaField);
    property Status: IJanuaField read GetStatus write SetStatus;
    function GetReserved: IJanuaField;
    procedure SetReserved(const Value: IJanuaField);
    property Reserved: IJanuaField read GetReserved write SetReserved;
    function GetExtraFlag: IJanuaField;
    procedure SetExtraFlag(const Value: IJanuaField);
    property ExtraFlag: IJanuaField read GetExtraFlag write SetExtraFlag;
    function GetBranchId: IJanuaField;
    procedure SetBranchId(const Value: IJanuaField);
    property BranchId: IJanuaField read GetBranchId write SetBranchId;
    function GetMinHeigth: IJanuaField;
    procedure SetMinHeigth(const Value: IJanuaField);
    property MinHeigth: IJanuaField read GetMinHeigth write SetMinHeigth;
    function GetMaxHeigth: IJanuaField;
    procedure SetMaxHeigth(const Value: IJanuaField);
    property MaxHeigth: IJanuaField read GetMaxHeigth write SetMaxHeigth;
    function GetRepeats: IJanuaField;
    procedure SetRepeats(const Value: IJanuaField);
    property Repeats: IJanuaField read GetRepeats write SetRepeats;
    function GetPeriodic: IJanuaField;
    procedure SetPeriodic(const Value: IJanuaField);
    property Periodic: IJanuaField read GetPeriodic write SetPeriodic;
    function GetGuarantee: IJanuaField;
    procedure SetGuarantee(const Value: IJanuaField);
    property Guarantee: IJanuaField read GetGuarantee write SetGuarantee;
    function GetPromoPoints: IJanuaField;
    procedure SetPromoPoints(const Value: IJanuaField);
    property PromoPoints: IJanuaField read GetPromoPoints write SetPromoPoints;
    function GetPromoPointForfait: IJanuaField;
    procedure SetPromoPointForfait(const Value: IJanuaField);
    property PromoPointForfait: IJanuaField read GetPromoPointForfait write SetPromoPointForfait;
    function GetPromoGroup: IJanuaField;
    procedure SetPromoGroup(const Value: IJanuaField);
    property PromoGroup: IJanuaField read GetPromoGroup write SetPromoGroup;
    function GetPromo: IJanuaField;
    procedure SetPromo(const Value: IJanuaField);
    property Promo: IJanuaField read GetPromo write SetPromo;
    function GetBrandId: IJanuaField;
    procedure SetBrandId(const Value: IJanuaField);
    property BrandId: IJanuaField read GetBrandId write SetBrandId;
    function GetTypeId: IJanuaField;
    procedure SetTypeId(const Value: IJanuaField);
    property TypeId: IJanuaField read GetTypeId write SetTypeId;
    function GetTypeRefId: IJanuaField;
    procedure SetTypeRefId(const Value: IJanuaField);
    property TypeRefId: IJanuaField read GetTypeRefId write SetTypeRefId;
    function GetMunitId: IJanuaField;
    procedure SetMunitId(const Value: IJanuaField);
    property MunitId: IJanuaField read GetMunitId write SetMunitId;
    function GetFamilyId: IJanuaField;
    procedure SetFamilyId(const Value: IJanuaField);
    property FamilyId: IJanuaField read GetFamilyId write SetFamilyId;
    function GetIconfile: IJanuaField;
    procedure SetIconfile(const Value: IJanuaField);
    property Iconfile: IJanuaField read GetIconfile write SetIconfile;
    function GetBannerfile: IJanuaField;
    procedure SetBannerfile(const Value: IJanuaField);
    property Bannerfile: IJanuaField read GetBannerfile write SetBannerfile;
    function GetImagefile: IJanuaField;
    procedure SetImagefile(const Value: IJanuaField);
    property Imagefile: IJanuaField read GetImagefile write SetImagefile;
    function GetTitle: IJanuaField;
    procedure SetTitle(const Value: IJanuaField);
    property Title: IJanuaField read GetTitle write SetTitle;
    function GetSubtitle: IJanuaField;
    procedure SetSubtitle(const Value: IJanuaField);
    property Subtitle: IJanuaField read GetSubtitle write SetSubtitle;
    function GetLefimage: IJanuaField;
    procedure SetLefimage(const Value: IJanuaField);
    property Lefimage: IJanuaField read GetLefimage write SetLefimage;
    function GetRightimage: IJanuaField;
    procedure SetRightimage(const Value: IJanuaField);
    property Rightimage: IJanuaField read GetRightimage write SetRightimage;
    function GetItemRtftext: IJanuaField;
    procedure SetItemRtftext(const Value: IJanuaField);
    property ItemRtftext: IJanuaField read GetItemRtftext write SetItemRtftext;
    function GetItemText: IJanuaField;
    procedure SetItemText(const Value: IJanuaField);
    property ItemText: IJanuaField read GetItemText write SetItemText;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
  end;

  IItemsDefs = interface(IJanuaRecordSet)
    ['{42A5C94C-6E17-449A-BD3C-C815EB5951D3}']
    function GetDbSchemaId: IJanuaField;
    procedure SetDbSchemaId(const Value: IJanuaField);
    property DbSchemaId: IJanuaField read GetDbSchemaId write SetDbSchemaId;
    function GetId: IJanuaField;
    procedure SetId(const Value: IJanuaField);
    property Id: IJanuaField read GetId write SetId;
    function GetCode: IJanuaField;
    procedure SetCode(const Value: IJanuaField);
    property Code: IJanuaField read GetCode write SetCode;
    function GetModel: IJanuaField;
    procedure SetModel(const Value: IJanuaField);
    property Model: IJanuaField read GetModel write SetModel;
    function GetDescription: IJanuaField;
    procedure SetDescription(const Value: IJanuaField);
    property Description: IJanuaField read GetDescription write SetDescription;
    function GetMainSupplierId: IJanuaField;
    procedure SetMainSupplierId(const Value: IJanuaField);
    property MainSupplierId: IJanuaField read GetMainSupplierId write SetMainSupplierId;
    function GetConventions: IJanuaField;
    procedure SetConventions(const Value: IJanuaField);
    property Conventions: IJanuaField read GetConventions write SetConventions;
    function GetSupplierCode: IJanuaField;
    procedure SetSupplierCode(const Value: IJanuaField);
    property SupplierCode: IJanuaField read GetSupplierCode write SetSupplierCode;
    function GetInsertDate: IJanuaField;
    procedure SetInsertDate(const Value: IJanuaField);
    property InsertDate: IJanuaField read GetInsertDate write SetInsertDate;
    function GetUpdateDate: IJanuaField;
    procedure SetUpdateDate(const Value: IJanuaField);
    property UpdateDate: IJanuaField read GetUpdateDate write SetUpdateDate;
    function GetInsId: IJanuaField;
    procedure SetInsId(const Value: IJanuaField);
    property InsId: IJanuaField read GetInsId write SetInsId;
    function GetUpdId: IJanuaField;
    procedure SetUpdId(const Value: IJanuaField);
    property UpdId: IJanuaField read GetUpdId write SetUpdId;
    function GetUserInsert: IJanuaField;
    procedure SetUserInsert(const Value: IJanuaField);
    property UserInsert: IJanuaField read GetUserInsert write SetUserInsert;
    function GetUserUpdate: IJanuaField;
    procedure SetUserUpdate(const Value: IJanuaField);
    property UserUpdate: IJanuaField read GetUserUpdate write SetUserUpdate;
    function GetLocal: IJanuaField;
    procedure SetLocal(const Value: IJanuaField);
    property Local: IJanuaField read GetLocal write SetLocal;
    function GetWildcard: IJanuaField;
    procedure SetWildcard(const Value: IJanuaField);
    property Wildcard: IJanuaField read GetWildcard write SetWildcard;
    function GetRefTypeId: IJanuaField;
    procedure SetRefTypeId(const Value: IJanuaField);
    property RefTypeId: IJanuaField read GetRefTypeId write SetRefTypeId;
    function GetPkgUnits: IJanuaField;
    procedure SetPkgUnits(const Value: IJanuaField);
    property PkgUnits: IJanuaField read GetPkgUnits write SetPkgUnits;
    function GetStatus: IJanuaField;
    procedure SetStatus(const Value: IJanuaField);
    property Status: IJanuaField read GetStatus write SetStatus;
    function GetReserved: IJanuaField;
    procedure SetReserved(const Value: IJanuaField);
    property Reserved: IJanuaField read GetReserved write SetReserved;
    function GetExtraFlag: IJanuaField;
    procedure SetExtraFlag(const Value: IJanuaField);
    property ExtraFlag: IJanuaField read GetExtraFlag write SetExtraFlag;
    function GetBranchId: IJanuaField;
    procedure SetBranchId(const Value: IJanuaField);
    property BranchId: IJanuaField read GetBranchId write SetBranchId;
    function GetMinHeigth: IJanuaField;
    procedure SetMinHeigth(const Value: IJanuaField);
    property MinHeigth: IJanuaField read GetMinHeigth write SetMinHeigth;
    function GetMaxHeigth: IJanuaField;
    procedure SetMaxHeigth(const Value: IJanuaField);
    property MaxHeigth: IJanuaField read GetMaxHeigth write SetMaxHeigth;
    function GetRepeats: IJanuaField;
    procedure SetRepeats(const Value: IJanuaField);
    property Repeats: IJanuaField read GetRepeats write SetRepeats;
    function GetPeriodic: IJanuaField;
    procedure SetPeriodic(const Value: IJanuaField);
    property Periodic: IJanuaField read GetPeriodic write SetPeriodic;
    function GetGuarantee: IJanuaField;
    procedure SetGuarantee(const Value: IJanuaField);
    property Guarantee: IJanuaField read GetGuarantee write SetGuarantee;
    function GetPromoPoints: IJanuaField;
    procedure SetPromoPoints(const Value: IJanuaField);
    property PromoPoints: IJanuaField read GetPromoPoints write SetPromoPoints;
    function GetPromoPointForfait: IJanuaField;
    procedure SetPromoPointForfait(const Value: IJanuaField);
    property PromoPointForfait: IJanuaField read GetPromoPointForfait write SetPromoPointForfait;
    function GetPromoGroup: IJanuaField;
    procedure SetPromoGroup(const Value: IJanuaField);
    property PromoGroup: IJanuaField read GetPromoGroup write SetPromoGroup;
    function GetPromo: IJanuaField;
    procedure SetPromo(const Value: IJanuaField);
    property Promo: IJanuaField read GetPromo write SetPromo;
    function GetBrandId: IJanuaField;
    procedure SetBrandId(const Value: IJanuaField);
    property BrandId: IJanuaField read GetBrandId write SetBrandId;
    function GetTypeId: IJanuaField;
    procedure SetTypeId(const Value: IJanuaField);
    property TypeId: IJanuaField read GetTypeId write SetTypeId;
    function GetTypeRefId: IJanuaField;
    procedure SetTypeRefId(const Value: IJanuaField);
    property TypeRefId: IJanuaField read GetTypeRefId write SetTypeRefId;
    function GetMunitId: IJanuaField;
    procedure SetMunitId(const Value: IJanuaField);
    property MunitId: IJanuaField read GetMunitId write SetMunitId;
    function GetFamilyId: IJanuaField;
    procedure SetFamilyId(const Value: IJanuaField);
    property FamilyId: IJanuaField read GetFamilyId write SetFamilyId;
    function GetIconfile: IJanuaField;
    procedure SetIconfile(const Value: IJanuaField);
    property Iconfile: IJanuaField read GetIconfile write SetIconfile;
    function GetBannerfile: IJanuaField;
    procedure SetBannerfile(const Value: IJanuaField);
    property Bannerfile: IJanuaField read GetBannerfile write SetBannerfile;
    function GetImagefile: IJanuaField;
    procedure SetImagefile(const Value: IJanuaField);
    property Imagefile: IJanuaField read GetImagefile write SetImagefile;
    function GetTitle: IJanuaField;
    procedure SetTitle(const Value: IJanuaField);
    property Title: IJanuaField read GetTitle write SetTitle;
    function GetSubtitle: IJanuaField;
    procedure SetSubtitle(const Value: IJanuaField);
    property Subtitle: IJanuaField read GetSubtitle write SetSubtitle;
    function GetLefimage: IJanuaField;
    procedure SetLefimage(const Value: IJanuaField);
    property Lefimage: IJanuaField read GetLefimage write SetLefimage;
    function GetRightimage: IJanuaField;
    procedure SetRightimage(const Value: IJanuaField);
    property Rightimage: IJanuaField read GetRightimage write SetRightimage;
    function GetItemRtftext: IJanuaField;
    procedure SetItemRtftext(const Value: IJanuaField);
    property ItemRtftext: IJanuaField read GetItemRtftext write SetItemRtftext;
    function GetItemText: IJanuaField;
    procedure SetItemText(const Value: IJanuaField);
    property ItemText: IJanuaField read GetItemText write SetItemText;
    function GetJguid: IJanuaField;
    procedure SetJguid(const Value: IJanuaField);
    property Jguid: IJanuaField read GetJguid write SetJguid;
    function GetItemDef: IItemDef;
    procedure SetItemDef(const Value: IItemDef);
    property ItemDef: IItemDef read GetItemDef write SetItemDef;

  end;

implementation

end.
