-- FUNCTION: logistic.shipments_update(bigint, uuid, timestamp with time zone, timestamp without time zone, timestamp without time zone, integer, uuid, integer, integer, json, json, smallint, smallint, smallint, character, integer, character varying, character varying, integer, character varying, bigint, integer, character varying, character varying, integer, character varying, character varying, integer, text, integer, timestamp without time zone, smallint, integer, character varying, character varying, text, text, text, character, boolean, boolean, boolean, timestamp without time zone, timestamp without time zone, smallint, smallint, timestamp without time zone, boolean, boolean, boolean, boolean, character varying, timestamp without time zone, timestamp with time zone, timestamp with time zone, boolean, integer, character varying)

DROP FUNCTION IF EXISTS logistic.shipments_update(bigint, uuid, timestamp with time zone, timestamp without time zone, timestamp without time zone, integer, uuid, integer, integer, json, json, smallint, smallint, smallint, character, integer, character varying, character varying, integer, character varying, bigint, integer, character varying, character varying, integer, character varying, character varying, integer, text, integer, timestamp without time zone, smallint, integer, character varying, character varying, text, text, text, character, boolean, boolean, boolean, timestamp without time zone, timestamp without time zone, smallint, smallint, timestamp without time zone, boolean, boolean, boolean, boolean, character varying, timestamp without time zone, timestamp with time zone, timestamp with time zone, boolean, integer, character varying);

CREATE OR REPLACE FUNCTION logistic.shipments_update(
	p_id bigint,
	p_jguid uuid,
	p_creation_date timestamp with time zone,
	p_pickup_date timestamp without time zone,
	p_delivery_date timestamp without time zone,
	p_office_id integer,
	p_workflow_uid uuid,
	p_agent_id integer,
	p_shipper_id integer,
	p_shipper_address json,
	p_pickup_address json,
	p_year smallint,
	p_groupage_number smallint,
	p_export_type_id smallint,
	p_fullcontainer character,
	p_vessel_id integer,
	p_work_code character varying,
	p_travel_identification_code character varying,
	p_carrier_id integer,
	p_carrier_code character varying,
	p_workflow_id bigint,
	p_pol_id integer,
	p_pol_code character varying,
	p_pol_name character varying,
	p_pod_id integer,
	p_pod_name character varying,
	p_pod_code character varying,
	p_customer_id integer,
	p_notes text,
	p_warehouse_id integer,
	p_work_date timestamp without time zone,
	p_order_state smallint,
	p_airport_id integer,
	p_airport_code character varying,
	p_awb_number character varying,
	p_internal_notes text,
	p_internal_notes2 text,
	p_warehouse_notes text,
	p_route_type character,
	p_internet_visible boolean,
	p_flag_air boolean,
	p_flag_ground boolean,
	p_departure_date timestamp without time zone,
	p_arrival_date timestamp without time zone,
	p_po_state smallint,
	p_po_level smallint,
	p_final_date timestamp without time zone,
	p_flg_house boolean,
	p_flg_master boolean,
	p_delivered boolean,
	p_flg_billable boolean,
	p_customs_declearer character varying,
	p_customs_date timestamp without time zone,
	p_update_date timestamp with time zone,
	p_insert_date timestamp with time zone,
	p_deleted boolean,
	p_db_schema_id integer,
	p_carrier_name character varying,
    p_work_number integer)
    RETURNS bigint
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
BEGIN
  UPDATE logistic.shipments SET
    jguid = p_jguid,
    creation_date = p_creation_date,
    pickup_date = p_pickup_date,
    delivery_date = p_delivery_date,
    office_id = p_office_id,
    workflow_uid = p_workflow_uid,
    agent_id = p_agent_id,
    shipper_id = p_shipper_id,
    shipper_address = p_shipper_address,
    pickup_address = p_pickup_address,
    year = p_year,
    groupage_number = p_groupage_number,
    export_type_id = p_export_type_id,
    fullcontainer = p_fullcontainer,
    vessel_id = p_vessel_id,
    work_code = p_work_code,
    travel_identification_code = p_travel_identification_code,
    carrier_id = p_carrier_id,
    carrier_code = p_carrier_code,
    workflow_id = p_workflow_id,
    pol_id = p_pol_id,
    pol_code = p_pol_code,
    pol_name = p_pol_name,
    pod_id = p_pod_id,
    pod_name = p_pod_name,
    pod_code = p_pod_code,
    customer_id = p_customer_id,
    notes = p_notes,
    warehouse_id = p_warehouse_id,
    work_date = p_work_date,
    order_state = p_order_state,
    airport_id = p_airport_id,
    airport_code = p_airport_code,
    awb_number = p_awb_number,
    internal_notes = p_internal_notes,
    internal_notes2 = p_internal_notes2,
    warehouse_notes = p_warehouse_notes,
    route_type = p_route_type,
    internet_visible = p_internet_visible,
    flag_air = p_flag_air,
    flag_ground = p_flag_ground,
    departure_date = p_departure_date,
    arrival_date = p_arrival_date,
    po_state = p_po_state,
    po_level = p_po_level,
    final_date = p_final_date,
    flg_house = p_flg_house,
    flg_master = p_flg_master,
    delivered = p_delivered,
    flg_billable = p_flg_billable,
    customs_declearer = p_customs_declearer,
    customs_date = p_customs_date,
    update_date = p_update_date,
    insert_date = p_insert_date,
    deleted = p_deleted,
    db_schema_id = p_db_schema_id,
    carrier_name = p_carrier_name, 
	work_number = p_work_number
  WHERE 
    (id = p_id) ;
END;
$BODY$;

--ALTER FUNCTION logistic.shipments_update(bigint, uuid, timestamp with time zone, timestamp without time zone, timestamp without time zone, integer, uuid, integer, integer, json, json, smallint, smallint, smallint, character, integer, character varying, character varying, integer, character varying, bigint, integer, character varying, character varying, integer, character varying, character varying, integer, text, integer, timestamp without time zone, smallint, integer, character varying, character varying, text, text, text, character, boolean, boolean, boolean, timestamp without time zone, timestamp without time zone, smallint, smallint, timestamp without time zone, boolean, boolean, boolean, boolean, character varying, timestamp without time zone, timestamp with time zone, timestamp with time zone, boolean, integer, character varying, integer)
--    OWNER TO ergo;
