CREATE OR REPLACE FUNCTION anagraph.sp_sel_anagraphs ()
RETURNS refcursor
AS
$$
  DECLARE result_cursor REFCURSOR;
BEGIN
  OPEN result_cursor FOR SELECT 
    db_schema_id,
    anagraph_id,
    an_title,
    an_name,
    an_second_name,
    an_last_name,
    an_notes,
    an_address,
    an_town,
    an_postal_code,
    an_iso_country_code,
    an_state_province,
    an_phone,
    an_phone2,
    an_fax,
    an_cellular,
    an_code,
    an_vat_numeric,
    an_email,
    an_web,
    an_contact_id,
    an_bank_account,
    an_payment_des,
    an_discount,
    an_distance,
    an_distance_mesunit,
    an_sex,
    an_cod_comune,
    an_cod_provincia,
    an_credit_line,
    an_currency_id,
    an_cat_id,
    an_notes2,
    an_notes3,
    an_edi,
    an_privacy,
    an_office_id,
    an_cod_prov_rif,
    an_data_fido,
    an_user_insert,
    an_user_update,
    an_area_id,
    an_agent_id,
    an_area_code,
    an_zone_id,
    an_ins_id,
    an_upd_id,
    an_documents,
    an_last_date,
    an_birthdate,
    an_office_type_id,
    an_searchname,
    an_extra_ue_flag,
    an_external_code,
    an_vat_id,
    an_personal_fiscal_code,
    an_privacy_print,
    an_sms,
    an_encrypted_fiscal_code,
    an_vat_purcentage,
    an_status,
    an_ownsite,
    an_insurance_id,
    an_anagraphs_anagraph_id,
    an_main_language_code,
    an_main_culture_code,
    an_fiscal_code,
    an_main_group_id,
    an_image_id,
    latitude,
    longitude,
    test,
    search_index,
    an_birthplace,
    an_birthplace_code,
    anagraph64,
    main_category_id,
    osm_id,
    an_description,
    an_address_number,
    anag_jguid,
    anag_deleted,
    insert_date,
    update_date,
    user_insert,
    jguid,
    custom_field_1,
    custom_field_2,
    custom_field_3,
    custom_float_1,
    custom_float_2,
    custom_int_1,
    custom_int_2,
    supplier_id,
    vessel_id,
    an_country_id,
    an_iso_country_code2
  FROM 
    anagraph.anagraphs;
  RETURN result_cursor;
END;
$$
LANGUAGE 'plpgsql';



CREATE OR REPLACE FUNCTION anagraph.sp_upd_anagraphs ( 
  IN p_db_schema_id integer,
  IN p_anagraph_id integer,
  IN p_an_title varchar(32),
  IN p_an_name varchar(128),
  IN p_an_second_name varchar(128),
  IN p_an_last_name varchar(128),
  IN p_an_notes varchar(512),
  IN p_an_address varchar(256),
  IN p_an_town varchar(128),
  IN p_an_postal_code varchar(20),
  IN p_an_iso_country_code varchar(3),
  IN p_an_state_province varchar(128),
  IN p_an_phone varchar(30),
  IN p_an_phone2 varchar(20),
  IN p_an_fax varchar(30),
  IN p_an_cellular varchar(20),
  IN p_an_code varchar(15),
  IN p_an_vat_numeric varchar(128),
  IN p_an_email varchar(256),
  IN p_an_web varchar(128),
  IN p_an_contact_id integer,
  IN p_an_bank_account varchar(255),
  IN p_an_payment_des varchar(128),
  IN p_an_discount numeric(5,2),
  IN p_an_distance integer,
  IN p_an_distance_mesunit smallint,
  IN p_an_sex varchar(1),
  IN p_an_cod_comune varchar(3),
  IN p_an_cod_provincia varchar(3),
  IN p_an_credit_line numeric(14,2),
  IN p_an_currency_id smallint,
  IN p_an_cat_id smallint,
  IN p_an_notes2 varchar(40),
  IN p_an_notes3 text,
  IN p_an_edi boolean,
  IN p_an_privacy boolean,
  IN p_an_office_id smallint,
  IN p_an_cod_prov_rif varchar(3),
  IN p_an_data_fido date,
  IN p_an_user_insert varchar(30),
  IN p_an_user_update varchar(30),
  IN p_an_area_id smallint,
  IN p_an_agent_id smallint,
  IN p_an_area_code varchar(1),
  IN p_an_zone_id varchar(1),
  IN p_an_ins_id bigint,
  IN p_an_upd_id bigint,
  IN p_an_documents smallint,
  IN p_an_last_date date,
  IN p_an_birthdate date,
  IN p_an_office_type_id smallint,
  IN p_an_searchname varchar(128),
  IN p_an_extra_ue_flag boolean,
  IN p_an_external_code varchar(20),
  IN p_an_vat_id smallint,
  IN p_an_personal_fiscal_code varchar(16),
  IN p_an_privacy_print smallint,
  IN p_an_sms boolean,
  IN p_an_encrypted_fiscal_code varchar(256),
  IN p_an_vat_purcentage smallint,
  IN p_an_status smallint,
  IN p_an_ownsite boolean,
  IN p_an_insurance_id bigint,
  IN p_an_anagraphs_anagraph_id integer,
  IN p_an_main_language_code varchar(2),
  IN p_an_main_culture_code varchar(6),
  IN p_an_fiscal_code varchar(16),
  IN p_an_main_group_id integer,
  IN p_an_image_id bigint,
  IN p_latitude double precision,
  IN p_longitude double precision,
  IN p_test double precision,
  IN p_search_index varchar(2048),
  IN p_an_birthplace varchar(256),
  IN p_an_birthplace_code varchar(20),
  IN p_anagraph64 varchar(64),
  IN p_main_category_id smallint,
  IN p_osm_id bigint,
  IN p_an_description varchar(512),
  IN p_an_address_number varchar(20),
  IN p_anag_jguid varchar(40),
  IN p_anag_deleted boolean,
  IN p_insert_date timestamp without time zone,
  IN p_update_date timestamp without time zone,
  IN p_user_insert integer,
  IN p_jguid uuid,
  IN p_custom_field_1 varchar(128),
  IN p_custom_field_2 varchar(128),
  IN p_custom_field_3 varchar(128),
  IN p_custom_float_1 real,
  IN p_custom_float_2 real,
  IN p_custom_int_1 integer,
  IN p_custom_int_2 integer,
  IN p_supplier_id integer,
  IN p_vessel_id smallint,
  IN p_an_country_id integer,
  IN p_an_iso_country_code2 char(2)  
)
RETURNS integer
AS
$$
DECLARE
  v_count bigint; v_id bigint; v_jguid uuid;
BEGIN
  v_id := p_anagraph_id; 
  v_jguid := p_jguid; 
  
  if (v_id is null or v_id = 0) and (p_jguid is not null) then  
	 select 
         count(1), id
     into 
         v_count, v_id
	   from 
          anagraph.anagraph where jguid = v_jguid 
       group by id;  
  end if; 
   

  UPDATE anagraph.anagraphs SET
    db_schema_id = p_db_schema_id,
    an_title = p_an_title,
    an_name = p_an_name,
    an_second_name = p_an_second_name,
    an_last_name = p_an_last_name,
    an_notes = p_an_notes,
    an_address = p_an_address,
    an_town = p_an_town,
    an_postal_code = p_an_postal_code,
    an_iso_country_code = p_an_iso_country_code,
    an_state_province = p_an_state_province,
    an_phone = p_an_phone,
    an_phone2 = p_an_phone2,
    an_fax = p_an_fax,
    an_cellular = p_an_cellular,
    an_code = p_an_code,
    an_vat_numeric = p_an_vat_numeric,
    an_email = p_an_email,
    an_web = p_an_web,
    an_contact_id = p_an_contact_id,
    an_bank_account = p_an_bank_account,
    an_payment_des = p_an_payment_des,
    an_discount = p_an_discount,
    an_distance = p_an_distance,
    an_distance_mesunit = p_an_distance_mesunit,
    an_sex = p_an_sex,
    an_cod_comune = p_an_cod_comune,
    an_cod_provincia = p_an_cod_provincia,
    an_credit_line = p_an_credit_line,
    an_currency_id = p_an_currency_id,
    an_cat_id = p_an_cat_id,
    an_notes2 = p_an_notes2,
    an_notes3 = p_an_notes3,
    an_edi = p_an_edi,
    an_privacy = p_an_privacy,
    an_office_id = p_an_office_id,
    an_cod_prov_rif = p_an_cod_prov_rif,
    an_data_fido = p_an_data_fido,
    an_user_insert = p_an_user_insert,
    an_user_update = p_an_user_update,
    an_area_id = p_an_area_id,
    an_agent_id = p_an_agent_id,
    an_area_code = p_an_area_code,
    an_zone_id = p_an_zone_id,
    an_ins_id = p_an_ins_id,
    an_upd_id = p_an_upd_id,
    an_documents = p_an_documents,
    an_last_date = p_an_last_date,
    an_birthdate = p_an_birthdate,
    an_office_type_id = p_an_office_type_id,
    an_searchname = p_an_searchname,
    an_extra_ue_flag = p_an_extra_ue_flag,
    an_external_code = p_an_external_code,
    an_vat_id = p_an_vat_id,
    an_personal_fiscal_code = p_an_personal_fiscal_code,
    an_privacy_print = p_an_privacy_print,
    an_sms = p_an_sms,
    an_encrypted_fiscal_code = p_an_encrypted_fiscal_code,
    an_vat_purcentage = p_an_vat_purcentage,
    an_status = p_an_status,
    an_ownsite = p_an_ownsite,
    an_insurance_id = p_an_insurance_id,
    an_anagraphs_anagraph_id = p_an_anagraphs_anagraph_id,
    an_main_language_code = p_an_main_language_code,
    an_main_culture_code = p_an_main_culture_code,
    an_fiscal_code = p_an_fiscal_code,
    an_main_group_id = p_an_main_group_id,
    an_image_id = p_an_image_id,
    latitude = p_latitude,
    longitude = p_longitude,
    test = p_test,
    search_index = p_search_index,
    an_birthplace = p_an_birthplace,
    an_birthplace_code = p_an_birthplace_code,
    anagraph64 = p_anagraph64,
    main_category_id = p_main_category_id,
    osm_id = p_osm_id,
    an_description = p_an_description,
    an_address_number = p_an_address_number,
    anag_jguid = p_anag_jguid,
    anag_deleted = p_anag_deleted,
    insert_date = p_insert_date,
    update_date = p_update_date,
    user_insert = p_user_insert,
    jguid = p_jguid,
    custom_field_1 = p_custom_field_1,
    custom_field_2 = p_custom_field_2,
    custom_field_3 = p_custom_field_3,
    custom_float_1 = p_custom_float_1,
    custom_float_2 = p_custom_float_2,
    custom_int_1 = p_custom_int_1,
    custom_int_2 = p_custom_int_2,
    supplier_id = p_supplier_id,
    vessel_id = p_vessel_id,
    an_country_id = p_an_country_id,
    an_iso_country_code2 = p_an_iso_country_code2
  WHERE 
    (anagraph_id = v_id) ;
	
   return p_anagraph_id; 
END;
$$
LANGUAGE 'plpgsql';    
  



CREATE OR REPLACE FUNCTION anagraph.sp_del_anagraphs ( 
  IN p_anagraph_id integer  
)
RETURNS integer
AS
$$
BEGIN
  DELETE FROM anagraph.anagraphs
  WHERE 
    (anagraph_id = p_anagraph_id) ;
END;
$$
LANGUAGE 'plpgsql';