-- FUNCTION: anagraph.sp_ins_anagraphs(integer, integer, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, integer, character varying, character varying, numeric, integer, smallint, character varying, character varying, character varying, numeric, smallint, smallint, character varying, text, boolean, boolean, smallint, character varying, date, character varying, character varying, smallint, smallint, character varying, character varying, bigint, bigint, smallint, date, date, smallint, character varying, boolean, character varying, smallint, character varying, smallint, boolean, character varying, smallint, smallint, boolean, bigint, integer, character varying, character varying, character varying, integer, bigint, double precision, double precision, double precision, character varying, character varying, character varying, character varying, smallint, bigint, character varying, character varying, character varying, boolean, timestamp without time zone, timestamp without time zone, integer, uuid, character varying, character varying, character varying, real, real, integer, integer, integer, smallint, integer, character, character varying)

-- DROP FUNCTION IF EXISTS anagraph.sp_ins_anagraphs(integer, integer, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, integer, character varying, character varying, numeric, integer, smallint, character varying, character varying, character varying, numeric, smallint, smallint, character varying, text, boolean, boolean, smallint, character varying, date, character varying, character varying, smallint, smallint, character varying, character varying, bigint, bigint, smallint, date, date, smallint, character varying, boolean, character varying, smallint, character varying, smallint, boolean, character varying, smallint, smallint, boolean, bigint, integer, character varying, character varying, character varying, integer, bigint, double precision, double precision, double precision, character varying, character varying, character varying, character varying, smallint, bigint, character varying, character varying, character varying, boolean, timestamp without time zone, timestamp without time zone, integer, uuid, character varying, character varying, character varying, real, real, integer, integer, integer, smallint, integer, character, character varying);

CREATE OR REPLACE FUNCTION anagraph.sp_ins_anagraphs(
	p_db_schema_id integer,
	p_anagraph_id integer,
	p_an_title character varying,
	p_an_name character varying,
	p_an_second_name character varying,
	p_an_last_name character varying,
	p_an_notes character varying,
	p_an_address character varying,
	p_an_town character varying,
	p_an_postal_code character varying,
	p_an_iso_country_code character varying,
	p_an_state_province character varying,
	p_an_phone character varying,
	p_an_phone2 character varying,
	p_an_fax character varying,
	p_an_cellular character varying,
	p_an_code character varying,
	p_an_vat_numeric character varying,
	p_an_email character varying,
	p_an_web character varying,
	p_an_contact_id integer,
	p_an_bank_account character varying,
	p_an_payment_des character varying,
	p_an_discount numeric,
	p_an_distance integer,
	p_an_distance_mesunit smallint,
	p_an_sex character varying,
	p_an_cod_comune character varying,
	p_an_cod_provincia character varying,
	p_an_credit_line numeric,
	p_an_currency_id smallint,
	p_an_cat_id smallint,
	p_an_notes2 character varying,
	p_an_notes3 text,
	p_an_edi boolean,
	p_an_privacy boolean,
	p_an_office_id smallint,
	p_an_cod_prov_rif character varying,
	p_an_data_fido date,
	p_an_user_insert character varying,
	p_an_user_update character varying,
	p_an_area_id smallint,
	p_an_agent_id smallint,
	p_an_area_code character varying,
	p_an_zone_id character varying,
	p_an_ins_id bigint,
	p_an_upd_id bigint,
	p_an_documents smallint,
	p_an_last_date date,
	p_an_birthdate date,
	p_an_office_type_id smallint,
	p_an_searchname character varying,
	p_an_extra_ue_flag boolean,
	p_an_external_code character varying,
	p_an_vat_id smallint,
	p_an_personal_fiscal_code character varying,
	p_an_privacy_print smallint,
	p_an_sms boolean,
	p_an_encrypted_fiscal_code character varying,
	p_an_vat_purcentage smallint,
	p_an_status smallint,
	p_an_ownsite boolean,
	p_an_insurance_id bigint,
	p_an_anagraphs_anagraph_id integer,
	p_an_main_language_code character varying,
	p_an_main_culture_code character varying,
	p_an_fiscal_code character varying,
	p_an_main_group_id integer,
	p_an_image_id bigint,
	p_latitude double precision,
	p_longitude double precision,
	p_test double precision,
	p_search_index character varying,
	p_an_birthplace character varying,
	p_an_birthplace_code character varying,
	p_anagraph64 character varying,
	p_main_category_id smallint,
	p_osm_id bigint,
	p_an_description character varying,
	p_an_address_number character varying,
	p_anag_jguid character varying,
	p_anag_deleted boolean,
	p_insert_date timestamp without time zone,
	p_update_date timestamp without time zone,
	p_user_insert integer,
	p_jguid uuid,
	p_custom_field_1 character varying,
	p_custom_field_2 character varying,
	p_custom_field_3 character varying,
	p_custom_float_1 real,
	p_custom_float_2 real,
	p_custom_int_1 integer,
	p_custom_int_2 integer,
	p_supplier_id integer,
	p_vessel_id smallint,
	p_an_country_id integer,
	p_an_iso_country_code2 character,
	p_an_full_address character varying)
    RETURNS integer
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$

DECLARE
  v_count integer; v_id integer; v_jguid uuid; v_vessel_id integer; v_full_address character varying;
BEGIN
  v_count := 0; 
  v_id := p_anagraph_id;
  
  if v_id is null or v_id = 0 then
    v_id:=nextval('anagraph.an_anagraph_seq');
  end if; 
  
  v_jguid := p_jguid; 
  
  if v_jguid is null then
     v_jguid := '{' || public.uuid_generate_v1mc() || '}';
  end if; 
  
  if p_vessel_id = 0 then v_vessel_id := null; else v_vessel_id := p_vessel_id; end if; 
  
  v_full_address := 
  	CASE WHEN p_full_address IS NULL THEN
	     p_an_address || ',' || p_an_postal_code || ',' || p_an_town || ',' || p_an_state_province
	  ELSE
	  	p_an_full_address 
	END;
  
  
  INSERT INTO anagraph.anagraphs (
    db_schema_id,	
    anagraph_id,
    an_title,
    an_name,
    an_second_name,
    an_last_name,
    an_notes,
    an_address,
    an_town,
    an_postal_code,
    an_iso_country_code,
    an_state_province,
    an_phone,
    an_phone2,
    an_fax,
    an_cellular,
    an_code,
    an_vat_numeric,
    an_email,
    an_web,
    an_contact_id,
    an_bank_account,
    an_payment_des,
    an_discount,
    an_distance,
    an_distance_mesunit,
    an_sex,
    an_cod_comune,
    an_cod_provincia,
    an_credit_line,
    an_currency_id,
    an_cat_id,
    an_notes2,
    an_notes3,
    an_edi,
    an_privacy,
    an_office_id,
    an_cod_prov_rif,
    an_data_fido,
    an_user_insert,
    an_user_update,
    an_area_id,
    an_agent_id,
    an_area_code,
    an_zone_id,
    an_ins_id,
    an_upd_id,
    an_documents,
    an_last_date,
    an_birthdate,
    an_office_type_id,
    an_searchname,
    an_extra_ue_flag,
    an_external_code,
    an_vat_id,
    an_personal_fiscal_code,
    an_privacy_print,
    an_sms,
    an_encrypted_fiscal_code,
    an_vat_purcentage,
    an_status,
    an_ownsite,
    an_insurance_id,
    an_anagraphs_anagraph_id,
    an_main_language_code,
    an_main_culture_code,
    an_fiscal_code,
    an_main_group_id,
    an_image_id,
    latitude,
    longitude,
    test,
    search_index,
    an_birthplace,
    an_birthplace_code,
    anagraph64,
    main_category_id,
    osm_id,
    an_description,
    an_address_number,
    anag_jguid,
    anag_deleted,
    insert_date,
    update_date,
    user_insert,
    jguid,
    custom_field_1,
    custom_field_2,
    custom_field_3,
    custom_float_1,
    custom_float_2,
    custom_int_1,
    custom_int_2,
    supplier_id,
    vessel_id,
    an_country_id,
    an_iso_country_code2,
	p_an_full_address
  )
  values( 
    p_db_schema_id,
    case when v_id = 0 then NULL else v_id end,
    p_an_title,
    p_an_name,
    p_an_second_name,
    p_an_last_name,
    p_an_notes,
    p_an_address,
    p_an_town,
    p_an_postal_code,
    p_an_iso_country_code,
    p_an_state_province,
    p_an_phone,
    p_an_phone2,
    p_an_fax,
    p_an_cellular,
    p_an_code,
    p_an_vat_numeric,
    p_an_email,
    p_an_web,
    case when p_an_contact_id = 0 then NULL else p_an_contact_id end,
    p_an_bank_account,
    p_an_payment_des,
    p_an_discount,
    p_an_distance,
    p_an_distance_mesunit,
    p_an_sex,
    p_an_cod_comune,
    p_an_cod_provincia,
    p_an_credit_line,
    case when p_an_currency_id = 0 then NULL else p_an_currency_id end,
    case when p_an_cat_id = 0 then NULL else p_an_cat_id end,
    p_an_notes2,
    p_an_notes3,
    p_an_edi,
    p_an_privacy,
    case when p_an_office_id = 0 then NULL else p_an_office_id end,
    p_an_cod_prov_rif,
    p_an_data_fido,
    p_an_user_insert,
    p_an_user_update,
    case when p_an_area_id = 0 then NULL else p_an_area_id end,
    case when p_an_agent_id = 0 then NULL else p_an_agent_id end,
    p_an_area_code,
    case when p_an_zone_id = '' then NULL else p_an_zone_id end,
    case when p_an_ins_id = 0 then NULL else p_an_ins_id end,
    case when p_an_upd_id = 0 then NULL else p_an_upd_id end,
    p_an_documents,
    p_an_last_date,
    p_an_birthdate,
    case when p_an_office_type_id = 0 then NULL else p_an_office_type_id end,
    p_an_searchname,
    p_an_extra_ue_flag,
    p_an_external_code,
    case when p_an_vat_id = 0 then NULL else p_an_vat_id end,
    p_an_personal_fiscal_code,
    p_an_privacy_print,
    p_an_sms,
    p_an_encrypted_fiscal_code,
    p_an_vat_purcentage,
    p_an_status,
    p_an_ownsite,
    case when p_an_insurance_id = 0 then NULL else p_an_insurance_id end,
    case when p_an_anagraphs_anagraph_id = 0 then NULL else p_an_anagraphs_anagraph_id end,
    p_an_main_language_code,
    p_an_main_culture_code,
    p_an_fiscal_code,
    p_an_main_group_id,
    case when p_an_image_id = 0 then NULL else p_an_image_id end,
    p_latitude,
    p_longitude,
    p_test,
    p_search_index,
    p_an_birthplace,
    p_an_birthplace_code,
    p_anagraph64,
    case when p_main_category_id = 0 then NULL else p_main_category_id end,
    case when p_osm_id = 0 then NULL else p_osm_id end,
    p_an_description,
    p_an_address_number,
    p_anag_jguid,
    p_anag_deleted,
    p_insert_date,
    p_update_date,
    p_user_insert,
    v_jguid,
    p_custom_field_1,
    p_custom_field_2,
    p_custom_field_3,
    p_custom_float_1,
    p_custom_float_2,
    p_custom_int_1,
    p_custom_int_2,
    case when p_supplier_id = 0 then NULL else p_supplier_id end,
    case when v_vessel_id = 0 then NULL else v_vessel_id end,
    case when p_an_country_id = 0 then NULL else p_an_country_id end,
    p_an_iso_country_code2,
	p_an_full_address
	)
  ;
  
  return v_id; 
END;
$BODY$;

ALTER FUNCTION anagraph.sp_ins_anagraphs(integer, integer, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, integer, character varying, character varying, numeric, integer, smallint, character varying, character varying, character varying, numeric, smallint, smallint, character varying, text, boolean, boolean, smallint, character varying, date, character varying, character varying, smallint, smallint, character varying, character varying, bigint, bigint, smallint, date, date, smallint, character varying, boolean, character varying, smallint, character varying, smallint, boolean, character varying, smallint, smallint, boolean, bigint, integer, character varying, character varying, character varying, integer, bigint, double precision, double precision, double precision, character varying, character varying, character varying, character varying, smallint, bigint, character varying, character varying, character varying, boolean, timestamp without time zone, timestamp without time zone, integer, uuid, character varying, character varying, character varying, real, real, integer, integer, integer, smallint, integer, character, character varying)
    OWNER TO ergo;
