inherited dmTestWhatsAppWebBrokerService: TdmTestWhatsAppWebBrokerService
  inherited JanuaWebBrokerServerManager1: TJanuaWebBrokerServerManager
    OnBeforeStartServer = JanuaWebBrokerServerManager1BeforeStartServer
  end
end
