SET TERM ^ ;

create or alter procedure SET_STATINI_STATO
as
begin
    UPDATE STATINI SET STATO = 0 WHERE STATO IS NULL;
    UPDATE STATINI SET STATO = 9 WHERE DATA_INTERVENTO IS NOT NULL AND STATO <> 9;
    UPDATE STATINI SET STATO = 9 WHERE DATA_CHIUSURA_DA_SERVER IS NOT NULL AND STATO <> 9;
    UPDATE STATINI SET STATO = 4 WHERE STATO_LAVORAZIONE = 'R' AND STATO <> 9;
    UPDATE STATINI SET STATO = 5 WHERE STATO_LAVORAZIONE = 'P' AND STATO <> 9;
end^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT SELECT,UPDATE ON STATINI TO PROCEDURE SET_STATINI_STATO;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE SET_STATINI_STATO TO SYSDBA;

