CREATE OR ALTER VIEW INTERVENTI_STATINI_SINTESI_VIEW(
    STATINO,
    ESTINTORI_ORDINARIO,
    ESTINTORI_STRAORDINARIO,
    GRUPPI_ELETTR,
    FUMI,
    LUCI,
    IDRANTI,
    SPRINKLER,
    IMPIANTI_EL)
AS
SELECT   STATINO,
 SUM (ESTINTORI_ORDINARIO) AS ESTINTORI_ORDINARIO,
 SUM (ESTINTORI_STRAORDINARIO) AS ESTINTORI_STRAORDINARIO,
 SUM (GRUPPI_ELETTR) AS GRUPPI_ELETTR,
 SUM (FUMI) AS FUMI,
 SUM (LUCI) AS LUCI,
 SUM (IDRANTI) AS IDRANTI,
 SUM (SPRINKLER) AS SPRINKLER,
 SUM (SPRINKLER) AS IMPIANTI_EL
FROM
(
Select STATINO,
  CASE WHEN INTERVENTO = 'Estintori' THEN ORDINARIO ELSE 0 END AS ESTINTORI_ORDINARIO,
  CASE WHEN INTERVENTO = 'Estintori' THEN STRAORDINARIO ELSE 0 END AS ESTINTORI_STRAORDINARIO,
  CASE WHEN INTERVENTO = 'Gruppi Elettr.' THEN NUMERO ELSE 0 END AS GRUPPI_ELETTR,
  CASE WHEN INTERVENTO = 'Fumi' THEN NUMERO ELSE 0 END AS FUMI,
  CASE WHEN INTERVENTO = 'Luci' THEN NUMERO ELSE 0 END AS LUCI,
  CASE WHEN INTERVENTO = 'Porte' THEN NUMERO ELSE 0 END AS PORTE,
  CASE WHEN INTERVENTO = 'Idranti' THEN NUMERO ELSE 0 END AS IDRANTI,
  CASE WHEN INTERVENTO = 'Sprinkler' THEN NUMERO ELSE 0 END AS SPRINKLER,
  CASE WHEN INTERVENTO = 'Impianti El.' THEN NUMERO ELSE 0 END AS IMPIANTI_EL
from INTERVENTI_STATINI
) A
GROUP BY STATINO
;