// CodeGear C++Builder
// Copyright (c) 1995, 2022 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'ipstudiowinwordxp.dpk' rev: 36.00 (Windows)

#ifndef IpstudiowinwordxpHPP
#define IpstudiowinwordxpHPP

#pragma delphiheader begin
#pragma option push
#if defined(__BORLANDC__) && !defined(__clang__)
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#endif
#pragma pack(push,8)
#include <System.hpp>	// (rtl)
#include <SysInit.hpp>
#include <vcl.wwrichedspellxp.hpp>
#include <System.Types.hpp>	// (rtl)
#include <System.UITypes.hpp>	// (rtl)
#include <Winapi.Windows.PkgHelper.hpp>	// (rtl)
#include <Winapi.Windows.hpp>	// (rtl)
#include <Winapi.Messages.hpp>	// (rtl)
#include <System.SysConst.hpp>	// (rtl)
#include <Winapi.ImageHlp.hpp>	// (rtl)
#include <Winapi.SHFolder.hpp>	// (rtl)
#include <Winapi.PsAPI.hpp>	// (rtl)
#include <System.RTLConsts.hpp>	// (rtl)
#include <System.Character.hpp>	// (rtl)
#include <System.Internal.ExcUtils.hpp>	// (rtl)
#include <System.SysUtils.hpp>	// (rtl)
#include <System.VarUtils.hpp>	// (rtl)
#include <System.Variants.hpp>	// (rtl)
#include <Winapi.ActiveX.hpp>	// (rtl)
#include <System.TypInfo.hpp>	// (rtl)
#include <System.Hash.hpp>	// (rtl)
#include <System.Math.hpp>	// (rtl)
#include <System.Generics.Defaults.hpp>	// (rtl)
#include <System.Generics.Collections.hpp>	// (rtl)
#include <System.TimeSpan.hpp>	// (rtl)
#include <System.Diagnostics.hpp>	// (rtl)
#include <System.SyncObjs.hpp>	// (rtl)
#include <System.Rtti.hpp>	// (rtl)
#include <System.Classes.hpp>	// (rtl)
#include <System.MaskUtils.hpp>	// (rtl)
#include <System.DateUtils.hpp>	// (rtl)
#include <Data.DBConsts.hpp>	// (dbrtl)
#include <System.StrUtils.hpp>	// (rtl)
#include <Data.SqlTimSt.hpp>	// (dbrtl)
#include <Data.FmtBcd.hpp>	// (dbrtl)
#include <Data.DBCommonTypes.hpp>	// (dbrtl)
#include <Data.DB.hpp>	// (dbrtl)
#include <Winapi.Wincodec.hpp>	// (rtl)
#include <Winapi.CommCtrl.hpp>	// (rtl)
#include <Winapi.Qos.hpp>	// (rtl)
#include <Winapi.Winsock2.hpp>	// (rtl)
#include <Winapi.IpExport.hpp>	// (rtl)
#include <Winapi.ShellAPI.hpp>	// (rtl)
#include <Winapi.RegStr.hpp>	// (rtl)
#include <Winapi.WinInet.hpp>	// (rtl)
#include <Winapi.UrlMon.hpp>	// (rtl)
#include <Winapi.ObjectArray.hpp>	// (rtl)
#include <Winapi.StructuredQueryCondition.hpp>	// (rtl)
#include <Winapi.PropSys.hpp>	// (rtl)
#include <Winapi.MSXMLIntf.hpp>	// (rtl)
#include <Winapi.ShlObj.hpp>	// (rtl)
#include <Winapi.KnownFolders.hpp>	// (rtl)
#include <System.Masks.hpp>	// (rtl)
#include <System.IOUtils.hpp>	// (rtl)
#include <System.IniFiles.hpp>	// (rtl)
#include <System.Win.Registry.hpp>	// (rtl)
#include <System.UIConsts.hpp>	// (rtl)
#include <Vcl.Consts.hpp>	// (vcl)
#include <Vcl.Graphics.hpp>	// (vcl)
#include <Winapi.MultiMon.hpp>	// (rtl)
#include <System.Contnrs.hpp>	// (rtl)
#include <System.ImageList.hpp>	// (rtl)
#include <System.Messaging.hpp>	// (rtl)
#include <System.Actions.hpp>	// (rtl)
#include <Winapi.Imm.hpp>	// (rtl)
#include <Vcl.ActnList.hpp>	// (vcl)
#include <System.HelpIntfs.hpp>	// (rtl)
#include <Winapi.UxTheme.hpp>	// (rtl)
#include <Winapi.Dwmapi.hpp>	// (rtl)
#include <System.AnsiStrings.hpp>	// (rtl)
#include <System.Win.Crtl.hpp>	// (rtl)
#include <System.ZLib.hpp>	// (rtl)
#include <Vcl.GraphUtil.hpp>	// (vcl)
#include <Vcl.StdCtrls.hpp>	// (vcl)
#include <Vcl.Clipbrd.hpp>	// (vcl)
#include <Vcl.Mask.hpp>	// (vcl)
#include <Winapi.CommDlg.hpp>	// (rtl)
#include <Winapi.WinSpool.hpp>	// (rtl)
#include <Vcl.Printers.hpp>	// (vcl)
#include <Winapi.RichEdit.hpp>	// (rtl)
#include <Vcl.ToolWin.hpp>	// (vcl)
#include <Vcl.ListActns.hpp>	// (vcl)
#include <Vcl.ComStrs.hpp>	// (vcl)
#include <Vcl.StdActns.hpp>	// (vcl)
#include <Vcl.ComCtrls.hpp>	// (vcl)
#include <System.WideStrUtils.hpp>	// (rtl)
#include <Winapi.Dlgs.hpp>	// (rtl)
#include <Vcl.Dialogs.hpp>	// (vcl)
#include <Vcl.ExtCtrls.hpp>	// (vcl)
#include <Vcl.Themes.hpp>	// (vcl)
#include <System.Win.ComConst.hpp>	// (rtl)
#include <System.Win.ComObj.hpp>	// (rtl)
#include <System.Win.Taskbar.hpp>	// (rtl)
#include <System.Win.TaskbarCore.hpp>	// (rtl)
#include <Winapi.ShellScaling.hpp>	// (rtl)
#include <Winapi.Wtsapi32.hpp>	// (rtl)
#include <Winapi.FlatSB.hpp>	// (rtl)
#include <Vcl.Forms.hpp>	// (vcl)
#include <Vcl.ImgList.hpp>	// (vcl)
#include <Vcl.Menus.hpp>	// (vcl)
#include <Winapi.TpcShrd.hpp>	// (rtl)
#include <Winapi.MsCTF.PkgHelper.hpp>	// (rtl)
#include <Winapi.MsCTF.hpp>	// (rtl)
#include <Winapi.MsInkAut.hpp>	// (rtl)
#include <Winapi.PenInputPanel.hpp>	// (rtl)
#include <Vcl.Controls.hpp>	// (vcl)
#include <Vcl.Buttons.hpp>	// (vcl)
#include <Vcl.BaseImageCollection.hpp>	// (vclwinx)
#include <Vcl.ImageCollection.hpp>	// (vclwinx)
#include <Vcl.VDBConsts.hpp>	// (vcldb)
#include <Vcl.DBLogDlg.hpp>	// (vcldb)
#include <Vcl.DBPWDlg.hpp>	// (vcldb)
#include <Vcl.VirtualImageList.hpp>	// (vclwinx)
#include <Vcl.DBCtrls.hpp>	// (vcldb)
#include <vcl.wwdialog.hpp>	// (ipstudiowin)
#include <Vcl.Grids.hpp>	// (vcl)
#include <vcl.wwmemo.hpp>	// (ipstudiowin)
#include <vcl.Wwsystem.hpp>	// (ipstudiowin)
#include <vcl.wwmonthcalendar.hpp>	// (ipstudiowin)
#include <vcl.wwcombobutton.hpp>	// (ipstudiowin)
#include <vcl.wwdbdatetimepicker.hpp>	// (ipstudiowin)
#include <vcl.wwmenuitem.hpp>	// (ipstudiowin)
#include <vcl.wwtreeview.hpp>	// (ipstudiowin)
#include <vcl.wwdblook.hpp>	// (ipstudiowin)
#include <vcl.wwpict.hpp>	// (ipstudiowin)
#include <vcl.wwdotdot.hpp>	// (ipstudiowin)
#include <vcl.wwdbedit.hpp>	// (ipstudiowin)
#include <vcl.wwinputstring.hpp>	// (ipstudiowin)
#include <vcl.wwinputstring2.hpp>	// (ipstudiowin)
#include <vcl.wwdatsrc.hpp>	// (ipstudiowin)
#include <vcl.Wwfltdum.hpp>	// (ipstudiowin)
#include <Vcl.Tabs.hpp>	// (vcl)
#include <vcl.wwhistorylist.hpp>	// (ipstudiowin)
#include <vcl.wwdbcomb.hpp>	// (ipstudiowin)
#include <vcl.wwclearbuttongroup.hpp>	// (ipstudiowin)
#include <vcl.wwradiogroup.hpp>	// (ipstudiowin)
#include <System.WideStrings.hpp>	// (rtl)
#include <vcl.wwfltvw.hpp>	// (ipstudiowin)
#include <vcl.wwfltdlg.hpp>	// (ipstudiowin)
#include <Vcl.CheckLst.hpp>	// (vclx)
#include <vcl.wwgridselectcolumns.hpp>	// (ipstudiowin)
#include <vcl.wwgridfilter.hpp>	// (ipstudiowin)
#include <vcl.wwchangelink.hpp>	// (ipstudiowin)
#include <vcl.Wwbitmap.hpp>	// (ipstudiowin)
#include <vcl.wwtext.hpp>	// (ipstudiowin)
#include <vcl.wwspeedbutton.hpp>	// (ipstudiowin)
#include <vcl.wwtoolbar.hpp>	// (ipstudiowin)
#include <vcl.wwbutton.hpp>	// (ipstudiowin)
#include <vcl.wwpaintoptions.hpp>	// (ipstudiowin)
#include <vcl.wwimagecombo.hpp>	// (ipstudiowin)
#include <vcl.wwdbigrd.hpp>	// (ipstudiowin)
#include <vcl.wwexport.hpp>	// (ipstudiowin)
#include <vcl.wwdbgrid.hpp>	// (ipstudiowin)
#include <vcl.wwcheckbox.hpp>	// (ipstudiowin)
#include <vcl.wwradiobutton.hpp>	// (ipstudiowin)
#include <vcl.wwlocate.hpp>	// (ipstudiowin)
#include <System.RegularExpressionsAPI.hpp>	// (rtl)
#include <System.RegularExpressionsConsts.hpp>	// (rtl)
#include <System.RegularExpressionsCore.hpp>	// (rtl)
#include <System.RegularExpressions.hpp>	// (rtl)
#include <vcl.Wwcommon.hpp>	// (ipstudiowin)
#include <vcl.wwframe.hpp>	// (ipstudiowin)
#include <vcl.wwcollection.hpp>	// (ipstudiowin)
#include <vcl.wwclearpanel.hpp>	// (ipstudiowin)
#include <vcl.wwkeycb.hpp>	// (ipstudiowin)
#include <vcl.wwdbdlg.hpp>	// (ipstudiowin)
#include <vcl.wwidlg.hpp>	// (ipstudiowin)
#include <vcl.wwdbnavigator.hpp>	// (ipstudiowin)
#include <vcl.wwrcdvw.hpp>	// (ipstudiowin)
#include <vcl.wwrcdpnl.hpp>	// (ipstudiowin)
#include <Vcl.CategoryButtons.hpp>	// (vcl)
#include <Vcl.ButtonGroup.hpp>	// (vcl)
#include <Vcl.SysStyles.hpp>	// (vcl)
#include <Winapi.DxgiFormat.hpp>	// (rtl)
#include <Winapi.DXTypes.hpp>	// (rtl)
#include <Winapi.DxgiType.hpp>	// (rtl)
#include <Winapi.DXGI.hpp>	// (rtl)
#include <Winapi.D3DCommon.hpp>	// (rtl)
#include <Winapi.D2D1.hpp>	// (rtl)
#include <Vcl.Direct2D.hpp>	// (vcl)
#include <Vcl.StyleBitmap.hpp>	// (vcl)
#include <Vcl.StyleAPI.hpp>	// (vcl)
#include <Vcl.Styles.hpp>	// (vcl)
#include <vcl.wwFixStyleForHiRes.hpp>	// (ipstudiowin)
#include <vcl.wwintl.hpp>	// (ipstudiowin)
#include <vcl.wwtypes.hpp>	// (ipstudiowin)
#include <vcl.Wwstr.hpp>	// (ipstudiowin)
#include <vcl.Wwtrackicon.hpp>	// (ipstudiowin)
#include <vcl.wwrichole.hpp>	// (ipstudiowin)
#include <Winapi.OleDlg.hpp>	// (rtl)
#include <Vcl.OleConst.hpp>	// (vcl)
#include <Vcl.OleCtnrs.hpp>	// (vcl)
#include <Vcl.FileCtrl.hpp>	// (vclx)
#include <vcl.wwrtfconverter.hpp>	// (ipstudiowin)
#include <Vcl.DBGrids.hpp>	// (vcldb)
#include <vcl.wwrchdlg.hpp>	// (ipstudiowin)
#include <vcl.Wwrichtb.hpp>	// (ipstudiowin)
#include <Winapi.oleacc.hpp>	// (rtl)
#include <Vcl.ExtDlgs.hpp>	// (vcl)
#include <Winapi.Mapi.hpp>	// (rtl)
#include <Vcl.ExtActns.hpp>	// (vcl)
#include <Vcl.ActnColorMaps.hpp>	// (vclactnband)
#include <Vcl.ActnCtrls.hpp>	// (vclactnband)
#include <Vcl.ShadowWnd.hpp>	// (vclactnband)
#include <Vcl.ABAccessibility.hpp>	// (vclactnband)
#include <Winapi.MMSystem.hpp>	// (rtl)
#include <Vcl.ActnMenus.hpp>	// (vclactnband)
#include <Vcl.ActnMan.hpp>	// (vclactnband)
#include <Vcl.XPActnCtrls.hpp>	// (vclactnband)
#include <Vcl.StdActnMenus.hpp>	// (vclactnband)
#include <Vcl.ThemedActnCtrls.hpp>	// (vclactnband)
#include <Vcl.PlatformDefaultStyleActnCtrls.hpp>	// (vclactnband)
#include <Vcl.ActnPopup.hpp>	// (vclactnband)
#include <vcl.wwricheditbar.hpp>	// (ipstudiowin)
#include <vcl.wwrich.hpp>	// (ipstudiowin)
#include <vcl.wwricholecallback.hpp>	// (ipstudiowin)
#include <vcl.wwrichobjinfo.hpp>	// (ipstudiowin)
#include <vcl.wwspin.hpp>	// (ipstudiowin)
#include <vcl.wwdbspin.hpp>	// (ipstudiowin)
#include <vcl.wwrtfprintpreview.hpp>	// (ipstudiowin)
#include <vcl.wwriched.hpp>	// (ipstudiowin)
#include <Vcl.OleServer.hpp>	// (vcl)
#include <System.Win.StdVCL.hpp>	// (rtl)
#include <OfficeXP.hpp>	// (OfficeXPrt)
#include <VBIDEXP.hpp>	// (OfficeXPrt)
#include <WordXP.hpp>	// (OfficeXPrt)
// SO_SFX: 290
// PRG_EXT: .bpl
// BPI_DIR: ..\Lib\22.0\Win64
// OBJ_DIR: ..\lib\22.0\Win64
// OBJ_EXT: .o

//-- user supplied -----------------------------------------------------------

namespace Ipstudiowinwordxp
{
//-- forward type declarations -----------------------------------------------
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------
}	/* namespace Ipstudiowinwordxp */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_IPSTUDIOWINWORDXP)
using namespace Ipstudiowinwordxp;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// IpstudiowinwordxpHPP
