CREATE TABLE public.TABOPER
(
  USERNAME        VARCHAR2(320 )            NOT NULL,
  FULLNAME        VARCHAR2(60 ),
  DEFLEVEL        NUMBER(5),
  PSWBO           VARCHAR2(100 ),
  VALE_DA         DATE,
  VALE_A          DATE,
  COD_CANAL       VARCHAR2(10 ),
  COD_FIL         VARCHAR2(10 ),
  TELEFONO        VARCHAR2(25 ),
  FAX             VARCHAR2(25 ),
  E_MAIL          VARCHAR2(4000 ),
  SPVRPRICING     NUMBER(1)                     DEFAULT 0                     NOT NULL,
  SPVRFIDO        NUMBER(1)                     DEFAULT 0                     NOT NULL,
  CELLULARE       VARCHAR2(25 ),
  FLAG_GESTORE    NUMBER(1)                     DEFAULT 0                     NOT NULL,
  FLAG_CLIENTE    NUMBER(1)                     DEFAULT 0                     NOT NULL,
  FLAG_PROVIDER   NUMBER(1)                     DEFAULT 0                     NOT NULL,
  FLAG_CALLCNTR   NUMBER(1)                     DEFAULT 0                     NOT NULL,
  FLAG_VENDOR     NUMBER(1)                     DEFAULT 0                     NOT NULL,
  NPRATICHEMAX    NUMBER(9),
  FLAG_RECUP      NUMBER(1)                     DEFAULT 0                     NOT NULL,
  PSWWEB          VARCHAR2(100 ),
  MAILUSERID      VARCHAR2(80 ),
  MAILPASSWORD    VARCHAR2(20 ),
  SMTPPORT        NUMBER(9),
  SMTPSERVER      VARCHAR2(25 ),
  MAILFLGAUT      NUMBER(1)                     DEFAULT 0                     NOT NULL,
  FLAG_AUDITOR    NUMBER(1)                     DEFAULT 0                     NOT NULL,
  CODDNE          VARCHAR2(10 ),
  LINGUA          VARCHAR2(10 )             DEFAULT 'ITA'                 NOT NULL,
  FLAG_MNG        NUMBER(1)                     DEFAULT 0                     NOT NULL,
  FLAG_ADMN       NUMBER(1)                     DEFAULT 0                     NOT NULL,
  FLAG_BATCH      NUMBER(1)                     DEFAULT 0                     NOT NULL,
  FLAG_DFLT_DEL   NUMBER(1)                     DEFAULT 0                     NOT NULL,
  BO_TOKEN        VARCHAR2(200 ),
  TEPRJUNTILPURC  NUMBER(1)                     DEFAULT 0                     NOT NULL,
  TEPRJ           NUMBER(1)                     DEFAULT 0                     NOT NULL,
  NRMAXPRJ        NUMBER(9),
  TEGESTCA        NUMBER(1)                     DEFAULT 0                     NOT NULL,
  TEANACRED       NUMBER(1)                     DEFAULT 0                     NOT NULL,
  TEPROP          NUMBER(1)                     DEFAULT 0                     NOT NULL,
  DTCHANGEPSW     DATE,
  OPERCODANA      NUMBER(9),
  TECLIMAN        NUMBER(1)                     DEFAULT 0                     NOT NULL,
  TESUPUSR        NUMBER(1)                     DEFAULT 0                     NOT NULL,
  TELOCK          NUMBER(1)                     DEFAULT 0                     NOT NULL,
  TEFIDU          NUMBER(1)                     DEFAULT 0                     NOT NULL,
  TEMOVCOGE       NUMBER(1)                     DEFAULT 0                     NOT NULL,
  TEENAPENALTY    NUMBER(1)                     DEFAULT 0                     NOT NULL,
  MAILUSETLS      VARCHAR2(1 ),
  TEMODAMOUNT     NUMBER(1)                     DEFAULT 0                     NOT NULL,
  TETEMPDIS       NUMBER(1)                     DEFAULT 0                     NOT NULL
)