unit udmPgFootballStorage;

interface

uses
  System.SysUtils, System.Classes, udmPgStorage, Data.DB, DBAccess, PgAccess, MemDS;

type
  TdmPgFootballStorage = class(TdmPgStorage)
    qryPlayer: TPgQuery;
    qryPlayeranagraph_id: TIntegerField;
    qryPlayerbirth_date: TDateField;
    qryPlayerbirth_year: TSmallintField;
    qryPlayerfirst_name: TWideStringField;
    qryPlayerfamily_name: TWideStringField;
    qryPlayerbirth_place: TWideStringField;
    qryPlayernotes: TWideMemoField;
    qryPlayerrole: TSmallintField;
    qryPlayerfull_name: TWideStringField;
    qryMatchDay: TPgQuery;
    qryMatchDayseason_des: TWideStringField;
    qryMatchDayseason_code: TWideStringField;
    qryMatchDayleague_name: TWideStringField;
    qryMatchDayseason_id: TSmallintField;
    qryMatchDayleague_id: TSmallintField;
    qryMatchDaymatch_day_number: TSmallintField;
    qryMatchDaymatch_day_date: TDateField;
    qryMatchDayrest_team_id: TIntegerField;
    qryMatchDaydb_schema_id: TIntegerField;
    qryMatchDaymatch_day_played: TDateField;
    qryPlayerCareer: TPgQuery;
    qryPlayerCareerdb_schema_id: TIntegerField;
    qryPlayerCareercareer_id: TIntegerField;
    qryPlayerCareermatches: TWideStringField;
    qryPlayerCareergoals: TWideStringField;
    qryPlayerCareerplayer_id: TIntegerField;
    qryPlayerCareernotes: TWideStringField;
    qryPlayerCareervotes: TFloatField;
    qryPlayerCareerminutes: TIntegerField;
    qryPlayerCareerimage_id: TLargeintField;
    qryPlayerCareerseason_id: TIntegerField;
    qryPlayerCareerseason_des: TWideStringField;
    qryPlayerCareerseason_code: TWideStringField;
    qryPlayerCareerdb_schema_id_1: TIntegerField;
    qryPlayerCareerteam_name: TWideStringField;
    qryPlayerCareerteam_id: TIntegerField;
    qryPlayerCareerleague_id: TSmallintField;
    qryPlayerCareerleague_name: TWideStringField;
    qryPlayerCareeriso_country_code: TWideStringField;
    qryPlayerCareerleague_position: TSmallintField;
    qryPlayerCareerleague_code: TWideStringField;
    qryPlayerCareerdb_schema_id_2: TSmallintField;
    qryPlayerCareerremote_id: TSmallintField;
    qryPlayerCareerpromotedcss: TWideStringField;
    qryPlayerCareerplayoffcss: TWideStringField;
    qryPlayerCareerchampionscss: TWideStringField;
    qryPlayerCareerplayoutcss: TWideStringField;
    qryPlayerCareerrelegationcss: TWideStringField;
    qryPlayerCareerall_players: TBooleanField;
    dsTeam: TDataSource;
    qryTeamHistory: TPgQuery;
    qryTeamHistoryseason_des: TWideStringField;
    qryTeamHistoryseason_code: TWideStringField;
    qryTeamHistoryteam_id: TIntegerField;
    qryTeamHistoryseason_id: TSmallintField;
    qryTeamHistoryleague_id: TSmallintField;
    qryTeamHistoryleague_code: TWideStringField;
    qryTeamHistorypos: TWideStringField;
    qryTeamHistoryresult_id: TSmallintField;
    qryTeamHistoryrank_code: TWideStringField;
    dsPlayer: TDataSource;
    qryTeamMatches: TPgQuery;
    qryTeamMatchesrownum: TLargeintField;
    qryTeamMatchesmatch_id: TIntegerField;
    qryTeamMatchesleague_id: TSmallintField;
    qryTeamMatchesseason_id: TSmallintField;
    qryTeamMatchesmatch_day_number: TSmallintField;
    qryTeamMatchesmatch_date: TDateField;
    qryTeamMatcheshome_team_id: TSmallintField;
    qryTeamMatchesvisitors_team_id: TSmallintField;
    qryTeamMatchesgoal_home: TSmallintField;
    qryTeamMatchesgoal_visitor: TSmallintField;
    qryTeamMatchespoints_home: TSmallintField;
    qryTeamMatchespoints_visitors: TSmallintField;
    qryTeamMatchesnotes: TWideMemoField;
    qryTeamMatchesconfirmed: TBooleanField;
    qryTeamMatchesdb_schema_id: TIntegerField;
    qryTeamMatchesinsert_date: TSQLTimeStampField;
    qryTeamMatchesupdate_date: TSQLTimeStampField;
    qryTeamMatcheshome_notes: TWideStringField;
    qryTeamMatchesvisitors_notes: TWideStringField;
    qryTeamMatchesfiled_id: TIntegerField;
    qryTeamMatchesremote_id: TIntegerField;
    qryTeamMatchesforfeit: TBooleanField;
    qryTeamMatchespostponed: TBooleanField;
    qryTeamMatchessuspended: TBooleanField;
    qryTeamMatchesreferee_third_id: TIntegerField;
    qryTeamMatchesreferee_second_id: TIntegerField;
    qryTeamMatchesreferee_id: TIntegerField;
    qryTeamMatchesmatch_time: TSQLTimeStampField;
    qryTeamMatcheshome_team: TWideStringField;
    qryTeamMatchesvisitors_team: TWideStringField;
    qryTeamMatchesmatch_level: TSmallintField;
    dsChampionship: TPgDataSource;
    qryChampionshipTeam: TPgQuery;
    IntegerField9: TIntegerField;
    SmallintField39: TSmallintField;
    WideStringField22: TWideStringField;
    IntegerField10: TIntegerField;
    IntegerField15: TIntegerField;
    IntegerField16: TIntegerField;
    qryChampionshipTeamranking_id: TIntegerField;
    qryChampionshipTeamseason_id: TSmallintField;
    qryChampionshipTeamleague_id: TSmallintField;
    qryChampionshipTeampos: TSmallintField;
    qryChampionshipTeamplayed_matches: TSmallintField;
    qryChampionshipTeamwon_matches: TSmallintField;
    qryChampionshipTeamlost_matches: TSmallintField;
    qryChampionshipTeamtied_matches: TSmallintField;
    qryChampionshipTeamhome_matches: TSmallintField;
    qryChampionshipTeamhome_won: TSmallintField;
    qryChampionshipTeamhome_lost: TSmallintField;
    qryChampionshipTeamhome_tied: TSmallintField;
    qryChampionshipTeamoutside_played: TSmallintField;
    qryChampionshipTeamoutside_won: TSmallintField;
    qryChampionshipTeamoutside_lost: TSmallintField;
    qryChampionshipTeamoutside_tied: TSmallintField;
    qryChampionshipTeamgoal_done: TSmallintField;
    qryChampionshipTeamgoal_lost: TSmallintField;
    qryChampionshipTeampoints: TSmallintField;
    qryChampionshipTeamgoal_diff: TSmallintField;
    qryChampionshipTeamscoring_average: TFloatField;
    dsChampionshipTeam: TDataSource;
    qryTeamPlayers: TPgQuery;
    qryTeamPlayersteam_id: TSmallintField;
    qryTeamPlayersplayer_id: TIntegerField;
    qryTeamPlayersseason_id: TSmallintField;
    qryTeamPlayerssince: TDateField;
    qryTeamPlayersuntil: TDateField;
    qryTeamPlayersclub_origin_id: TIntegerField;
    qryTeamPlayersgoal: TSmallintField;
    qryTeamPlayersowngoal: TSmallintField;
    qryTeamPlayerslostgoal: TSmallintField;
    qryTeamPlayerssent_off: TSmallintField;
    qryTeamPlayersinjuries: TSmallintField;
    qryTeamPlayersminutes: TSmallintField;
    qryTeamPlayersmatches: TIntegerField;
    qryTeamPlayersgoals: TIntegerField;
    qryTeamPlayersvotes: TFloatField;
    qryTeamPlayersanagraph_id: TIntegerField;
    qryTeamPlayersbirth_date: TDateField;
    qryTeamPlayersbirth_year: TSmallintField;
    qryTeamPlayersfirst_name: TWideStringField;
    qryTeamPlayersfamily_name: TWideStringField;
    qryTeamPlayersbirth_place: TWideStringField;
    qryTeamPlayersnotes: TWideMemoField;
    qryTeamPlayersrole: TSmallintField;
    qryTeamPlayersleague_id: TIntegerField;
    qryTeamPlayersteam_name: TWideMemoField;
    qryFirstSeasonLeague: TPgQuery;
    qryFirstSeasonLeagueleague_id: TSmallintField;
    qryFirstSeasonLeagueleague_name: TWideStringField;
    qryFirstSeasonLeagueiso_country_code: TWideStringField;
    qryFirstSeasonLeagueleague_position: TSmallintField;
    qryFirstSeasonLeagueleague_code: TWideStringField;
    qryFirstSeasonLeaguedb_schema_id: TSmallintField;
    qryFirstSeasonLeagueremote_id: TSmallintField;
    qryFirstSeasonLeaguepromotedcss: TWideStringField;
    qryFirstSeasonLeagueplayoffcss: TWideStringField;
    qryFirstSeasonLeaguechampionscss: TWideStringField;
    qryFirstSeasonLeagueplayoutcss: TWideStringField;
    qryFirstSeasonLeaguerelegationcss: TWideStringField;
    dsCalendarDay: TPgDataSource;
    qryCalendarDay: TPgQuery;
    WideStringField12: TWideStringField;
    WideStringField13: TWideStringField;
    WideStringField14: TWideStringField;
    SmallintField23: TSmallintField;
    SmallintField24: TSmallintField;
    SmallintField25: TSmallintField;
    DateField4: TDateField;
    IntegerField7: TIntegerField;
    IntegerField8: TIntegerField;
    DateField5: TDateField;
    qryCalendarMatches: TPgQuery;
    qryCalendarMatchesrownum: TLargeintField;
    qryCalendarMatchesmatch_id: TIntegerField;
    qryCalendarMatchesleague_id: TSmallintField;
    qryCalendarMatchesseason_id: TSmallintField;
    qryCalendarMatchesmatch_day_number: TSmallintField;
    qryCalendarMatchesmatch_date: TDateField;
    qryCalendarMatcheshome_team_id: TSmallintField;
    qryCalendarMatchesvisitors_team_id: TSmallintField;
    qryCalendarMatchesgoal_home: TSmallintField;
    qryCalendarMatchesgoal_visitor: TSmallintField;
    qryCalendarMatchespoints_home: TSmallintField;
    qryCalendarMatchespoints_visitors: TSmallintField;
    qryCalendarMatchesnotes: TWideMemoField;
    qryCalendarMatchesconfirmed: TBooleanField;
    qryCalendarMatchesdb_schema_id: TIntegerField;
    qryCalendarMatchesinsert_date: TSQLTimeStampField;
    qryCalendarMatchesupdate_date: TSQLTimeStampField;
    qryCalendarMatcheshome_notes: TWideStringField;
    qryCalendarMatchesvisitors_notes: TWideStringField;
    qryCalendarMatchesfiled_id: TIntegerField;
    qryCalendarMatchesremote_id: TIntegerField;
    qryCalendarMatchesforfeit: TBooleanField;
    qryCalendarMatchespostponed: TBooleanField;
    qryCalendarMatchessuspended: TBooleanField;
    qryCalendarMatchesreferee_third_id: TIntegerField;
    qryCalendarMatchesreferee_second_id: TIntegerField;
    qryCalendarMatchesreferee_id: TIntegerField;
    qryCalendarMatchesmatch_time: TSQLTimeStampField;
    qryCalendarMatcheshome_team: TWideStringField;
    qryCalendarMatchesvisitors_team: TWideStringField;
    qryMatchDetailEvents: TPgQuery;
    qryMatchDetailEventsmatch_id: TIntegerField;
    qryMatchDetailEventsteam_id: TSmallintField;
    qryMatchDetailEventsplayer_id: TIntegerField;
    qryMatchDetailEventsevent_id: TSmallintField;
    qryMatchDetailEventsminute: TIntegerField;
    qryMatchDetailEventsvalue: TSmallintField;
    qryMatchDetailEventsmatch_events_row_id: TLargeintField;
    qryMatchDetailEventsnotes: TWideStringField;
    qryMatchDetailEventsfavor_team_id: TIntegerField;
    qryMatchDetailEventsteamplayer: TWideStringField;
    qryMatchDetailEventsfamily_name: TWideStringField;
    qryMatchDetailEventsteam_name: TWideStringField;
    qryMatchDetailEventsanagraph_id: TIntegerField;
    qryMatchDetailEventsbirth_date: TDateField;
    qryMatchDetailEventsbirth_year: TSmallintField;
    qryMatchDetailEventsfirst_name: TWideStringField;
    qryMatchDetailEventsbirth_place: TWideStringField;
    qryMatchDetailEventsrole: TSmallintField;
    qryMatchVisitorsPlayers: TPgQuery;
    qryMatchHomePlayers: TPgQuery;
    dsMatchDetail: TDataSource;
    qryMatchDetail: TPgQuery;
    qryMatchDetailmatch_id: TIntegerField;
    qryMatchDetailleague_id: TSmallintField;
    qryMatchDetailseason_id: TSmallintField;
    qryMatchDetailmatch_day_number: TSmallintField;
    qryMatchDetailmatch_date: TDateField;
    qryMatchDetailhome_team_id: TSmallintField;
    qryMatchDetailvisitors_team_id: TSmallintField;
    qryMatchDetailgoal_home: TSmallintField;
    qryMatchDetailgoal_visitor: TSmallintField;
    qryMatchDetailpoints_home: TSmallintField;
    qryMatchDetailpoints_visitors: TSmallintField;
    qryMatchDetailnotes: TWideMemoField;
    qryMatchDetailconfirmed: TBooleanField;
    qryMatchDetaildb_schema_id: TIntegerField;
    qryMatchDetailinsert_date: TSQLTimeStampField;
    qryMatchDetailupdate_date: TSQLTimeStampField;
    qryMatchDetailhome_notes: TWideStringField;
    qryMatchDetailvisitors_notes: TWideStringField;
    qryMatchDetailfiled_id: TIntegerField;
    qryMatchDetailremote_id: TIntegerField;
    qryMatchDetailforfeit: TBooleanField;
    qryMatchDetailpostponed: TBooleanField;
    qryMatchDetailsuspended: TBooleanField;
    qryMatchDetailreferee_third_id: TIntegerField;
    qryMatchDetailreferee_second_id: TIntegerField;
    qryMatchDetailreferee_id: TIntegerField;
    qryMatchDetailmatch_time: TSQLTimeStampField;
    qryMatchDetailhome_team: TWideStringField;
    qryMatchDetailvisitors_team: TWideStringField;
    qryMatchDetailmatch_level: TSmallintField;
    qryLkpEventTypes: TPgQuery;
    qryNextMatchDay: TPgQuery;
    qryNextMatchDayseason_des: TWideStringField;
    qryNextMatchDayseason_code: TWideStringField;
    qryNextMatchDayleague_name: TWideStringField;
    qryNextMatchDayseason_id: TSmallintField;
    qryNextMatchDayleague_id: TSmallintField;
    qryNextMatchDaymatch_day_number: TSmallintField;
    qryNextMatchDayrest_team_id: TIntegerField;
    qryNextMatchDaydb_schema_id: TIntegerField;
    qryNextMatchDaymatch_day_date: TDateField;
    qryNextMatchDaymatch_day_played: TDateField;
    qryChampionship: TPgQuery;
    qryChampionshipleague_id: TSmallintField;
    qryChampionshipleague_name: TWideStringField;
    qryChampionshipseason_id: TIntegerField;
    qryChampionshipseason_des: TWideStringField;
    qryChampionshipseason_code: TWideStringField;
    qryChampionshipdb_schema_id: TIntegerField;
    qryChampionshippromoted: TSmallintField;
    qryChampionshipplayoff: TSmallintField;
    qryChampionshiprelegation: TSmallintField;
    qryChampionshipchampions: TSmallintField;
    qryChampionshipplayout: TSmallintField;
    qryChampionshipteams: TSmallintField;
    qryChampionshipiso_country_code: TWideStringField;
    qryChampionshipleague_position: TSmallintField;
    qryChampionshipleague_code: TWideStringField;
    qryChampionshiprelegationcss: TWideStringField;
    qryChampionshipplayoutcss: TWideStringField;
    qryChampionshipchampionscss: TWideStringField;
    qryChampionshipplayoffcss: TWideStringField;
    qryChampionshippromotedcss: TWideStringField;
    qryNextMatches: TPgQuery;
    IntegerField1: TIntegerField;
    SmallintField1: TSmallintField;
    SmallintField2: TSmallintField;
    SmallintField3: TSmallintField;
    DateField1: TDateField;
    SmallintField4: TSmallintField;
    SmallintField5: TSmallintField;
    SmallintField6: TSmallintField;
    SmallintField7: TSmallintField;
    SmallintField8: TSmallintField;
    SmallintField9: TSmallintField;
    WideMemoField1: TWideMemoField;
    BooleanField1: TBooleanField;
    IntegerField2: TIntegerField;
    SQLTimeStampField1: TSQLTimeStampField;
    SQLTimeStampField2: TSQLTimeStampField;
    WideStringField1: TWideStringField;
    WideStringField2: TWideStringField;
    WideStringField3: TWideStringField;
    WideStringField4: TWideStringField;
    qryNextMatchesrownum: TLargeintField;
    qryNextMatchesmatch_time: TSQLTimeStampField;
    qryNextMatchesreferee_id: TIntegerField;
    qryNextMatchesreferee_second_id: TIntegerField;
    qryNextMatchesreferee_third_id: TIntegerField;
    qryNextMatchessuspended: TBooleanField;
    qryNextMatchespostponed: TBooleanField;
    qryNextMatchesforfeit: TBooleanField;
    qryNextMatchesremote_id: TIntegerField;
    qryNextMatchesfiled_id: TIntegerField;
    qryMatchTeamPlayers: TPgQuery;
    qryMatchTeamPlayersmatch_id: TIntegerField;
    qryMatchTeamPlayersplayer_id: TIntegerField;
    qryMatchTeamPlayersminutes: TSmallintField;
    qryMatchTeamPlayersvote: TFloatField;
    qryMatchTeamPlayersplayed: TBooleanField;
    qryMatchTeamPlayersteam_id: TSmallintField;
    qryMatchTeamPlayerspos: TSmallintField;
    qryMatchTeamPlayersfull_name: TWideStringField;
    qryMatchTeamPlayerssubst_id: TIntegerField;
    qryMatchTeamPlayersfamily_name: TWideStringField;
    qryMatchTeamPlayersfirst_name: TWideStringField;
    qryMatchTeamPlayersgoal: TSmallintField;
    qryMatchTeamPlayersowngoal: TSmallintField;
    qryMatchTeamPlayerslostgoal: TSmallintField;
    qryMatchTeamPlayersrole_id: TSmallintField;
    qryMatchTeamPlayerssince: TSmallintField;
    qryMatchTeamPlayersuntil: TSmallintField;
    qryMatchTeamPlayerssent_off: TSmallintField;
    qryMatchTeamPlayersinjuries: TSmallintField;
    qryMatchTeamPlayersrole_code: TWideStringField;
    qryMatchTeamPlayersrole_name: TWideStringField;
    qryMatchTeamPlayersanagraph_id: TIntegerField;
    qryMatchTeamPlayersbirth_date: TDateField;
    qryMatchTeamPlayersbirth_year: TSmallintField;
    qryMatchTeamPlayersbirth_place: TWideStringField;
    qryMatchTeamPlayersnotes: TWideMemoField;
    qryMatchTeamPlayersrole: TSmallintField;
    qryMatchTeamPlayersrow_name: TWideStringField;
    qryLastMatch: TPgQuery;
    qryLastMatchlast_match: TSmallintField;
    qryGolRanking: TPgQuery;
    qryGolRankingrownum: TLargeintField;
    qryGolRankingfamily_name: TWideStringField;
    qryGolRankingteam_name: TWideStringField;
    qryGolRankingleague_id: TSmallintField;
    qryGolRankingseason_id: TSmallintField;
    qryGolRankingteam_id: TSmallintField;
    qryGolRankingplayer_id: TIntegerField;
    qryGolRankingfirst_name: TWideStringField;
    qryGolRankinggoals: TLargeintField;
    qryGolRankinggoal: TLargeintField;
    qryLastSeason: TPgQuery;
    qryLastSeasonseason_id: TIntegerField;
    dsMatchTeams: TDataSource;
    qryMatches: TPgQuery;
    qryMatchesrownum: TLargeintField;
    qryMatchesmatch_id: TIntegerField;
    qryMatchesleague_id: TSmallintField;
    qryMatchesseason_id: TSmallintField;
    qryMatchesmatch_day_number: TSmallintField;
    qryMatchesmatch_date: TDateField;
    qryMatcheshome_team_id: TSmallintField;
    qryMatchesvisitors_team_id: TSmallintField;
    qryMatchesgoal_home: TSmallintField;
    qryMatchesgoal_visitor: TSmallintField;
    qryMatchespoints_home: TSmallintField;
    qryMatchespoints_visitors: TSmallintField;
    qryMatchesnotes: TWideMemoField;
    qryMatchesconfirmed: TBooleanField;
    qryMatchesdb_schema_id: TIntegerField;
    qryMatchesinsert_date: TSQLTimeStampField;
    qryMatchesupdate_date: TSQLTimeStampField;
    qryMatcheshome_notes: TWideStringField;
    qryMatchesvisitors_notes: TWideStringField;
    qryMatcheshome_team: TWideStringField;
    qryMatchesvisitors_team: TWideStringField;
    qryMatchesmatch_time: TSQLTimeStampField;
    qryMatchesreferee_id: TIntegerField;
    qryMatchesreferee_second_id: TIntegerField;
    qryMatchesreferee_third_id: TIntegerField;
    qryMatchessuspended: TBooleanField;
    qryMatchespostponed: TBooleanField;
    qryMatchesforfeit: TBooleanField;
    qryMatchesremote_id: TIntegerField;
    qryMatchesfiled_id: TIntegerField;
    qryMatchesmatch_name: TStringField;
    qryMatchesmatch_level: TSmallintField;
    qryChampRanking: TPgQuery;
    qryChampRankingteam_name: TWideStringField;
    qryChampRankingranking_id: TIntegerField;
    qryChampRankingseason_id: TSmallintField;
    qryChampRankingleague_id: TSmallintField;
    qryChampRankingteam_id: TIntegerField;
    qryChampRankingpos: TSmallintField;
    qryChampRankingplayed_matches: TSmallintField;
    qryChampRankingwon_matches: TSmallintField;
    qryChampRankinglost_matches: TSmallintField;
    qryChampRankingtied_matches: TSmallintField;
    qryChampRankinghome_matches: TSmallintField;
    qryChampRankinghome_won: TSmallintField;
    qryChampRankinghome_lost: TSmallintField;
    qryChampRankinghome_tied: TSmallintField;
    qryChampRankingoutside_played: TSmallintField;
    qryChampRankingoutside_won: TSmallintField;
    qryChampRankingoutside_lost: TSmallintField;
    qryChampRankingoutside_tied: TSmallintField;
    qryChampRankinggoal_done: TSmallintField;
    qryChampRankinggoal_lost: TSmallintField;
    qryChampRankingpoints: TSmallintField;
    qryChampRankinggoal_diff: TSmallintField;
    qryChampRankingscoring_average: TFloatField;
    qryMatchEvents: TPgQuery;
    qryMatchEventsmatch_id: TIntegerField;
    qryMatchEventsteam_id: TSmallintField;
    qryMatchEventsplayer_id: TIntegerField;
    qryMatchEventsevent_id: TSmallintField;
    qryMatchEventsminute: TIntegerField;
    qryMatchEventsvalue: TSmallintField;
    qryMatchEventsmatch_events_row_id: TLargeintField;
    qryMatchEventslkpTeamPlayer: TStringField;
    qryMatchEventslkpEventType: TStringField;
    qryMatchEventsnotes: TWideStringField;
    qryMatchEventsfavor_team_id: TIntegerField;
    qryMatchEventsteamplayer: TWideStringField;
    qryMatchEventsfamily_name: TWideStringField;
    qryMatchTeams: TPgQuery;
    qryMatchTeamsteam_id: TIntegerField;
    qryMatchTeamsclub_id: TSmallintField;
    qryMatchTeamsteam_name: TWideStringField;
    qryTeam: TPgQuery;
    qryTeamteam_id: TIntegerField;
    qryTeamclub_id: TSmallintField;
    qryTeamteam_name: TWideStringField;
    qryTeamtrainer_id: TIntegerField;
    qryTeamremote_id: TIntegerField;
    qryTeamdb_schema_id: TIntegerField;
    qryChampionships: TPgQuery;
    qryChampionshipsleague_name: TWideStringField;
    qryChampionshipsleague_position: TSmallintField;
    qryChampionshipsseason_id: TIntegerField;
    qryChampionshipsseason_des: TWideStringField;
    qryChampionshipsseason_code: TWideStringField;
    qryChampionshipsdb_schema_id: TIntegerField;
    qryChampionshipsleague_id: TSmallintField;
    qryChampionshipspromoted: TSmallintField;
    qryChampionshipsplayoff: TSmallintField;
    qryChampionshipsrelegation: TSmallintField;
    qryChampionshipschampions: TSmallintField;
    qryChampionshipsplayout: TSmallintField;
    qryChampionshipsteams: TSmallintField;
    qryChampionshipsiso_country_code: TWideStringField;
    qryChampionshipsleague_code: TWideStringField;
    qryChampionshipsrelegationcss: TWideStringField;
    qryChampionshipsplayoutcss: TWideStringField;
    qryChampionshipschampionscss: TWideStringField;
    qryChampionshipsplayoffcss: TWideStringField;
    qryChampionshipspromotedcss: TWideStringField;
    qryChampionshipsremote_id: TSmallintField;
    qryDynamicRanking: TPgQuery;
    lkpMatchDays: TPgQuery;
    lkpMatchDaysmatch_day_number: TSmallintField;
    qryDynamicRankingpos: TLargeintField;
    qryDynamicRankingleague_id: TSmallintField;
    qryDynamicRankingseason_id: TSmallintField;
    qryDynamicRankingteam_id: TIntegerField;
    qryDynamicRankinglast_match_day: TSmallintField;
    qryDynamicRankinghome_matches: TFloatField;
    qryDynamicRankingoutside_played: TFloatField;
    qryDynamicRankinggoal_win_home: TFloatField;
    qryDynamicRankinggoal_win_visitor: TFloatField;
    qryDynamicRankinggoal_lost_home: TFloatField;
    qryDynamicRankinggoal_lost_visitor: TFloatField;
    qryDynamicRankingpoints_home: TFloatField;
    qryDynamicRankingpoints_visitor: TFloatField;
    qryDynamicRankingpoints: TFloatField;
    qryDynamicRankingaverage_home: TFloatField;
    qryDynamicRankingaverage_visitor: TFloatField;
    qryDynamicRankingaverage: TFloatField;
    qryDynamicRankinggoal_done: TFloatField;
    qryDynamicRankinggoal_lost: TFloatField;
    qryDynamicRankinggoal_difference: TFloatField;
    qryDynamicRankinghome_lost: TFloatField;
    qryDynamicRankinghome_won: TFloatField;
    qryDynamicRankinghome_tied: TFloatField;
    qryDynamicRankingoutside_lost: TFloatField;
    qryDynamicRankingoutside_won: TFloatField;
    qryDynamicRankingoutside_tied: TFloatField;
    qryDynamicRankinglost_matches: TFloatField;
    qryDynamicRankingwon_matches: TFloatField;
    qryDynamicRankingplayed_matches: TFloatField;
    qryDynamicRankingpenalty: TSmallintField;
    qryDynamicRankingteam_name: TWideStringField;
    DynamicGolRanking: TPgQuery;
    DynamicGolRankingrownum: TLargeintField;
    DynamicGolRankingfirst_name: TWideStringField;
    DynamicGolRankingfamily_name: TWideStringField;
    DynamicGolRankingteam_name: TWideStringField;
    DynamicGolRankingleague_id: TSmallintField;
    DynamicGolRankingseason_id: TSmallintField;
    DynamicGolRankingteam_id: TSmallintField;
    DynamicGolRankingplayer_id: TIntegerField;
    DynamicGolRankinggoals: TLargeintField;
    DynamicGolRankinggoal: TLargeintField;
    qrySeasons: TPgQuery;
    qrySeasonsseason_id: TIntegerField;
    qrySeasonsseason_des: TWideStringField;
    qrySeasonsseason_code: TWideStringField;
    qrySeasonsdb_schema_id: TIntegerField;
    qryMatchHomePlayersmatch_id: TIntegerField;
    qryMatchHomePlayersplayer_id: TIntegerField;
    qryMatchHomePlayersminutes: TSmallintField;
    qryMatchHomePlayersvote: TFloatField;
    qryMatchHomePlayersplayed: TBooleanField;
    qryMatchHomePlayersteam_id: TSmallintField;
    qryMatchHomePlayerspos: TSmallintField;
    qryMatchHomePlayerssubst_id: TIntegerField;
    qryMatchHomePlayersgoal: TSmallintField;
    qryMatchHomePlayersowngoal: TSmallintField;
    qryMatchHomePlayerslostgoal: TSmallintField;
    qryMatchHomePlayerssince: TSmallintField;
    qryMatchHomePlayersuntil: TSmallintField;
    qryMatchHomePlayerssent_off: TSmallintField;
    qryMatchHomePlayersinjuries: TSmallintField;
    qryMatchHomePlayersdb_schema_id: TIntegerField;
    qryMatchHomePlayersfmtp_jguid: TWideStringField;
    qryMatchHomePlayersfmtp_deleted: TBooleanField;
    qryMatchHomePlayersanagraph_id: TIntegerField;
    qryMatchHomePlayersbirth_date: TDateField;
    qryMatchHomePlayersbirth_year: TSmallintField;
    qryMatchHomePlayersfirst_name: TWideStringField;
    qryMatchHomePlayersfamily_name: TWideStringField;
    qryMatchHomePlayersbirth_place: TWideStringField;
    qryMatchHomePlayersnotes: TWideMemoField;
    qryMatchHomePlayersrole: TSmallintField;
    qryMatchHomePlayersremote_id: TIntegerField;
    qryMatchHomePlayersheight: TSmallintField;
    qryMatchHomePlayersweight: TSmallintField;
    qryMatchHomePlayerspplr_jguid: TWideStringField;
    qryMatchHomePlayerspplr_deleted: TBooleanField;
    qryMatchHomePlayersfull_name: TWideStringField;
    qryMatchHomePlayersrow_name: TWideStringField;
    qryMatchHomePlayersrole_id: TSmallintField;
    qryMatchHomePlayersrole_code: TWideStringField;
    qryMatchHomePlayersrole_name: TWideStringField;
    qryMatchHomePlayersfrls_jguid: TWideStringField;
    qryMatchHomePlayersfrls_deleted: TBooleanField;
    qryMatchHomePlayersseason_id: TIntegerField;
    qryMatchHomePlayersleague_id: TIntegerField;
    qryMatchHomePlayersteam_name: TWideStringField;
    qryMatchVisitorsPlayersmatch_id: TIntegerField;
    qryMatchVisitorsPlayersplayer_id: TIntegerField;
    qryMatchVisitorsPlayersminutes: TSmallintField;
    qryMatchVisitorsPlayersvote: TFloatField;
    qryMatchVisitorsPlayersplayed: TBooleanField;
    qryMatchVisitorsPlayersteam_id: TSmallintField;
    qryMatchVisitorsPlayerspos: TSmallintField;
    qryMatchVisitorsPlayerssubst_id: TIntegerField;
    qryMatchVisitorsPlayersgoal: TSmallintField;
    qryMatchVisitorsPlayersowngoal: TSmallintField;
    qryMatchVisitorsPlayerslostgoal: TSmallintField;
    qryMatchVisitorsPlayerssince: TSmallintField;
    qryMatchVisitorsPlayersuntil: TSmallintField;
    qryMatchVisitorsPlayerssent_off: TSmallintField;
    qryMatchVisitorsPlayersinjuries: TSmallintField;
    qryMatchVisitorsPlayersdb_schema_id: TIntegerField;
    qryMatchVisitorsPlayersfmtp_jguid: TWideStringField;
    qryMatchVisitorsPlayersfmtp_deleted: TBooleanField;
    qryMatchVisitorsPlayersanagraph_id: TIntegerField;
    qryMatchVisitorsPlayersbirth_date: TDateField;
    qryMatchVisitorsPlayersbirth_year: TSmallintField;
    qryMatchVisitorsPlayersfirst_name: TWideStringField;
    qryMatchVisitorsPlayersfamily_name: TWideStringField;
    qryMatchVisitorsPlayersbirth_place: TWideStringField;
    qryMatchVisitorsPlayersnotes: TWideMemoField;
    qryMatchVisitorsPlayersrole: TSmallintField;
    qryMatchVisitorsPlayersremote_id: TIntegerField;
    qryMatchVisitorsPlayersheight: TSmallintField;
    qryMatchVisitorsPlayersweight: TSmallintField;
    qryMatchVisitorsPlayerspplr_jguid: TWideStringField;
    qryMatchVisitorsPlayerspplr_deleted: TBooleanField;
    qryMatchVisitorsPlayersfull_name: TWideStringField;
    qryMatchVisitorsPlayersrow_name: TWideStringField;
    qryMatchVisitorsPlayersrole_id: TSmallintField;
    qryMatchVisitorsPlayersrole_code: TWideStringField;
    qryMatchVisitorsPlayersrole_name: TWideStringField;
    qryMatchVisitorsPlayersfrls_jguid: TWideStringField;
    qryMatchVisitorsPlayersfrls_deleted: TBooleanField;
    qryMatchVisitorsPlayersseason_id: TIntegerField;
    qryMatchVisitorsPlayersleague_id: TIntegerField;
    qryMatchVisitorsPlayersteam_name: TWideStringField;
    qryDynamicRankingtied_matches: TFloatField;
    procedure qryMatchesCalcFields(DataSet: TDataSet);
    procedure qryChampRankingCalcFields(DataSet: TDataSet);
    procedure qryCalendarMatchesCalcFields(DataSet: TDataSet);
    procedure qryChampionshipTeamCalcFields(DataSet: TDataSet);
    procedure UpdatePlayerCareer(DataSet: TDataSet);
    procedure qryMatchDetailAfterOpen(DataSet: TDataSet);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  dmPgFootballStorage: TdmPgFootballStorage;

implementation

{%CLASSGROUP 'System.Classes.TPersistent'}
{$R *.dfm}

procedure TdmPgFootballStorage.qryCalendarMatchesCalcFields(DataSet: TDataSet);
begin
  inherited;
  /// qryCalendarMatchesmatch_name.Value := qryMatcheshome_team.AsWideString + ' - ' + qryMatchesvisitors_team.AsWideString;

end;

procedure TdmPgFootballStorage.qryChampionshipTeamCalcFields(DataSet: TDataSet);
begin
  inherited;
  qryChampionshipTeamscoring_average.AsInteger :=
    (-3 * qryChampionshipTeamhome_matches.AsInteger + qryChampionshipTeamhome_won.AsInteger * 3 +
    qryChampionshipTeamhome_tied.AsInteger);

  qryChampionshipTeamscoring_average.AsInteger := qryChampionshipTeamscoring_average.AsInteger +
    (-qryChampionshipTeamoutside_played.AsInteger + qryChampionshipTeamoutside_won.AsInteger * 3 +
    qryChampionshipTeamoutside_tied.AsInteger);
end;

procedure TdmPgFootballStorage.qryChampRankingCalcFields(DataSet: TDataSet);
begin
  inherited;
  qryChampRankingscoring_average.AsInteger :=
    (-3 * qryChampRankinghome_matches.AsInteger + qryChampRankinghome_won.AsInteger * 3 +
    qryChampRankinghome_tied.AsInteger);

  qryChampRankingscoring_average.AsInteger := qryChampRankingscoring_average.AsInteger +
    (-qryChampRankingoutside_played.AsInteger + qryChampRankingoutside_won.AsInteger * 3 +
    qryChampRankingoutside_tied.AsInteger);
end;

procedure TdmPgFootballStorage.qryMatchDetailAfterOpen(DataSet: TDataSet);
begin
  inherited;
  ServerFunctions.OpenDataset(qryMatchDetailEvents);
  ServerFunctions.OpenDataset(qryMatchHomePlayers);
  ServerFunctions.OpenDataset(qryMatchVisitorsPlayers);
end;

procedure TdmPgFootballStorage.qryMatchesCalcFields(DataSet: TDataSet);
begin
  inherited;
  qryMatchesmatch_name.AsWideString := qryMatcheshome_team.AsWideString + ' - ' +
    qryMatchesvisitors_team.AsWideString;
end;

procedure TdmPgFootballStorage.UpdatePlayerCareer(DataSet: TDataSet);
var
  LID: Integer;
begin
  inherited;
  LID := qryPlayeranagraph_id.AsInteger;
  if (LID > 0) and (qryPlayerCareer.ParamByName('anagraph_id').AsInteger <> LID) then
  begin
    self.qryPlayerCareer.Close;
    self.qryPlayerCareer.ParamByName('anagraph_id').AsInteger := LID;
    self.qryPlayerCareer.Open;
  end
  else
    qryPlayerCareer.Close;
end;

end.
