-- FUNCTION: anagraph.anagraphs_insert_update(smallint, integer, integer, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, integer, character varying, character varying, numeric, integer, smallint, character varying, character varying, character varying, numeric, smallint, smallint, character varying, text, boolean, boolean, smallint, character varying, date, character varying, character varying, smallint, smallint, character varying, character varying, bigint, bigint, smallint, date, date, smallint, character varying, boolean, character varying, smallint, character varying, smallint, boolean, character varying, smallint, smallint, boolean, bigint, integer, character varying, character varying, character varying, integer, bigint, double precision, double precision)

-- DROP FUNCTION IF EXISTS anagraph.anagraphs_insert_update(smallint, integer, integer, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, integer, character varying, character varying, numeric, integer, smallint, character varying, character varying, character varying, numeric, smallint, smallint, character varying, text, boolean, boolean, smallint, character varying, date, character varying, character varying, smallint, smallint, character varying, character varying, bigint, bigint, smallint, date, date, smallint, character varying, boolean, character varying, smallint, character varying, smallint, boolean, character varying, smallint, smallint, boolean, bigint, integer, character varying, character varying, character varying, integer, bigint, double precision, double precision);

CREATE OR REPLACE FUNCTION anagraph.anagraphs_insert_update(
	INOUT an_group_id smallint,
	INOUT db_schema_id integer,
	INOUT anagraph_id integer,
	INOUT an_title character varying,
	INOUT an_name character varying,
	INOUT an_second_name character varying,
	INOUT an_last_name character varying,
	INOUT an_notes character varying,
	INOUT an_address character varying,
	INOUT an_town character varying,
	INOUT an_postal_code character varying,
	INOUT an_iso_country_code character varying,
	INOUT an_state_province character varying,
	INOUT an_phone character varying,
	INOUT an_phone2 character varying,
	INOUT an_fax character varying,
	INOUT an_cellular character varying,
	INOUT an_code character varying,
	INOUT an_vat_numeric character varying,
	INOUT an_email character varying,
	INOUT an_web character varying,
	INOUT an_contact_id integer,
	INOUT an_bank_account character varying,
	INOUT an_payment_des character varying,
	INOUT an_discount numeric,
	INOUT an_distance integer,
	INOUT an_distance_mesunit smallint,
	INOUT an_sex character varying,
	INOUT an_cod_comune character varying,
	INOUT an_cod_provincia character varying,
	INOUT an_credit_line numeric,
	INOUT an_currency_id smallint,
	INOUT an_cat_id smallint,
	INOUT an_notes2 character varying,
	INOUT an_notes3 text,
	INOUT an_edi boolean,
	INOUT an_privacy boolean,
	INOUT an_office_id smallint,
	INOUT an_cod_prov_rif character varying,
	INOUT an_data_fido date,
	INOUT an_user_insert character varying,
	INOUT an_user_update character varying,
	INOUT an_area_id smallint,
	INOUT an_agent_id smallint,
	INOUT an_area_code character varying,
	INOUT an_zone_id character varying,
	INOUT an_ins_id bigint,
	INOUT an_upd_id bigint,
	INOUT an_documents smallint,
	INOUT an_last_date date,
	INOUT an_birthdate date,
	INOUT an_office_type_id smallint,
	INOUT an_searchname character varying,
	INOUT an_extra_ue_flag boolean,
	INOUT an_external_code character varying,
	INOUT an_vat_id smallint,
	INOUT an_personal_fiscal_code character varying,
	INOUT an_privacy_print smallint,
	INOUT an_sms boolean,
	INOUT an_encrypted_fiscal_code character varying,
	INOUT an_vat_purcentage smallint,
	INOUT an_status smallint,
	INOUT an_ownsite boolean,
	INOUT an_insurance_id bigint,
	INOUT an_anagraphs_anagraph_id integer,
	INOUT an_main_language_code character varying,
	INOUT an_main_culture_code character varying,
	INOUT an_fiscal_code character varying,
	INOUT an_main_group_id integer,
	INOUT an_image_id bigint,
	INOUT latitude double precision,
	INOUT longitude double precision)
    RETURNS record
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$

declare
  newid bigint; 
begin

    if anagraph_id is null or anagraph_id = 0 then
       newid := nextval('anagraph.an_anagraph_seq');
    else
	    newid := anagraph_id; 
    end if; 

    insert into anagraph.anagraphs
    (db_schema_id ,
    anagraph_id ,
    an_title ,
    an_name ,
    an_second_name ,
    an_last_name ,
    an_notes ,
    an_address ,
    an_town ,
    an_postal_code ,
    an_iso_country_code ,
    an_state_province ,
    an_phone ,
    an_phone2 ,
    an_fax ,
    an_cellular ,
    an_code ,
    an_vat_numeric ,
    an_email ,
    an_web ,
    an_contact_id ,
    an_bank_account ,
    an_payment_des ,
    an_discount ,
    an_distance ,
    an_distance_mesunit ,
    an_sex ,
    an_cod_comune ,
    an_cod_provincia ,
    an_credit_line ,
    an_currency_id ,
    an_cat_id ,
    an_notes2 ,
    an_notes3 ,
    an_edi ,
    an_privacy ,
    an_office_id ,
    an_cod_prov_rif ,
    an_data_fido ,
    an_user_insert ,
    an_user_update ,
    an_area_id ,
    an_agent_id ,
    an_area_code ,
    an_zone_id ,
    an_ins_id ,
    an_upd_id ,
    an_documents ,
    an_last_date ,
    an_birthdate ,
    an_office_type_id ,
    an_searchname ,
    an_extra_ue_flag ,
    an_external_code ,
    an_vat_id ,
    an_personal_fiscal_code ,
    an_privacy_print ,
    an_sms ,
    an_encrypted_fiscal_code ,
    an_vat_purcentage ,
    an_status ,
    an_ownsite ,
    an_insurance_id ,
    an_anagraphs_anagraph_id ,
    an_main_language_code ,
    an_main_culture_code ,
    an_fiscal_code ,
    an_main_group_id ,
    an_image_id,
    latitude ,
    longitude  
    )
    values
    (    
    db_schema_id ,
    newid ,
    an_title ,
    an_name ,
    an_second_name ,
    an_last_name ,
    an_notes ,
    an_address ,
    an_town ,
    an_postal_code ,
    an_iso_country_code ,
    an_state_province ,
    an_phone ,
    an_phone2 ,
    an_fax ,
    an_cellular ,
    an_code ,
    an_vat_numeric ,
    an_email ,
    an_web ,
    an_contact_id ,
    an_bank_account ,
    an_payment_des ,
    an_discount ,
    an_distance ,
    an_distance_mesunit ,
    an_sex ,
    an_cod_comune ,
    an_cod_provincia ,
    an_credit_line ,
    an_currency_id ,
    an_cat_id ,
    an_notes2 ,
    an_notes3 ,
    an_edi ,
    an_privacy ,
    an_office_id ,
    an_cod_prov_rif ,
    an_data_fido ,
    an_user_insert ,
    an_user_update ,
    an_area_id ,
    an_agent_id ,
    an_area_code ,
    an_zone_id ,
    an_ins_id ,
    an_upd_id ,
    an_documents ,
    an_last_date ,
    an_birthdate ,
    an_office_type_id ,
    an_searchname ,
    an_extra_ue_flag ,
    an_external_code ,
    an_vat_id ,
    an_personal_fiscal_code ,
    an_privacy_print ,
    an_sms ,
    an_encrypted_fiscal_code ,
    an_vat_purcentage ,
    an_status ,
    an_ownsite ,
    an_insurance_id ,
    an_anagraphs_anagraph_id ,
    an_main_language_code ,
    an_main_culture_code ,
    an_fiscal_code ,
    an_main_group_id ,
    an_image_id, 
    latitude ,
    longitude  
    );

    insert into anagraph.identities
    (  
      db_schema_id ,
      anagraph_id , 
      an_group_id
    )
    values
    (
      db_schema_id,
      newid, 
      an_group_id
    );
    
    select  
    db_schema_id ,
    anagraph_id ,
    an_title ,
    an_name ,
    an_second_name ,
    an_last_name ,
    an_notes ,
    an_address ,
    an_town ,
    an_postal_code ,
    an_iso_country_code ,
    an_state_province ,
    an_phone ,
    an_phone2 ,
    an_fax ,
    an_cellular ,
    an_code ,
    an_vat_numeric ,
    an_email ,
    an_web ,
    an_contact_id ,
    an_bank_account ,
    an_payment_des ,
    an_discount ,
    an_distance ,
    an_distance_mesunit ,
    an_sex ,
    an_cod_comune ,
    an_cod_provincia ,
    an_credit_line ,
    an_currency_id ,
    an_cat_id ,
    an_notes2 ,
    an_notes3 ,
    an_edi ,
    an_privacy ,
    an_office_id ,
    an_cod_prov_rif ,
    an_data_fido ,
    an_user_insert ,
    an_user_update ,
    an_area_id ,
    an_agent_id ,
    an_area_code ,
    an_zone_id ,
    an_ins_id ,
    an_upd_id ,
    an_documents ,
    an_last_date ,
    an_birthdate ,
    an_office_type_id ,
    an_searchname ,
    an_extra_ue_flag ,
    an_external_code ,
    an_vat_id ,
    an_personal_fiscal_code ,
    an_privacy_print ,
    an_sms ,
    an_encrypted_fiscal_code ,
    an_vat_purcentage ,
    an_status ,
    an_ownsite ,
    an_insurance_id ,
    an_anagraphs_anagraph_id ,
    an_main_language_code ,
    an_main_culture_code ,
    an_fiscal_code ,
    an_main_group_id ,
    an_image_id,
    latitude ,
    longitude  
    INTO 
    db_schema_id ,
    anagraph_id ,
    an_title ,
    an_name ,
    an_second_name ,
    an_last_name ,
    an_notes ,
    an_address ,
    an_town ,
    an_postal_code ,
    an_iso_country_code ,
    an_state_province ,
    an_phone ,
    an_phone2 ,
    an_fax ,
    an_cellular ,
    an_code ,
    an_vat_numeric ,
    an_email ,
    an_web ,
    an_contact_id ,
    an_bank_account ,
    an_payment_des ,
    an_discount ,
    an_distance ,
    an_distance_mesunit ,
    an_sex ,
    an_cod_comune ,
    an_cod_provincia ,
    an_credit_line ,
    an_currency_id ,
    an_cat_id ,
    an_notes2 ,
    an_notes3 ,
    an_edi ,
    an_privacy ,
    an_office_id ,
    an_cod_prov_rif ,
    an_data_fido ,
    an_user_insert ,
    an_user_update ,
    an_area_id ,
    an_agent_id ,
    an_area_code ,
    an_zone_id ,
    an_ins_id ,
    an_upd_id ,
    an_documents ,
    an_last_date ,
    an_birthdate ,
    an_office_type_id ,
    an_searchname ,
    an_extra_ue_flag ,
    an_external_code ,
    an_vat_id ,
    an_personal_fiscal_code ,
    an_privacy_print ,
    an_sms ,
    an_encrypted_fiscal_code ,
    an_vat_purcentage ,
    an_status ,
    an_ownsite ,
    an_insurance_id ,
    an_anagraphs_anagraph_id ,
    an_main_language_code ,
    an_main_culture_code ,
    an_fiscal_code ,
    an_main_group_id ,
    an_image_id,
    latitude ,
    longitude  
    WHERE 
      anagraph_id = newid; 
    --return newid; 

end;
$BODY$;

ALTER FUNCTION anagraph.anagraphs_insert_update(smallint, integer, integer, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, character varying, integer, character varying, character varying, numeric, integer, smallint, character varying, character varying, character varying, numeric, smallint, smallint, character varying, text, boolean, boolean, smallint, character varying, date, character varying, character varying, smallint, smallint, character varying, character varying, bigint, bigint, smallint, date, date, smallint, character varying, boolean, character varying, smallint, character varying, smallint, boolean, character varying, smallint, smallint, boolean, bigint, integer, character varying, character varying, character varying, integer, bigint, double precision, double precision)
    OWNER TO ergo;
